### ISSUE TITLE
support http methods

### ISSUE THREAD

**Issue by traskat** [totaljs/framework#196]
Hi,

are the methods put,get and post only supported or the other too?

thanks and best,

normen

**Comment by g13013** [comment]
Hi @petersirka , I am actually trying to handle HEAD requests but there is not valid response

I tried:
```js
F.route('/test', handler, ['head'])
F.route('/test', ['head']);
```
any idea ?

**Comment by petersirka** [comment]
Hi @g13013,
this works correctly:

```javascript
require('total.js');

F.route('/', function() {
    var self = this;
    // the framework doesn't send the content if the request method will be HEAD
    self.plain('TEST');
}, ['get', 'head']);

F.http('debug');
```

Thanks.
PS: works only with `v1.7.3` (currently: BETA version)

**Comment by g13013** [comment]
Thanks @petersirka, I have 1.7.2, that's why it doesn't work as expected

**Comment by petersirka** [comment]
No problem. I fixed the __head method__ in the new version. There was a bug.
Thanks.

**Comment by g13013** [comment]
any workaround for the current version ?

**Comment by petersirka** [comment]
Do you mean for the version `v1.7.2`?

**Comment by g13013** [comment]
@petersirka Yes i mean v1.7.2, I am trying the v1.7.3 and it works, when do you think it will be released ?

**Comment by petersirka** [comment]
@g13013 I want to publish it in the coming days :+1: 
I'm testing it in many projects.

Thanks!

**Comment by g13013** [comment]
@petersirka thanks you, I've submited a merge request on the `nosql` project to fix a problem with the `nosql.one` function.
