### ISSUE TITLE
Compile html always works

### ISSUE THREAD

**Issue by pssupport** [totaljs/framework#211]
Option "allow-compile-html" has no effect. HTML always minified.

total.js v1604
`./config-debug`
> allow-compile-html       : false

```javascript
console.log('allow-compile-html: ' + CONFIG('allow-compile-html'));
```
`$ node debug.js`
> $ allow-compile-html: false

Open any page in browser. View source. All content is displayed in a single line without spaces and line breaks.

**Comment by petersirka** [comment]
I published a new version.
Closed.
