### ISSUE TITLE
models execute before definitions

### ISSUE THREAD

**Issue by satrong** [totaljs/framework#230]
version: v1.7.0 (build: 44)
I have defined a global variable "mongoose" in definitions, and in the models use the global variable, but totaljs will throw an error:"ReferenceError: mongoose is not defined". Is Models execute before Definitions?
In the version v1.6.4 is ok.

**Comment by petersirka** [comment]
Hi @satrong,
yes and sorry for it. One company contacted me and they wanted: they have many models which is need to set (they don't use Mongoose). So I had to change loading the framework dependencies.

`Initialization: Modules --> Packages --> Models --> Definitions --> Controllers`

__How to solve this problem?__

1. add `require` to mongoose in each model
2. wrap the model with `framework.on('load', function() {})`

Thanks and sorry for this complication.

**Comment by satrong** [comment]
Thanks for your reply, i have solved this problem. In the release.js, i just write: global.mongoose=require("mongoose").

**Comment by petersirka** [comment]
Super! I published a new version now (with new homepage and new documentation).
Download it.
