### ISSUE TITLE
Using bookshelf js?

### ISSUE THREAD

**Issue by LeventeNagy** [totaljs/framework#231]
I looked at the examples, but did not really help much.

I wanted to use bookshelf.js with the framwork but its not working

In my definitions i made a bookshelf.js file

<pre>
var knex = require('knex')({
  client: 'mysql',
  connection: {
    host     : '127.0.0.1',
    user     : 'root',
    password : '',
    database : 'test',
    charset  : 'utf8'
  }
});

var bookshelf = require('bookshelf')(knex);

global.bookshelf = bookshelf;
</pre>

Created a User model in models folder named User.js

<pre>
var User = bookshelf.Model.extend({
  tableName: 'users'
});

module.exports = User;
</pre>

And i get the following error when i start the server

<code>
======= 2015-01-05 13:22:19: framework.install('model', 'user') ---> ReferenceEr
ror: bookshelf is not defined ReferenceError: bookshelf is not defined
</code>

So im confused and i know im getting it wrong i guess,.isn't the definitions supposed to be a global config?

Because for example, if i console.log out <b>global.bookshelf</b> in my controller (just to test) all fine, but if i do it in my models, i get back undefined,

It only works if define the whole connection over again in every model

Any help?

**Comment by petersirka** [comment]
Hi @LeventeNagy,
we had to change the order loading dependencies, so it is currently:
`Initialization: Modules --> Packages --> Models --> Definitions --> Controllers`

__Solution:__
1. create your own modul e.g. bookshelf with your definition.
2. or wrap the content of the model into the `framework.on('load', function() {});`

Sorry for this change :-( but it was very important.
Thanks!

**Comment by LeventeNagy** [comment]
thank you @petersirka 
Placed it in the modules now its okay

And Happy New Year

**Comment by petersirka** [comment]
Thanks! And Happy New Year too :-))))
