### ISSUE TITLE
Passport js Error: Can't render headers after they are sent to the client

### ISSUE THREAD

**Issue by LeventeNagy** [totaljs/framework#232]
So i took a look at the example, could not figure it out 

I made a passport.js file in my definitions

<pre>
var passport = require('passport')
  , LocalStrategy = require('passport-local').Strategy
  , User = MODEL('user').schema
  , bcrypt = require('bcryptjs');

passport.serializeUser(function(user, done) {
  done(null, user.id);
});

passport.deserializeUser(function(id, done) {
  User.one({id: id}, function(err, user) {
    done(err, user);
  });
});

passport.use(new LocalStrategy({
        usernameField: 'email',
        passwordField: 'password'
    },
    function(email, password, done) {
	  
    User.one({ email: email}, function(err, user) {
	    if (err) { return done(err); }

	    if (!user) { return done(null, false, { message: 'Unknown E-mail address ' + email }); }

	    if (user.password != password) { return done(null, false, { message: 'Invalid password' }); }
	    
	    return done(null, user);
	  });
    }
)); 

framework.middleware('passport.js', passport.initialize());
framework.middleware('passport.js', passport.session());
</pre>

My Controller 

<pre>
exports.install = function(framework) {
	framework.route('/admin', view_admin);
	framework.route('/admin/login', view_login);
	framework.route('/admin/auth', auth, ['post', '#session', '#passport.js']);
}
</pre>

<pre>
function view_admin() {
	var self = this;

	self.view('index')
}

function view_login() {
	var self = this;

	self.view('login')
}

function auth() {
	var self = this;
	passport.authenticate('local')(self.req, self.res, function(err) {
		if (err)
			return console.log(err);

		// self.json(self.user);
		self.json({ object: self.user });
	});

}
</pre>

When i submit the form i get the following error

<pre>
====== 2015-01-09 09:11:08: Error: Can't render headers after they are sent to
he client. Error: Can't render headers after they are sent to the client.
   at ServerResponse.OutgoingMessage._renderHeaders (http.js:731:11)
   at ServerResponse.writeHead (http.js:1152:20)
   at C:\server\apache2\htdocs\total\node_modules\total.js\index.js:2:30593
   at Gzip.onEnd (zlib.js:166:5)
   at Gzip.emit (events.js:117:20)
   at _stream_readable.js:943:16
   at process._tickCallback (node.js:419:13)

</pre>

Am i missing something? Is there a middleware for http? or im doing it wrong?

Thank you

**Comment by petersirka** [comment]
Hi @LeventeNagy,
what version ot total.js do you use?

I looked into it. The problem:
1. the framework executes 408 (request-timeout) because passport does not respond
2. add `self.custom()` before: `auth() action -> passport.authenticate('local')`
3. session is missing (use: https://github.com/totaljs/examples/blob/master/passport.js/definitions/modules.js)

I looked into passport.js examples and they work correctly.
Thanks.

**Comment by LeventeNagy** [comment]
Hello @petersirka 
First sorry for the slow reply, actually module is loaded correctly.

Added self.custom() new problem occured

<pre>

======= 2015-01-09 14:06:49: Error: passport.initialize() middleware not in use
Error: passport.initialize() middleware not in use
    at IncomingMessage.req.login.req.logIn (C:\server\apache2\htdocs\total\node_
modules\passport\lib\http\request.js:44:34)
</pre>

So it can't  initialize because it has a problem: <code>IncomingMessage.req.login.req.logIn     at IncomingMessage.req.login.req.logIn (C:\server\apache2\htdocs\total\node_
modules\passport\lib\http\request.js:44:34)</code>

Any hint on this? Because its od, i tried a nother test by downloading the example files and get the same error. (I am using 1.7.1)

**Comment by petersirka** [comment]
I'll look on it today evening. I'll give you a feedback.

**Comment by LeventeNagy** [comment]
Thank you for your help and time

**Comment by petersirka** [comment]
Hi @LeventeNagy,
please download v1.7.1 again. It's better optimized for passport.js.

And full example:
```javascript
require('total.js');

var passport = require('passport');
var LocalStrategy = require('passport-local').Strategy;

passport.use(new LocalStrategy(function(username, password, done) {
    var user = { alias: '123456' };
    if (username === '123456' && password === '123456')
        return done(null, user);
    return done(null, false, { message: 'Incorrect credentials.' });
}));

F.route('/login/', function() {
    var self = this;
    self.body.username = self.query.username;
    self.body.password = self.query.password;

    // this is better way: failureRedirect: '/failure/'
    passport.authenticate('local', { session: false })(self.req, self.res, function(err) {
        if (err)
            return self.throw500(err);
        self.json(self.user);
    });
}, ['#passport']);

F.middleware('passport', passport.initialize());
F.http('debug');
```

And open ...
```plain
http://127.0.0.1:8000/login/?username=123456&password=123456
```

Thanks!

**Comment by LeventeNagy** [comment]
First would like to thank for your time and help, bust still have an error what i cannot debug
(copied your example and updated total js)
<pre>

======= 2015-01-10 08:39:51: TypeError: Property 'error' of object #<Subscribe>
is not a function TypeError: Property 'error' of object #<Subscribe> is not a fu
nction
    at Subscribe.execute (C:\server\apache2\htdocs\total\node_modules\total.js\i
ndex.js:4:16707)
    at Subscribe.prepare (C:\server\apache2\htdocs\total\node_modules\total.js\i
ndex.js:4:17606)
    at Subscribe.doEnd (C:\server\apache2\htdocs\total\node_modules\total.js\ind
ex.js:4:21308)
    at IncomingMessage.<anonymous> (C:\server\apache2\htdocs\total\node_modules\
total.js\index.js:4:15048)
    at IncomingMessage.emit (events.js:92:17)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
</pre>

I will try to dig in more my self

**Comment by petersirka** [comment]
You don't have latest version from GitHub (I see it in the exception).
<https://www.totaljs.com/share/example-passport.zip> and install passport and passport-local and give me a feedback.

**Comment by LeventeNagy** [comment]
Okay will do

**Comment by LeventeNagy** [comment]
Thank you for your time Peter, now it works as it suposed to.

Thank you again

**Comment by petersirka** [comment]
No, I thank! I found a small bug with your help, thanks.
