### ISSUE TITLE
A suggestion about the IP

### ISSUE THREAD

**Issue by satrong** [totaljs/framework#237]
We can normally get the real IP, but if I use a CDN for my site, I got the IP is the CDN's, so I suggest you can think about it.(I'm a Chinese, my english is not very good)
正常情况下可以获取到用户真实的IP，但是如果网站使用了CDN的话，获取到的IP是节点的IP，所以我建议你考虑一下这种情况。

this is my code:
```js
var ip = self.req.headers["x-real-forwarded-for"] || self.req.ip;
```

**Comment by petersirka** [comment]
Hi @satrong, your english is good -> I understand.
Can you send me __all headers__ from the request? It will be better.

**Comment by satrong** [comment]
Think you, @petersirka 
This is the **self.req.headers**'s info:
```js
{
	"x-real-ip" : "183.60.235.57",
	"x-forwarded-for" : "183.60.235.57",
	"host" : "www.xiaoboy.com",
	"x-nginx-proxy" : "true",
	"connection" : "upgrade",
	"accept-encoding" : "gzip",
	"x-real-forwarded-for" : "116.30.110.198",
	"accept" : "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
	"user-agent" : "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36",
	"accept-language" : "en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4",
	"cookie" : "",
	"x-from" : "FHL"
}
```

**Comment by petersirka** [comment]
... and @satrong which IP is correct in headers for you?
Thanks.

**Comment by satrong** [comment]
@petersirka , you can open this url [http://www.xiaoboy.com/test](http://www.xiaoboy.com/test)
My IP is 116.30.110.198.

**Comment by petersirka** [comment]
You can get `real` IP, right? So your code is correct:
```js
var ip = self.req.headers["x-real-forwarded-for"] || self.req.ip
```
Where is the problem? Those headers are generated through CDN? If yes, where is the problem?

**Comment by satrong** [comment]
Yeah, I can get real IP.
I just want get real IP whether use CDN if I use **self.req.ip**, because I think the CDN's IP is unuseful.
If I use **self.req.ip** can get real IP, I didn't care about if use CDN.
This is just my suggestion.
(Hope you understand my thought.)

**Comment by petersirka** [comment]
Ahaa, I understand. I suggest:

Create some definitions:
```javascript
framework.on('controller', function(controller) {
    controller.realip = self.req.headers["x-real-forwarded-for"] || self.req.ip;
});
```

Usage in controller:
```javascript
exports.install = function() {
   framework.route('/', plain_homepage);
};

function plain_homepage() {
    var self = this;
    self.plain('My IP:' + self.realip);
}
```

**Comment by satrong** [comment]
OK, thank you.
