### ISSUE TITLE
Multiple configurations for each stage

### ISSUE THREAD

**Issue by mateuszgachowski** [totaljs/framework#238]
Hi,

Im using the framework version 1.6.2. I would be great to have something like "stage configs". For now we just have debug and release, but why not just make an option to select the config file which each instance should use?

E.g.:

```js
require('total.js').useConfig('dev').http(); // fires default config for dev env, inside the config we can for example define if its a debug mode or a release mode
require('total.js').useConfig('qa').http(true); // loads the config-qa file and the debug mode is passed via http() method
require('total.js').useConfig('prod').http(); // same as above but uses config-prod
```

What do you think?

Cheers,
Mateusz

**Comment by petersirka** [comment]
Hi @mateuszgachowski,
the framework knows 4x types of configuration file:

1. `config` - global for all modes
2. `config-debug` - for development
3. `config-release` - for production
4. `config-text` - for testing

But I can add this option into the new version. But we must more specify behaviours.

**Comment by mateuszgachowski** [comment]
I understand stages but they are not very "enterprise" tbh.
In enterprise env you will probably have more than just separation between dev and prod. You will have some stages that can use different settings during the deploy journey.

What kind of info you exactly need? Is it possible to just load configs based on "useConfig"?

**Comment by petersirka** [comment]
Yes.
I'll add `framework.useConfig()` today or do you want to add?

Your idea is good:
```js
framework.useConfig('filename in the application root'); // OK?
// or
// what do you think about framework.configure(filename)?
```
But this method must be executed before the framework initialization `F.http()` or `F.https()`.
What do you think about it?
Thanks.

**Comment by mateuszgachowski** [comment]
Looks ok for me. The other option would be to leave the 'config-' prefix for all the configs. It will make clear how the config pattern is defined. Anyway the first option is more flexible.
`filename in the application root` - maybe it can be just a path to the config for example? If you will have multiple configs it would be great to put them in a separate directory (for example: `/configs`).

What do you think?
Thanks,
Mateusz

**Comment by petersirka** [comment]
Yes that's good idea. OK I'll add it today. I'll give you a feedback.

So I'll create: `framework.useConfig()` or `framework.configure()`? What do you think?

**Comment by mateuszgachowski** [comment]
I think that `.configure()` seems that you should pass an object with configuration, `useConfig` seems more "file based" for me. But that is only my opinion - both will work :)

**Comment by petersirka** [comment]
OK I added it:
<https://github.com/totaljs/framework/tree/v1.7.1> try it :-)

Thanks.

**Comment by mateuszgachowski** [comment]
Thanks!
