### ISSUE TITLE
Using fragment for routing

### ISSUE THREAD

**Issue by Antoine-Pous** [totaljs/framework#239]
Hi,

for certain requirement i need to use fragment for routing some query.

The framework seem use it for specific purpose but doesn't allow to use it for our usage.

```Javascript
framework.route('/#{fragment}', test_fragment);

function test_fragment(fragment) {
  var self = this;
  console.log(self.url);
  console.log(fragment);
}
```

Currently nothing seem working with this kind of routing, there is any trick for that?

**Comment by petersirka** [comment]
Hi @Antoine-Pous,
this is not possibble, because:
clients are not supposed to send URI-fragments to servers when they retrieve a document.

Source: <http://en.wikipedia.org/wiki/Fragment_identifier>
Thanks.

**Comment by Antoine-Pous** [comment]
Can we pass values to the controller from the view?

I can get the fragment with a bit of client-side JavaScript.

**Comment by petersirka** [comment]
__Can we pass values to the controller from the view?__
Why do you need this?

__I can get the fragment with a bit of client-side JavaScript.__

Client-side:
```javascript
function locationHashChanged() {
    var hash = location.hash;
    // jQuery request
    $.get('/api/' + hash + '/', function(d) {
        $('#some-container').html(d);
    });
}
window.onhashchange = locationHashChanged;
```

Server-side (controller):
```javascript
exports.install = function() {
    framework.route('/api/{hash}/', view_hash);
};

function view_hash(hash) {
    var self = this;
    // disable layout
    self.layout('');
    // respond: view according to the hash
    self.view(hash);
}
```
Do you understand? Thanks.

**Comment by Antoine-Pous** [comment]
I understand, i have already choose this way :+1: 

Thank you for your help
