### ISSUE TITLE
init total.js project issue

### ISSUE THREAD

**Issue by stact** [totaljs/framework#241]
Hi,

When we install a fresh total.js with npm

<code>$ npm install -g total.js </code>
<code>$ total -angular </code>

It seems that angular modules file is truncated

Can you check if something went wrong please recently?
Thank you for your feedback

**Comment by petersirka** [comment]
Hi @stact,
holy shit, you're right. I'll publish a new version today. I'll give you feedback.

**Comment by petersirka** [comment]
Hi @stact I published it now.
Thanks.

**Comment by stact** [comment]
Thank you!
