### ISSUE TITLE
Session is undefined after redirect

### ISSUE THREAD

**Issue by LeventeNagy** [totaljs/framework#244]
So i was able to improve passport js more, got back to my project and what i dont really understand is, after a redirect the session gets destroyed (atleast it seem like)

route
<pre>
framework.route('/auth', auth, ['post', '#session', '#passport'])
</pre>
 login 

<pre>
function auth() {
    var self = this;

    passport.authenticate('local', function(err, user, info) {
    
    if (err) { throw err; }

    if (!user) { 

    	return self.redirect('/login'); 
    }
    
    self.req.logIn(user, function(err) {

      if (err) { throw err; }

      self.session.user = user.dataValues;
      
      console.log('session', self.session.user.id);

       return self.redirect('/');
    });

  })(self.req, self.res);

}
</pre>

I get back <code>session 1</code>

But after the redirect is done it gives <code>session null</code>

Any help or hint?

**Comment by LeventeNagy** [comment]
Oh im so stupid, forgott to pass it to my route.

Sorry

**Comment by petersirka** [comment]
:-) Hi @LeventeNagy super :-) thanks.
