### ISSUE TITLE
"Bug" in doc

### ISSUE THREAD

**Issue by dacrhu** [totaljs/framework#247]
Hi,

in page:
http://docs.totaljs.com/v1.7.x/en.html#api~FrameworkCache

framework.cache.add('key', 'value', '5 minutes');
\- console.log(framework.get('key'));
\+ console.log(framework.cache.get('key'));

controller.cache.add('key', { name: 'Peter Širka' }, new Date().add('minute', 10));
\- console.log(controller.get('key'));
\+ console.log(controller.cache.get('key'));

**Comment by petersirka** [comment]
Thanks, I fixed it.
