### ISSUE TITLE
How to disable css and javascript minifier?

### ISSUE THREAD

**Issue by nonameplum** [totaljs/framework#25]
Hi

When I'm debugging application I want to disable javascript/css minifier.
How can I do that?

Best regards,
Lukas

**Comment by capslow** [comment]
I am having a problem with the javascript compressor. The message I get is the following one: JavaScript compressor ---> ReferenceError: c is not defined ReferenceError: c is not defined.
I don't know how to solve this, I tries everything, an even if I put the javascript code in a .min.js file I get this message. Is there any possibility to disable the javascript compressor now?

**Comment by petersirka** [comment]
Hi @capslow,
can you send me your js file? What version of total.js do you have?

Disable minification:
<http://docs.totaljs.com/v1.7.x/en.html#api~FrameworkConfiguration~allow-compile-js>

**Comment by capslow** [comment]
Hi @petersirka ,
Thank you for answering so quick. Finally I was able to solve the problem, I think that I was making a mistake in the javascript or something like that.
Sorry for the inconveniences and thanks for developing such a  great tool.

**Comment by petersirka** [comment]
Thanks, no problem :+1:
