### ISSUE TITLE
Logfile separate request

### ISSUE THREAD

**Issue by dacrhu** [totaljs/framework#252]
Hi Peter,

I would like separate the log files.
Example:
2015-03-01_access.log
2015-03-01_error.log
...

Can you make a new method?
Example:
framework.logWithName(name, [param..1], [param..2], [param..n]);

Thank you for your time!

**Comment by petersirka** [comment]
Hi @dacrhu,
good idea, but should the method add a date stamp before the filename?

Thanks

**Comment by dacrhu** [comment]
After or before, all the same. The date will be helpful.

**Comment by petersirka** [comment]
Sorry, I mean whether is the date important for filename. My idea is filename without date because each line in log file will have date/time stamp. What do you think about it?

**Comment by dacrhu** [comment]
Will framework rotating log same like currently? Or in the future need to rotate the logs with logrotate application?

**Comment by petersirka** [comment]
Sorry I don't understand completely. But logs will same as today in near future. I added:

```javascript
F.logger('access', true, false, 'OK'); 
controller.logger('access', true, false, 'OK');
LOGGER('access', true, false, 'OK');
```

**Comment by dacrhu** [comment]
Sorry, my english is bad :)

Currently in documents page I find one function: framework.log().
This method make files, something like this: YYYY-MM-DD.log
Therefore I suggested similar filenames.

Thank you for your work!

**Comment by petersirka** [comment]
No no, I understand you. Try it, but I removed a date from a filename because you can specify the filename. It's a development version, so please test it. Thanks!

Here is the change: <https://github.com/totaljs/framework/tree/v1.7.3>
Code: <https://github.com/totaljs/framework/commit/ce72a3517ebe56047ed1e34f213737b398edb611>

**Comment by dacrhu** [comment]
Ok, working fine, thx! Eventually I can init a Date object to filename. ;)

**Comment by petersirka** [comment]
Yes, so can be this solution in new version?
Thanks.

**Comment by dacrhu** [comment]
Yes, it is perfect!
