### ISSUE TITLE
removeDiacritics bug

### ISSUE THREAD

**Issue by dacrhu** [totaljs/framework#253]
Hi,

Utils.removeDiacritics('Árvíztűrő tükörfúrógép');

Result: "Arviztűrő tukorfurogep"

Thank you,
David

**Comment by petersirka** [comment]
Hi @dacrhu,
I fixed it and it's better/faster about about 30%. Please download latest version from GitHub (branch: 1.7.3)

https://github.com/totaljs/framework/commit/576efeea16a07d4d10013ae746d52fb36802790b

Thanks.

**Comment by dacrhu** [comment]
Thx!
