### ISSUE TITLE
Large scale application

### ISSUE THREAD

**Issue by tegeek** [totaljs/framework#254]
Once you've more than 30 controllers, complex domain logic, large database etc. it is very hard to maintain the project according to current directory structure. May be its only me but I feel & experience it is much better to organize any medium to large application into separate modules. And then each module contains controllers, views, domain logic etc. This way we can share modules across different projects. 

So the end product's directory structure looks like this 

 --- application 
       ------server 
         --------- user_registration 
                     ---- controllers 
                     ---- views 
                     .... definitions 
                     ---- tests 

     ------client       
        ----- shopping_cart 
           ---- controllers 
           ---- views 
           ---- services 

I would say almost any kind of application (small, medium or large) can be maintained better with this kind of directory structure and one module can be shared with other modules by just dropping a folder inside modules folders. A module becomes a pretty decoupled from any others (only shared common Utility functions provided by the totaljs or some shared libraries.)

Overall totaljs is a nice framework with all the batteries provided.

**Comment by petersirka** [comment]
Hi @tegeek,
thanks for feedback.

The packages are similar as your idea (but they will need to be packed):
<http://docs.totaljs.com/v1.7.x/en.html#pages~Packages>

Can you create a small example (.zip) with your idea of directory structure? The example should not work. Thanks!

**Comment by tegeek** [comment]
Ok, I looked at the source code of totaljs and it'll be a little tricky to have my preferred directory structure and probably will have to do some breaking changes. And doing all that just for another directory structure isn't wise at all. 

Another thing I'm wondering once you've definitions, models and controllers, how you unit test each component and how you can inject the other as dependency during tests?

**Comment by petersirka** [comment]
You don't need to change the source-code. I want to see some "example application" with good directory structure. I want to understand it.

Unit tests in total.js are not a magic. The framework starts the server and perform requests or methods to tests. Controllers are tested via internal requests into controller actions or the framework tests the methods. So you can inject some depedency during the test.

This example describes the functionality of unit-tests in total.js:
<https://github.com/totaljs/examples/tree/master/assertion-testing>

Thanks

**Comment by tegeek** [comment]
I created the directory structure [here](https://github.com/tegeek/appstructure)

1. server -- contains all the server side code 
2. client -- contains the client side code (this code be angularjs related or any custom js code, this code can also use npm modules via browserify)
3. node_modules are, well, the node packages. 

Now if you see the server folder it contains shared (which is shared code like Util functions, etc.) and 
modules. (modules can also be named plugins). 
Every module or plugin is a self-contained fully independant code from other modules/plugins. The action folders are basically controller functions. views are the views only for that module. 
I put two extra files Init.js and package.json. totaljs can load Init.js and that will define what the module will expose to the outside world. The package.json file can contains module config, and some other things. 

This way every module can be shared with other totaljs applications by simply copying pasting and without fearing of breaking anything. This structure can be scaled to any size of application. 

We can have wrapper around nodejs's module system to resolve modules at "compile" time which means when totaljs runs, it can look which modules using others and see if they are present and in case failure we can stop the loading further. 

I've actually idea and some code which can provide this but i'm not sure the scope of totaljs or others like the idea.

**Comment by petersirka** [comment]
I'm here. It's not bad idea but it's too different than total.js. The directory structure is the base of the framework. I thought about it and currently I don't see a way for implementation it in near future. But I'll think about it. I want to improve the current state of the framework, so maybe for large application (for some peoples) is need to update the core of the framework. The change is not code only, there is a more things (documentation, examples, etc.). Thanks for your idea, I'll think about it and maybe I'll implement a part of them.

:100:

**Comment by petersirka** [comment]
I have closed this issue.

**Comment by neonnds** [comment]
Just for those interrested. I have several total.js projects that build on top of a base project. 

-Core-Site
--controllers
---Core-Site
----home.js
--assets
---static
---views
...

-SiteA
--controllers
---SiteA
----home.js
--assets
---static
---views
...

-SiteB
--controllers
---SiteB
----home.js
--assets
---static
---views
...

This allows me to share code easily etc, and not double up effort from project to project. 

I then have a bash script that deploys resources (controllers, views, etc) into a new site..called Live.

So for example: $> ./delpoy.sh SiteA

This would result in a new project with the following structure:

-Live
--controllers
---Core-Site
----home.js
---SiteA
----home.js
--assets
---static
---views

I can then just run the live site with nodejs.

There are problems with this approach, in that you have to deploy every time a resource changes. But if your from the J2EE world this is normal. It also means you have to be careful not to have resource collisions and url mapping issues. I solve this by putting resources in folders with the site name and I have a mapping JS file for urls.

Just food for thought...for those with large sites and doubled up resources.
