### ISSUE TITLE
Sending utf-8 data over websockets

### ISSUE THREAD

**Issue by fatihky** [totaljs/framework#257]
I am tried to send "Hoş Geldin" over websocket, it sends as "Ho_ Geldin" to client. How can I send "Hoş Geldin" to client.
Note: I am turned off 'default-websocket-encodedecode'. And "Hoş Geldin" means "Welcome" in Turkish.

**Comment by petersirka** [comment]
Hi @fatihky,
you must turn on `default-websocket-encodedecode`. Here is a screenshot from an example: <https://github.com/totaljs/examples/tree/master/websocket>.

![Screenshot](https://www.online-clipboard.com/142674601588922175f694f4aabax28/clipboard.png)

Thanks.

**Comment by fatihky** [comment]
Hi @petersirka, thanks for your response. I tried this and it is working now.

**Comment by petersirka** [comment]
Great! Thanks!
