### ISSUE TITLE
Modularisation of total.js

### ISSUE THREAD

**Issue by neonnds** [totaljs/framework#258]
I've had an itch i've needed to scratch since the partial.js days.

I like to use handle-bars.js for my templating and I like to use my own form validation library. I'm also in favour of modular design over monolithic.

Is it possible to move total.js templating and form validation out of index.js and into their own modules. Just like the nosql.js, image.js and mail.js have been. 

I'm sure this will also assist in reducing maintenance and future proofing the framework in case you decide to cut out certain components etc.

**Comment by petersirka** [comment]
Hi @neonnds,
I understand. Currently I don't think about splitting the view engine and the validation into the single files (I don't see any benefits now). The modular design is not bad, but it's not the win (everything has pros and cons). As an idea into the near future: OK. I want a total solution with several options for different developers.

I added option to rewrite the view engine and other functionality. The validation can be overwritten too `Utils.validation()`.

Thanks for the feedback!

**Comment by neonnds** [comment]
Ok sounds good. Its nice to know you can overwriting existing functionality, but ultimately its best to be able to say...this is the core framework...and these are auxiliary modules that are optional. Keep up the good work.
