### ISSUE TITLE
Websocket 302 (redirect) error

### ISSUE THREAD

**Issue by darrudi** [totaljs/framework#259]
Hi Peter,
I have this problem and I guess it is not related to total.js specifically. I wonder if you have any idea regarding this strange problem of mine:
From some clients I cannot connect to the total's websockets. I receive a 302 redirect response which is quite odd.
The client side:
```
var websocket = new WebSocket('mail.nikoo.ir');
```
server side:
```
exports.install = function(framework) {

	framework.websocket('/', socket_homepage, ['json']);
};

function socket_homepage() {
    // the rest of logic
}
```
The error I receive on the Chrome's console:
```
WebSocket connection to 'ws://mail.nikoo.ir/' failed: Error during WebSocket handshake: Unexpected response code: 302
```
The Chrome's network tab says:

![untitled](https://cloud.githubusercontent.com/assets/5983954/6780848/3a5984c2-d186-11e4-9f3c-d75f1a274878.png)

Interestingly I can connect from another computer:

![untitled](https://cloud.githubusercontent.com/assets/5983954/6780783/e12666cc-d185-11e4-86a7-334a336dfa5c.png)

Do you think that it is a network-related issue? Or maybe something is meddling with the websocket connection? 
My total's version is `1.7.2`

**Comment by petersirka** [comment]
Hi @darrudi,
this is very interesting.

Do you use some middleware?
Do you work with a raw response object?

Can you send me on my e-mail (some) login name and password for testing? I'm worried about response headers, why is there 302 .... Don't worry, we'll resolve it.

Thanks!

**Comment by darrudi** [comment]
Sure, Please navigate to:
http://mail.nikoo.ir
and use the following info to login (sorry, the language is in Persian):

![untitled](https://cloud.githubusercontent.com/assets/5983954/6781264/111bf974-d18a-11e4-861d-a074e1c775e8.png)

then look for a websocket error on the Chrome's or Firefox's console.

However it is quite probable that you would not encounter any problem. As I mentioned before this problem happens for some computers residing on some networks. I can't figure out what causes the problem!

And thanx for your help Peter! :)

**Comment by petersirka** [comment]
The language it's ok, design is intuitive.
I don't see any problem in my Chrome and Firefox (under OSX) everything works correctly. As I say: 302 code in the response is very interesting. I think that I must see a code.

Are you sure that you do not use `res.redirect` in websocket?
Thanks.

**Comment by darrudi** [comment]
Thanks for the compliments! :)
Yeah, I am sure that there isn't any redirect involved in the websocket logic.
I traced the error and found out that when that cursed error happens it is actually handled by my default http route! it is my `default.js`:
```
exports.install = function (framework) {
	//framework.route('/*', view_app);
	framework.route('/*', view_app);
	framework.route('/home', view_home);
	framework.route('/print', view_print);
	framework.route('/policy', view_policy);
};

function view_app() {
	var self = this;
	return self.redirect('/login');
}
//...
```
When that 302 error shows up, the `'/*'` routes has been activated indeed! This route redirects the user to the login page as you saw in the redirect response.
I guess there is nothing wrong with `total.js`. However the websocket `upgrade` request is turned into an ordinary http request somehow, somewhere!
I will dig into the matter tomorrow and post my findings here. If I failed I'd post the code for your kind review.
Thanks again Peter,

**Comment by petersirka** [comment]
@darrudi thanks! Please give me a feedback, I'd like to help you.

**Comment by petersirka** [comment]
Hi @darrudi any news?
Thanks.

**Comment by darrudi** [comment]
Sorry Peter, I was on a trip and had no access to internet at all. 
Now after a few days I cannot reproduce the problem! I am on the same computer and the same network. It is mind boggling indeed! It is completely sporadic in nature.
Anyway, I continue monitoring the websocket problem and let you know when it happens again. Please leave the issue open for a few more days.
Thanx

**Comment by darrudi** [comment]
Hi Peter, 
I extensively investigated the problem. I logged incoming connections to total.js and noticed wesocket connections have no `upgrade` command in this situation. e.g:
```
headers: 
   { host: 'staging.nikoo.ir',
     pragma: 'no-cache',
     origin: 'http://staging.nikoo.ir',
     'sec-websocket-version': '13',
     'user-agent': 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36',
     'accept-encoding': 'gzip, deflate, sdch',
     'accept-language': 'en-US,en;q=0.8,fa;q=0.6',
     cookie: '__ssid=OTc9QU4CT0wNHE1cW0NKcVlMAQocHk0GDVwbW1cPZm9kLDQ8MGtGEVQfVwcEAkltSVJGSgNOBx8eDBIYSE5ETA0OGx9KHhEjOWw4aD8oZD1ARw; ...',
     'sec-websocket-key': '2plrNNLzVAix5Ww2MBVWkg==',
     'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits',
     'cache-control': 'no-cache, max-age=0',
     connection: 'keep-alive' }
```
it is the expected headers (a working example):
```
headers: 
   { host: 'staging.nikoo.ir',
     connection: 'Upgrade',
     pragma: 'no-cache',
     'cache-control': 'no-cache',
     upgrade: 'websocket',
     origin: 'http://staging.nikoo.ir',
     'sec-websocket-version': '13',
     'user-agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36',
     'accept-encoding': 'gzip, deflate, sdch',
     'accept-language': 'en-US,en;q=0.8,fa;q=0.6',
     cookie: '__ssid=OTc9QU4CT0wNHE1cW0NKcQoaBFkZSUpXDwgbW1cPZm9kLDQ8Yz1DQlFIUFYGVkltSVJGSgNOBx8eDBIYSE5ETA0OGx9KHhEjajo9Ozp-Y2xCEw;...',
     'sec-websocket-key': 'voIySAu7w3K4wloc288Gfg==',
     'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits' }
```
So the faulty request is the culprit and I can say for sure that it has nothing to do with `total.js`. 
I checked websocket connections from my computer to another tested server (http://www.websocket.org/echo.html) and found them to be broken too. I don't know if it is my ISP or a third-party application (antivirus, etc) on my computers which causes the problem. I'll check it out further and post the result here when I cornered the issue.

**Comment by petersirka** [comment]
Hi @darrudi,
thanks for feedback.
