### ISSUE TITLE
Request Payload vs. Form Data

### ISSUE THREAD

**Issue by eMarek** [totaljs/framework#26]
I was used to **jQuery** in my apps and I was doing ajax request like this:

``` js
$('#btn-login').click(function() {
    $.ajax({
        type: 'post',
        url: '/login',
        data: {
            username: $('#username').val(),
            password: $('#password').val()
        },
        success: function(server) {
            alert('ok');
        },
        dataType: 'json'
    });
});
```

If I take a look on my ajax request in  `Chrome Developer Tools` under `Network` tab, I see that `username` and `password` were sent like **Form Data**.
## ![screen shot 2013-08-10 at 4 59 09 pm](https://f.cloud.github.com/assets/311634/942705/4ed7c1c2-01ce-11e3-980e-1fe322643648.png)

Lately I am testing **angular.js** and a similar ajax request I do with $http service:

``` js
$scope.login = function() {
    $http.post('/login', {
        username: $scope.username,
        password: $scope.password,
    }).success(function() {
        alert('ok');
    });
}
```

I noticed the difference how the data were sent. In this case with angular `username` and `password` were sent like **Request Payload**.
## ![screen shot 2013-08-10 at 5 01 11 pm](https://f.cloud.github.com/assets/311634/942709/6e9863ea-01ce-11e3-87a5-e6a5a7127bb1.png)

The question is how to get Request Payload data in partial.js? In the case with jQuery I simply do `self.post.username` and `self.post.password`. In the case with angular.js I am without any idea.

**Comment by sahilsethi16** [comment]
Hii,
Can anyone tell me how insert image file in the request payload which is stored in local file system???
Thanks in advance.

**Comment by petersirka** [comment]
HI @sahilsethi16,
did you mean from the server-side or client-side?

Thanks.

**Comment by sahilsethi16** [comment]
I have to send some image in my ajax request to server. my question is how to insert it its request payload

snippet is 

var settings = {
  "url": "https://servername.com/profiles/photo.do?key=a16895d8-2fe8-46d7-9658-8194d9b2ecc8",
  "method": "PUT",
  "headers": {
    "authorization": "Basic c2FoaWwuc2V0aGk6V2VsY29tZUAwNw==",
    "content-type": "image/jpeg"
  }
}

Now how to insert a image in its payload?

**Comment by EnhengBenben** [comment]
Hi
when I send form as form data,like "key":"value".
but,how to send my array,like "skills": [[{id:1,name:"tom"}]]

**Comment by molda** [comment]
Hi
 there are multiple ways to send array to server. What have you tried so far? What didn't work for you? Have you tried JSON.stringify or jQuery.serialize?

**Comment by mansouridonia** [comment]
Hi,
It's my first time to work with web service, so can anyone of you help me? I want to know how to consume a JSON web service? When I  consulted the Developer tools in Chrome, I've found this:
![sans titre](https://user-images.githubusercontent.com/30044947/28015835-c9feae8a-6569-11e7-9709-b2761ae998b9.png)

**Comment by petersirka** [comment]
@mansouridonia do you want to call this web service in Total.js application? Can you write me on Total.js Messenger, it will be faster.
