### ISSUE TITLE
TotalJS is support .coffee file 

### ISSUE THREAD

**Issue by evmek** [totaljs/framework#260]
Hi,

Is TotalJS supporting .coffee file  in totalJS folders (Modules , Packages , Models , Definitions , Controllers) ?

I read "http://docs.totaljs.com/v1.7.x/en.html#api~Framework~framework.isCoffee" but no understand.

I dont find examples in "https://github.com/totaljs/examples" for it.

Can you write sample code for me

Thanks,

**Comment by petersirka** [comment]
Hi @evmek,
older versions of total.js support coffee script, but I had to remove it because I had a lot of work with it. Also `v1.7.x` doesn't support coffee scripts. Sorry :-1:

**Comment by evmek** [comment]
Ok. No problem.
I was solved by CoffeeScript --watch param.

Thanks
