### ISSUE TITLE
layout.html

### ISSUE THREAD

**Issue by sarankup** [totaljs/framework#261]
Hi,

It looks like all my view files are wrapped with layout.html by default. Please advise, how to create multiple layout files and configure? ie., instead of only one layout.html, I want to create various layout files and which will import different view files.

Are there anyway, I can ignore the layout file and just display the view file only?

**Comment by petersirka** [comment]
Hi @sarankup,
the framework supports multiple layouts. The layout is a plain html (view) file with one tag `@{body}` in addition.

__views/layout1.html__
```html
...
<h1>Layout 1</h1>
@{body}
...
```

__views/layout2.html__
```html
...
<h1>Layout 2</h1>
@{body}
...
```

__views/index.html__
```html
@{layout('layout2')}
My content.
```

__views/contact.html__
```html
@{layout('layout1')}
My content.
```

__views/nolayout.html__
```html
@{layout('')}
Without layout.
```

In views: <http://docs.totaljs.com/v1.7.x/en.html#api~FrameworkViews~%40%7Blayout>
In controllers: <http://docs.totaljs.com/v1.7.x/en.html#api~FrameworkController~controller.layout>
In config: <http://docs.totaljs.com/v1.7.x/en.html#api~FrameworkConfiguration~default-layout>

Thanks!

**Comment by petersirka** [comment]
I close this issue.

**Comment by sarankup** [comment]
total.js is brilliant. Thanks Petersirka.
