### ISSUE TITLE
Additional functionality

### ISSUE THREAD

**Issue by neonnds** [totaljs/framework#262]
I use Handlebars for my views. But I haven't found a native total.js way of integrating the two. What I do is add two functions **view** and **html** to the framework. 

To get the raw view to process from the filesystem I use **view**. 
To respond with a rendered html page I use **html**. 

I couldn't find such functions in index.js that i could call directly from the controller. Am I missing an easier way to do this? Any help is appreaciated :)  My solution is below:

```javascript

//in index.js
/*
        Response with type as text/html
        @contentBody {String}
        @headers {Object} :: optional
        return {Controller};
*/
Controller.prototype.html = function(contentBody, headers) {

        var self = this;

        return this.content(contentBody, "text/html", headers);
};

/*
        Return a view's raw content from filesystem
        @name {String}
        return {String}; string is returned
*/
Controller.prototype.view = function(name) {
        var self = this;

        var filename = utils.combine(self.config['directory-views'], name + '.html');

        var tmp = '';

        if(fs.existsSync(filename))
            tmp = fs.readFileSync(filename).toString(ENCODING);

        return tmp;
};
```

And now my controller that uses these functions:

```javascript
function getHomePage()
{
        var self = this;

        var model = {};

        //Get raw html view
        var source = self.view(view);

        //Get handlebars to render it using supplied model
        var template = hb.compile(source);
        var out = template(model);
 
        //Return a html page to the browser
        self.html(out);
}
```

**Comment by petersirka** [comment]
Hi @neonnds,
I created a module with handlerbars:
<https://github.com/totaljs/modules/blob/master/View%20Engines/handlebars/v1.00/handlebars.js>

__HOT NEWS: I added today:__
<https://bufferwall.com/blogs/2015-03-26-beta-version-total-js-supports-multiple-view-engines-together/>

**Comment by neonnds** [comment]
Good work. Love your work!
