### ISSUE TITLE
400 (Bad Request)

### ISSUE THREAD

**Issue by sarankup** [totaljs/framework#263]
Hi,

I am using <textarea> in my form and the textarea is managed by CKEditor. When I post the form using below code, I am getting 400 (Bad Request error).

$('#formsubmit').click(function(){
    CKEDITOR.instances.brief.updateElement();
    $.ajax({
		type:"POST",data:$("#postform").serialize(),url:"postsubmit",
		success:function(data){
            console.log(data);
		}
	});
});

However, if I delete the <textarea> or remove the CKEditor from <textarea> the post works well. Please advise how to fix.

**Comment by petersirka** [comment]
Hi @sarankup,
show me the server-side `route` implementation. I think that the problem is in __XSS__ (because CKEditor sends HTML content), try to add `xss` to route flags and give me a feedback.

Thanks

**Comment by sarankup** [comment]
Hi @Petersirka,

I am not sure on this route implementation. Here is my controller
framework.route('/postsubmit',postsubmit,['post']);


function postsubmit(){
	var self=this;
	var model=self.body;
    model.by=new Date();
	var myDate=new Date();
	myDate.setHours(myDate.getHours()+model.expire);
	model.expire=myDate;
	var users=framework.database('post');
    users.insert(model,{w:1},function(err,object){
        if(err){console.warn(err.message);}
        else{console.dir(object);
        }
    });
    sendemail();
	self.json({success:true});
}

**Comment by petersirka** [comment]
Try to change it:
```javascript
framework.route('/postsubmit', postsubmit, ['post', 'xss']);
```

**Comment by sarankup** [comment]
Hi @Petersirka,

Thank you so much. It works very well. I think, I need study the documentation.

**Comment by petersirka** [comment]
Great! Thanks.
