### ISSUE TITLE
woff 2.0 get 404 in public directory

### ISSUE THREAD

**Issue by hepr** [totaljs/framework#264]
Hi,

I've included font-awesome in my public directory and in the css it include fontawesome-webfont.woff2. The file is in good directory but I've got a 404.
The same file in same directory with woff extension is ok, but not if the file .woff2

Regards,

Herve

**Comment by petersirka** [comment]
Hi @hepr,
do you have the latest beta version?

`$ npm install total.js@beta`

Give me a feedback.

**Comment by hepr** [comment]
Hi Peter,

all is good with beta version

Thanks,

Herve

Herve Prot

President LE&CO
2 rue des Faubourgs
F-63960 Veyre-Monton
Tel : +33 6 76 76 17 65
herve.prot@leandco.fr


2015-04-02 9:45 GMT+02:00 Peter Širka <notifications@github.com>:

**Comment by petersirka** [comment]
OK super. I'll publish a new version in few days.
Thanks!
