### ISSUE TITLE
header view

### ISSUE THREAD

**Issue by sarankup** [totaljs/framework#265]
Hi,

For learning purposes,
[1] In couple of ways .js can be imported into page into total.js. They are,
@{js('bootstrap.min')}
<script src='bootstrap.min.js' type='text/javascript'>

Are there any advantage one method over the other, interms of performance, speed...

[2] Especially with favicon,
This works for me <link rel="icon" href="logo.png" type="image/png">
But not when @{favicon('logo.png')}
Please advise how to call png images as favicon.

**Comment by petersirka** [comment]
HI @sarankup,
I have tested `favicon('logo.png')` and it works correctly. Try to add `.png` to `@{favicon()}` and check it via HTML source-code.

![image](https://cloud.githubusercontent.com/assets/2414252/6979502/083c39fa-d9e5-11e4-9ffb-e1ad688db39a.png)

Give me a feedback.

**Comment by sarankup** [comment]
Hi @petersirka,

Thank you so much. I think, I had refreshing issue in the browser. total.js rocks!

**Comment by petersirka** [comment]
Super :+1:
