### ISSUE TITLE
http page parameters (restapi)

### ISSUE THREAD

**Issue by sarankup** [totaljs/framework#266]
Hi,

My framework is self.view('/passport',{m:''});

When I open a page 'passport', and can be able to access the post parameter in my html using @{model.m}

However, when I open the same page from my external applications using rest like
http://localhost:8000/passport?m=1000, @{model.m} is not giving any value.

Please advise.

**Comment by petersirka** [comment]
Hi @sarankup,
you can use:

```html
GET/DELETE: @{query.m}
POST/PUT: @{body.m}
MODLE: @{model.m}
```

```javascript
// model will be contain a GET/DELETE params
self.view('/passport', self.query);

// or

// model will be contain a POST/PUT params
self.view('/passport', self.body);
```
