### ISSUE TITLE
HTTP method routing using JSON 

### ISSUE THREAD

**Issue by manglade** [totaljs/framework#267]
Hi Peter, 

I encountered the following issue. When defining routes using twice the same URL, different functions and switching from get to post method, it seems that it's getting routed in the "get" path systematically. 

Example : 

F.route('/',json_test,['get','json']);
F.route('/',json_test_b,['post','json']);

=> the POST route in never invoked despite the fact that the request is a post request. The GET route function is called no matter what HTTP Method I use to send my request.  

If I comment out the GET route and re-send a POST request it is handled succesfully. 

My total.js version is 1.7.2 

Thanks for your help.

**Comment by petersirka** [comment]
Hi @manglade,
`json` flag is not possible to use with `get` method, because `json` flags checks if the request content-type is `application/json` -> and it will never be. If you remove `json` flag -> everything will be work correctly.

**Comment by manglade** [comment]
Hi Peter, 

Thanks for your very quick response. Maybe I should have specified that at the end of both methods I return a json stream using self.json(...). So If I remove the json flag and keep invoking my API, I get a 400 response.

**Comment by petersirka** [comment]
@manglade, sorry ... :-D :-D I read very quickly and I have skipped the important.
I'll look into it today and I'll give you a feedback.

Thanks.

**Comment by manglade** [comment]
Great !!! Thanks for your availability and efforts !

**Comment by petersirka** [comment]
I have fixed it, please try it:
`npm install total.js@beta`

Thanks :+1:

**Comment by manglade** [comment]
Hi Peter, 

Still have the same behavior, sorry :(

**Comment by petersirka** [comment]
I have tested it now and everything works.
<https://www.dropbox.com/s/r7rnswfehdbhi5p/test.js>

1. GET with application/json header: executes `json_test`
2. GET without application/json header: executes `404`
3. POST with application/json header: executes `json_test_b`
4. POST without application/json header: __connection destroyed__
5. POST with application/json and bad data: executes `400 - bad request`

It works.

**Comment by manglade** [comment]
Hi Peter, 

I must be missing something, what I did was to  create an index.js file that contains the first line of your dropbox example (require(total) etc). Then I started my node server on this JS file. I copy/pasted the whole example and here's what I get in the console : 

GET: GET undefined
GET: POST application/json
GET: POST application/json
GET: POST application/json
GET: POST application/json

So eventhough the self.req.method is correct when using post it is still invoking the GET action, right ? 

Sorry for bothering you with that.

**Comment by petersirka** [comment]
I think that you have a bad version of total.js. Check the version like this:

![Postman](https://cloud.githubusercontent.com/assets/2414252/7119813/0df798fe-e209-11e4-89d1-d7e4fb45b8c1.png)

**Comment by manglade** [comment]
Hi Peter, 
The version is wrong I still have the build 50 instead of 51 but I can't get to install the version 51 could you publish it please ?

**Comment by petersirka** [comment]
Hi @manglade,
NPM contains `-52` build, try to install it.

**Comment by manglade** [comment]
Hi Peter, 

My bad, when I try the 51 build, it works just fine. Thanks for everything.
