### ISSUE TITLE
Authorization definition runs everywhere

### ISSUE THREAD

**Issue by LeventeNagy** [totaljs/framework#269]
Hello Peter

I took a look at the examples and im sure i'm doing something wrong.

I use passport js for authentication, works fine, andcheck with passport if the user is logged in or not.

If i create the definition folder containing the <code>authorization.js</code>

authorization.js code

<pre>
framework.onAuthorization = function(req, res, flags, next) {

	if (!req.isAuthenticated()) {
		res.redirect('login');
	};

};
</pre>

I pass the flag to my default controller

<pre>
exports.install = function() {
    F.route('/', view_app, ['authorize']);
};

function view_app() {
    var self = this;

    self.view('app');
}
</pre>

It works, but not for the specified route, it runs on every server startup and applies for all routes

Could you please give me a hint what im doing wrong?

**Comment by petersirka** [comment]
Hi @LeventeNagy,

```javascript
F.onAuthorization = function(req, res, flags, next) {
    next(req.isAuthenticated());
};
```

You must not redirect in `onAuthorization` because the route mechanism waits for the result and then evaluates other routes.

Thanks :-)

**Comment by LeventeNagy** [comment]
Oh, thank you again, and sorry for my stupid question.
Hope this framework stays alive long, keep up the good work, cheers, and thanks again

**Comment by petersirka** [comment]
No problem, it's ok.
