### ISSUE TITLE
config

### ISSUE THREAD

**Issue by g13013** [totaljs/framework#271]
#### Suggestion
move the configuration to the directory `config` and optionally parse json config formats with support for comments and array values. 

#### Reason
the actual config file prevented me to create the `config` folder

### Steps
* implement
* Raise deprecation for old config formats and location
* remove in the next version

what do you think ? I can help if you agree.

**Comment by petersirka** [comment]
I understand, but all directories (with expect `public`) are in plural (so you can create `configs` directory) and implementation for `config` directory is really hard for current state (we must think on existing documetation, examples and projects). I don't see any benefits, what are benefits?

Thanks.

**Comment by g13013** [comment]
oh it's unfortunate, it's because sometimes other modules/utils/cli's use predefined directories

**Comment by petersirka** [comment]
I understand, but I must keep backward compatibility. We can create only `configs` directory, but what will it do? (behavior)

Thanks.

**Comment by g13013** [comment]
`backward compatibility` Sure , that's why I suggested raising a deprecation message on the console to let the time for developers to migrate to the new config

I think about a structure like this:
```
configs/
    main.json // `default` accessible with `framework.config.main.key
    main_debug.json // `default` accessible with `framework.config.main.key
    custom.json // accessible with `framework.config.custom.key
    custom_debug.json // accessible with `framework.config.custom.debugKey
    ....
```

**Comment by petersirka** [comment]
I'm thinking about it, give me a time. I'm considering...
Thanks.

**Comment by g13013** [comment]
contact me if you need help 👍

**Comment by petersirka** [comment]
Sorry for delay. Done, this behaviour has been added.

`npm install total.js@beta`

Thanks.

**Comment by petersirka** [comment]
Behaviour:

```html
/configs/my-custom-config         - this config file is loaded for all modes (debug, release, test)
/configs/my-custom-config-debug   - this config file is loaded only for debug mode
/configs/my-custom-config-release - this config file is loaded only for release mode
/configs/my-custom-config-test    - this config file is loaded only for test mode
```

**Comment by g13013** [comment]
Awesome, thank you so much :)
