### ISSUE TITLE
Passport js stopped working after upgrade

### ISSUE THREAD

**Issue by LeventeNagy** [totaljs/framework#272]
Hello @petersirka 

Do not know what really happend, i upgraded from 1.7.2 to 1.8.0 and passport js stopped working as it should be

I created a module to check if a use is logged in

Authcheck module

<pre>
F.middleware('authcheck', function(req, res, next) {
    if (req.isAuthenticated()) {
        return res.json('all okay');
    } else {
    	return res.redirect('/login');
    }
});
</pre>

the <code>req.isAuthenticated()</code> always returns false, in fact it only works at the login controller

<pre>
var passport = require('passport');

exports.install = function() {
	F.route('login', login);
	F.route('logout', logout, ['#session']);
	F.route('check', check, ['#session', '#passport.js', 'post'])
}

function login () {
	var self = this;

	self.view('login');
}

function check() {
	var self = this;
	passport.authenticate('local', function(err, user, info) {
	    if (err) return self.json(err); 

	    if (!user) return self.res.redirect('/login'); 
	    
	    self.req.logIn(user, function(err) {

	      if (err) return self.json(err); 
n
		  return self.res.redirect('/');
	    
	    });
	})(self.req, self.res);
}

function logout () {
	var self = this;

	self.req.logout()

	self.res.redirect('/home');
}
</pre>

In the check function it returns true, but in the middleware and every other controller returns false

Could you please give me a hand?

PS: Session is enabled and passport initialize is okay, it stopped working since the upgrade

Thank you

**Comment by petersirka** [comment]
Hi @LeventeNagy,
I need an example with the problem, can you send me it on my e-mail?

__Why?__
- you create `authcheck` middleware and I don't see its using.
- I don't see implementation of `passport.js'

There will be a small bug because I haven't peformed any big changes in middlewares.
Thanks!

**Comment by LeventeNagy** [comment]
Yes sure, one second

**Comment by petersirka** [comment]
Hmm, it's weird. I have problem with `v1.7.2` and `v1.8.0`. Why do you use passport.js? I have checked examples with passport.js (passport.js and passport.js-bearer-local) and they work correctly.

Thanks.

**Comment by LeventeNagy** [comment]
This is really odd than, no matter what i try same results, passport request object only works in the login no where else, tried a fresh install same results

**Comment by petersirka** [comment]
OK and why do you use passport.js? You can use simple auth.js module or custom solution. It's not hard to write it.

**Comment by LeventeNagy** [comment]
Okay, thank you, i will do that, thank you for your time

**Comment by LeventeNagy** [comment]
Just want to thank, i implemented the auth module with my logic under 10 mins, awesome. thanks again for the advice

**Comment by petersirka** [comment]
Great! Thanks.

**Comment by petersirka** [comment]
@LeventeNagy if you want to implement OAUTH2 (Google, Facebook, etc.) use <https://github.com/totaljs/modules/tree/master/Security/oauth2>, it's very easy.

**Comment by LeventeNagy** [comment]
Thanks for you help, promise when i will travel to Slovakia  again i will buy you a beer or coffee :)

**Comment by petersirka** [comment]
:-) thanks! I'm looking forward to you.
