### ISSUE TITLE
total.js becomes unresponsive when exceptions are thrown

### ISSUE THREAD

**Issue by darrudi** [totaljs/framework#274]
Hi Peter,

I am back again with a brand new strange problem! :)

I use `Cassandra` for my backend server. When exactly two exceptions are thrown inside the `Cassandra`'s response callback `total.js` (or should I say `Cassandra`) becomes totally unresponsive. As a result the whole application goes down as no user can query the database anymore, unless the app is restarted.

I don't know if it is something related to `total.js` or not. I wonder if you could shed some light on it. 

To reproduce the problem I sent you a sample project (the `total.js`'s empty project + a simple route inside `default.js`) by email (the `Cassandra` database is ready for testing).

Please let me know if the problem pertains to the `Cassandra` driver. In that case I will file a bug there.

**Comment by petersirka** [comment]
Hi @darrudi,
I don't have any e-mail from you. Can you send me again with the problem?

I'm waiting.
Thanks.

**Comment by darrudi** [comment]
Yeah, I sent it again to petersirka@gmail.com.

Thanx again.

**Comment by petersirka** [comment]
Hi @darrudi,
the problem is in cassandra driver. I think that the module doesn't close opened pool. Notice that: you create 4 requests and new requests will hang because I think that cassandra driver has 4 opened pools and any pool is not released.

Try, here is the answer:
```javascript
function test() {
	var self = this;

	console.log('-> Before executing the query');
	self.plain('Got it!');

	driver.execute('SELECT * FROM domain', [], function(err, result) {

		console.log('-> After executing the query');
		throw new Error('Raising an exception here <--');
	});
}
```

Thanks.

**Comment by darrudi** [comment]
That seems logical. Ok, then. I will file a bug on the Cassandra's issue tracker and and leave a reference here.

Thanx for looking into the matter.

**Comment by darrudi** [comment]
Here it is the issue I filed on the Cassandra driver's issue tracker (JIRA):

https://issues.apache.org/jira/browse/CASSANDRA-9246

**Comment by darrudi** [comment]
For reference:
I ended up warping the whole Cassandra driver in a new module and enclosing the callback in a try catch.
```
myDriver.execute = function(query, params, callback) {

	originalDriver.execute(query, params, option, function(err, result) {

		if (err) {
			// log the error, whatever
		}

		try {

			callback(err, result);

		} catch (err) {

			logger.error('UNCAUGHT-EXCEPTION: ' + err.message);
			logger.log(err.stack);
		}
	});
};
```
That will catch any error which might happen inside the driver's response and so solves the driver's crash in that situations.
