### ISSUE TITLE
mount multiple static folder

### ISSUE THREAD

**Issue by meongx** [totaljs/framework#275]
in express, we can mount more than one folder to serve static files

    app.use(express.static('public'));
    app.use('/upload', express.static('upload'));

is it possible in totaljs?

**Comment by petersirka** [comment]
Hi @meongx,
multiple no, but you can use (one) `virtual directory`:
<http://docs.totaljs.com/v1.8.x/en.html#api~FrameworkConfiguration~directory-public-virtual>

or you can map specific files like this:

```javacript
F.map('/layout.html', F.path.views('layout.html'));
```
and you can map a whole directory in the beta version  `npm install total.js@beta`:

```javacript
F.map('/views/', F.path.views());

// or with filter
F.map('/views/', F.path.views(), ['.html']);
```

Why total.js doesn't support multiple public directories?
__The performance is a reason..__

Thanks.

**Comment by sant123** [comment]
Hi @petersirka, ¿this code would have performance impacts? 

```js
F.map("fonts/", "~/node_modules/bootstrap/fonts");
F.map("fonts/", "~/node_modules/font-awesome/fonts");
```
I don't find other ways to expose fonts from vendors.

¡Thank you!

**Comment by petersirka** [comment]
Hi, don't worry - no performance issue.
