### ISSUE TITLE
the "allow-compile-html/js" set "false" still was compiled

### ISSUE THREAD

**Issue by satrong** [totaljs/framework#276]
Hi, Peter:
I has used the latest version (master), and the config file(app/config) I has set:
```js
allow-compile-html : false
allow-compile-js : false
```
but, my codes still was  compressed.
and also, I find another problem, if I write some code, such as:
```html
<div>word</div>
<script>
var data = @{place("initData")}
</script>
```
the `place("initData")` is an Array, when these codes was compressed, an error was thrown:
```shell
======= 2015-05-01 16:50:45: JavaScript compressor ---> Unexpected character '@' ...
```
if I write like blow will be ok:
```html
<div>word</div>
<script>
var data = '@{place("initData")}'
</script>
```

I  think the reason is the Javascript compressor execute before the Model data load into the view.

**Comment by petersirka** [comment]
Hi @satrong,
thanks. I'll test it today + I'll give you a feedback.

**Comment by petersirka** [comment]
Hi @satrong,
I have tested it and I don't see any problem. Everything works. Which version of total.js do you have?

Can you create an example on my e-mail? It will be best.
Thanks.

**Comment by satrong** [comment]
I has send to you.

**Comment by satrong** [comment]
Hi @petersirka ,
the gmail rejected my mail, I has uploaded the files on Github https://github.com/satrong/example

**Comment by petersirka** [comment]
The problem is in Uglify, because it doesn't know that `@{}` is server side tag. Try to comment your definition with `onCompileScript` and everything will be ok or better solution:

```html
<script type="application/json" id="data">
{"a":1,"b":2,"c":@{place("initData")}}
</script>

<script>
var data = JSON.parse(document.getElementById('data').innerHTML);
console.log(data);
</script>
```

I have disabled `allow-compile-js` and then `allow-compile-html` behaviour of the framework works correctly.

Thanks.

**Comment by satrong** [comment]
I am sorry to cause you trouble.
