### ISSUE TITLE
HTML minification failure

### ISSUE THREAD

**Issue by martinambrus** [totaljs/framework#277]
I've read on multiple occasions that you're not a fun of disabling HTML minification. However, I've just came across a use case where minification will concatenate 2 words in an HTML paragraph if they are on separate lines. This is, obviously not acceptable, so it's be cool if there was either an option to disable minification or the minifier was fixed.

Example code:

    <p>
      hello
      world
    </p>

**Comment by petersirka** [comment]
Hi @martinambrus,
I have updated total.js@beta on NPM `npm install total.js@beta`. I have fixed the HTML compressor, but it's not easy. I must test it on my projects.

Please install the beta version and try it.
Thanks.

**Comment by martinambrus** [comment]
Thank you, I'm unable to test this at the moment, as I'm on a shared FS for which I cannot install totaljs via NPM (I've just used the default project). Please do test it on your projects and thanks again for the quick response :)

**Comment by petersirka** [comment]
You can download it from GitHub and copy all files (index, mail, builders, internal, nosql, utils and image) to `/node_modules/total.js/`. Thanks!

**Comment by martinambrus** [comment]
Thank you, I can confirm that this update has fixed it for my project.
