### ISSUE TITLE
Configure timeout

### ISSUE THREAD

**Issue by capslow** [totaljs/framework#278]
Following the example, I have updated my project to Heroku but sometimes, as I have to parse a lot of data, I have error 408, Request Timeout. Is there any possibility to change the time for the timeout?

**Comment by petersirka** [comment]
Hi @capslow,
yes and you have two ways:

1. disable the timeout `F.route('/url/', action, [0, flags])` (
2. increase the timeout `F.route('/url/', action, [10000, flags])` (10 seconds)

or other way to change the timeout:
`F.route('/url/', action, { timeout: false })`

Thanks and give me the feedback.

**Comment by capslow** [comment]
I have used the second method and is working perfectly. Thanks for your attention.

**Comment by jhonny111s** [comment]
what's default timeout?

**Comment by petersirka** [comment]
@jhonny111s 3 seconds <https://docs.totaljs.com/latest/en.html#api~FrameworkConfiguration~default-request-timeout>
