### ISSUE TITLE
Streaming video

### ISSUE THREAD

**Issue by neonnds** [totaljs/framework#279]
Hi Peter,

I have created a total.js module for streaming data using the Range header because i couldn't find any clear documentation or looking through index.js any controller prototypes that allowed for it. Is there an easier way using the framework, rather than writing a module? Also I noticed mmr has been deprecated...which is the closest i could find to what i wanted in the documentation.

```
// Filename: modules/extension.js

var definition = (function() {

	/*
		Response with file stream that uses the Range and Accept-Range headers
		See: https://gist.github.com/paolorossi/1993068
		@filePath {String}
		return HTTP data stream
	*/
	Controller.prototype.streamFile = function(filePath, fileType) {

		var self = this;

 		var stat = fs.statSync(filePath);

		var total = stat.size;

		if(self.req.headers['range']) {

			var range = self.req.headers.range;
			var parts = range.replace(/bytes=/, "").split("-");
			var partialstart = parts[0];
			var partialend = parts[1];

			var start = parseInt(partialstart, 10);
			var end = partialend ? parseInt(partialend, 10) : total-1;
			var chunksize = (end-start)+1;

			var file = fs.createReadStream(filePath, {start: start, end: end});

			self.res.writeHead(206, { 
				'Content-Range': 'bytes ' + start + '-' + end + '/' + total, 
				'Accept-Ranges': 'bytes', 
				'Content-Length': chunksize, 
				'Content-Type': fileType
			});

			file.pipe(self.res);
	
		} else {

			self.res.writeHead(200, { 'Content-Length': total, 'Content-Type': fileType });

			fs.createReadStream(filePath).pipe(self.res);
		}
	};
});

setTimeout(function() {
	framework.eval(definition);
}, 100);

```

**Comment by petersirka** [comment]
Hi @neonnds,
the framework contains streaming functions, it works automatically if the request contains Range header <https://github.com/totaljs/framework/blob/v1.8.1/index.js#L3728> :)

So you can use: `controller.file()` or `F.responseFile()`.

**Comment by petersirka** [comment]
Example: <https://github.com/totaljs/examples/tree/master/video-streaming>

**Comment by neonnds** [comment]
Your right. I should have used Controller.prototype.file()...works like a charm!
