### ISSUE TITLE
Sub-domain failing in total.js@Beta

### ISSUE THREAD

**Issue by gnetsys** [totaljs/framework#281]
exports.install = function (F) {
   F.route('[a,b]/', sub-domain);
}
function sub-domain() {
   this.plain('Sub-domain Working');
}

The plain is displayed on the default route "/";  a.subdomain.com returns error;

**Comment by petersirka** [comment]
@gnetsys can you show me the error?

**Comment by petersirka** [comment]
Hi @gnetsys,
I have fixed it.

`npm install total.js@beta`
