### ISSUE TITLE
Images not rendering in view

### ISSUE THREAD

**Issue by LeventeNagy** [totaljs/framework#282]
First sorry if its a nother stupid question.
For some reason images not rendering in my views.

I made an image uploader what creates the folder all file <code>var upload_path = './uploads/portfolio/'+self.user.id;</code>

This creates the followind <code>./uploads/portfolio/1</code>
But if i render the image (example)

<pre>
< img class="ui small image" alt="" src="./uploads/portfolio/1/thumb_01.jpg" >
</pre>

nothing

if i try
<pre>
< img class="ui small image" alt="" src="/uploads/portfolio/1/thumb_01.jpg" >
</pre>

nothing, but the images are uploaded correctly.

What am i doing wrong?

**Comment by petersirka** [comment]
Hi @LeventeNagy,
it's not stupid question.

Is `uploads` directory out of public directory?

**Comment by LeventeNagy** [comment]
Sorry for the slow reply, yes it is outside, it is in the root folder

**Comment by petersirka** [comment]
So the problem is here.
You must create a file handler or move `upload` directory to `public` directory or change http://docs.totaljs.com/v1.8.x/en.html#api~FrameworkConfiguration~directory-public-virtual to `upload` directory :+1:

**Comment by LeventeNagy** [comment]
Ah thanks again @petersirka works now :)

**Comment by LeventeNagy** [comment]
Sorry i was wrong. Thought it works, added directory-public-virtual        : /uploads/ still the same result

**Comment by LeventeNagy** [comment]
Okay sorry, problem was at my part, did not move the uploads folder to the public folder
