### ISSUE TITLE
[suggestion] More comfortable title setting

### ISSUE THREAD

**Issue by max258** [totaljs/framework#285]
I try create the title in head, but i haven't success with this:

1. When isn't setup title in template - "TITLE"
2. When is setup title in template, the title would be subtitle - "TITLE - SUBTITLE"

I try do this with new title in head, but the effect was title tag two times.
I think there may be better handling the subtitles.
Maybe some hack will be nice.

Thanks

**Comment by LeventeNagy** [comment]
When you download an empty project you will see the layout html.

Inside it.

<pre>
<head>
    @{meta}
    < meta charset="utf-8" / >
	< meta http-equiv="X-UA-Compatible" content="IE=11" / >
	< meta name="format-detection" content="telephone=no" / >
	< meta name="viewport" content="width=device-width, initial-scale=1" / >
	< meta name="robots" content="all,follow" / >
	@{css('default.css')}
	@{favicon('favicon.ico')}
</head>
</pre>

See the @meta? thats where your title, description keyword beeing displayed.

In your page view define the following.

<code>@{meta('Title', 'Description (optional)', 'Keywords (optional)')}</code>

First param is the title, second the description, third the keywords. if you just need the title leave the others empty

So it should look like this
<code>@{meta('Site title goes here', 'Description goes here)', 'Keywords goes here)')}</code>

**Comment by petersirka** [comment]
@max258 can you create some example for understanding?

```html
@{meta} renders current meta tags
@{meta('title', 'description (optional)', 'keywords (optional)')} sets all meta tags
@{title('title')} sets the current title into the @{meta} and @{title}
@{description('description')} sets the current description into the @{meta} and @{description}
@{keywords('keywords')} sets the current keywords into the @{meta} and @{keywords}
```
Disable adding of `config.name` into the title in all subpages.
<http://docs.totaljs.com/v1.8.x/en.html#api~FrameworkConfiguration~allow-custom-titles>

---

@LeventeNagy thanks for the prompt reply.

**Comment by max258** [comment]
@LeventeNagy  That's not me question. But maybe is the problem hard to understanding. Anyway thank you for reply.

@petersirka Sure.
1. I have in layout.html @{meta}
2. I have in index.html @{meta('@(Subtitle)', '@(Desc)', 'keys')}
3. I have in config title: My amazing website

I want:
1. If no @{meta...} is defined in index.html or nothing is clicked, there would be title from config "My amazing website".
2. If @{meta...} in index.html is defined - "My amazing website - Subtitle"

In slovak language:
Proste chcel by som, aby titulok zo stranok v layoute bol iba pridavkom k titulku za kladnumu. Ak nejaky existuje doplni sa nejaky znak, trebars pomlcka a potom titulok v layoute. Cize priklad: "My amazing website - login". 
Nenasiel som sposob ako by sa to dalo docielit, lebo ked pridam k @meta v layoute tag title, su tam potom dva.

Dakujem

**Comment by petersirka** [comment]
@max258 I understand. I have one solution for you, you can rewrite <http://docs.totaljs.com/v1.8.x/en.html#api~Framework~framework.onMeta>. Here is a default declaration:

```javascript
F.onMeta = function(title, description, keywords, image) {
    var builder = '';
    if (title)
        builder += '<title>' + U.encode(title) + '</title>';
    if (description)
        builder += '<meta name="description" content="' + U.encode(description) + '" />';
    if (keywords)
        builder += '<meta name="keywords" content="' + U.encode(keywords) + '" />';
    return builder;
};
```

Thanks :+1:

**Comment by jhonny111s** [comment]
if i want use other meta tag for example twitter:card, what's the way.

```
function categories(category) {
    var self = this;
    self.title('Categories');
    self.description('description Categories');
    self.keywords('keywords categories');
 //another meta tag ?
.
.
}
```

**Comment by petersirka** [comment]
You have to use `controller.place` or `controller.section` (missing in docs, I'll add it):

__Layout__:

```html
<html>
<head>
    @{section('meta')}
</head>
```
__Add meta tags from a controller__:

```javascript
function some_action() {
    this.section('meta', '<meta name="twitter:title" content="BLA BLA" />');
    this.view('someview');
}
```

__Add meta tags from a view__:

```html
@{section meta}
<meta name="twitter:title" content="BLA BLA" />
@{end}
```
