### ISSUE TITLE
Global variable and function

### ISSUE THREAD

**Issue by sarankup** [totaljs/framework#286]
Hi,

I have two controllers say john.js and peter.js. Please advise how to define a variable and function in one controller which can be used in other controller.

Sorry, if this is very basic question.

**Comment by petersirka** [comment]
Hi @sarankup,

__john.js__
```javascript
exports.getName = function() {
    return 'John';
};
```

__peter.js__
```javascript
function some_action() {
    this.plain(F.controller('john').getName());
}
```
