### ISSUE TITLE
[Question,Improvement] Routing

### ISSUE THREAD

**Issue by max258** [totaljs/framework#287]
Hello, maybe is this me missunderstanding, but maybe this can be improvement.
I have issue with routing the page.
My code:

##### controllers/default.js
```javascript
exports.install = function() {
    F.route('/register', view_register);
    F.route('/register', view_register, ['post']);
};

function view_register() {
    var self = this;
    
    if (!self.post) {
        self.view('index');
        return;
    }

    //var result = self.validate(self.post, ['FirstName', 'LastName', 'Age', 'Email', 'Terms'], 'Form');
    //...
}
```

Me problem:
1) Can be the two routes merged to one?
For example: F.route('/register', view_register, ['view page','post']);
One for view page with layout, second for post.
2) !self.post get me POST request. Maybe this is me problem, but i cannot understand why is it inversed. I think if(!self.post) may refer to NOT POST, but i get POST.

**Comment by petersirka** [comment]
Hi @max258,

__1.)__ yes, two routes can be merged like this:

```javascript
F.route('/register/', view_register);
F.route('/register/', view_register, ['post']);
F.route('/register/', view_register, ['put']);

// or you can use multiple flags
F.route('/register/', view_register, ['post', 'put', 'get']);
```

I don't understand `F.route('/register', view_register, ['view page','post'])`, what does it mean `view page` in the flags?

__2.)__ `self.body` (`self.post` is the alias) is always plain empty project `{}`.

```javascript
function view_register() {
    var self = this;
    switch (self.req.method) {
        case 'post':
            self.view('index', self.body);
            break;
        case 'get':
            self.view('index');
            break;
    }
}
```
Here is a very good solution for submitting of forms:
<https://github.com/totaljs/examples/tree/master/contact-form>

**Comment by max258** [comment]
Thanks for advice. I work on registering form.
I have template with view and form in route /register and i want work with the submited data (POST) on same route.
In this case i have there 'view page' which may made - show the template with form. But this is only example. I don't have in mind which request show the template, maybe GET.
I think this is only me missunderstanding, but I try do the solution and then I close this issue.

**Comment by max258** [comment]
Ok, this do the job:
```javascript
F.route('/register', view_register, ['get','post']);
```
