### ISSUE TITLE
framework.assert places extra headers in cookie instead of request header

### ISSUE THREAD

**Issue by dbelca** [totaljs/framework#288]
Hi,

first many thanks for this framework and your work!

I tried to add some testing to my app today and all runned smooth, until wanted to add an Authorization-Header to the request.

The documentation says:
headers
Object	optional Additional headers.

One would think that this refers to HTTP-Headers, right? As it turned out, the header values are wrapped in a cookie instead:

{"content-type":"application/json","x-assertion-testing":"1","x-powered-by":"total.js v1.8.0","cookie":"Authorization=ZmV4OmFwaWtvQ3JlZGl0czo%3D","content-length":"17","host":"127.0.0.1:8000","connection":"close"}

(from access log request.headers)

Is there a way to really add HTTP-Headers?

Many thanks in advance!

**Comment by petersirka** [comment]
Hi @dbelca,
many thanks for your compliment. I have found a problem in documentation, here a correction solution.

```javascript
F.assert(name, url, flags, callback, [data], [cookies], [headers]);
```

I'll update documentation. 
Many thanks.

PS: give me a feedback.

**Comment by dbelca** [comment]
Many thanks for your very quick response.

You are right, I changed my code and added an empty dummy cookie object and the behavior change a bit.

I generate the header Object this way:

```
function getAPIHeader(key) {
	var base64 = require('js-base64').Base64;

	key = key || '';

	// use username, leave pw empty
	authorization = base64.encode(key + ':');

	return {
		Authorization: authorization
	};
};
```

So I would expect that 

```
var auth = request.authorization();
apiKey = auth.user;
```

would giv me my key back. But it contains (loged as JSON):

```
{"user":"","password":"","empty":true}
```

When I use a Client like Needle, this works perfectly. Can you please tell me where I could find a hook to debug this further?

**Comment by petersirka** [comment]
Try this:

```javascript
exports.run = function() {
    F.assert('Test auth', '/', ['get'], function(err, data, code) {
        console.log(data);
    }, null, null, { 'authorization': 'Basic ' + new Buffer('petersirka:123456').toString('base64') });
};
```

But important in http auth:
```javascript
result.empty = result.user.length === 0 || result.password.length === 0;
```

My advice: add key as username and password. The password can't be empty.
Thanks.

**Comment by dbelca** [comment]
Argh, sorry. I fucked up the Basic Authentication, the "Basic " part was simply missing.

Thanks for your Help, there is no Framework issue here.
