### ISSUE TITLE
handle jsonp files

### ISSUE THREAD

**Issue by capslow** [totaljs/framework#289]
I am having problems to load son files from the server into the client. I've been reading and it is a common issue related to cross-domain. Actually, I have in my controller the following code which works perfectly if I do a local request but not if I asked to the server:

function json_incidents() {
    var self = this;
    var db= require('../dbUtils.js');
    db.getIncidents(function(collection){self.json(collection)});
}

If it possible to serve from the server a jsonp file which supports a callback? This is the only solution I found to solve this kind of problems.

**Comment by petersirka** [comment]
Hi @capslow,
yes ... I added `controller.jsonp()` to new total.js version, try it: `npm install total.js@beta`.

__Usage:__

```javascript
function some_action() {
    var self = this;
    var callback = self.query.callback || 'myCallback';
    self.jsonp(callback, { name: 'total.js' });
}
```

Please give me a feedback.
Thanks.

**Comment by capslow** [comment]
Thank you, I will try it tomorrow and I will tell you if it works.

**Comment by capslow** [comment]
Finally I am not developing that functionally. Thanks for all your support.
