### ISSUE TITLE
timeout  bug

### ISSUE THREAD

**Issue by evmek** [totaljs/framework#290]
Hi @petersirka 

```
exports.install = function() {
    F.route("/timeout/", m.Bos, {
      timeout: 15000
    });    
  };

var  m = {
   Bos: function() {}
}
```
timeout , first time good work ,   after 15 second
but  second time and more time ,  30 second  after work  

node.js      : v0.12.2
total.js     : v1.8.0

**Comment by petersirka** [comment]
Hi @evmek,
which browser do you use? thanks.

**Comment by evmek** [comment]
Hi @petersirka 
I use Chrome 43.0.2357.124 m

and 

```
exports.install = function() {
    F.route("/timeout/", m.Bos, {
      timeout: 15000
    });   
   
    F.route("#408", m.f408);

  };

var  m = {
   Bos: function() {}
   , 
   f408: function() {
      this.json(SUCCESS(false));
   }
}
```
this code is work good , i use  F.route "#408"  problem solved

**Comment by petersirka** [comment]
Great. __But, important:__
Chrome creates multiple requests when the server doesn't respond in short time. sk
