### ISSUE TITLE
foreach error in view (release mode)

### ISSUE THREAD

**Issue by maxxam11** [totaljs/framework#293]
Hello.
I create file view.html with code:

```javascript
<script>            
@{foreach key in [1,2,3]}   
    alert(@{key});
@{end}   
</script>
```

in **release** mode return error:  Error: View: /view - SyntaxError: Unexpected identifier
in debug mode all right
if remove tag `<script>`, then all right.

**Comment by petersirka** [comment]
Hi @maxxam11,
I have fixed it. Please download the latest beta version `npm install total.js@beta`.
Thanks
