### ISSUE TITLE
sync method use mysql

### ISSUE THREAD

**Issue by goldalworming** [totaljs/framework#294]
hi @petersirka 

I tried total.js new feature synchronouse method but failed to run it

I read from generators controllers code in examples and read in http://docs.totaljs.com/v1.8.x/en.html#pages~Synchronous%20programming

but I don't understand how to use it

    exports.install = function(framework) {
                   // framework.route('/sv', viewsave_homepage);
                   framework.route('/', view_homepage);
    };

    function view_homepage() {
    	var self = this;
      var obj  = {};
      self.db(function(err, connection){
        connection.prototype.$$query = function(query, parameters) {
            // this === connection
            var self = this;
            return function(callback) {
                // callback must be the last argument
                self.query(query, parameters, callback);
            };
        };

        async(function *() {
          obj.post = yield sync(connection.$$query("select * from post where ?", {idauthor:'329627751'}))();
          self.json({rows: obj});
        })(self);      
      });

    }

I tried this code and return error
    async(function *() {
                             ^
======= 2015-07-01 13:01:57: framework.install('controller', '') ---> SyntaxError: Unexpected token * SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at EventEmitter.Framework.install (/home/lmvm/node_modules/total.js/index.js:1:30669)
    at /home/lmvm/node_modules/total.js/index.js:1:24885
    at Array.forEach (native)
    at EventEmitter.Framework.load (/home/lmvm/node_modules/total.js/index.js:1:24857)

I don't undestand whats happen in this code

**Comment by petersirka** [comment]
Hi,
yes, because you must run node.js with:

```bash
$ node --harmony debug.js
```

Thanks.

**Comment by goldalworming** [comment]
I still get error like above

**Comment by petersirka** [comment]
Which version of node.js do you have?

**Comment by goldalworming** [comment]
v0.10.31

**Comment by petersirka** [comment]
Only: node.js +v0.11.x and io.js +v1.0.

**Comment by goldalworming** [comment]
ok, I've updated to version 0.12.5
now got new error

======= 2015-07-01 16:26:21: TypeError: Cannot set property '$$query' of undefined TypeError: Cannot set property '$$query' of undefined
    at /home/lmvm/umrota/controllers/default.js:35:34
    at Pool.<anonymous> (/home/lmvm/node_modules/mysql/lib/Pool.js:51:14)
    at Handshake.Sequence.end (/home/lmvm/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Handshake.Sequence.OkPacket (/home/lmvm/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
    at Protocol._parsePacket (/home/lmvm/node_modules/mysql/lib/protocol/Protocol.js:270:23)
    at Parser.write (/home/lmvm/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/home/lmvm/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/lmvm/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)

**Comment by petersirka** [comment]
@goldalworming `Connection.prototype.$$query` is example how to create sync method, try this:
```javascript
var Connection = require('mysql/lib/Connection');
```

**Comment by goldalworming** [comment]
======= 2015-07-02 12:41:22: framework.install('controller', '') ---> SyntaxError: /home/lmvm/xxxx/controllers/default.js:35
    async(function *() {
                   ^
Unexpected token * /home/lmvm/xxxx/controllers/default.js:35
    async(function *() {
                   ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at EventEmitter.Framework.install (/home/lmvm/node_modules/total.js/index.js:1:30669)
    at /home/lmvm/node_modules/total.js/index.js:1:24885
    at Array.forEach (native)
====================================================
PID          : 38367
node.js      : v0.12.5
total.js     : v1.8.0
====================================================

still go error

I'll try sqlagent.

**Comment by petersirka** [comment]
Yes, because you must run node.js with `-- harmony` argument:

```bash
```

**Comment by goldalworming** [comment]
my bad, thanks a lot it works.

does sqlagent need harmony too?

**Comment by petersirka** [comment]
__Yes:__
https://github.com/petersirka/node-sqlagent#generators-in-totaljs

No problem.

**Comment by goldalworming** [comment]
@petersirka, how to make sure the connection release or close in sync method?

it tried this code

    self.db(function(err, connection){
      async(function *() {
        connection.release();
        obj.post = yield sync(connection.$$query("select * from post where ?", {id:'1'}))();
        obj.tes = yield sync(connection.$$query("select * from post where ?", {id:'1'}))();
        
        self.json({rows: obj});
      })(self);      
    });

and it show complete result. that means connection not release before both two query or it doesn't disconnect at all

**Comment by petersirka** [comment]
```javascript
self.db(function(err, connection){
  async(function *() {
    obj.post = yield sync(connection.$$query("select * from post where ?", {id:'1'}))();
    obj.tes = yield sync(connection.$$query("select * from post where ?", {id:'1'}))();
    connection.release();
    self.json({rows: obj});
  })(self);    
});
```
or
```javascript
self.db(function(err, connection) {
    async(function*() {
        obj.post = yield sync(connection.$$query("select * from post where ?", { id: '1' }))();
        obj.tes = yield sync(connection.$$query("select * from post where ?", { id: '1' }))();
        self.json({ rows: obj });
    })(self, function() {
        connection.release();
    });
});
```

**Comment by goldalworming** [comment]
thanks a lot
