### ISSUE TITLE
Having HTTP and HTTPS on the save total.js server

### ISSUE THREAD

**Issue by darrudi** [totaljs/framework#298]
Hi Peter,
Is is possible to have a single total.js handling both HTTP and HTTPS requests at the same time?

I'd like to share sessions between the HTTP and HTTPS server.

currently I am using this code for HTTPS:
```
var fs = require('fs');
var options = {};
options.https = {key: fs.readFileSync('keys/server/nikoo.com.key'), cert: fs.readFileSync('keys/server/nikoo.com.crt')};
options.port = 443;

require('total.js').https('release', options);
```

**Comment by petersirka** [comment]
Hi @darrudi,
good question. This is not possible in current version (but I'll think about it).

Only solution is NGINX as reverse proxy. Why do you not to use it?

**Comment by darrudi** [comment]
At present we don't use nginx or any other kind of reverse proxy as we are still in development phase. However, I'd consider using it if there isn't any other workaround.
Thanx

**Comment by petersirka** [comment]
@darrudi I have added a new method `F.listener(req, res)`:

```javascript
require('total.js').http('debug');

// We add a new server
var https = require('https');
var fs = require('fs');

var options = {
  key: fs.readFileSync('test/fixtures/keys/agent2-key.pem'),
  cert: fs.readFileSync('test/fixtures/keys/agent2-cert.pem')
};

https.createServer(options, F.listener).listen(8000);
```

Can it be? :+1:

**Comment by darrudi** [comment]
Yeah Peter, it works! :+1: 
It is also very convenient that the session is shared between both HTTP and HTTPS connections.
Thakx!
