### ISSUE TITLE
Polymer support

### ISSUE THREAD

**Issue by teckays** [totaljs/framework#299]
I'm using `total.js` with polymer and this:

```html

@{foreach item in model.response}
    <my-component item="@{item}"></my-component>
@{end}

```

passes `item` property as `[object Object] typeof = "String"` . Any ideas on this? 

PS. Passing every single `item` key separately isn't a solution for me.

**Comment by petersirka** [comment]
Hi @teckays,
please serialize `model.response` to JSON and write me it here + which version of total.js do you use?

```html
@{repository.arr = [1, 2, 3, 4]}

@{foreach item in repository.arr}
    <my-component item="@{item}"></my-component>
@{end}
```

Thanks.

**Comment by teckays** [comment]
Hi @petersirka,
`total.js -v  = 1.4.9`

I'm not quite sure what you think by serialising, the `model.response` is passed into the view as a JSON object already. I mean it's an elasticsearch response which is an object. Also the item is really big to paste it here. The response is well JSON formatted if that's the question.

**Comment by petersirka** [comment]
@teckays please download latest version of total.js `npm install total.js@beta` (stable release candidate) and then try to write `@{json(model)}` and send me the output from HTML.

Thanks.

**Comment by teckays** [comment]
@petersirka https://gist.github.com/teckays/fa0b22c95bb6bcb34fc7

**Comment by teckays** [comment]
sorry wrong paste. will edit the gist shortly

**Comment by teckays** [comment]
done https://gist.github.com/teckays/fa0b22c95bb6bcb34fc7

**Comment by petersirka** [comment]
Great. So which data do you want to fill into the tag `<my-component item="@{item}"></my-component>` from the model?

Please send me the output from `json(model.response)`.
Thanks :-)

**Comment by teckays** [comment]
@petersirka this is the output from `@{json(model.response)}`. I'm iterating this object and pass each object item into the polymer custom component

```html
@{foreach item in model.response}
    <my-component item="@{item}"></my-component>
@{end}
```
`model.response` is the one in gist which is an array of objects, therefore each `item` is an object that gets passed into `<my-component>`

**Comment by petersirka** [comment]
@teckays ok, so you can use this:

```html
@{foreach item in model.response}
    <my-component item="@{json(item).escape()}"></my-component>
@{end}
```

**Comment by teckays** [comment]
@petersirka there's an error using that `object has no method 'escape'`

**Comment by petersirka** [comment]
Ohh sorry, use `.encode()`.

**Comment by teckays** [comment]
@petersirka worked, thank you.

**Comment by petersirka** [comment]
Great :-)
