### ISSUE TITLE
how to return the data from database() in a variable ?

### ISSUE THREAD

**Issue by alsemany** [totaljs/framework#305]
I just would like to know how to return the data from the database() to a variable 
for example how to use return docs outside the function 
```
var users = DATABASE('users').find({}).toArray(function(err, docs) {
console.log(docs);
// this will log the data however just inside the function
    } );
```

```
   var users = DATABASE('users').find({}).toArray(function(err, docs) {
   return docs;
   } );
console.log(docs);
// this will not log any data and return docs = undefined 
```

kindly how to get docs outside the callback function

**Comment by petersirka** [comment]
Hi @alsemany,

```javascript
var map = function(doc) {
    return doc;
};

DATABASE('users').all(map, function(err, docs) {
    console.log(docs);
});
```

or if you use (harmony argument) `node --harmony yourapp.js` then you can use arrow functions:

```javascript
DATABASE('users').all(n => n, function(err, docs) {
    console.log(docs);
});
```

> kindly how to get docs outside the callback function

You must use `--harmony` argument again:
- Generators in NoSQL <https://github.com/petersirka/nosql#generators>
- Usage in total.js <http://docs.totaljs.com/v1.9.x/en.html#pages~Synchronous%20programming>

```javascript
var users = yield sync2(DATABASE('users').$$all(n => n.age > 10));
```

Thanks.

**Comment by alsemany** [comment]
Thank you for your reply I will try to use harmony argument, 
however I think there's no support to harmony while using (forever) to run the application server 
I will check for this 
Thank you so much
