### ISSUE TITLE
The built-in JS compressor doesn't insert semicolon for JS code without semicolon

### ISSUE THREAD

**Issue by CCharlieLi** [totaljs/framework#309]
Hi , 

Thanks for your working and I'm glad to see the 1.9 is releasde with all updated samples.
I'm using total.js with vue.js, and I find there is a built-in JS compressor in total.js, After webpack all code (including Vue, which has no semicolon after each statement), all the JS code in one line without semicolon, and the browser will be blocked. It seems the compressor didn't insert semicolon at all, is that standard? After webpack vue code, I tried to use YUI compressor(and then tried uglify) to compress the generated code, but it still didn't work util I modified the source code of total.js to avoid using the built-in compressor.

For a better solution, I used the project "semi" to add semicolon to vue, and everything came back to normal. Hope you can fix this.

Thanks.

**Comment by petersirka** [comment]
Hi @CCharlieLi,
the JavaScript compressor doesn't check semicolon, only compresses JavaScript. HTML and CSS compressors don't check content too. So if you write a bad code then the bad code is compressed.

__Solution:__
- use Uglify <https://github.com/totaljs/examples/tree/master/external-compile-uglifyjs>
- disable compression <http://docs.totaljs.com/v1.9.x/en.html#api~FrameworkConfiguration~allow-compile-script>

Thanks.

**Comment by CCharlieLi** [comment]
Hi @petersirka ,
I'm not sure that javascript code without semicolon is a bad code, it's just another code style, have a look at [No semicolons unless necessary](http://inimino.org/%7Einimino/blog/javascript_semicolons).(although I'm more comfortable with semicolon), but as a standard JS compressor, it should check the code and insert semicolon if necessary. Just a suggestion. ; )
Cheers.

**Comment by petersirka** [comment]
@CCharlieLi I understand, the compressor in total.js doesn't check missing semicolons. It's too complicated add it but I will think on it.

Thanks.
