### ISSUE TITLE
Server Variable with HTML string

### ISSUE THREAD

**Issue by sarankup** [totaljs/framework#310]
Hi,

Here is my controller
``
var model=self.body;
self.query.recentpost='<div><b>html bold string</b></div>;
    self.view('index',self.query);	
``

when I render this self.query.recentpost in my html page as @{query.recentpost}, I am getting html page as code, ``<div>`` is changed to &lt;div&gt;. I want to render the html string as html formatted output (**html bold string**). Please advise.

**Comment by petersirka** [comment]
Hi @sarankup,
<http://docs.totaljs.com/v1.9.x/en.html#pages~View%20engine>

```html
Raw output: @{!self.query.recentpost}
```
