### ISSUE TITLE
Feature Request: mail header

### ISSUE THREAD

**Issue by dacrhu** [totaljs/framework#314]
Hi,

please make a method is FrameworkMail to I can put custom header to mail file.
What do you think?

Eg.: "Precedence: bulk"

Thank you for your time!

David

**Comment by petersirka** [comment]
Hi @dacrhu,
I have added it, try `npm install total.js@beta`.

__Usage__:

```javascript
var mail = F.mail(..);
mail.headers = {};
mail.headers.Precedence = 'bulk';
```

Please try it and give me a feedback.

**Comment by dacrhu** [comment]
That's great, working fine!

Thank you Peter!
