### ISSUE TITLE
Add more info for Pagination

### ISSUE THREAD

**Issue by liaosankai** [totaljs/framework#316]
Add more info for Pagination in builders.js

+ beginItem  (for show item {beginItem} ~ {endItem} of {items})
+ endItem
+ prevPage
+ nextPage 
+ firstPage 
+ lastPage 

Fix: Use **Number()** for params `items`, `page`, `max` if they are string number
Fix: `self.items` shold not be less `0`
Fix: `self.max` should not be less then `1`
Fix: `self.page` should not be great then `self.count` or less then `1`
Fix: `self.take` should not great then (`self.items - self.skip`)

	Pagination.prototype.refresh = function(items, page, max) {
		var self = this;

		self.items = Math.max(0, Number(items));
		self.max = Math.max(1, Number(max));
		self.count = Math.ceil(self.items / self.max);
		self.page = Math.min(Math.max(1, Number(page)), Math.max(1, self.count));

		self.beginItem = Math.min(((self.page - 1) * self.max) + 1, self.items);
		self.endItem = Math.min(self.beginItem + self.max - 1, self.items);
		self.prevPage = (self.page > 1) ? self.page - 1 : false;
		self.nextPage = (self.page < self.count) ? self.page + 1 : false;
		self.firstPage = (self.page === 1) ? false : 1;
		self.lastPage = (self.page >= self.count) ? false : self.count;

		self.skip = (self.page - 1) * self.max;
		self.isPrev = self.page > 0;
		self.isNext = self.page < self.count - 1;
		self.isFirst = self.count > 1;
		self.isLast = self.count > 1;
		self.visible = self.count > 1;
		self.take = Math.min(self.max,(self.items - self.skip));

		return self;
	};

**Comment by petersirka** [comment]
Hi @liaosankai,
many thanks for your update. I have implemented it into the [v1.9.2 branch](https://github.com/totaljs/framework/tree/v1.9.2) without `beginItems` and `endItems` (I don't see any benefits of them).

Thanks!
