### ISSUE TITLE
error : ReferenceError: args is not defined > exports.sync2 function in the utils.js 

### ISSUE THREAD

**Issue by evmek** [totaljs/framework#317]
hi @petersirka 

I am try use "yield sync2" function but not work

error : "ReferenceError: args is not defined"
  on  exports.sync2 function in the utils.js

node.js      : v0.12.2
total.js     : v1.9.1

thanks, for this great framework

**Comment by petersirka** [comment]
Hi @evmek,
yes, f*uck --> I'm going to fix it now.

1000x thanks!

**Comment by petersirka** [comment]
@evmek many thanks again. I have fixed it now, please download latest beta `npm install total.js@beta`. Thanks :+1:
