### ISSUE TITLE
Fix required for nosql.js

### ISSUE THREAD

**Issue by evmek** [totaljs/framework#318]
Hi @petersirka 

fix required for nosql.js genarator  functions

about  :  https://github.com/evmek/nosql/commit/7e126be24f4dc834e43ace6b98070bc0d9b89dba

thanks for @totaljs

**Comment by petersirka** [comment]
Hi @evmek,
many thanks for your changes. Sometimes I write nice bullshits. I have fixed it.

Thanks.
