### ISSUE TITLE
'route' undefined in index.js:5428

### ISSUE THREAD

**Issue by molda** [totaljs/framework#320]
I'm getting error on line 5428 in total.js/index.js

I believe route.middleware[i] should be self.routes.middleware[i]

**Comment by petersirka** [comment]
Ooo shit. Many thanks!
I have fixed it in <https://github.com/totaljs/framework/tree/v1.9.3> branch.

Thanks :+1:

**Comment by molda** [comment]
Wow, that was quick. Thanks.
