### ISSUE TITLE
Package feature be boken ?

### ISSUE THREAD

**Issue by liaosankai** [totaljs/framework#321]
### Env
+ Windows7 zh-tw (x64)
+ node.js 4.1.1(x64)
+ total.js 1920
+ cmder v1.2

![version](https://cloud.githubusercontent.com/assets/82476/10358424/ba7181d8-6dc0-11e5-9bf9-8c550d24ce32.jpg)

#### Make package file 
I try step by step to make package file follow in `http://docs.totaljs.com/v1.9.x/en.html#pages~Packages` doc

![000](https://cloud.githubusercontent.com/assets/82476/10358237/83dc1680-6dbe-11e5-989f-b87b990d2892.jpg)

#### Package file success created
![001](https://cloud.githubusercontent.com/assets/82476/10358238/8a838496-6dbe-11e5-94e8-bd7910400566.jpg)

### Create new total.js project 
Avoid others factors, I do `mkdir totaltest` to create empty directory and total.js init, then mv the package file to `totaltest/packages`

![002](https://cloud.githubusercontent.com/assets/82476/10358240/903d754a-6dbe-11e5-9133-fca8139e93d3.jpg)

### Run Test Result
![003](https://cloud.githubusercontent.com/assets/82476/10358241/96039b4e-6dbe-11e5-8dfa-7c9689490801.jpg)

Do I miss something ?

**Comment by petersirka** [comment]
Hi @liaosankai,
can you send me you package file?

Thanks.

**Comment by liaosankai** [comment]
@petersirka I had sent. Thank you for your assistance.

**Comment by petersirka** [comment]
Hi @liaosankai,
many thanks. I found a bug on Windows.

Please try new beta: `npm install total.js@beta`

---

```bash
cd firstpackage
totalpackage create firstpackage
```

Give me a feedback.

**Comment by liaosankai** [comment]
### npm install -g total.js@beta
![ok-0](https://cloud.githubusercontent.com/assets/82476/10362958/1acb3f4c-6de4-11e5-8426-76506422267d.jpg)

### Make package file again
use `totalpackage create firstpackage` for `firstpackage.package`
use `totalpackage create firstpackage2 .` for `firstpackage2.package`

![2015-10-08_180216](https://cloud.githubusercontent.com/assets/82476/10363372/c638fd40-6de6-11e5-9331-a7fcb9ec904e.jpg)

### Try `firstpackage.package` file
#### Package load 
![ok-001](https://cloud.githubusercontent.com/assets/82476/10362969/282af1b4-6de4-11e5-859d-b50c145ff8f0.jpg)
#### Open `http://127.0.0.1:8000/hello-world/` in brower
![ok-002](https://cloud.githubusercontent.com/assets/82476/10362976/2ecac3aa-6de4-11e5-9913-27b1199cdd8c.jpg)

### Try `firstpackage2.package` file
#### Package load 
![nono](https://cloud.githubusercontent.com/assets/82476/10363448/1c152fe0-6de7-11e5-8cd1-319bfb3ecc7d.jpg)

**Comment by petersirka** [comment]
Rename the package file `firstpackage.package` to `helloworld.package` because I found an unexpected problem with filename and package id `export.id = ""` (in `index.js`). `export.id` can't be different than its filename because the package is extracted into `/tmp/` directory according its filename, but its executed be another name. I must think about it.

Thanks!

PS: `firstpackage2.package`, please send me the file. I'll perform many tests on Windows this week.
```

**Comment by liaosankai** [comment]
Rename `export.id=helloworld` and try make again, it's working now. 

![a00](https://cloud.githubusercontent.com/assets/82476/10364195/f434894e-6deb-11e5-94d9-3849a1dc9193.jpg)
![a01](https://cloud.githubusercontent.com/assets/82476/10364201/fb52966c-6deb-11e5-8dc7-acf272428099.jpg)
![a03](https://cloud.githubusercontent.com/assets/82476/10364205/00be7b84-6dec-11e5-88ce-a935747ecd51.jpg)

I also rename `export.id=helloworld2` and use `totalpackage create helloworld2 .` (with `'.'`) make package file `helloworld2.package` to sent for you.

![b00](https://cloud.githubusercontent.com/assets/82476/10364251/59dac196-6dec-11e5-9455-49e8bd736389.jpg)
![b01](https://cloud.githubusercontent.com/assets/82476/10364256/61660a06-6dec-11e5-92c0-2c7f52310f5a.jpg)

**Comment by petersirka** [comment]
Open your helloworld2.package in some text editor. All files in the file are without extension. Try to create package without `.` (dot) at the end of command.

BAD:
```bash
totalpackage create helloworld2.package .
```

GOOD:
```bash
totalpackage create helloworld2.package
```

Thanks.
Give me a feedback.

I must check completely the totalpackage application on Windows.

**Comment by petersirka** [comment]
I have tested it on Windows 7 and everything works correctly now.
Thanks!

**Comment by molda** [comment]
I'm just playing with package system and on windows 10 and without the `dot` it doesn't create package

![package](https://cloud.githubusercontent.com/assets/3585693/10907139/dc05a1f0-8227-11e5-84bc-0e1a5957f47f.png)

**Comment by petersirka** [comment]
@molda do you have latest beta version?

**Comment by molda** [comment]
yes total.js@1.9.3-23

**Comment by molda** [comment]
Soory i haven't installed it globaly so it's ok now

**Comment by petersirka** [comment]
Great! I want to publish a new version this week.
