### ISSUE TITLE
error in compile html

### ISSUE THREAD

**Issue by maxxam11** [totaljs/framework#322]
hello
My config:
allow-compile-html          : true
allow-compile-style         : true
allow-compile-script        : true
Framework version: 1.9.0

Error was detected during compilation for line break in tag or two spaces between attributes
#### Example for line break
Before compilation:
`<tag`
` id="tag1"></tag>`
After  compilation:
`<tagid="tag1"></tag>`

#### Example for two spaces between "tag" and attribute "id"
Before compilation:
`<tag  id="tag1"></tag>`
After  compilation:
`<tagid="tag1"></tag>`

**Comment by petersirka** [comment]
Hi @maxxam11,
I think that your tag contians TAB `<tag TAB id="tag1">`. Can you send me your HTML on my email? Thanks!

**Comment by petersirka** [comment]
Hi @maxxam11,
any news? Thanks.

**Comment by maxxam11** [comment]
Hello. This is my view file.
<svg SPACE SPACE id=""> don't work

 @{foreach hour in model.weather.hourly.data}
            <table class="wether-block-hourly__block">
                <tr><td class="wether-block-hourly__time">@{index == 0 ?
'сейчас' : hour.now.timeFormat}</td></tr>

                <tr><td class="wether-block-hourly__icon"><img
src="@{hostname}/img/weather/100/@{hour.iconN}.png"></td></tr>
                <tr><td
class="wether-block-hourly__temp">@{hour.temperature}°</td></tr>

                <tr><td class="wether-block-hourly__wind">
                    <svg id="svg_@{index}_@{hour.windBearing + '_' +
(hour.wind.speed > 20 ? 20  : hour.wind.speed)}"
                        xmlns="http://www.w3.org/2000/svg"
                        xmlns:xlink="http://www.w3.org/1999/xlink"
                        x="0px"
                        y="0px"
                        width="268.832px"
                        height="268.832px"
                        viewBox="0 0 268.832 268.832"
                        style="enable-background:new 0 0 268.832 268.832;"
                        xml:space="preserve"
                        version="1.1">
                        <style>
                            #svg_@{index}_@{hour.windBearing + '_' +
(hour.wind.speed > 20 ? 20  : hour.wind.speed)} {
                                width:@{(hour.wind.speed ? 10 +
(hour.wind.speed > 10 ? 10  : hour.wind.speed) * 2 : 0 )}px;
                                height:@{(hour.wind.speed ? 10 +
(hour.wind.speed > 10 ? 10  : hour.wind.speed) * 2 : 0)}px;
                                -moz-transform:
rotate(@{hour.windBearing}deg);  /* FF3.5/3.6 */
                                -o-transform:
rotate(@{hour.windBearing}deg);  /* Opera 10.5 */
                                -webkit-transform:
rotate(@{hour.windBearing}deg);  /* Saf3.1+ */
                                transform: rotate(@{hour.windBearing}deg);
 /* Newer browsers (incl IE9) */
                                fill: @{hour.wind.colorRGBPercent};
                                color: @{hour.wind.colorRGBPercent};

                            }
                        </style>
                        <g>
                            <path
d="M223.255,167.493c-4.881-4.882-12.797-4.882-17.678,0l-58.661,58.661V12.5c0-6.903-5.598-12.5-12.5-12.5

c-6.904,0-12.5,5.597-12.5,12.5v213.654l-58.661-58.659c-4.883-4.881-12.797-4.881-17.678,0c-4.883,4.882-4.883,12.796,0,17.678

l80,79.998c2.439,2.44,5.64,3.661,8.839,3.661s6.397-1.221,8.839-3.661l80-80C228.137,180.289,228.137,172.375,223.255,167.493z"/>
                        </g>
                    </svg>
                </td></tr>
                <tr><td
class="wether-block-hourly__wind-speed">@{hour.wind.speed}м/c</td></tr>

                
                <tr><td class="wether-block-hourly__precip-block">
                    <div style="background-color: #00BCD4; height:
@{hour.precipProbability}%"></div>
                </td></tr>
                <tr><td
class="wether-block-hourly__precip">@{hour.precipProbability}%</td></tr>
            </table>
        @{end}

--
С уважением,
Максим Карачёв

2015-10-11 20:59 GMT+03:00 Peter Širka <notifications@github.com>:

**Comment by maxxam11** [comment]
I checked, there is not TAB. '<tag SPACE SPACE id="tag1">` don't work.

**Comment by petersirka** [comment]
@maxxam11 can you send me the view as file? ... Because I don't know how to read it from your comment.

**Comment by maxxam11** [comment]
This is view file without errors, but if write two spaces bitween
attributes will be error.

--
С уважением,
Максим Карачёв

2015-10-11 22:34 GMT+03:00 Peter Širka <notifications@github.com>:

**Comment by petersirka** [comment]
Hmmm, thanks! I found the problem.
I'll give you a feedback.

Thanks!

**Comment by petersirka** [comment]
Hi @maxxam11,
I have fixed it now, but the problem is too complicated.

Can you test it? `npm install total.js@beta`

Thanks.

**Comment by liaosankai** [comment]
### version

    total.js -v 
    1930

### Test-1
HTML:

    <p id="t1">Test</p>

compile:

    <p id="t1">Test</p>

### Test-2
HTML:

    <p     id="t2">Test</p>

compile:

    <pid="t2">Test</p>

### Test-3
HTML:

    <p     
        id="t3">Test</p>

compile:

    <pid="t3">Test</p>

### Test-4
HTML:

    <p id="t4" title="">Test</p>

compile:

    <p id="t4" title="">Test</p>

### Test-5
HTML:

    <p id="t5"    title="">Test</p>

compile:

    <p id="t5"title="">Test</p>

### Test-6
HTML:

    <p id="t6"    title=""    data-test="">Test</p>

compile:

    <p id="t6"title=""data-test="">Test</p>

### Test-7
HTML:

    <p id="            t7   " title="" data-test="">Test</p>

compile:

    <p id="t7" title="" data-test="">Test</p>

**Comment by petersirka** [comment]
You didn't use the new beta version:
`npm install total.js@beta` ---> `1.9.3-13`

Give me a feedback.

**Comment by maxxam11** [comment]
In new beta version 1.9.3-13 all right.
Thank you!

--
С уважением,
Максим Карачёв

2015-10-12 12:14 GMT+03:00 Peter Širka <notifications@github.com>:

**Comment by liaosankai** [comment]
I try uninstall total.js and `npm install total.js@beta` again.

![ok](https://cloud.githubusercontent.com/assets/82476/10425338/688cf95a-7109-11e5-8802-70787c9f3615.jpg)

It's working well.

![ok8000](https://cloud.githubusercontent.com/assets/82476/10425341/6dcc0230-7109-11e5-9c43-aa8a023e2e4d.jpg)

**Comment by petersirka** [comment]
Great. Thanks.
