### ISSUE TITLE
F.map() have path problem on WIN operating system

### ISSUE THREAD

**Issue by liaosankai** [totaljs/framework#323]
@see http://docs.totaljs.com/v1.9.x/en.html#api~Framework~framework.map

I try to put `console.log(self.routes.mapping);` after line in file `node_modules/total.js/index.php:1447` for track bug

### Mapping directories `F.map('xyz','public');`

![liunx](https://cloud.githubusercontent.com/assets/82476/10532452/edff829e-73f0-11e5-8d36-b58908e12087.png)

![win-7](https://cloud.githubusercontent.com/assets/82476/10532454/f37ead62-73f0-11e5-82ea-114269b606a0.png)

### Mapping for packages `F.map('/my-assets', '@helloworld/assets');`
![@liunx](https://cloud.githubusercontent.com/assets/82476/10532440/def2989a-73f0-11e5-862d-ce32873dedd8.png)

![@win-7](https://cloud.githubusercontent.com/assets/82476/10532448/e9042434-73f0-11e5-8247-74dd3b6bf646.png)

**Comment by petersirka** [comment]
Hi @liaosankai,
this is not possible with me. I'll fix it today. Thanks for the report.

I'll give you a feedback.

**Comment by petersirka** [comment]
Hi @liaosankai,
I have pubslihed a new version. Please try it. Thanks! :+1:

**Comment by liaosankai** [comment]
## Test for Mapping directories F.map('xyz','public');

Use git bash on Win7

![test](https://cloud.githubusercontent.com/assets/82476/10562830/8f9d1974-75a2-11e5-85a3-273256b6aa65.jpg)

Test url paths:

+ `/xyz/favicon.ico`
+ `/xyz/robots.txt`
+ `/xyz/css/default.css`
+ `/xyz/js/default.js`

Result Screenshot:

![test-4](https://cloud.githubusercontent.com/assets/82476/10562836/aa6e1ff0-75a2-11e5-9abb-61b4cc1ffadb.png)
![test-1](https://cloud.githubusercontent.com/assets/82476/10562833/9be0492c-75a2-11e5-80ce-982b938bbf22.png)
![test-3](https://cloud.githubusercontent.com/assets/82476/10562835/a5880d7a-75a2-11e5-916d-01a36e3aee44.png)
![test-2](https://cloud.githubusercontent.com/assets/82476/10562834/a0e4cae2-75a2-11e5-9535-f2eb8a597447.png)

It's working.

## Test Mapping for packages F.map('/my-assets', '@helloworld/assets');

I make package again after update to v1.9.3-19

![package](https://cloud.githubusercontent.com/assets/82476/10562986/db30ca92-75a8-11e5-97c4-21825bc4d829.jpg)

Use package in new total.js 

![nnn](https://cloud.githubusercontent.com/assets/82476/10562991/ef026788-75a8-11e5-9dc2-b4376f52424c.jpg)

Result Screenshot:
![a](https://cloud.githubusercontent.com/assets/82476/10562996/14347dac-75a9-11e5-81de-c10ed87c30d0.jpg)
![b](https://cloud.githubusercontent.com/assets/82476/10562997/190b4824-75a9-11e5-8bad-e8ad14b79839.jpg)
![d](https://cloud.githubusercontent.com/assets/82476/10562998/2100e94e-75a9-11e5-82e1-ba82528b87be.jpg)

It's working,too.

**Comment by petersirka** [comment]
Thanks!
