### ISSUE TITLE
Flash message module timeout configuration

### ISSUE THREAD

**Issue by LeventeNagy** [totaljs/framework#324]
Hi @petersirka 

I am using the flash messages module. https://github.com/totaljs/modules/tree/master/Miscellaneous/flash

In the docs I see timeout 5 minutes.

Is there any way to manipulate this?

Because i would also like to use this for form validation messages, and since the timeout is 5 minutes, the message does not expire and duplicates the messages.

Any info on this please?

PS

When I tried to us connect flash got the following error

<pre>
: route is not defined
    at Server.Framework.listener (C:\node\total\node_modules\total.js\index.js:5
428:42)
</pre>

**Comment by liaosankai** [comment]
Hi, @LeventeNagy 

@see https://github.com/totaljs/modules/blob/master/Miscellaneous/flash/v1.00/flash.js

    flash[id].expire = Date.now() + ((1000 * 60) * 5); // 5 minutes

Modify for you want :)

**Comment by LeventeNagy** [comment]
That my problem actually, if i modify it for 30 seconds, restart the server, it still uses 5 minutes

**Comment by petersirka** [comment]
Yes, it's there a problem. I'll fix it today.
Thanks.

**Comment by LeventeNagy** [comment]
Thank you

**Comment by petersirka** [comment]
__I have updated the module:__

- fixed expiration
- add custom settings

```javascript
MODULE('flash').expire = 10;
```

__New URL address to script__:
<https://github.com/totaljs/modules/blob/master/Miscellaneous/flash/flash.js>

Thanks!

**Comment by LeventeNagy** [comment]
It still has an error.

Defined the expire, and where flash is included i get

<pre>
Unhandled rejection TypeError: Cannot read property 'expire' of undefined
</pre>

**Comment by petersirka** [comment]
Show me your routes, they must contain middleware 'flash'.

**Comment by LeventeNagy** [comment]
Oh crap, i frogot to include sorry, all okay, thank you
