### ISSUE TITLE
How about add `btoa()` and `atob()` to `Utils` module ?

### ISSUE THREAD

**Issue by liaosankai** [totaljs/framework#325]
Hi, @petersirka 

I use mailgun to send mail and it must use basic auth via base64 encode as follow

https://gist.github.com/liaosankai/6411b5d178df0384bffb

I think maybe `btoa()` and `atob()` should be a part of `Utils` module, What do you think this?

**Comment by petersirka** [comment]
Hi,
I have added it now `npm install total.js@beta`.

Thanks!
