### ISSUE TITLE
Is it possible put variables in one localization sentence ?

### ISSUE THREAD

**Issue by liaosankai** [totaljs/framework#326]
Hi, @petersirka

The translation tools is great idea for handle localization.
I wanted to put model variables in one localization sentence like:

	<p>@(I have @{model.count} books)</p>

For avoid one sentence be split to plural keys map resource 
	
	T-1116222951      : I have @{model.count} books
	
Would it be possible? 

Or it still only use as follow now ? 

	<p>@(I have) @{model.count} @(books)</p>

keys map resource is
	
	T2122675935       : I have
	T93921962         : books

**Comment by petersirka** [comment]
Hi @liaosankai,
you can use both solutions. I should prefer the first way because in different languages can be `@{model.count}` defined differently.

Avoid long text :-)

**Comment by liaosankai** [comment]
Sorry, I should to try it before ask

controller:

    function view_index() {
        var self = this;
        self.view('index', {
    	    "count": 99
        });
    }

views:

    <p>@(I have @{model.count} books)</p>

Yes! It's working well.

![2015-10-21_201422](https://cloud.githubusercontent.com/assets/82476/10636168/5c6fcf48-7830-11e5-8ff4-7bac9945dc45.jpg)

@see http://docs.totaljs.com/v1.9.x/en.html#pages~Localization
 If doc has example about this, so much the better :)

Thank you!!

**Comment by petersirka** [comment]
Good idea. Thanks.
