### ISSUE TITLE
Receiver Name in Email

### ISSUE THREAD

**Issue by VarunBatraIT** [totaljs/framework#327]
I am using function this.onEmail (i.e. controller.onEmail) 

First parameter is supposed to be an array or a string.(http://docs.totaljs.com/v1.9.x/en.html#api~FrameworkController~controller.mail)

So it works just fine with a first param as "someone@gmail.com" but doesn't work for "James Bond <someone@gmail.com>"

```
//says email is invalid  of course it is :)
 this.onMail("Varun Batra <XXX@gmail.com>", "API Error!" , "Still got a problem in API");

//works
 this.onMail("XXX@gmail.com", "API Error!" , "Still got a problem in API");




```

If there is any way I can actually write a receiver name in email? I looked at a function where it checks for valid email and it doesn't honor receiver's name 

```

/**
 * Add a recipient
 * @param  {String} address A valid e-mail addrčess.
 * @return {Message}
 */
Message.prototype.to = function(address) {

	if (!address.isEmail())
		throw new Error(errors.notvalid);

	var self = this;
	self.addressTo.push(address);
	return self;

};
```

Thanks

**Comment by petersirka** [comment]
Hi @VarunBatraIT,
you can use `F.mail()` or `controller.mail()` each function returns `MailMessage` object.

Thanks.

**Comment by VarunBatraIT** [comment]
mail and onMail both should return MailMessage as per documentation signature and I am using onMail because I don't want to render anything in view it is just a string in an email (body). In fact mail calls onMail. In both function there isn't any way to specify receiver or receipt's name. Suppose I am sending email to James Bond, I need to specify his name in "to" field. Like "James Bond \<bond007@gmail.com\>" (just an example)

Thanks


```
/**
 * Send e-mail
 * @param {String or Array} address E-mail address.
 * @param {String} subject E-mail subject.
 * @param {String} view View name.
 * @param {Object} model Optional.
 * @param {Function(err)} callback Optional.
 * @return {MailMessage}
 */
Controller.prototype.mail = function(address, subject, view, model, callback, language) {

	if (typeof(model) === TYPE_FUNCTION) {
		callback = model;
		model = null;
	}

	var self = this;
	var body = self.view(view, model, true);

	return framework.onMail(address, subject, body, callback, language);
};
```



```

/**
 * Mail delegate
 * @param {String or Array String} address
 * @param {String} subject
 * @param {String} body
 * @param {Function(err)} callback
 * @param {String} replyTo
 * @return {MailMessage}
 */
Framework.prototype.onMail = function(address, subject, body, callback, replyTo) {

	var tmp;

	if (typeof(callback) === STRING) {
		tmp = replyTo;
		replyTo = callback;
		callback = tmp;
	}

	var message = Mail.create(subject, body);

	if (address instanceof Array) {
		var length = address.length;
		for (var i = 0; i < length; i++)
			message.to(address[i]);
	} else
		message.to(address);

	var self = this;

	message.from(self.config['mail.address.from'] || '', self.config.name);
	tmp = self.config['mail.address.reply'];

	if (replyTo)
		message.reply(replyTo);
	else if (tmp && tmp.isEmail())
		message.reply(self.config['mail.address.reply']);

	tmp = self.config['mail.address.copy'];

	if (tmp && tmp.isEmail())
		message.bcc(tmp);

	var opt = self.temporary['mail-settings'];

	if (opt === undefined) {
		var config = self.config['mail.smtp.options'];
		if (config && config.isJSON())
			opt = JSON.parse(config);
		self.temporary['mail-settings'] = opt;
	}

	setTimeout(function() {
		message.send(self.config['mail.smtp'], opt, callback);
	}, 2);

	return message;
};
```

**Comment by petersirka** [comment]
I understand, but why do you need to add a name into the `address to` field?
You use `F.logmail()` for a plain text mail.

**Comment by VarunBatraIT** [comment]
I don't know how to answer this however I am also looking for an answer :)

In most software one can see name coming or just an email address coming. Specially when one has to import sent email to 3rd party api like salesforce for example. Some api provider like mandrill auto saves name and email which can be used further to send marketing emails by auto saving contacts. 

https://github.com/eleith/emailjs supports this which I have been using so far. Don't like to add another dependency not just yet :)

Thanks for the logmail. From name it appears to be logging of an email so I could have ignored it.

**Comment by petersirka** [comment]
I understand. I'll look on it.
Thanks.

**Comment by VarunBatraIT** [comment]
Much appreciated. I could have helped but I am a novice coder not the brutal one :+1:

**Comment by petersirka** [comment]
And sorry I forgot to anwser your question: "Explain Brutal Web Developer":
`Brutal` means --> without any limits :-D

**Comment by petersirka** [comment]
I have added it into the framework. Try it: `npm install total.js@beta`.

```javascript
controller.mail('Brutal Web Developer <petersirka@gmail.com>', ...);
controller.mail('Brutal Web Developer <petersirka@gmail.com>', ...);
// or

var mail = new Mail.Message();
mail.to('Brutal Web Developer <petersirka@gmail.com>');
mail.to('petersirka@gmail.com', 'Brutal Web Developer');

mail.cc('Brutal Web Developer <petersirka@gmail.com>');
mail.cc('petersirka@gmail.com', 'Brutal Web Developer');
```

Thanks!
