### ISSUE TITLE
Wrong number of files in multipart form

### ISSUE THREAD

**Issue by evgeny-t** [totaljs/framework#328]
Hi @petersirka,

First of all, thank you for an awesome framework.

It seems that I've encountered a bug in multipart form parser -- it fails to process multipart form sometimes. Here is an app for reproducing the issue: https://github.com/evgeny-t/total-multipart-issue.

I open an index page, choose all files from `data` directory and keep clicking on `Send` button. The app  receives the wrong number of files each, approximately, 5th request.

Versions:  
```
node.js      : v4.2.1
total.js     : v1.9.2

ubuntu     14.04
```

I'm not able to reproduce the bug after applying this patch https://github.com/evgeny-t/framework/commit/ce84fcb6d9eb2dc11635a532d88ce37ca06bf0c4.

I'd appreciate any help.

Thanks.

**Comment by petersirka** [comment]
Hi @evgeny-t,
many thanks.

I don't have any problem with uploading:
![image](https://cloud.githubusercontent.com/assets/2414252/10826514/6ec92c44-7e6a-11e5-9d6a-241fe5cb75d3.png)

- please, try to install total.js@beta
- can you record some video? 
- which OS do you use? (OSX, Windows or Linux)

Thanks.

**Comment by evgeny-t** [comment]
@petersirka I use ubuntu 14.04. I will record a vid.

**Comment by evgeny-t** [comment]
@petersirka I've just realized that I was not able to reproduce the issue using https://github.com/danwrong/restler, so the issue can be client related.

**Comment by evgeny-t** [comment]
@petersirka here is the vid https://youtu.be/TTc1BmbZlyo

it prints:
```
Wrong file length. post is  { file_33: '�PNG\r\n\u001a\n\u0000\u0000\u0000\rIHDR\u0000\u0000\u0000�\u0000\u0000\u00002\b\u0000\u0000\u0000\u0000<:�=\u0000\u0000\u0003\fIDATh\u0005���q�H\f\u00040t�A��cJ���&  ^"^"^"^"^"^"^"^"^"^"^"^"^"^"��\u0011\u001fjć\u001a��F|�\u0011\u001fj��T�O��*��[��Ū[��Ū[���?��G]����n��\u0016�n��\u0016�n��\u001jğ�\u0013��Y�P#�\u001a�F\u001c5B�8j�\u001aq�\b5��\u0011jĥ~ĭ~\u0004%�ţ\u001a1jĨ\u0011�F�\u001a1jĨ\u0011�F�\u001a1jĨ\u0011�F��#n5�\u001a�(\u001e\u0015q\u00141�8�\u0018E\u001cE�"�"F\u0011G\u0011�����~ŭ�Q#\u001eţ"�"F\u0011G\u0011����Q�Q�(�(b\u0014q\u0014��Qĥ�\u001f5�Q<*�(b\u0014q\u00141�8�\u0018E\u001cE�"�"F\u0011G\u0011�".E\u001c%�œ"V\u0011�XE(b\u0015��U�"V\u0011�XE\\���P�w���U�"V\u0011�XE(b\u0015��U�"V\u0011�"V�+��\'E�"\u0014��P�*B\u0011�\bE�"\u0014���\u0014��C<�\'E�"\u0014��P�*B\u0011�\bE�"\u0014���\u0014��\b�#\u001eœ"V\u0011�XE(b\u0015��U�"V\u0011�XE\\�X�#F�x\u0014O�XE(b\u0015��U�"V\u0011�XE(b\u0015q)bՈ��G���U�"V\u0011�XE(b\u0015��U�"V\u0011�"V\u0011��\'���U�"V\u0011�XE(b\u0015��U�"V\u0011�"V\u0011��\'񨈣�Q�Q�(�(b\u0014q\u00141�8�\u0018E\u001cE܊XE�"�ģ"�"F\u0011G\u0011����Q�Q�(�(b\u0014q\u0014q+b\u0015��x\u0012��8�\u0018E\u001cE�"�"F\u0011G\u0011����Q�Qĭ�K\u0011G\u0011��Q�\u00185bԈQ#F�\u00185bԈQ#F�\u00185bԈQ#nE\\jĨ\u0011��Y�P#�\u001a�F\u001c5B�8j�\u001aq�\b5��\u0011jğ".�#ԏx\u0014_�-V�b�-V�b�-V��R��U��g�E�b�-V�b�-V�b�-V��_u�/��\u001a��F|�\u0011\u001fjć\u001a��F��.��F|\u0017/\u0011/\u0011/\u0011/\u0011/\u0011/\u0011/\u0011/\u0011/\u0011/\u0011/\u0011/�\u001f\n�=B<�R�\u0000\u0000\u0000\u0000IEND�B`�',

```

**Comment by petersirka** [comment]
Hmm this is very interesting, I'm not able to reproduce it.

Try to upload from your browser (15 uploads):
<http://test.totaljs.com>

Do you have Hangouts / GTalk?
Thanks.

**Comment by evgeny-t** [comment]
All responses are 
```
{"data":{"frames":[],"message":"multipart form parser error."}}
```

Sure, it's `timoshenko.evgeny@gmail.com`.

**Comment by petersirka** [comment]
@evgeny-t Any news?
