### ISSUE TITLE
F.map doesn't work in windows

### ISSUE THREAD

**Issue by molda** [totaljs/framework#329]
**Only related to Windows!!**

The problem is that following mapping
```javascript
F.map('/admin/', F.path.root() + '/admin/');
````
will produce 
```javascript
self.routes.mapping[ '/admin/D:\myApp\admin\app.js' ] = 'D:\myApp\admin\app.js';
````
since replacing doesn't do anything because variable `replace` in map function has forward slashes whereas variable `file` has backslashes 
```javascript
replace = 'D:/myApp/admin/';
file = 'D:\myApp\admin\';
//as expected this won't change anything
file.replace(replace, '');
```

what seems to work ok for me is placing `filename = filename.replace(/\\/g, '/');` at the top of map function and replacing
```javascript
var file = files[i].replace(replace, '');
```
with
```javascript
var file = files[i].replace(/\\/g, '/').replace(replace, '');
```

**Comment by petersirka** [comment]
Hi @molda,
yes, please try to download latest beta `npm install total.js@beta`, it's stable and give me a feedback.

**Comment by molda** [comment]
Hi @petersirka following code still fails to find anything in my admin folder
```
F.map('/admin/', '/admin/');
```
as soon as i remove "/" from second argument `F.map('/admin/', 'admin/');` it's working

and this
```
F.map('/admin/', path.join(F.path.private(), 'admin'));
```
wil produce
```
self.routes.mapping['/admin/D:/totaljs-beta/private/admin/app.js'] = 'D:/totaljs-beta/private/admin/app.js';
```
changing
```
framework_utils.ls(framework.isWindows ? filename.replace(/\//g, '\\')....
```
to
```
framework_utils.ls(framework.isWindows ? filename = filename.replace(/\//g, '\\')...
```
seem to fix it because otherwise 
```
if (framework.isWindows) files[i] = files[i].replace(filename, '').replace(/\\/g, '/');
```
will not replace anything since
```
filename == 'D:\totaljs-beta\private\admin/' // notice one forward slash
files[i] == 'D:\totaljs-beta\private\admin\app.js'
```

**Comment by molda** [comment]
So i changed following if statement in for loop in framework_utils.ls...
```
if (framework.isWindows)
    files[i] = files[i].replace(filename, '').replace(/\\/g, '/');
```
to this
```
if (framework.isWindows){
    files[i] = files[i].replace(/\\/g, '/');
    replace = replace.replace(/\\/g, '/');
}
```
which works for
```F.map('/admin/', path.join(F.path.private(), 'admin'));```

and adding this
```javascript
if(framework.isWindows) {
    filename = filename.replace(/\\/g, '/');
    if(filename[0] == '/') filename = filename.substring(1);
}
```
just before 
```javacsript
var isFile = path.extname(filename).length > 0;
```
works for 
```javascript
F.map('/admin/', '/admin/');
```
or
```javscript
F.map('/admin/app.js', '/admin/app.js');
```

**Comment by petersirka** [comment]
I have found a problem in documentation.

```javascript
// This must works:
F.map('/admin/', F.path.private('admin'));
``` 

The problem is in the paths between Windows and Unix. For mapping that will work you must use `F.path` object. Please try it and I must change the documentation.

**Comment by molda** [comment]
Cool i didn't realize i can use `F.path.private('admin')` instead of `path.join(F.path.private(), 'admin')`
I'll read docs more carefuly next time!

However it still isn't possible to use
```javascript
F.map('/admin/', F.path.root('admin'));
```
since it will create mapping to `/admin/D:/totaljs-beta/admin/app.js`

and
```javscript
F.map('/admin/', '/admin/');
```
doesn't work with the leading slash.
only working is
```javscript
F.map('/admin/', 'admin');
```
Notice about this in docs would be cool.
Thanks.

**EDIT**
I have following folders
`/admin`
`/private/admin`
and i tried this
```
console.log(F.path.private('admin')); //  D:/totaljs-beta/private/admin
console.log(F.path.root('admin')); //  D:\totaljs-beta\admin
```
F.path.private returns forward slashes and F.path.root returns backslashes which is inconsistent and probably causes some problems too.

**Comment by petersirka** [comment]
I have published a new beta version (I have fixed paths).
Please try it and give me a feedback.

**Comment by molda** [comment]
v1.9.3-25
`F.map('/admin/', '/admin/'); `
doesn't work in windows, framework_utils.ls returns empty array 
the leading slash is the problem, following works ok
`F.map('/admin/', 'admin/'); `

**Comment by petersirka** [comment]
Hi @molda,
please try it again `npm install total.js@beta`. Thanks.

**Comment by molda** [comment]
Great, it seems to work s expected now

and one more thing :)

in map function following check
```
// Checks if the directory exists
if (!isPackage && !filename.startsWith(directory)) {
```
will not work as expected (again windows only)
since in my case
directory = D:\totaljs-beta  //back slash
and 
filename = D:/totaljs-beta/private/admin // forward slashes


Thanks a lot

**Comment by petersirka** [comment]
@molda I have published a new beta version.
Can you test it on your computer? I have only the virtual pc and my view can be wrong.

Thanks!

**Comment by molda** [comment]
v1.9.3-27

Cool, both variables `directory` and `filename` now have forward slashes

Thanks

**Comment by petersirka** [comment]
Great, thanks!
