### ISSUE TITLE
Npm package `querystring` can't parse multiple query string, 

### ISSUE THREAD

**Issue by liaosankai** [totaljs/framework#331]
Hi, @petersirka 

I found total.js use `var qs = require('querystring');` npm package to parse query string, but it can't parse multiple query string with `[ ]` params. How about replaced with `qs` package ?

### [querystring](https://www.npmjs.com/package/querystring)

Ex1: `127.0.0.1:8000/?p[]=1&p[]=2`

    {
         'p[]': ['1', '2']
    }

Ex2: `127.0.0.1:8000/?p[x]=1&p[y]=2`

    {
        'p[x]': '1',
        'p[y]': '2'
    }

### [qs](https://www.npmjs.com/package/qs)

Ex1: `127.0.0.1:8000/?p[]=1&p[]=2`

    {
         p: [ '1', '2' ]
    }

Ex2: `127.0.0.1:8000/?p[x]=1&p[y]=2`

    {
        p: {
            x: '1',
            y: '2'
       }
    }

**Comment by petersirka** [comment]
Hi @liaosankai,
please download the framework from GitHub <https://github.com/totaljs/framework/tree/v1.9.3>

I added `F.onParseQuery` delegate:

```javascript
F.onParseQuery = function(value) {
    return qs.parse(value);
};
```

This delegate is executed when the framework parsing data from URL or REQUEST BODY.
Give me a feedback.

**Comment by liaosankai** [comment]
I try 

    npm install qs

and write delegate in file `definitions/test.js`

    F.onParseQuery = function(value) {
        var Qs = require('qs');
        return (!value) ? {} : Qs.parse(value);
    };

output query data in file `controllers/default.js`

    function view_index() {
        var self = this;
        self.json(self.query);
    }


then launch with `http://127.0.0.1:8000/?p[x]=1&p[y]=2` to get console result:

    {"p":{"x":"1","y":"2"}}

and it's working well. thank you.

Will `F.onParseQuery` delegate be publish to npm package registry for `total.js@beta` ?

**Comment by petersirka** [comment]
I'll publish new release today.
Thanks!
