### ISSUE TITLE
500: Internal Server Error :: SyntaxError: Unexpected token default

### ISSUE THREAD

**Issue by LeventeNagy** [totaljs/framework#333]
Hi @petersirka 

Just downloaded 1.9.3

If i run node release.js or debug.js I get the following error

<pre>
500: Internal Server Error :: SyntaxError: Unexpected token default
    at view_parse (C:\node\total\node_modules\total.js\internal.js:2011:14)
    at View.read (C:\node\total\node_modules\total.js\internal.js:2870:10)
    at View.load (C:\node\total\node_modules\total.js\internal.js:2932:19)
    at Object.exports.generateView (C:\node\total\node_modules\total.js\internal.js:2962:20)
    at Object.Controller.view (C:\node\total\node_modules\total.js\index.js:12382:37)
    at Object.Controller.view (C:\node\total\node_modules\total.js\index.js:12467:15)
    at Object.view_index (C:\node\total\controllers\default.js:9:7)
    at Subscribe.doExecute (C:\node\total\node_modules\total.js\index.js:9089:23)
    at Subscribe.execute (C:\node\total\node_modules\total.js\index.js:9000:15)
    at Subscribe.prepare (C:\node\total\node_modules\total.js\index.js:9062:7)
<pre>

**Comment by petersirka** [comment]
Hi @LeventeNagy,
I see the problem in a view template. Can you show your view template?

Thanks.

**Comment by LeventeNagy** [comment]
Sure, did not modify anything it's a fresh install

view template:

<pre>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=11" />
	<meta name="format-detection" content="telephone=no" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<meta name="robots" content="all,follow" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	@{import('meta', 'head', default.css', 'default.js', 'favicon.ico')}
</head>
<body>

	<div class="container-background">
		<div class="container">
			<div class="center"><a href="/"><img src="/img/logo.png" alt="total.js - web application framework for node.js" border="0" /></a></div>
			<br />
			@{body}
		</div>
	</div>
	<footer>
		&copy; Thank you for using <b>total.js</b>.
	</footer>

</body>
</html>
</pre>

Iindex.html

<pre>
@{title('Something awesome')}

<hr />
<br />
<p class="center">
	The node.js framework for all web developers with everything what you need.<br />
	<b>Create something awesome.</b>
</p>
<br />
<br />
<div class="center"><a href="http://docs.totaljs.com" class="linkbutton">DOCUMENTATION</a></div>
</pre>

Thank you

**Comment by petersirka** [comment]
Hmmm. Are you sure, you have the latest version?
Can you send me a whole example with node_modules directory on my email?

**Comment by dacrhu** [comment]
Hi Peter and Levente

the problem is in "import" method.

@{import('meta', 'head', default.css', 'default.js', 'favicon.ico')}

If I change to
@{meta} @{head} @{import('default.css', 'default.js', 'favicon.ico')}

working fine.

"Imports static files. Works with .js, .css and .ico and automatically creates tags <script>, <link> and <favicon>."

Best regards,
David

**Comment by dacrhu** [comment]
node.js      : v5.0.0
total.js     : v1.9.3

**Comment by petersirka** [comment]
@dacrhu thanks, I see the problem in your code:

`@{import('meta', 'head', default.css', 'default.js', 'favicon.ico')}` // bad
`@{import('meta', 'head', 'default.css', 'default.js', 'favicon.ico')}` // good

My mistake in the empty-project. I'm fixing it.

**Comment by petersirka** [comment]
I fixed the empty-project in releases.
Thanks!

**Comment by LeventeNagy** [comment]
Thank you
