### ISSUE TITLE
sync callback

### ISSUE THREAD

**Issue by dacrhu** [totaljs/framework#334]
Hi Peter,

I use memcached npm module with "yield sync".
Memcache in get method response is standard (err, result). If not err then value of err is 'undefined' but total.js expect 'null'.
Now I use workaround (callback (null, result)). Can you modify this section to sync method will accepts 'undefined' too?

Thank you,
David

**Comment by petersirka** [comment]
Hi @dacrhu,
can you send me a whole code of your action or a scope of `async` (where is the `sync` called)?


Thanks!

**Comment by dacrhu** [comment]
controller-user.js:
<code>
...
codeFromCache = yield sync(SOURCE('memcached').get('activation-' + this.body.type + '-' + this.user.userName))();
...
</code>

source memcached.js:
<code>
exports.get = function (key) {
    var Memcached = require('memcached');
    var memcached = new Memcached(CONFIG('memcachedIp') + ':' + CONFIG('memcachedPort'));
    return function (callback) {
// memcached.get(key, callback)
        memcached.get(key, function (err, result) {
            callback(null, result);
        });
    };
};

</code>

**Comment by petersirka** [comment]
Hmmm, try this:

```javascript
yield sync(SOURCE('memcached').get)('activation-' + this.body.type + '-' + this.user.userName);
```

**Comment by petersirka** [comment]
It works correctly, please look into my example:
<https://www.dropbox.com/s/wd65yt960mgvl5w/test-sync.zip>

**Comment by dacrhu** [comment]
Yes, your example is working fine.
If I call callback directly with null:

``` javascript
callback(null, result);
```
it working fine, but the memcached module response "undefined" instead of "null".

Similarly:
``` javascript
setTimeout(function() {
    		callback(undefined, 'OK: ' + key);
}, 1000);
```
Result is 500 error.

Other:
in ES6:
``` javascript
function* view_index()
```
in Total.js:
``` javascript
function *view_index()
```
Is there a difference between the two?

**Comment by petersirka** [comment]
@dacrhu this is bug :-D ... I'll fix it today.

**Comment by dacrhu** [comment]
Thanks :)

**Comment by petersirka** [comment]
Please try it:
`npm install total.js@beta`

**Comment by dacrhu** [comment]
Working fine, good job :)
Thank you!
