### ISSUE TITLE
Two spaces to empty

### ISSUE THREAD

**Issue by maxxam11** [totaljs/framework#338]
Hello.
When config 'allow-compile-html' is true, then two spaces between words compiled to 0 spaces.

`first[space]word[space][space]secon[space]word -> first[space]wordsecond[space]word`

**Comment by petersirka** [comment]
Hi @maxxam11,
which version of total.js do you use?

1.9.3 works correctly:

__View__:
```html
<div>A B C  D</div>
```

__Output__:
```html
<div>A B C D</div>
```

Thanks.

**Comment by maxxam11** [comment]
v1.9.3-13

--
С уважением,
Максим Карачёв

2015-12-19 14:29 GMT+03:00 Peter Širka <notifications@github.com>:

**Comment by petersirka** [comment]
OK, you have old beta version. Can you upgrade total.js to newest beta?
And if there will be a problem, can you send me a small example on my email?

Thanks!

**Comment by maxxam11** [comment]
It works in english symbols, but not working in russian:

*View*:

<div>А Б В  Г</div>

*Output*:
<div>А Б ВГ</div>



--
С уважением,
Максим Карачёв

2015-12-19 14:34 GMT+03:00 Peter Širka <notifications@github.com>:

**Comment by petersirka** [comment]
Shit, yes you're right. I have fixed it.
Please try the new beta version `npm install total.js@beta`.

Thanks!

**Comment by petersirka** [comment]
I'm waiting for your feedback :-)

**Comment by maxxam11** [comment]
I'm sorry for waiting. Now everything is fine. Thank you.

--
С уважением,
Максим Карачёв

2015-12-20 13:08 GMT+03:00 Peter Širka <notifications@github.com>:

**Comment by petersirka** [comment]
Thanks!

**Comment by maxxam11** [comment]
I forgot to say that in russian language symbol 'Ё' is exception and is out
of range [а-яА-Я].
If you use  regular epressions, then you must use [а-яА-ЯёЁ].

Now don't work with symbol 'Ё'

*View*:

<div>А  Ё  Я</div>

*Output*:
<div>А ЁЯ</div>

--
С уважением,
Максим Карачёв

2015-12-20 13:16 GMT+03:00 Peter Širka <notifications@github.com>:

**Comment by petersirka** [comment]
Please try again a beta `npm install total.js@beta`.
Thanks.

**Comment by maxxam11** [comment]
There is something wrong. Now don't work @{view('/path/to/view')} in view.

--
С уважением,
Максим Карачёв

2015-12-20 14:35 GMT+03:00 Peter Širka <notifications@github.com>:

**Comment by petersirka** [comment]
For me everything works correctly.
I have performed some tests and all is OK.

Can you send me a small example?

![viewengine](https://cloud.githubusercontent.com/assets/2414252/11917847/4c2b7606-a719-11e5-83ef-41d88d2e83a0.gif)

**Comment by maxxam11** [comment]
Don't work controller.view('/path/to/view').

--
С уважением,
Максим Карачёв

2015-12-20 14:45 GMT+03:00 Максим Карачёв <karachev.m@gmail.com>:

**Comment by maxxam11** [comment]
v1.9.4-20

controller:

exports.install = function() {
    F.route('/test', test);
};

function test() {
    this.layout('');
    this.view('/test');
}

view:
<div>А  Ё  Я</div>


output:
/test

**Comment by petersirka** [comment]
Hmm, this works for me.
Can you send me a whole example (zipped) on my email?

Thanks.

**Comment by maxxam11** [comment]
In the new test project all right.
Apparently a bug somewhere in my project. I will look for.

**Comment by maxxam11** [comment]
It was my error. Now everything is fine. Thank you.
