### ISSUE TITLE
FrameworkImage image.save() doesn't work in windows

### ISSUE THREAD

**Issue by liaotzukai** [totaljs/framework#339]
Hi, @petersirka 
It seems has the same problem as 

+ Issue #329
+ Issue #321 

I try add code after line:224 in `node_modules/total.js/image.js` for fix:

    var command = self.cmd(self.filename === null ? '-' : self.filename, filename);
    command = command.isWindows ? command.replace(/\//g, '\\') : command;

and it works ok!

### Env:
+ node 5.1.1
+ windows10 MINGW64 shell
+ total.js@1.9.4-23

**Comment by petersirka** [comment]
Hi @liaotzukai,
many thanks! I fixed it and I added you as contributor `readme.md` and `package.json`.
Please try the fix (I don't have Windows).

Thanks!

**Comment by liaosankai** [comment]
Hi @petersirka 

I'm sorry, there's been a misunderstanding. I forgot switch to my account in my brother computer. so @liaotzukai is my brother account.

I had try use branch: https://github.com/totaljs/framework/tree/v1.9.4 and it's working well.

**Comment by petersirka** [comment]
@liaosankai :+1: I updated contributors.
Thanks!
