### ISSUE TITLE
Miss `Sec-WebSocket-Protocol` header for use custom protocol socket

### ISSUE THREAD

**Issue by liaosankai** [totaljs/framework#342]
Hi, @petersirka 

I got an error message **`WebSocket connection to 'ws://127.0.0.1:8000/' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received`** in chrome broswer when I test custom protocol socket

    F.websocket('/', socket_private_homepage, ['json'], ['privatechat'], ['*']);

and it's also has the same problem in `Opera`, `IE11`, `Microsoft Edge`, `safari`expect for `firefox`. 

I found the cause of the trouble by [RFC6455](https://tools.ietf.org/html/rfc6455#section-1.2) and do patch as follow:

### Patch:

line: 12960 in total.js/index.js

    var SOCKET_RESPONSE = 'HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nX-Powered-By: {0}\r\nSec-WebSocket-Accept: {1}\r\n\r\n';

fix to:

    var SOCKET_RESPONSE = 'HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nX-Powered-By: {0}\r\nSec-WebSocket-Accept: {1}\r\nSec-WebSocket-Protocol: {2}\r\n\r\n';

line: 13650 in total.js/index.js

    	self.socket.write(new Buffer(SOCKET_RESPONSE.format('total.js v' + version, self._request_accept_key(self.req)), 'binary'));

fix to:

    	self.socket.write(new Buffer(SOCKET_RESPONSE.format('total.js v' + version, self._request_accept_key(self.req),protocols), 'binary'));

and now all browser is working well.

### Env:
+ node 5.1.1
+ windows10 MINGW64 shell
+ total.js@1.9.4-23

**Comment by petersirka** [comment]
Hi @liaosankai,
many thanks!

I have created new branch `v1.9.6` <https://github.com/totaljs/framework/tree/v1.9.6> and I have published a new beta version `npm install total.js@beta` with your fix.

Thanks!!!!!!!

**Comment by petersirka** [comment]
I must test it. I have problems with my WebSocket projects:
![image](https://cloud.githubusercontent.com/assets/2414252/12053102/045af734-af16-11e5-8f9d-acbe9798d3bb.png)

**Comment by petersirka** [comment]
OK, I found the problem.
I updated BETA version on NPM.

Thanks!

**Comment by rpochet** [comment]
Add problem with WebSocket on IPAD after an upgrade from 1.9.3, and it is solved now.

Thanks a lot!
