### ISSUE TITLE
1.9.5 - @{import()}

### ISSUE THREAD

**Issue by adrianrey05** [totaljs/framework#343]
Hi @petersirka.
I update my project to 1.9.4 to 1.9.5 total.js.
In the layout i have this
```html
@{import('//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css', '//maxcdn.bootstrapcdn.com/bootswatch/latest/cosmo/bootstrap.min.css')}
```
this response in 1.9.4 http://maxcdn...
now in 1.9.5 response http://localhost:8000/css//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css

any suggestions?

thanks for you help!

**Comment by adrianrey05** [comment]
I have a similar problem with @ {js ()}
this is the directory of public
* js/
* css/
* lib/ _<- bower components_

in layout 1.9.4 @{import('/lib/jquery/dist/jquery.min.js', '/lib/bootstrap/dist/js/bootstrap.min.js')}
this response ok http://locahost:8000/lib/jquery....
now in 1.9.5 response bad http://localhost:8000/**js**/lib/...

thanks for you help!

**Comment by petersirka** [comment]
Hi @adrianrey05,
there is a bug, sorry ... I'm going to fix it. You're right.

**Comment by petersirka** [comment]
Hi @adrianrey05, really sorry for this bug. Please download the latest beta `npm install total.js@beta` and give me a feedback.

1000x sorry.
Thank you!

**Comment by adrianrey05** [comment]
Hi @petersirka,

Perfect! It works!
thanks to you to solve the problem so quickly.

I hope you have a good end of the year!

**Comment by petersirka** [comment]
Great! Thanks yes I have :+1:  ... And I wish you all the best!
Thanks!
