### ISSUE TITLE
Could it be implement rooms or namespaces features for websocket?

### ISSUE THREAD

**Issue by liaosankai** [totaljs/framework#344]
Hi, @petersirka 

`framework.websocket()` seem don't has rooms or namespaces features like [socket.io/rooms-and-namespaces](http://socket.io/docs/rooms-and-namespaces/) for different channels in socket.

Could it be that add new controller method or options for `framework.websocket()` in the future ?
Or may I get websocket sample in current version for switch different chat rooms ?

Thank you for your time.

**Comment by petersirka** [comment]
Hi @liaosankai,
namespace works via dynamic routes and I considered it as rooms:

```javascript
F.websocket('/{namespace-room}/', action1);
F.websocket('/students/{namespace-room}/', action2);
```
Do you want to separate clients to different groups? I'm finding a simple solution for you :+1:

**Comment by liaosankai** [comment]
It's very clear, thank you! I will try study it and return feedback if I find any issues.

**Comment by petersirka** [comment]
I'm closing this issue. Give me the feedback if you find some problems :-)
