### ISSUE TITLE
Mail problems

### ISSUE THREAD

**Issue by deadman2000** [totaljs/framework#346]
1. Example from [docs](http://docs.totaljs.com/v1.9.x/en.html#api~FrameworkMail) is not working, because argument "options" in Message.send is required. Sending mail is still possible with using Framework.mail or Controller.mail.
2. Layout from email view accepts to requested view. Example:

*default.js*
```javascript
exports.install = function () {
    F.route('/test', test);
};

function test(){
	this.mail('marchukov.ivan@gmail.com', 'Test e-mail', '~email-registration', { name: 'MODEL NAME' });

    this.view('test');
}
```
*email-registration.html*
```html
@{layout('')}
<h1>message</h1>
```

*http://127.0.0.1:8000/test*
```html
<p>hello</p>
```

Without `@{layout('')}` request returnings with default layout.html content

**Comment by petersirka** [comment]
Thanks. I have published a new beta version: `npm install total.js@beta`.

- I have fixed the problem with the layout and mail
- `options` argument is optional in `MailMessage.send()`

1000x Thanks.

**Comment by deadman2000** [comment]
Thanks, problem with layout is resolved.
`MailMessage.send()` is work, but without options is not usability, bacause local config is not used.

**Comment by petersirka** [comment]
I understand, but I have in my work SMTP server without any options (only HOSTNAME).
Local config is meant only for `controller.mail()` and `F.mail()`.

Or do you mean something else?
Please write if you have some idea.

**Comment by deadman2000** [comment]
`F.mail()` send message immediately (after 2 ms). Is there a guarantee that the letter is not sent before I call method?
I have one idea:
```javascript
var message = F.createMail('marchukov.ivan@gmail.com', 'Test e-mail', '~email-registration', { name: 'MODEL NAME' });
message.attachment('/path/to/file', 'attachment');
message.send(callback);
```

**Comment by petersirka** [comment]
`2 ms` timeout is for that. So the answer: __yes__. I used the method in 20+ projects, but I can create something similar as you write.

**Comment by deadman2000** [comment]
Thanks! It would be great.

**Comment by petersirka** [comment]
@deadman2000
I have added just another solution, example:

```javascript
var message = F.mail(.....);

// Removes timeout
message.manually();

// You must send the email manually
message.send();
```

What do you think about it? `npm install total.js@beta`

**Comment by deadman2000** [comment]
@petersirka 
Thanks. Yes, i like this.
