### ISSUE TITLE
Loading session before onLocate Exacution

### ISSUE THREAD

**Issue by neoPix** [totaljs/framework#347]
Hi, 

Is it possible to gain access to the session object in the request object while executing the following function : `F.onLocate`.

The session is loaded after, and i'd like to use it to set the language of my user.

_Using cookie for now_

Thanks.

**Comment by petersirka** [comment]
Hi @neoPix,
I have looked into the code and `onLocate` is executed before the middleware, but `onLocate` doesn't perform nothing complicated.

You have 3 ways how to solve this problem:

1. create middleware
```javascript
F.middleware('language', function(req, res, next) {
    next();
});
```

**Comment by neoPix** [comment]
Well, that solved the issue. 
Thanks @petersirka  for the reactive and quick answer.
