### ISSUE TITLE
Websocket can't parse protobuf binary message

### ISSUE THREAD

**Issue by liaosankai** [totaljs/framework#351]
hi @petersirka 

I use google protocol buffer in socket follow the [DOC](https://github.com/dcodeIO/ProtoBuf.js/wiki/Builder) and get some error.

### Install

use `bower install protobuf` to install protobuf libs in `public` folder for clinet.

use `npm install protobufjs` to install protobuf libs for server.
	
Detail guide is [HERE](https://github.com/dcodeIO/protobuf.js/wiki/Installation)

### Protobuf define file
I use [json format](https://github.com/dcodeIO/protobuf.js/blob/master/tests/complex.json) file and copy to `private/complex.json`

### Clinet 
file in `views/index.html`

	<button id="test">
	    Open and send protobuf message
	</button>

	<script src="bower_components/bytebuffer/dist/ByteBufferAB.min.js"></script>
	<script src="bower_components/long/dist/long.min.js"></script>
	<script src="bower_components/protobuf/dist/protobuf.min.js"></script>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<script>
	$(document).ready(function() {
	    var ProtoBuf = dcodeIO.ProtoBuf;

	    // Creates a new empty Builder pointing at the root namespace:
	    var builder = ProtoBuf.loadJsonFile("complex.json");
	    var Game = builder.build("Game");
	    var Car = Game.Cars.Car;

	    var socket = null;
	    $('#test').on('click', function() {
	        socket = new WebSocket('ws://127.0.0.1:8000/');
	        socket.onopen = function() {
	            var car = new Car({
	                "model": "Rusty",
	                "vendor": {
	                    "name": "Iron Inc.",
	                    "address": {
	                        "country": "US"
	                    }
	                },
	                "speed": "SUPERFAST" 
	            });
	            var buffer = car.encode();
	            socket.send(buffer.toArrayBuffer());
	        };
	    });

	});
	</script>

### Server
file in `controllers/default.js`

	exports.install = function() {
	    F.route('/', view_index);
	    F.map('/complex.json', F.path.private('complex.json'));
	    F.websocket('/', socket_homepage, ['binary']);
	};

	function view_index() {
	    var self = this;
	    self.view('index');
	}

	function socket_homepage() {
	    var controller = this;
	    controller.on('open', function(client) {
	        console.log('Connect / Online:', controller.online);
	    });

	    controller.on('message', function(client, buffer) {
	        var ProtoBuf = require('protobufjs');
	        var builder = ProtoBuf.loadProtoFile(F.path.private('complex.json'))
	        var Game = builder.build("Game");
	        var Car = Game.Cars.Car;
	        var myMessage = Car.decode(buffer);
	        console.log(myMessage);
	    });

	}

		
### Error Message in Server

	[TypeError: Argument must be a string]
	======= 2016-01-11 10:46:45: TypeError: Argument must be a string TypeError: Argument must be a string
	at TypeError (native)
	at Buffer.write (buffer.js:568:21)
	at WebSocketClient.parse (~\test\node_modules\total.js\index.js:13784:11)
	at WebSocketClient._ondata (~\test\node_modules\total.js\index.js:13721:10)
	at emitOne (events.js:77:13)
	at Socket.emit (events.js:169:7)
	at readableAddChunk (_stream_readable.js:146:16)
	at Socket.Readable.push (_stream_readable.js:110:10)
	at TCP.onread (net.js:523:20)

### ENV
+ node 5.1.1
+ windows10 MINGW64 shell
+ total.js@1.9.6-15

**Comment by petersirka** [comment]
I have fixed `ArrayBuffer`:

```javascript

// client-side
socket = new WebSocket('ws://127.0.0.1:8000/');
socket.binaryType = 'arraybuffer';
...
socket.send(str2ab('TEST ARRAY BUFFER'));

// server-side
controller.on('message', function(client, arraybuffer) {
    console.log(ab2str(arraybuffer));
    // output: TEST ARRAY BUFFER
});

// HELPERS FOR BOTH: client-side & server-side
function ab2str(buf) {
  return String.fromCharCode.apply(null, new Uint16Array(buf));
}
function str2ab(str) {
  var buf = new ArrayBuffer(str.length*2); // 2 bytes for each char
  var bufView = new Uint16Array(buf);
  for (var i=0, strLen=str.length; i < strLen; i++) {
    bufView[i] = str.charCodeAt(i);
  }
  return buf;
}
```

But your example doesn't work with `protobufjs`, exception ` Error: Parse error at line 1: unexpected '{' Error: Parse error at line 1: unexpected '{'` and`ArrayBuffer` now works correctly --> `npm install total.js@beta`.

Thanks.

**Comment by liaosankai** [comment]
### Client
I add `socket.binaryType = 'arraybuffer';`

### Server 
fix:

    var builder = ProtoBuf.loadProtoFile(F.path.private('complex.json'));

To:

    var builder = ProtoBuf.loadJsonFile(F.path.private('complex.json'));

### Result

    { model: 'Rusty',
      vendor: { name: 'Iron Inc.', address: { country: 'US' }, models: [] },
      speed: 2 }

Yes, It's working for decode google protocol buffer.
Thank you very much!!

**Comment by petersirka** [comment]
Ohhh Great! Thanks!

**Comment by petersirka** [comment]
This week will be the new version of total.js.
Thanks.
