### ISSUE TITLE
Server can decode buffer from Client, but Client can't decode buffer from Server.

### ISSUE THREAD

**Issue by liaosankai** [totaljs/framework#352]
Hi, @petersirka 

I forgot to try decode buffer from server in client. I can decode protobuf from client in server,but can't decode protobuf from server in client. I try encode/decode simple binary in server/client and got the same problem.

### Server
file in `controllers/default.js`

	exports.install = function() {
	    F.route('/', view_index);
	    F.websocket('/binary', socket_binary, ['binary'], [], ['*']);
	};

	function view_index() {
	    var self = this;
	    self.view('index');
	}

	function socket_binary() {
	    var controller = this;
	    var ab2str = function(buf) {
	        return String.fromCharCode.apply(null, new Uint16Array(buf));
	    }
	    var str2ab = function(str) {
	        var buf = new ArrayBuffer(str.length * 2); // 2 bytes for each char
	        var bufView = new Uint16Array(buf);
	        for (var i = 0, strLen = str.length; i < strLen; i++) {
	            bufView[i] = str.charCodeAt(i);
	        }
	        return buf;
	    }
	    controller.on('open', function(client) {
	        console.log('Connect / Online:', controller.online);
	    });
	    controller.on('close', function(client) {
	        console.log('Disonnect / Online:', controller.online);
	    });
	    controller.on('message', function(client, arraybuffer) {
	        var msg = ab2str(arraybuffer);
	        console.log('--- BINARY ---');
	        console.log(msg); // <- It's working.

	        // send to client
	        var buffer = str2ab(msg);
	        controller.send(buffer);
	    });
	}

### Client
file in `views/index.html`

	<button id="test-binary">
	    ws://127.0.0.1:8000/binary
	</button>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<script>
	$(document).ready(function() {

	    var socket = null;

	    $('#test-binary').on('click', function() {
	        var ab2str = function(buf) {
	            return String.fromCharCode.apply(null, new Uint16Array(buf));
	        }
	        var str2ab = function(str) {
	            var buf = new ArrayBuffer(str.length * 2); // 2 bytes for each char
	            var bufView = new Uint16Array(buf);
	            for (var i = 0, strLen = str.length; i < strLen; i++) {
	                bufView[i] = str.charCodeAt(i);
	            }
	            return buf;
	        }
	        socket = new WebSocket('ws://127.0.0.1:8000/binary');
	        socket.binaryType = 'arraybuffer';
	        socket.onopen = function() {
	            console.log('connecting...');
	            if (socket.readyState === WebSocket.OPEN) {
	                console.log('connected');
	                console.log('Send test message');
	                var buffer = str2ab('TEST ARRAY BUFFER');
	                socket.send(buffer);
	            } else {
	                console.log('disconnected');
	            }
	        };
	        socket.onmessage = function(evt) {
	            var data = ab2str(evt.data);
	            console.log('msg from server:', data); // <- It's not working.
	        }
	    });
	});
	</script>

### ENV
+ node 5.1.1
+ windows10 MINGW64 shell
+ total.js@1.9.6-16

**Comment by petersirka** [comment]
Hi @liaosankai 100x sorry.
I have fixed it, please try `npm install total.js@beta` and give me the feedback.

**Comment by liaosankai** [comment]
Hi, @petersirka thank you for your prompt reply and assistance.

I try decode simple binary buffer from server in client is working. and the decode protobuf from server in client is working,too. It's quick example for protobuf encode/decode in client/server :)

### Server
file in `controllers/default.js`

    exports.install = function() {
        F.route('/', view_index);
        F.websocket('/protobuf_lite', socket_protobuf_lite, ['binary'], [], ['*']);
    };

    function view_index() {
        var self = this;
        self.view('index');
    }

    function socket_protobuf_lite() {
        var controller = this;
        var ProtoBuf = require('protobufjs');
        var builder = ProtoBuf.loadProto('package Zoo.Animals; message Dog {required string name = 1;}');
        var Zoo = builder.build("Zoo");
        var Dog = Zoo.Animals.Dog;

        controller.on('open', function(client) {
            console.log('Connect / Online:', controller.online);
        });
        controller.on('close', function(client) {
            console.log('Disonnect / Online:', controller.online);
        });
        controller.on('message', function(client, arraybuffer) {
            var msg = Dog.decode(arraybuffer);
            console.log('--- PROTOBUF ---');
            console.log(msg);
            // resend to client
            var dog = new Dog(msg);
            var buffer = dog.encode();
            controller.send(buffer.toArrayBuffer());
        });
    }

### Client
file in `views/index.html`

    <button id="test-protobuf_lite">
        ws://127.0.0.1:8000/protobuf_lite
    </button>

    <script src="bower_components/bytebuffer/dist/ByteBufferAB.min.js"></script>
    <script src="bower_components/long/dist/long.min.js"></script>
    <script src="bower_components/protobuf/dist/protobuf.min.js"></script>
    <script src="bower_components/jquery/dist/jquery.min.js"></script>
    <script>
    $(document).ready(function() {

        var socket = null;

        $('#test-protobuf_lite').on('click', function() {
            var ProtoBuf = dcodeIO.ProtoBuf;
            var builder = ProtoBuf.loadProto('package Zoo.Animals; message Dog {required string name = 1;}');
            var Zoo = builder.build("Zoo");
            var Dog = Zoo.Animals.Dog;

            socket = new WebSocket('ws://127.0.0.1:8000/protobuf_lite');
            socket.binaryType = 'arraybuffer';
            socket.onopen = function() {
                console.log("connecting...");
                if (socket.readyState === WebSocket.OPEN) {
                    console.log("connected");
                    console.log('Send test message');
                    var dog = new Dog({
                        "name": "Tom"                   
                    });
                    var buffer = dog.encode();
                    socket.send(buffer.toArrayBuffer());
                } else {
                    console.log('disconnected');
                }
            };
            socket.onmessage = function(evt) {
                var data = Dog.decode(evt.data);
                console.log('msg from server:', data);
            }
        });
    });
    </script>

### Result in client 
![decode-success](https://cloud.githubusercontent.com/assets/82476/12263945/ffb3d8ce-b96d-11e5-8b4e-363fadcfc997.jpg)

### ENV
+ node 5.1.1
+ windows10 MINGW64 shell
+ total.js@1.9.6-19

**Comment by petersirka** [comment]
Great! I'm closing this issue.
