### ISSUE TITLE
Add a setter for the query property

### ISSUE THREAD

**Issue by lpinca** [totaljs/framework#353]
If someone tries to set the `query` property on the request object an error is thrown, see https://github.com/primus/primus/issues/420.

This happens because the property has a [getter](https://github.com/totaljs/framework/blob/73e855354686602a636640d894f08c7c966b606b/index.js#L14483-L14489) but not a setter.

Providing an empty setter should fix the issue. If you are happy with it I can send a pr.

**Comment by petersirka** [comment]
Hi @lpinca,
mhhh --> thanks, I have added it `npm install total.js@beta`.
