### ISSUE TITLE
WebSocketClient.close() don't support message with UTF8 char

### ISSUE THREAD

**Issue by liaosankai** [totaljs/framework#354]
Hi, @petersirka 

[WebSocketClient.close()](http://docs.totaljs.com/v1.9.x/en.html#api~FrameworkWebSocketClient~client.close
) seem don't support pass message with UTF-8 chars

Example:

    controller.on('open', function(client) {
        client.close('中文');
    }

Error in client chrome console:

    WebSocket connection to 'ws://127.0.0.1:8000' failed: Received a broken close frame containing invalid UTF-8.

But if I pass only ASCII:

    controller.on('open', function(client) {
        client.close('chinese');
    }

Working in client chrome console:

![2016-01-15_170507](https://cloud.githubusercontent.com/assets/82476/12349428/96c209aa-bbaa-11e5-8bf1-06f0940b1836.jpg)

And my JS file is UTF-8 encode.

### ENV
node 5.1.1
windows10 MINGW64 shell
total.js@1.9.6-21

**Comment by petersirka** [comment]
Hi @liaosankai,
please download `index.js` from this branch <https://github.com/totaljs/framework/tree/v1.9.6>. I have added encoding. Please give me the feedback.

**Comment by liaosankai** [comment]
It's working in client 

    socket.onclose = function(evt) {
        // evt.reason = '%E4%B8%AD%E6%96%87'
        console.log('CLOSE:', decodeURIComponent(evt.reason)); // 中文
    }

![2016-01-15_180525](https://cloud.githubusercontent.com/assets/82476/12350539/99b4f566-bbb2-11e5-9a20-1860a7159703.jpg)

**Comment by petersirka** [comment]
Great, I'm closing issue.
I'll publish a new version next week.
