### ISSUE TITLE
self.file with ~ in path results in 404

### ISSUE THREAD

**Issue by neonnds** [totaljs/framework#356]
Hi Peter,

From a controller i'm trying to return a file:

self.file('~/files/test.png');

I use to be able to place a ~ in the path and it would result in being able to access files outside  'directory-public' . 

Any ideas? Thanks.

**Comment by petersirka** [comment]
Hi @neonnds,
try this:

```javascript
self.file('~' + F.path.root('/files/test.png'));
```

Thanks.

**Comment by neonnds** [comment]
That did the trick. So it seems it needed an absolute path instead of relative. Love your work Peter.

**Comment by petersirka** [comment]
Yes, the problem was on OS Windows, so I had to switch `relative` to `absolute`.
Many thanks!
