### ISSUE TITLE
Load page without refresh

### ISSUE THREAD

**Issue by Poliformado** [totaljs/framework#358]
Hi @petersirka, I am trying make a load of pages without refresh in the browser but no find the way of do what than the controller use the WebSockets for switch between views.

Is there any way with Total JS and WebSockets or he has to do with AJAX?

Thanks.

**Comment by petersirka** [comment]
Hi @Poliformado,
I have created a simple example with WebSocket for understanding.

__Websocket:__
<https://github.com/totaljs/examples/tree/master/views-websocket>

__Older XHR (AJAX)__:
<https://github.com/totaljs/examples/tree/master/views-xhr>

Thanks.
