### ISSUE TITLE
total init has error path in window

### ISSUE THREAD

**Issue by liaosankai** [totaljs/framework#360]
Hi, @petersirka 

![2016-01-27_185023](https://cloud.githubusercontent.com/assets/82476/12611334/0f48904e-c527-11e5-93d5-f8c11dc1d080.png)

ENV:
+ node 5.4.0
+ windows10 MINGW64 shell
+ total.js@1.9.7-2

**Comment by petersirka** [comment]
Nooooooooo :-(
I'm going to fix it, really sorry.

**Comment by petersirka** [comment]
I have fixed it.
Please install latest beta `npm install -g total.js@beta`. Really sorry again.

**Comment by petersirka** [comment]
@liaosankai I have updated in the beta version `F.websocket()`. Flags can contain origins + protocols like this 'F.websocket(..., ['https://www.privater.eu', 'https://www.totaljs.com', 'roomA', 'roomB'])`.

**Comment by liaosankai** [comment]
![2016-01-27_204649](https://cloud.githubusercontent.com/assets/82476/12613815/14620e56-c537-11e5-95f9-91de9d56952b.jpg)

It's working :) 

@petersirka the new flag for F.websocket() let's me easy to use in my project. thank you!!
