### ISSUE TITLE
total.js in producction: ubuntu:nginx:pm2

### ISSUE THREAD

**Issue by adrianrey05** [totaljs/framework#361]
Hi @petersirka 

I have nginx as web server, proxy inverse
pm2 total.js running two applications, ports 8000 and 8001

8000 app is at the root, example.com
and the app is in 8001 in example.com/faq

Entering example.com all right, but example.com/faq wanting to bring all js and css layout files using the tag @ {import ()} is not taking the path / faq

this is my configuration in ngnix
```nginx
server {
    listen 80;

    server_name example.com;

    location / {
        proxy_pass http://localhost:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
	
    location /faq {
        proxy_pass http://localhost:8001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
```

I hope you can help me.

**Comment by petersirka** [comment]
Hi @adrianrey05,
yes, because each application begins from the `/` root path.

You can change the mapping of static files easily:
<http://docs.totaljs.com/v1.9.x/en.html#api~FrameworkConfiguration~static-url-script>
<http://docs.totaljs.com/v1.9.x/en.html#api~FrameworkConfiguration~static-url-style>

```html
static-url-script     : /faq/js/
static-url-style      : /faq/css/
```
And the web routing must start too with:
```javascript
F.route('/faq/');
```

Do you understand? ... or I don't understand :-D

**Comment by adrianrey05** [comment]
Hi @petersirka 
lol :smile:  sorry for my inglish.
i add in the config-release:

 static-url : /faq/
 static-url-js : /faq/js/
 static-url-css : /faq/css/
 static-url-script     : /faq/js/
 static-url-style      : /faq/css/

and in the controllers:
```js
/* global F */
exports.install = function() {
    F.route('/faq/*', 'index');
    // or
    // F.route('/');
};
```
But it does not work.
And also I have a folder **/public/lib** which is bower_components, that does not work.

![image](https://cloud.githubusercontent.com/assets/5314570/12687851/29acfef8-c6b1-11e5-98ec-ffcdc539b595.png)

**Comment by petersirka** [comment]
OK and does this `example.com:81/faq/` work?

**Comment by adrianrey05** [comment]
yes.
![image](https://cloud.githubusercontent.com/assets/5314570/12687969/e76ed0a6-c6b1-11e5-8214-fb551477c53f.png)

**Comment by petersirka** [comment]
OK and send me please the content (create screenshot or whatever) of public directory in `/faq/` app.
Thanks.

**Comment by adrianrey05** [comment]
this is a [repo](https://github.com/adrianrey05/total-faq)

**Comment by petersirka** [comment]
OK, I see the problem:
<https://github.com/adrianrey05/total-faq/tree/master/public>

Append scripts and styles into the /public/faq/ directory and everything will be ok.
Thanks :-)

**Comment by adrianrey05** [comment]
the files are.
the folder /public/lib when I run "install bower" is created.

I can not access /public/views/index.html
![image](https://cloud.githubusercontent.com/assets/5314570/12688390/bdf07a2e-c6b4-11e5-83b0-06f73d0eaae3.png)

**Comment by petersirka** [comment]
`/faq/views/index.html` is routed into `/public/faq/views/index.html`.
Do you understand? :-)

**Comment by petersirka** [comment]
I'll add some feature into the framework for this case.
I'll will think about it.

**Comment by adrianrey05** [comment]
Ok, it works. :+1: 
But it remains unclear ...
I will review the code to try to help in this issue.

Thanks for your help.

**Comment by petersirka** [comment]
Hi @adrianrey05,
done, I have added it.
Try a new beta version `npm install total.js@beta`.

__How does it work?__

Add into your app config the line below:

```html
default-root    : /faq/
```

**Comment by adrianrey05** [comment]
Hi @petersirka.
It´s work :+1: 
you're a genius man!

but when using @{import()} for some cdn, the url is {default-root}//maxcdn....
I solved using the same link for each file

thanks for you help.

**Comment by petersirka** [comment]
Hi @adrianrey05,
yes, you're right. I have fixed it. Please download the latest beta `npm install total.js@beta`.

Thanks.
