### ISSUE TITLE
Error returning view

### ISSUE THREAD

**Issue by dmilovanovic** [totaljs/framework#362]
Hi,

I'm developing application using total.js and encounter strange bug. It doesn't happen every time but from time to time and that's event stranger.
Let's suppose we have two controllers - project.js and issue.js and two corresponding views - project/detail.html and issue/detail.html. When I try to open e.g. project/detail.html I get internal server error with following message:

`Error: View: detail - Error: self.repository.task.title - Line: 19 - Cannot read property 'title' of undefined (http://localhost:8000/project/12) Error: View: detail - Error: self.repository.task.title - Line: 19 - Cannot read property 'title' of undefined
    at Object.Controller.view (/home/dragan/nodejs/Archybility/node_modules/total.js/index.js:12432:13)
    at Query.<anonymous> (/home/dragan/nodejs/Archybility/controllers/project.js:60:9)
    at /home/dragan/nodejs/Archybility/node_modules/kareem/index.js:177:19
    at /home/dragan/nodejs/Archybility/node_modules/kareem/index.js:109:16
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickDomainCallback (node.js:422:13)`

Similar happens for the other view. Controller project.js returns self.view('detail', self).
The strangest thing is that the property it can't find - in this case self.repository.task.title doesn't exists in the detail.html. The other action for the issue/detail.html also fires up error with error that it can't find self.repository.project._id field which doesn't exist in the issue/detail.html but it exists in the project/detail.html.
It's just like the engine is returning wrong view sometime and after a while it get's back to normal.
Development env: Fedora 20, nodejs v5.4.1, npm v3.5.3, total.js v1.9.6.

Thanks in advance!

**Comment by petersirka** [comment]
Hi @dmilovanovic,
yes you're right. I found the bug in view caching.
Please download latest beta `npm install total.js@beta` and give me a feedback.

Thanks!

**Comment by dmilovanovic** [comment]
Hi @petersirka,

Now it seems ok!
Thanks very much!

**Comment by petersirka** [comment]
Great!
Thanks.
