### ISSUE TITLE
debug in vs.code

### ISSUE THREAD

**Issue by adrianrey05** [totaljs/framework#364]
Hi everyone,

I'm trying to debug in vs.code but just starting out this error.

![image](https://cloud.githubusercontent.com/assets/5314570/12851750/4b936b3e-cc0a-11e5-8804-710c7c8a60cf.png)

this is the command that starts
```cmd
node --debug-brk=39597 --nolazy --harmony debug.js 
```

This is the configuration file
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch",
			"type": "node",
			"request": "launch",
			"program": "debug.js",
			"stopOnEntry": false,
			"args": [],
			"cwd": ".",
			"runtimeExecutable": null,
			"runtimeArgs": [
				"--nolazy",
            "--harmony"
			],
			"env": {
				"NODE_ENV": "development"
			},
			"externalConsole": true,
			"sourceMaps": false,
			"outDir": null
		},
		{
			"name": "Attach",
			"type": "node",
			"request": "attach",
			"port": 5858
		}
	]
}
```

any suggestions?

**Comment by petersirka** [comment]
Hi @adrianrey05:

1. don't use `debug.js`
2. if you use `node > 12` then remove `--harmony` argument

Why don't use `debug.js`?
because `debug.js` runs another instance of total.js.

__Solution:__

- create `/app/index.js`
- append `require('total.js').http('debug');`
- save
- run it in the CMD

Thanks.

**Comment by adrianrey05** [comment]
ok. I could solve adding "debugging" in args
This is how it should be the configuration file
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch",
			"type": "node",
			"request": "launch",
			"program": "debug.js",
			"stopOnEntry": false,
			"args": [
            "debugging"
         ],
			"cwd": ".",
			"runtimeExecutable": null,
			"runtimeArgs": [
				"--nolazy",
				"--harmony"
			],
			"env": {
				"NODE_ENV": "development"
			},
			"externalConsole": true,
			"sourceMaps": false,
			"outDir": null
		},
		{
			"name": "Attach",
			"type": "node",
			"request": "attach",
			"port": 5858
		}
	]
}
```

but when you start creating an exception in fs.existSync(path) => (total.js line 8138)
![image](https://cloud.githubusercontent.com/assets/5314570/12853204/8394f622-cc11-11e5-9f35-6ee7824b8404.png)

debugging in vs.code
![image](https://cloud.githubusercontent.com/assets/5314570/12853157/5500fde2-cc11-11e5-93d1-d0e60dcdba3e.png)

output console
![image](https://cloud.githubusercontent.com/assets/5314570/12853223/a25586ee-cc11-11e5-9dc3-538e127e08b8.png)

**Comment by adrianrey05** [comment]
debug tab, deactivate "All Exceptions" and start all good
![sin titulo](https://cloud.githubusercontent.com/assets/5314570/12853800/ccb0dbde-cc14-11e5-8850-9e933d2fd321.jpg)

**Comment by sant123** [comment]
File lauch.json should be like this:

``` json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/debug.js"
        }
    ]
}
```
And debug.js like this:

``` js

const options = {};

// options.ip = '127.0.0.1';
// options.port = parseInt(process.argv[2]);
// options.config = { name: 'Total.js' };
// options.sleep = 3000;
// options.inspector = 9229;
// options.debugger = 40894;

// require('total.js/debug')(options);
require('total.js').http('debug', options);
```

Everything working :smile: 


PID         : 12619
Node.js     : v8.2.1
Total.js    : v2.7.0
OS          : linux 4.10.0-30-generic

**Comment by sant123** [comment]
Awesome. Thank you @vespaiach 🤓
