### ISSUE TITLE
get form data

### ISSUE THREAD

**Issue by Haajsaiko** [totaljs/framework#365]
Hello ! 
trying to get form field info in contact form! 
Using example controller.mail and can't figure how to get the form fields instead of the "MODEL NAME this is message."
Hope it's understandable

Thanks for your help

**Comment by petersirka** [comment]
Hi @Haajsaiko,

__Action in the controller__:
```javascript
// self.query ===> parsed values from URL (GET)
// self.body  ===> parsed values from request body (POST/PUT/DELETE)

var model = self.body;
// model contains form fields
self.mail('petersirka@gmail.com', 'Test e-mail', '~email', model);
```

__Mail template__:
```html
<div>name: @{model.form_field_name1}</div>
<div>email: @{model.form_field_name2}</div>
<div>phone: @{model.form_field_name3}</div>
<div>body: @{model.form_field_name4}</div>
```

Do you understand?
Thanks.

**Comment by Haajsaiko** [comment]
Thanks for your quick answer! (for the understandable thing I was speaking about my question! :p)

Now I think I don't really get the 'model' thing... 
Still have blank mail (in fact just label...) With a console log in redirect_mail() I have : 
"console.log(model) : object Object" idem for 'console.log(this)'... 

I'm sure I missed something there... :(

**Comment by petersirka** [comment]
Do you have a small example? Send me it on my email petersirka@gmail.com and I'll look into it.
Thanks..

**Comment by Haajsaiko** [comment]
okay just send you a mail ! 
big Thanks

**Comment by petersirka** [comment]
I found the problem, update your route to mail like this:

```javascript
F.route('/mail/', redirect_mail, ['post']);
```

The framework rejected your form, you create a nice fallback :+1: (therefore the model was empty)

```html
<a  class="btn btn-success" href="/mail/">Send message</a>
```

Give me a feedback.

**Comment by Haajsaiko** [comment]
Hello, me again! 

Now with this route I can't see my index. instead I just have this {"message":""} 

Any idea ?

**Comment by Haajsaiko** [comment]
When i tried another url like localhost:8000/news it's ok, then I tried to send a mail It gave me a 404 error but when trying to come back to the index, --> {"message":""}

**Comment by petersirka** [comment]
I'll answer tomorrow because I'm out. Thanks!

**Comment by Haajsaiko** [comment]
No problem!

**Comment by petersirka** [comment]
I'm here. I found the problem:

- you have declared two same routes to two different actions

```javascript
F.route('/', view_index);
// F.route('/', json_index);
```

**Comment by petersirka** [comment]
I'm closing issue, I don't have any response.

**Comment by Haajsaiko** [comment]
Hello, sorry I was disconnected all the weekend. 
I already changed it but I still can't get the fields in my mail... 

When I use "F.route('/mail/', redirect_mail);" in the mail I have blank fields in the mail 
but when I use "F.route('/mail/', redirect_mail, ['post']);" I don't receive mail and have a 404 error... 

If I understand maybe it's "@{model.name}" in email.html who can't get the field ?

Do you have any idea ? 

Thanks

**Comment by petersirka** [comment]
When I use `F.route('/mail/', redirect_mail);` in the mail I have blank fields in the mail:
__yes, because your model is empty (self.body too)__

Please study this example:
<https://www.dropbox.com/s/jbzhxag5xwrn2ej/contact-form.zip?dl=0>

Thanks

**Comment by Haajsaiko** [comment]
It works. !
A big THANK YOU for your help !
