### ISSUE TITLE
https server

### ISSUE THREAD

**Issue by maxxam11** [totaljs/framework#366]
Hello. How create https server with total.js? (I didn't find this information in docs).

**Comment by petersirka** [comment]
Hi @maxxam11,
yes, you're right.

```javascript
var options = {};

options.https = {
  key: fs.readFileSync('test/fixtures/keys/agent2-key.pem'),
  cert: fs.readFileSync('test/fixtures/keys/agent2-cert.pem')
};

require('total.js').https('debug', options);
```
<http://docs.totaljs.com/v1.9.x/en.html#api~Framework~framework.https>

PS: I recommend to use NGINX as reverse proxy for it.

**Comment by maxxam11** [comment]
Thank you!

--
С уважением, Максим Карачев
12 февр. 2016 г. 20:44 пользователь "Peter Širka" <notifications@github.com>
написал:

**Comment by petersirka** [comment]
Please give me a feedback if it works. I didn't use node.js HTTPS.
Thanks!

**Comment by maxxam11** [comment]
Https works without any problem.

--
С уважением, Максим Карачев
12 февр. 2016 г. 20:48 пользователь "Peter Širka" <notifications@github.com>
написал:

**Comment by petersirka** [comment]
Great! Thanks.
