### ISSUE TITLE
`F.log(message)` and then do `console.log(message)` synchronously ?

### ISSUE THREAD

**Issue by liaosankai** [totaljs/framework#369]
Hi, @petersirka 

I often use `F.log(message)`  and then `console.log(message)` for track code. Could  `F.log()` be add optional param for save log and console.log synchronously ?

It seems lik: 

    F.log(message, true);

equivalent to:

    F.log(message);
    console.log(message);

---

`F.logger` seem has asynchronous problem.

    for(var i=0; i<100; i++) {
        F.logger('mylog', i);
    }

content in mylog.log

    2016-02-24 12:04:03 | 0
    2016-02-24 12:04:03 | 2
    2016-02-24 12:04:03 | 3
    2016-02-24 12:04:03 | 4
    2016-02-24 12:04:03 | 7

or maybe I shouldn't have done that ?

**Comment by petersirka** [comment]
Hi @liaosankai,
this is a problem because `F.log` is multi-argument and `true` can be a value. I recommend to rewrite prototype and replace `Fs.appendFileSync()` instead of `Fs.appendFile()`. Create a definition or module with this content:

```javascript
var Fs = require('fs');
F.log = function() {

	var self = this;
	var now = new Date();
	var filename = now.getFullYear() + '-' + (now.getMonth() + 1).toString().padLeft(2, '0') + '-' + now.getDate().toString().padLeft(2, '0');
	var time = now.getHours().toString().padLeft(2, '0') + ':' + now.getMinutes().toString().padLeft(2, '0') + ':' + now.getSeconds().toString().padLeft(2, '0');
	var str = '';
	var length = arguments.length;

	for (var i = 0; i < length; i++) {
		var val = arguments[i];
		if (val === undefined)
			val = 'undefined';
		else if (val === null)
			val = 'null';
		else if (typeof(val) === OBJECT)
			val = util.inspect(val);
		str += (str ? ' ' : '') + val;
	}

	self.path.verify('logs');
	Fs.appendFileSync(utils.combine(self.config['directory-logs'], filename + '.log'), time + ' | ' + str + '\n');
	return self;
};
````

**Comment by liaosankai** [comment]
Sorry, I forget `F.log` is multi-argument like `console.log` :( 

---

It's good idea to rewrite prototype by module. I will try it.

Thank you :)

**Comment by petersirka** [comment]
No problem :-) and sorry for it.
