### ISSUE TITLE
`Array.findIndex()` Cannot read property if one element of array is empty object, null, undefined.

### ISSUE THREAD

**Issue by liaosankai** [totaljs/framework#370]
hi, @petersirka 

if array contain empty object , null, undefined will get TypeError

Test:

	var arr = [
		{id: 1, name: "Tom"},
		{id: 2, name: "John"},
		{}, // or null, undefined
		{id: 3, name: "Bill"},
	];

    var index = arr.findIndex('name', 'foo');

Error Message:

    TypeError: Cannot read property 'name' of undefined
      at Array.findIndex (\node_modules\total.js\utils.js:4220:15);

ENV: 
+ total.js@1.9.7-30
+ node 5.4.0
+ window 10 MINGW64(Git bash)

**Comment by petersirka** [comment]
Thanks!
I have fixed it.

Please download `utils.js` from <https://github.com/totaljs/framework/tree/v1.9.7>.
Thanks again!
