### ISSUE TITLE
leak memory in post

### ISSUE THREAD

**Issue by maxxam11** [totaljs/framework#371]
Hello!
I think in the http post request there is a memory leak.
If I send the post variable (size 250Kb) to a server, then server memory was not realesed (post request use 250Kb from server memory and not clear).
If I send one post per second, then total.js reboot from any times, becouse server don't have any memory.

Would you like to check it?

**Comment by petersirka** [comment]
Hi @maxxam11, do you have a small example? Thanks

**Comment by maxxam11** [comment]
**index.html**
setInterval(function(){
   $.ajax({
       uri: '/server',
       method: 'post',
       data: {imgBase64: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDh...'}, //size 250Kb
   });
}, 1000);

**server.js**
exports.install = function() {
    F.route('/server', img_to_cache, ['post']); 
}

function img_to_cache() {
   var self = this;
   self.header('Access-Control-Allow-Origin' , '*');
   var data = self.post.imgBase64;
   F.cache.add('cache_key', data, new Date().add('s', 20));
   self.json({ret: 1});
}

**htop**
In server every 1 second use +250Kb memory and dont clear.

**Comment by petersirka** [comment]
Try to new beta `npm install total.js@beta`.
The second number on the screenshot below is count of requests:

![screenshot](https://cloud.githubusercontent.com/assets/2414252/13365625/612b200e-dcd6-11e5-912c-b31b4a55470a.png)

**Comment by maxxam11** [comment]
I can not fully understand how the garbage collector. Perhaps the error in my project. Let's close the issue. If I find something interesting, I'll write.

**Comment by petersirka** [comment]
Try to run your script like this:

```bash
node --nouse-idle-notification --expose-gc yourscript.js
```

Thanks.
