### ISSUE TITLE
Helper for build query string from param object ?

### ISSUE THREAD

**Issue by liaosankai** [totaljs/framework#372]
Hi, @petersirka 

I use `String.prototype.parseQuery()` to get params object and then rebuild query string after add or remove some property 

    var query = 'p=1&b=2';
    var params = query.parseQuery();
    // param
    // {
    //     'p': '1',
    //     'b': '2'
    // }

Maybe should have a helper like as follow,or i miss it ?

    params['xyz] = 123;
    delete params.b;
    var query = U.buildQuery(params);

    // new query string
    // p=1&xyz=123

**Comment by petersirka** [comment]
Hi @liaosankai,
for this case is good:

```javascript
var Qs = require('querystring');
console.log(Qs.stringify(params));
```

<https://nodejs.org/dist/latest-v4.x/docs/api/querystring.html>

---

I have added a new method for views:

```html
<!-- @{href({ key1: 1, key2: 2 })} -->
<!-- @{href('key1=value1&key2=value2')} -->
<!-- @{href('key', 'value')} -->
<a href="@{href('sort', 1)}">ASC</a>
<a href="@{href('sort', 2)}">DESC</a>
<a href="@{href('search', '')}">Reset search</a>

<!-- OUTPUT -->
<!-- e.g. current URL: /?search=total&sort=5 -->

<a href="/?search=total&sort=1">ASC</a>
<a href="/?search=total&sort=2">DESC</a>
<a href="/?search=&sort=5">Reset search</a>
```

The method updates current QueryString and returns modified current relative URL.
Thanks.

**Comment by liaosankai** [comment]
Yes, I just want the new method in views. Thank you.!!

**Comment by petersirka** [comment]
No problem :-)
The only one problem with this method is that the method can't remove a value. The value can be changed, not removed.

Thanks
