### ISSUE TITLE
Mongodb access on index ?

### ISSUE THREAD

**Issue by Haajsaiko** [totaljs/framework#374]
Hello ! 
Sorry to bother, but in my project I can't access to db on my index page... 
The thing is that it works perfectly on other pages but not on index... 
I used the mongodb example, even tried to insert a view where it works but it displays nothing on index... 

Any idea ? 

Thanks.

**Comment by petersirka** [comment]
Hi @Haajsaiko,
which example? Please write me URL.

Thanks.

**Comment by Haajsaiko** [comment]
This one : 
https://github.com/totaljs/examples/tree/master/mongodb

I really can't understand why it works on all pages but index... u_u'

thx

**Comment by petersirka** [comment]
Hmmm I have tested it and everything works correctly. Can you send me your example on my email?

**Comment by Haajsaiko** [comment]
Just send it 
Thanks

**Comment by petersirka** [comment]
This works:

```javascript
DATABASE('logos').find({}).toArray(this.callback('index'));
```

and this doesn't work:

```javascript
```

**Comment by Haajsaiko** [comment]
Sorry, but it still displays nothing... :(

**Comment by petersirka** [comment]
You have sent me only a part of the code. I didn't see your data, I have tested it on my database from MongoDB example. Do you have teamviewer? Contact me on my email or hangouts: __petersirka__. I want to help you.

**Comment by Haajsaiko** [comment]
Thanks send you an invitation

**Comment by Haajsaiko** [comment]
Issue solved! Thank you again!!
