### ISSUE TITLE
FrameworkWebSocketClient how to ping() specially client id?

### ISSUE THREAD

**Issue by liaosankai** [totaljs/framework#375]
hi @petersirka 

I need to know every client connect quality. I want to make a timestamp and then ping specially client id to get their response timestamp for count connect speed. or have better soluttion ?

**Comment by petersirka** [comment]
Hi @liaosankai,
the framework doesn't have any solution for it. My recommendation:

1. each new client has to obtain a timestamp from the server e.g. `Date.now()`
2. the you have to maintain the timestamp on client-side e.g. `setInterval()` each 1 second
3. each message from client-side will contain timestamp
4. you will obtain information of duration between the client-side and server-side
5. you have to synchronize timestamp of each client each 5 minutes

This is sufficient.
Thanks :-)

**Comment by liaosankai** [comment]
@petersirka 

Thank your  recommendation. I had to implement follow your hints and it's working well.

**Comment by petersirka** [comment]
I found a bug in websocket `controller.send()`, so please download the latest version from GitHub :-)
I'll publish the new version this week.

Thanks.
