### ISSUE TITLE
Flash message module timeout still not correct

### ISSUE THREAD

**Issue by LeventeNagy** [totaljs/framework#377]
Hi @petersirka

I am using the flash messages module. https://github.com/totaljs/modules/tree/master/Miscellaneous/flash

No matter what I do i how I do, the flash message expires really late.
I am using the flash module for form validation messages, and the minimum what i can set is 1 minute, even if I do not use it for form validation, if I use it for something else 1 minute is really long.

Is there any way i can set the flash message to 1 second?

Thank you for your reply

**Comment by petersirka** [comment]
Hi @LeventeNagy,
I have updated the module on GitHub, try it:

```javascript
MODULE('flash').expire = '5 minutes';

// or you can set special expiration for specific route:
F.route('/message/', ..., ['#flash', { expire: '1 minute' }]);
```
Give me a feedback.

**Comment by LeventeNagy** [comment]
Am I doing something wrong?

I added 1 second and no still the same

` F.route('/login', get_login, ['unauthorize', '#flash', { expire: '1 second' }]);`

Still the same

If iI change 
`exports.expire = '1 second';` in the module still the same

if i use
`F.use('flash')`

still the same

**Comment by petersirka** [comment]
And do you download the module from GitHub?

**Comment by LeventeNagy** [comment]
Yes I did right after your reply :)

**Comment by petersirka** [comment]
Please try it again.

**Comment by LeventeNagy** [comment]
Looks like it works now

Thank you so much for solving this problem so fast

You are awesome
