### ISSUE TITLE
websocket won't dispatch close event when direct turn off wi-fi on client mobile

### ISSUE THREAD

**Issue by liaosankai** [totaljs/framework#380]
hi @petersirka 

In normal times, I close app directly and websocket server catch client disconnect and dispatch close event, but if I turn off wi-fi directly and keep app run, server can't catch client disconnect and i get some error info on server:

    Error: read EHOSTUNREACH Error: read EHOSTUNREACH
        at exports._errnoException (util.js:856:11)
        at TCP.onread (net.js:544:26)

or I should to catch on error event, not close event in controller?

### ENV
+ node.js: v5.5.0
+ total.js: v1.9.7-31
+ os: win10

**Comment by petersirka** [comment]
Hi @liaosankai,
please download the latest beta version `npm install total.js@beta` (__IMPORTANT:__ it's 2.0). I have added catching this exception and when it will exist then I kill the connection.

Give me a feedback.

**Comment by liaosankai** [comment]
I updated to total.js@2.0.0-6 and get `controller.cors is not a function` error. I found it's move to F.cors() and F.route() has new flag `cors` in `https://github.com/totaljs/framework/blob/v2.0.0/changes.txt`. Should I use new method or flag ?

**Comment by petersirka** [comment]
Sorry and yes.

- `F.cors()` automatically create own route for cors requests (the browser sends a preflight and the framework doesn't execute controller, only it responds for the request)
- `F.route()` with `cors` evalutes `F.route()` and then registers a cors route with same URL + flags via `F.cors()`

`v1.9.7` supports new cors mechanism and `v2.0.0` removed old.

Answer for your question:
- yes, you can use new flag or:

```javascript
F.route('/api/users/', some_action1, ['get']);
F.route('/api/users/', some_action2, ['post']);
F.route('/api/users/', some_action3, ['put']);
F.route('/api/users/', some_action4, ['delete']);
F.cors('/api/users/', ['get', 'post', 'put', 'delete', 'credentials']);

// is same as

F.route('/api/users/', some_action4, ['get', 'post', 'put', 'delete', 'cors', 'credentials']);
```

**Comment by liaosankai** [comment]
Is it also apply `F.websocket()` ? Like:

    F.websocket('/lobby', socket_lobby, ['binary','cors']);

**Comment by petersirka** [comment]
No, `websocket` is a bit different. Websocket is cors enabled by default. You can only restrict websocket flags about e.g. your own origin `http://` (default `*`) or protocol e.g. `chat`, `private`, etc..

**Comment by liaosankai** [comment]
I make a new test project

### controllers/default.js

	exports.install = function() {
		F.route('/', view_index);

		F.websocket('/wifi-test', socket_wifi, ['binary']);
	};

	function socket_wifi() {
		var ctrl = this;
		ctrl.on('open', function(client, arraybuffer){
			console.log('Connect / Online:', ctrl.online);
		});
		ctrl.on('close', function(client){
			console.log('Disconnect / Online:', ctrl.online);
		});	
		ctrl.on('error', function(err, arraybuffer){
			console.log('Error & Disconnect / Online:', ctrl.online);
		});	
	}

	function view_index() {
		var self = this;
		self.repository.ip = F.ip;
		self.repository.port = F.port;
		self.view('index');
	}

### views/index.html

	@{title('Something awesome')}
	<hr />
	<br />
	<p class="center">
	    The node.js framework for all web developers with everything what you need.
	    <br />
	    <b>Create something awesome.</b>
	</p>
	<br />
	<br />
	<div class="center"><a href="http://docs.totaljs.com" class="linkbutton">DOCUMENTATION</a></div>
	<script>
	var socket = null;
	$(document).ready(function() {
	    socket = new WebSocket('ws://@{repository.ip}:@{repository.port}/wifi-test');
	    socket.onopen = function() {
	        console.log('open');
	    };
	    socket.onclose = function() {
	        console.log('close');
	    };
	});
	</script>
</script>

### Test by brower websocket
![2016-03-23_161858](https://cloud.githubusercontent.com/assets/82476/13979545/2d039606-f114-11e5-804a-1aa755e519b2.jpg)

**Comment by petersirka** [comment]
I understand, but node.js doesn't trigger any event for this case. For this case I have added `ping`:
<http://docs.totaljs.com/v1.9.x/en.html#api~FrameworkConfiguration~default-interval-websocket-ping>

Try to wait. I tried to simulate it 2 hours before.

**Comment by liaosankai** [comment]
I tried to set `default-interval-websocket-ping` and redo test case then wait a night , I found [someone had the same question](http://stackoverflow.com/questions/27356937/how-to-detect-client-side-internet-disconnection-using-node-js) as I have, so I had check `allow-performance` config is true to ensure run `socket.setKeepAlive`, but it doesn't seem to work.

**Comment by petersirka** [comment]
Do you use nginx?
__Try to use__:
```javascript
controller.on('open', function(client) {
   client.socket.setTimeout(0);
});
```

**Comment by liaosankai** [comment]
@petersirka 

I don't use nginx, just use node.js in Win10 without any HTTP Server. I had try code `client.socket.setTimeout(0)` on open, but it's still not working. I google about related topics and discover most language had the same issue. it seems a better solution is to implement heartbeat mechanism. I will try to research it. Thanks for being so thoughtful anyway.
