### ISSUE TITLE
default-websocket-request-length is boken

### ISSUE THREAD

**Issue by liaosankai** [totaljs/framework#381]
hi @petersirka 

I got error `Maximum request length exceeded.` and try to track the cause of the problemin in `total.js/index.js`, the line at 2041

    2031: self.routes.websockets.push({
             ...
    2041:    length: (length || self.config['default-websocket-request-length']) * 1024,
             ...
    2057: });

if the length is NaN and value always `0` to set, not default-websocket-request-length

### ENV
+ node.js: v5.7.0
+ total.js: v2.0.0-6
+ os: win10

**Comment by petersirka** [comment]
Hmmm and how do you define a route? I have tested it and everything works correctly.

**Comment by liaosankai** [comment]
Sorry, I use old usage for route after updated. I pass a array to length param.

    // function(url, funcInitialize, flags, protocols, allow, length, middleware, options) @1.9.7
    F.websocket('my-url', doSomething, ['binary'], ['http']);
