### ISSUE TITLE
websocket origin flag check

### ISSUE THREAD

**Issue by liaosankai** [totaljs/framework#382]
when I updated total.js to new version 2.0.0, my mobile app use websocket  (dev by unity) can't connect total.js server (it's work before updated), I check request raw header from mobile app just only:

    "user-agent": 'websocket-sharp/1.0',
    "upgrade": 'websocket',
    "connection": 'Upgrade',
    "host": '125.227.87.64:8888',
    "sec-websocket-key": 'ZoT14UJsEqzo3hT00fgkmw==',
    "sec-websocket-version": '13' 

it's not like browser websocket add "origin" request raw header automatically, I know just  to add `origin` header can be resolve, but now had some app release. Is it possible to replace `origin` header with `host` header ?

**Comment by petersirka** [comment]
I understand, I think that yes .. I will think about it today, ok?

**Comment by petersirka** [comment]
mmmt... I'll look into it .... I'll fix the problem.

**Comment by petersirka** [comment]
@liaosankai how do you send a message? I have updated `controller.send()` method, do you use it? Or where is the problem? Is the websocket connection destroyed? Or?

**Comment by liaosankai** [comment]
I use supports  [RFC 6455 websocket](https://github.com/sta/websocket-sharp) C# lib in Unity to  establish a WebSocket connection with total.js server, but the lib send request headers without origin to  server and get rejected.

**Comment by petersirka** [comment]
@liaosankai please download the latest beta `npm install total.js@beta`. I have found a bug in `origin` validator. Give me a feedback.

**Comment by liaosankai** [comment]
Sweet! I updated to total.js v2.0.0-9 and both browser and mobile app are working to establish a WebSocket connection now. thank you.
