### ISSUE TITLE
Image save() not working at all

### ISSUE THREAD

**Issue by LeventeNagy** [totaljs/framework#383]
I am not able to solve this problem.

I am trying to upload an image but the save() method doesn't do anything

```
Image.load(self.files[0].filename, true).make(function(image) {
        image.save(self.files[0].filename);
    });
```
Same thing if i try

```
    var image =  Image.load(self.files[0].filename, true);
    image.save(self.files[0].filename, function() {
        self.json('done');
    });
```

Adding a path does not work either

```
Image.load(self.files[0].filename, true).make(function(image) {
        image.save('/public/tmp/'+self.files[0].filename);

        self.json('done');
    });
```

It does not work this way either

```
Image.load(self.files[0].filename, true).make(function(image) {
        image.resizeAlign(200, 200, 'center');
        image.blur(1);
        image.output('jpg');
        image.save(F.path.public('/tmp/resized.jpg'));
    });
```

I do not get back any errors

And my config looks like this

```
default-image-converter         : im
directory-public-virtual		: /public/tmp/
```

ImageMagick is installed works fine

Any hint on this?

**Comment by petersirka** [comment]
Hi @LeventeNagy:
1. which version of total.js do you use?
2. which OS do you use?

Thanks.

**Comment by LeventeNagy** [comment]
I am using v1.9.7 and the same  thing happens on Windows 10 and Ubuntu 14.04 based Linux distro.

Tested on both, both are the same, and currently Im using linux Ubuntu 14.04

**Comment by petersirka** [comment]
Can you test it on `total.js 2.0` --> `npm install total.js@beta`?

__I know about this bug in `v1.9.7` :__
1. when `image()` doens't contain any operations.
2. `windows` doesn't have associated `convert` as global path for CMD (try to use GraphicsMagick or try to write `convert` in `CMD` whether it exists or no).

I prepare `v1.9.8` with bug fixes, but I recommend to use `total.js 2.0`.
Thanks.

**Comment by LeventeNagy** [comment]
Okay thank you for the fast reply, I will test it and give you feedback in a few

**Comment by LeventeNagy** [comment]
Okay, installed` npm install total.js@beta` restarted the server, restarted the computer, still the same :(

**Comment by petersirka** [comment]
OK and try to run in your CMD `convert` argument, what's the output?

**Comment by LeventeNagy** [comment]
Could you please give me an example for the command?

**Comment by petersirka** [comment]
My big mistake :100: 

__Try 1:__
```javascript
var image = self.files[0].image();
image.blur(5);
```

__Try 2:__
- `filname` contains only `filename` not a full path
- `path` contains a path to the real file in `tmp`

```javascript
Image.load(self.files[0].path, true).make(function(image) {
    image.save('/public/tmp/'+self.files[0].path);
    self.json('done');
});
```

Give me a feedback.

**Comment by LeventeNagy** [comment]
```
Image.load(self.files[0].path, true).make(function(image) {
    image.save('/public/tmp/'+self.files[0].path);
    self.json('done');
});

Process runs, no errors, image not saved :( 
returns the following path `"/home/levente/node/fitfeed2/tmp/127001-1459159255863-72450.upload"`

```
Second

```
var image = self.files[0].image();
image.blur(5);

```
If i debug it it returns

```
Image {
  width: 816,
  height: 612,
  builder: [ { cmd: '-blur "5"', priority: 10 } ],
  filename: '/home/levente/node/fitfeed2/tmp/127001-1459159436281-10883.upload',
  currentStream: null,
  isIM: true,
  outputType: 'upload' }
```

**Comment by LeventeNagy** [comment]
Nother test

```
Image.load(self.files[0].path, true).make(function(image) {
        image.save('/public/tmp/'+self.files[0].path);
        self.json(image);
    });
```

outputs

`{"builder":[{"cmd":"+profile \"*\""}],"filename":"/home/levente/node/fitfeed2/tmp/127001-1459159663703-48384.upload","currentStream":null,"isIM":true,"outputType":"upload"}`

**Comment by petersirka** [comment]
You can't save file to `file.path` because when do you responds via `controller.json()` or `controller.view()` or `etc.` then the framework removes all uploaded files. You can disable it via `controller.noClear()` (but I don't recommend it).

__Server-side__:
```javascript
var file = self.files[0];
var target = 'my-new-file.jpg';

file.image().make(function(image) {
    image.output('jpg');
    image.quality(90);
    image.save(F.path.public(target), () => self.json(target));
});
```

__Client-side__:
```javascript
var response = JSON.parse(SERVERRESPONSE);
$(document.body).append('<img src="/' + response + '" />');
```

PS: you can't serialize `self.json(image)` because image is an instance of the `FrameworkImage` and `FrameworkImage` executes only CMD/TERMINAL.

**Comment by LeventeNagy** [comment]
Ah thanks for the info.

This way it works like a charm thank you Peter for your help and fast reply, and sorry for taking your time

Thank you again it works now
