### ISSUE TITLE
Bug in Number.prototype.add

### ISSUE THREAD

**Issue by FKasa** [totaljs/framework#388]
It looked wrong the moment I saw it [on the documentation page](http://docs.totaljs.com/v1.9.x/en.html#api~Number.prototype~Number.prototype.add):

```javascript
var number = 100;

console.log(number.add('-90%'));
// output: 90.9090909...
```

From what I understand, the output should be 10.

When I tried it, it gave me something else entirely:

```javascript
var number = 100;

console.log(number.add('-90%'));
// output: 52.631578947368425
```

Tested on:

```
Windows		 : 8.1 64 bit
node.js      : v4.2.6
total.js     : v1.9.8
```

**Comment by petersirka** [comment]
Hi @FKasa, what the hell, you're right. I have fixed it in v2.0.0.

```javascript
var number = 100;

console.log(number.add('+10'));
// output: 110

console.log(number.add('-10'));
// output: 90

console.log(number.add('*10'));
// output: 1000

console.log(number.add('/10'));
// output: 10

console.log(number.add('10%'));
// output: 10

console.log(number.add('+10%'));
// output: 110

console.log(number.add('-90%'));
// output: 10

console.log(number.add('*10%'));
// output: 1000

console.log(number.add('/10%'));
// output: 10
```

Thank you!

**Comment by petersirka** [comment]
Please download all `*.js` files from GitHub `branch 2.0.0` and copy them to `node_modules/total.js` directory.
<https://github.com/totaljs/framework/tree/v2.0.0>

**Comment by FKasa** [comment]
Thanks, I can confirm the method works correctly now.

Also there was some .ds_store in the node_modules folder in the empty project of the v1.9.8 release. You may want to not include them in next release ;)

**Comment by petersirka** [comment]
@FKasa shiit, I don't know about it. I'll remember it.
Thanks.
