### ISSUE TITLE
eShop order form form wrong lables

### ISSUE THREAD

**Issue by aubergine10** [totaljs/framework#390]
On the [eShop order form](https://www.totaljs.com/eshop/), the labels are wrong way round:

![region capture 5](https://cloud.githubusercontent.com/assets/1386719/14834000/e66aad28-0bf9-11e6-8cb4-8dbc1d0946ac.png)

The drop-down on the right should say Country and the text box on left should say State.

**Comment by petersirka** [comment]
Hmm, maybe you have right. The fields are correct in our country, but I can rename it. I didn't realize it.

**Comment by petersirka** [comment]
Replaced.
Thank you.
