### ISSUE TITLE
AppDesigner - password in plaintext email

### ISSUE THREAD

**Issue by aubergine10** [totaljs/framework#392]
When I create a project in AppDesigner, I get a plain text email which include the password....

![image](https://cloud.githubusercontent.com/assets/1386719/14852027/cfdd1226-0c7b-11e6-9916-c62fef6525b1.jpg)

Luckily I'd used an auto-generated random password rather than any password I might more commonly use.

**Suggestion:** Why not have the app designer auto-generate a password for each new project (so the user doesn't need to specify a password) - that way there is no chance the user will suddenly find one of their personal passwords (eg. that they might use to log in to other sites) floating across the internet in plain text.

Alternatively, don't put password in email and provide a "forgot password" feature.

**Comment by petersirka** [comment]
Yes. The passwords are encrypted in DB. But yes, you're right, I'll add auto-generate password or better solution is to implement user accounts (I didn't have free time for it).

**Comment by aubergine10** [comment]
A reusable user account module would be good, and something you could use on all your apps and also sell in your online store.

* Manual sign-up, login
 * ...option to require email address verification
* Social sign-up, login (using facebook, twitter, etc)
 * ...also populate fields such as name, email, avatar image when signing up
* Forgot password
* Delete account
* Basic "edit profile" page for users to change their email, name, avatar image, etc.
* Account reporting features - users can flag a user as spammer/troll
* Administrator features for managing user accounts
 * Add/remove/edit user profiles
 * Switch to user profile (become that user temporarily to see site as they would see it, and then easily switch back to admin account)
 * Shadow banning

**Comment by petersirka** [comment]
I have added generating random number password.
Thank you.

I will think about your last comment.

**Comment by petersirka** [comment]
I have postponed this task.
