### ISSUE TITLE
SchemaBuilderEntity.prototype.$parse - possible errors in new v2.0.0 types?

### ISSUE THREAD

**Issue by aubergine10** [totaljs/framework#393]
Are you returning too soon if a length is defined?

Example: [v2.0.0/builders.js#L337](https://github.com/totaljs/framework/blob/v2.0.0/builders.js#L337)...

```javascript
if (lower.contains(['camelize', 'camelcase', 'camel'])) { // <-- somewhat excessive?
   result.type = 3;
   var beg = lower.indexOf('(');
   if (beg === -1)
      return result; // <-- uhm, we've not set .subtype yet!
   var size = lower.substring(beg + 1, lower.length - 1).parseInt();
   result.length = size;
   result.raw = lower.substring(0, beg);
   result.subtype = 'camelcase'; // <-- never going to get here if length isn't specified
   return result;
}
```

Should it not be more like this....

```javascript
if (lower.contains(['camel'])) { // <-- is this sufficient?
   result.type = 3;
   result.subtype = 'camelcase'; // <-- make sure we set .subtype!
   var beg = lower.indexOf('(');
   if (beg === -1)
      return result;
   var size = lower.substring(beg + 1, lower.length - 1).parseInt();
   result.length = size;
   result.raw = lower.substring(0, beg);
   return result;
}
```

Note: I'm assuming `lower.contains()` does partial matches? If not then you could just use `lower.indexOf('camel') > -1` (or `!= -1`, whichever is faster)

Also, if the length checking code is used often, why not turn it in to a function to make code cleaner? The `$parse` function is only getting called when models are initially defined so it doesn't need to be super-fast...?

```javascript
var $parseLength = function( lower, result ) {
   var beg = lower.indexOf('(');
   if (beg === -1)
      return result;
   // var size = lower.substring(beg + 1, lower.length - 1).parseInt();
   // -- the size var is only used once, can't we just inline the calc?
   result.length = lower.substring(beg + 1, lower.length - 1).parseInt(); // <-- inlined
   result.raw = lower.substring(0, beg);
   return result;
}

SchemaBuilderEntity.prototype.$parse = function(name, value, required, custom) {

   // ...

   if (lower.contains(['string', 'text', 'varchar', 'nvarchar'])) {
      result.type = 3;
      return $parseLength( lower, result );
   }

   if (lower.contains(['camel'])) {
      result.type = 3;
      result.subtype = 'camelcase';
      return $parseLength( lower, result );
   }

   if (lower.contains(['lower'])) {
      result.type = 3;
      result.subtype = 'lowercase';
      return $parseLength( lower, result );
   }

   if (lower.contains(['upper'])) {
      result.type = 3;
      result.subtype = 'uppercase';
      return $parseLength( lower, result );
   }

  // so much cleaner ;)
}
```

**Comment by petersirka** [comment]
__Code 1 and Code 2__
Ohhh shit, you're right. I have fixed it and yes the code can be optimized better (I'll look into it).

__Code 3__
Yes, you're right, I'll change it.

Thank you!

**Comment by petersirka** [comment]
I have improved the code. What do you think about `Camelize`, __do I have to rename it?__

**Comment by aubergine10** [comment]
I like 'Camelize', it makes it clearer that the field data will be transformed (in this case, Camelized) - as for the parser it can still just check the start of the lower string `camel` to facilitate the synonyms. The docs can list the synonyms.

Same applies to `Upperize` and `Lowerize`.

**Comment by aubergine10** [comment]
Actually, looking at the code for Camelize it's not actually CamelCase (which conventionally removes spaces - like some Wikis use) but "[Title Case](https://en.wikipedia.org/wiki/Letter_case#Case_styles)" which conventionally uppercases the first letter of each word and retains spaces.

So I think the current Camelize/Camel/Camelcase function should be used for 3 new types Titleize/Title/Titlecase, and the Camelize/Camel/Camelcase types should be routed to a new function that also removes spaces.

**Comment by petersirka** [comment]
The framework performs `trim` for all strings. You can disable this behaviour via `schema.trim = false`. Yes, I have renamed `Camelize` to `Capitalize`, it will be better.

I think that other types are not important. Otherwise we can update their in `schema.setPrepare()`. What do you think?

Thank you for improving words.
