### ISSUE TITLE
Enhancement request: enum-like field type

### ISSUE THREAD

**Issue by aubergine10** [totaljs/framework#394]
It would be nice if I could use an enum-like field type in my schemas...

```javascript
schema.define('settings', '[a,b,c,d]');
// allow any or none of the options from the list

schema.define('config', '[a,b,c,d](2)');
// allow up to 2 options from the list (eg. a,c but not a,b,c)
```

Would make code a bit more readable in certain cases (where performance isn't important) as an alternate to using bitmasks.

**Comment by petersirka** [comment]
Too complicated and with minimal benefits. You can use `schema.setPrepare()` method for preparing values.

**Comment by aubergine10** [comment]
Yes, good point.
