### ISSUE TITLE
Enhancement request: tags field type

### ISSUE THREAD

**Issue by aubergine10** [totaljs/framework#395]
Would be nice to have an inbuilt 'tags' field type, for example:

```javascript
schema.define('settings', 'tags');
```

Just as 'camel' transforms text to CamelCase, the 'tags' type would transform text to an array (split on ',' and trim any spaces around each tag).

For example, if a form posts `'a, b, c'` then the value would be transformed to `['a', 'b', 'c']`.

I've not thought about it enough so possible that there's a much better way to handle this scenario.

**Comment by petersirka** [comment]
I don't see any benefits. You can use:

```javascript
// settigns must be an array
schema.define('settings', '[lower(10)]');

// or
schema.define('settings', 'String');

schema.setPrepare(function(name, value) {
    if (name === 'settings')
        return value.toLowerCase().split(',').trim();
});
```

**Comment by aubergine10** [comment]
Agreed. :thumbsup:
