### ISSUE TITLE
utils.js - isDate(): use instanceof instead?

### ISSUE THREAD

**Issue by aubergine10** [totaljs/framework#396]
Current code: https://github.com/totaljs/framework/blob/v2.0.0/utils.js#L1444

```javascript
exports.isDate = function(obj) {
	return (obj && typeof(obj.getTime) === 'function') ? true : false;;
};
```

Suggested change:

```javascript
exports.isDate = function(obj) {
	return ( obj instanceof Date ); // more concise but won't pick up pseudo-date objects
};
```

**Comment by petersirka** [comment]
This is bad because your function `Invalid Date` returns `true` and it's not a valid date object. My solution returns `false` 👍 

Thanks.

**Comment by aubergine10** [comment]
I'm not sure what you mean... `instanceof` returns `true` or `false` like so...

```javascript
function isDate( obj ) {
  return ( obj instanceof Date );
}

console.log( isDate( {} ) ); // false
console.log( isDate( { getTime: function(){} } ) ); // false
console.log( isDate() ); // false
console.log( isDate(12341234) ); // false
console.log( isDate( " " ) ); // false

console.log( isDate( new Date() ) ); // true
```

**Comment by petersirka** [comment]
OK, try this:

```javascript
var dt = new Date('BULLSHIT');
console.log(isDate(dt)); // true
console.log(dt); // Invalid Date
```

**Comment by aubergine10** [comment]
Both my code and your code return `true` as they are checking that it's date object and not an actual valid date in that object.

So code could be better written as:

```javascript
exports.isDate = function(obj) {
    return ( obj instanceof Date && obj.toString() !== 'Invalid Date' );
}
```

Test here: http://js.do/aubergine10/totaljs

**Comment by petersirka** [comment]
Definitely not. I have optimized code 💯 

```javascript
function oldis(obj) {
	return (obj && typeof(obj.getTime) === 'function') ? true : false;
};

function newis(obj) {
    return ( obj instanceof Date && obj.toString() !== 'Invalid Date' );
}

var dtA = new Date();
var dtB = new Date('INVALID');

console.time('old');
for (var i = 0; i < 10000000; i++) {
	oldis(dtA);
	oldis(dtB);
}
console.timeEnd('old');

console.time('old');
for (var i = 0; i < 10000000; i++) {
	newis(dtA);
	newis(dtB);
}
console.timeEnd('old');
```

```html
old: 16.002ms
new: 3153.651ms
```

**Comment by aubergine10** [comment]
Your version still doesn't determine that value of dtB is bullshit though... It's only checking for presence of a .getTime() method on the object, not that the value stored in the object is a valid date...

If we're not worried about the date value being invalid, then my version is slightly faster and also more accurate when it comes to identifying Date instances (rather than any object that has a .getTime() method):

```javascript
function oldis(obj) {
    return (obj && typeof(obj.getTime) === 'function') ? true : false;
};

function newis(obj) {
    return ( obj instanceof Date );
};

var dtA = new Date();
var dtB = new Date('INVALID');

console.time('old');
for (var i = 0; i < 10000000; i++) {
    oldis(dtA);
    oldis(dtB);
}
console.timeEnd('old');

console.time('old');
for (var i = 0; i < 10000000; i++) {
    newis(dtA);
    newis(dtB);
}
console.timeEnd('old');
```

```
old: ~39ms
new: ~37ms
```

**Comment by petersirka** [comment]
Your method is still slowed. But yes this solves all problems with date object:

```javascript
function oldis(obj) {
    return (obj instanceof Date && typeof(obj.getTime) === 'function') ? true : false;
};

function newis(obj) {
    return ( obj instanceof Date );
};

var dtA = new Date();
var dtB = new Date('INVALID');

console.time('old');
for (var i = 0; i < 10000000; i++) {
    oldis(dtA);
    oldis(dtB);
}
console.timeEnd('old');

console.time('new');
for (var i = 0; i < 10000000; i++) {
    newis(dtA);
    newis(dtB);
}
console.timeEnd('new');
```

I' going to change it, satisfied? 👍

**Comment by aubergine10** [comment]
:)

**Comment by petersirka** [comment]
OK done
- https://github.com/totaljs/framework/blob/v2.0.0/changes.txt#L61
- https://github.com/totaljs/framework/blob/v2.0.0/utils.js#L1450

Thank you.

**Comment by docgit** [comment]
Hi Peter,

it seems the change has not actually been merged in properly. As far as I can see, the function returns false for all valid dates that refer to a year before 1970. The reason for this is obviously the getTime() check for -1. 

Regards
Marcel

**Comment by petersirka** [comment]
Hi @docgit, thank you! I have fixed it.
<https://github.com/totaljs/framework/blob/v2.4.0/utils.js#L1583>

Thank you!
