### ISSUE TITLE
U.send() how return percent progress data...

### ISSUE THREAD

**Issue by danielbernalo** [totaljs/framework#398]
Hi peter, total.js is amazing. Thanks, I use it to learn nodejs. excuse my bad English, I'm from Venezuela.

One question, I have a computer that generates a file every 15 days and must send it to a server for processing then I use this function to send and it really works, but I want to add a progress bar but do not know how to make it work. my code:

"/workers/xls.js":

require ("total.js");

U.send ("archivo.bin" F.path.root ("../ public / upload / incidente.xlsx"), http://127.0.0.1:9001/,function (err, res) {
 
    console.log (res);
})

But In U.request () <--- emiter data to progress,

Utils.request("http://127.0.0.1:9001/",['post','upload'],F.path.root("../public/upload/incidente.xlsx"),function(err,res){
   
}). On ('data', function (e, perc) {
     console.log (perc); // percentage
});

When I use the U.request function, not as I send the file if a stream or something, you help me in this. Thanks again for your time and dedication.

**Comment by petersirka** [comment]
Hi @danielbernalo, my english is bad too, so don't worry (I understand to you). The `U.send()` method has a problem with couting of percentage, because I don't have any information about file size.

The `stream` argument supports 3 types:

1. `string` as filename, we can get the file size, but it's a bit complicated to obtain it
2. `stream` as `ReadableStream` and here we can't get the file size (and here is a big problem)
3. `buffer` as `Buffer` and here we have the buffer length

I have updated the method and now it returns `EventEmitter`.

```javascript
require('total.js');

var e = U.send('somefile.txt', '/users/petersirka/desktop/file.txt', 'http://127.0.0.1:8000/', NOOP);
e.on('data', function(chunk, percentage) {
    // chunk will be null
    // percentage will be always 100
});
```

Do you need a percentage? Is it very important for you?
Download all files from this branch: <https://github.com/totaljs/framework/tree/v2.0.0> and replace `total.js` directory in `node_modules` directory.

**Comment by danielbernalo** [comment]
For now it is the only way to see the progress of the transfer, I made a backend with a progress bar to generate the file transfer and had no way of knowing how it goes but when finished.

Thanks a lot for this small change, I try to do it myself before bother you, but could not.

**Comment by petersirka** [comment]
Here you have the method with progress :-)

```javascript
require('total.js');

var Http = require('http');
var Https = require('https');
var Fs = require('fs');
var Url = require('url');
var Events = require('events');

function send(filename, url, callback, headers, method) {

	var BOUNDARY = '----totaljs' + Math.random().toString(16).substring(2);
	var h = {};

	if (headers)
		U.extend(h, headers);

	var name = U.getName(filename);
	var NEWLINE = '\r\n';

	h['Cache-Control'] = 'max-age=0';
	h['Content-Type'] = 'multipart/form-data; boundary=' + BOUNDARY;
	h['X-Powered-By'] = 'total.js';

	var uri = Url.parse(url);
	var options = { protocol: uri.protocol, auth: uri.auth, method: method || 'POST', hostname: uri.hostname, port: uri.port, path: uri.path, agent: false, headers: h };
	var e = new Events.EventEmitter();

	var response = function(res) {
		res.body = '';
		res.on('data', (chunk) => res.body += chunk.toString('utf8'));
		res.on('end', function() {
			var self = this;
			e.emit('end', self.statusCode, self.headers);
			e.removeAllListeners();
			e = null;
			callback(null, self.body, self.statusCode, self.headers);
		});
	};

	Fs.lstat(filename, function(err, info) {

		if (err) {
			// File not found
			e.removeAllListeners();
			e = null;
			callback(err);
			return;
		}

		var size = info.size;
		var connection = options.protocol === 'https:' ? Https : Http;
		var req = connection.request(options, response);

		req.on('error', function(err) {
			e.removeAllListeners();
			e = null;
			callback(err);
		});

		var length = 0;
		var header = NEWLINE + NEWLINE + '--' + BOUNDARY + NEWLINE + 'Content-Disposition: form-data; name="File"; filename="' + name + '"' + NEWLINE + 'Content-Type: ' + U.getContentType(U.getExtension(name)) + NEWLINE + NEWLINE;

		req.write(header);

		var stream = Fs.createReadStream(filename);

		stream.on('data', function(chunk) {
			length += chunk.length;
			e.emit('data', chunk, ((length / size) * 100) >> 0);
		});

		stream.on('end', () => req.end(NEWLINE + NEWLINE + '--' + BOUNDARY + '--'));
		stream.pipe(req, { end: false });
	});
	return e;
};

var upload = send('/users/petersirka/desktop/somefile.zip', 'http://127.0.0.1:8000/', (e, r) => console.log(r));
upload.on('data', function(chunk, percentage) {
	console.log(percentage);
});
```
