### ISSUE TITLE
Better rnd() for GUID()...?

### ISSUE THREAD

**Issue by aubergine10** [totaljs/framework#399]
The v2.0 `rnd()` function in [utils.js #L1609](https://github.com/totaljs/framework/blob/v2.0.0/utils.js#L1609) uses base 16:

```javascript
function rnd() {
	return Math.floor(Math.random() * 65536).toString(16);
}
```

Would it not be better to use base 36 (0-9, a-z)?

```javascript
function rnd() {
	return Math.floor(Math.random() * 65536).toString(36);
}
```

This would greatly increase the uniqueness for a GUID.

**Comment by petersirka** [comment]
Why not? Great idea.

**Comment by petersirka** [comment]
Thank you!
<https://github.com/totaljs/framework/blob/v2.0.0/changes.txt#L47>
