### ISSUE TITLE
Suggestion: Faster someDate.add()

### ISSUE THREAD

**Issue by aubergine10** [totaljs/framework#400]
Would it be worth adding some constants like this...?

```javascript
// msec   sec  min  hrs    1 day
// 1000 * 60 * 60 * 24 === 86400000ms

global.SECONDS = 1000;
global.MINUTES = global.SECONDS * 60;
global.HOURS = global.MINUTES * 60;
global.DAYS = global.HOURS * 24;
global.WEEKS = global.DAYS * 7;

// for months and years the existing Date.add() variants should be used.
```

Then tweak `Date.add()` to also accept a single integer param:

> **`Date.add( timestamp )`**
> Where **`timestamp`** is an integer value representing the number of milliseconds to add or subtract from the date.

```javascript
Date.prototype.add = function( type, value ) {

  if ( type.constructor === Number ) {

    // need to ensure `type` is an integer in case someone tries 1.3 * DAYS etc...
    // either this way:
    return new Date( this.getTime() + ( type - type%1 ) );
    // or the ES6 way:
    return new Date( this.getTime() + Math.trunc( type ) );
    // or even this way:
    return new Date( this.getTime() + parseInt( type ) );

    // Note:
    // Can't use x|0 or ~~x approaches as they break above 32 bit number
    // which would limit to just a week or two from current date.

  } else if ( value === undefined ) {

    var arr = type.split(' ');
    type = arr[1];
    value = exports.parseInt(arr[0]);

  }

  var dt = new Date( this.getTime() );

  switch ( type ) {
    // trimmed for brevity....
  }
  return dt;
};
```

And now you can do significantly faster date math like this:

```javascript
var today = new Date();

var tomorrow = today.add( 1 * DAYS );
var yesterday = today.add( -1 * DAYS );
var fortnight = today.add( 2 * WEEKS );
```

It's drastically faster than the existing string-based variants of `Date.add()` yet remains backwards compatible. A good example of where the numeric variant would be beneficial is the [auth module](https://github.com/totaljs/modules/blob/master/Security/auth/auth.js) which obviously needs to be as fast as possible.

Example of where it could be used in [auth.js](https://github.com/totaljs/modules/blob/master/Security/auth/auth.js#L158):

```javascript
// old version:
self.users[id].expire = utils.isDate(expire) ? expire : new Date().add('m', expire || self.options.expireSession).getTime();

// new version:
var TTL = ( expire || self.options.expireSession ) * MINUTES;
self.users[id].expire = utils.isDate(expire) ? expire : new Date().add( TTL ).getTime();
```

**Comment by aubergine10** [comment]
Also, a `now()` function would make code more semantic:

```javascript
// utils.js
Date.now = function() {
  // ^ directly on Date, not Date.prototype
  return new Date();
}

// somewhere else...

var tomorrow = Date.now().add(1*DAYS);
```

**Comment by petersirka** [comment]
Total.js supports:

```javascript
var today = new Date();

var tomorrow = today.add('1 day');
var yesterday = today.add('-1 day');
var fortnight = today.add('1 weeks');
```

Rewrite `Date.now()` method isn't good idea, because this method is used in many scripts. I think that current funcionallity is sufficient. Thanks!

**Comment by aubergine10** [comment]
OMG, JS already has a `Date.now()`?!! - when did that get added? \*hangs head in shame\* No problem, just change the way the constants are used...

```javascript
// if you want Date instance...
var tomorrow = new Date( Date.now() + 1*DAYS );

// or if you just want timestamp...
var tomorrow = Date.now() + 1*DAYS;
```

What do you think to the other idea - the numerical variant to Date.add() and the DAYS, WEEKS etc constants? The existing Date.add() parameter variants would still exist for backwards compatibility.

```javascript
// all have same result, just different performance...

// fast (JS compiler will inline the calculation rather than do it each time):
tomorrow = today.add(1*DAY);

// quick:
tomorrow = today.add('d', 1);

// slow (due to string splitting, array GC, etc):
tomorrow = today.add('1 day');
```

**Comment by petersirka** [comment]
I haved added `return new Date(this.getTime() + ( type - type%1 ));` to `Date.add()`.
Thanks :-)

**Comment by aubergine10** [comment]
Without the `Date()` wrapped around it, it will just return timestamp so code comment should be changed:

```javascript
/*
	@type {String|Number}
	@value {Number}
	return {Date|Number}
*/
```

?

**Comment by petersirka** [comment]
I think that this method has to return the Date object all the time `solution 1`.

```javascript
// Solution 1:
// It's easy to create a timestamp
new Date().add(30430).getTime();

// Solution 2:
// Or this is a complicated way how to get a date, but simple way for getting the timestamp
new Date(new Date().add(30430));
```

What do you mean about it?

**Comment by aubergine10** [comment]
I think the `.add()` method should always return a `Date` object.

You currently have this in the [utils.js #L2181](https://github.com/totaljs/framework/blob/v2.0.0/utils.js#L2181):

```javascript
	if (type.constructor === Number)
		return self.getTime() + (type - type%1); // <-- currently returns timestamp
```

It should be changed to:

```javascript
	if (type.constructor === Number)
		return new Date(self.getTime() + (type - type%1)); // <-- should return date object
```

The result will be:

```javascript
var today = new Date();

tomorrow = today.add(1*DAYS) // --> date object returned
```

It depends what's more commonly required - a timestamp or a date object. I'm still fresh to the framework so I don't know what most common use case is regarding `.add()`. I see things like cookies need a date object, whereas TTL on objects (like sessions in `auth` module) generally use timestamps.

**Comment by petersirka** [comment]
Yes, I know.
Cookies support `string` expiration e.g. `2 days` and I have to update all modules because they contain older implementation. So I'm going to change it today.
