### ISSUE TITLE
Enhancement? Subscribe.prototype.execute

### ISSUE THREAD

**Issue by aubergine10** [totaljs/framework#401]
https://github.com/totaljs/framework/blob/v2.0.0/index.js#L9532

Currently a big switch statement. Why not replace...

```javascript
switch (status) {
   // ...
}
```

With...

```javascript
framework.stats.response['error'+status]++;
```

Possible downside: if `'error'+status` isn't a key in `framework.stats.response` then it will throw an error. I'm not sure if there's code elsewhere that limits status to [valid values](https://httpstatuses.com/) that are already defined in `framework.stats.response`?

If there is possibility of unrecognised status then the switch statement could be retained but simplified:

```javascript
		switch (status) {
			case 400:
			case 401:
			case 403:
			case 404:
			case 408:
			case 431:
			case 500:
			case 501:
				framework.stats.response['error'+status]++;
		}
```
?

**Comment by petersirka** [comment]
Yes, you're right. Your first solution is really great! Thank you!
