### ISSUE TITLE
mail success on 3 times 

### ISSUE THREAD

**Issue by maxxam11** [totaljs/framework#403]
Hello, Peter.
When I use 

    var mail = require('total.js/mail');
    ...
    mail.on('success', function(message){
        console.log('sended');
    });

After sended email event "sucess" run 3 times. Result:

    sended
    sended
    sended

node.js      : v5.7.1
total.js     : v2.0.0-20

**Comment by petersirka** [comment]
Hi @maxxam11,
please try to download the latest beta, I removed some events and the mail library was complete rewrited. Try it according to the documentation below:

<http://docs.totaljs.com/latest/en.html#api~FrameworkMail>

**Comment by maxxam11** [comment]
Latest beta solved my problem. Thanks.

--
С уважением,
Максим Карачёв

2016-05-14 14:45 GMT+03:00 Peter Širka <notifications@github.com>:
