### ISSUE TITLE
Should it be possible to override framework.global from a controller?

### ISSUE THREAD

**Issue by aubergine10** [totaljs/framework#404]
This looks dodgy:

https://github.com/totaljs/framework/blob/v2.0.0/index.js#L10215

It would allow any script to completely overwrite framework.global just by setting this.global on a controller. Is that intended functionality?

**Comment by petersirka** [comment]
It looks dodgy, but it works correctly. Second question: yes, but property transfers only reference to the `F.global`. But better solution will be to remove this property from the controller.

**Comment by petersirka** [comment]
@aubergine10 removed 👍 
Thank you!
