### ISSUE TITLE
Minor improvements to Controller prototype

### ISSUE THREAD

**Issue by aubergine10** [totaljs/framework#406]
There are a few getters that don't use `this`, would it be worth converting them to lightweight arrow functions (no `arguments` object, no `__proto__`, etc)? I'm not sure if the V8 JIT compiler already handles such optimisation, but regardless it will make code clearer.

These are the specific getters I'm thinking of:

```javascript
Controller.prototype = {

	get path() {
		return framework.path;
	},

	get cache() {
		return framework.cache;
	},

	get config() {
		return framework.config;
	},

	get controllers() {
		return framework.controllers;
	},

	get isDebug() {
		return framework.config.debug;
	},

	get global() {
		return framework.global;
	},

};
```

Those would become:

```javascript
Controller.prototype = {

	get path = () => framework.path,

	get cache = () => framework.cache,

	get config = () => framework.config,

	get controllers = () => framework.controllers,

	get isDebug = () => framework.config.debug,

	get global = () => framework.global,

};
```

**Comment by petersirka** [comment]
I don't know about it. What do we do with the rest of them? e.g. `ip`, `xhr`, etc.. It's not applicated for all properties, so I suggest to skip this change.

**Comment by aubergine10** [comment]
agreed
