### ISSUE TITLE
Tidy the controller `.view<status>` & `.throw<status>` methods?

### ISSUE THREAD

**Issue by aubergine10** [totaljs/framework#407]
Starting here: https://github.com/totaljs/framework/blob/v2.0.0/index.js#L12430

There is a lot of duplicate code which seems unnecessary. Could it be cleaned up with a helper function like this...?

```javascript
var _doStatus = ( self, status, problem, isError ) => {

	// this seems specific to #400 status - why?
	if (problem && !problem.items)
		self.problem(problem);

	// all other #4xx & #501 use this:
	if (problem)
		self.problem(problem);

	// not sure what to do about #500 as its Error object so prolly don't
	// want that going in to self.problem?

	if (self.res.success || self.res.headersSent || !self.isConnected)
		return self;

	let sub = self.subscribe;

	self.req.path = EMPTYARRAY;
	if (isError)
		sub.exception = problem;
	sub.success();
	sub.route = framework.lookup(self.req, '#'+status);
	sub.exception = problem;
	sub.execute(status, true);
	return self;
}

// #400
Controller.prototype.throw400 = Controller.prototype.view400 = function(problem) {
	return _doStatus(this, 400, problem);
}

// #401
Controller.prototype.throw401 = Controller.prototype.view401 = function(problem) {
	return _doStatus(this, 401, problem);
}

// #403
Controller.prototype.throw403 = Controller.prototype.view403 = function(problem) {
	return _doStatus(this, 403, problem);
}

// #404
Controller.prototype.throw404 = Controller.prototype.view404 = function(problem) {
	return _doStatus(this, 404, problem);
}

// #500
Controller.prototype.throw500 = Controller.prototype.view500 = function(error) {
	if (error && error instanceof String)
		error = new Error(error);

	framework.error(error, this.name, this.req.uri);

	return _doStatus(this, 500, error, true);
}

// #501
Controller.prototype.throw501 = Controller.prototype.view501 = function(problem) {
	return _doStatus(this, 501, problem);
}
```

I'm not sure why `#400` checks for `!problem.items` when none of the others do.

Also, I wasn't sure why `#500` adds an exception before `self.subscribe.success()` when none of the others do, including `#501`.

I'm still somewhat confused as to why there are separate methods for `throw<status>` and `view<status>` when they both do the same thing for a given status. Could either the `throw` or the `view` be made obsolete or is there some reason why both are provided?

**Comment by petersirka** [comment]
Hi @aubergine10,
sorry for dealy and yes, you're. I'll update it. Thanks!

**Comment by petersirka** [comment]
@aubergine10 really nice update. Thank you (__I__ and __total.js__) very much!

👍

**Comment by petersirka** [comment]
@aubergine10 if you have a company or your company works with total.js please send me a logo. I'd like to publish it on the website.

**Comment by aubergine10** [comment]
@petersirka I don't have company at moment, but am working on a large website that doesn't have logo design yet, will send one over later in year.

**Comment by petersirka** [comment]
OK I'll wait :-)
