### ISSUE TITLE
Issue with routing in packages

### ISSUE THREAD

**Issue by harry-stot** [totaljs/framework#412]
Using this example (http://docs.totaljs.com/v1.9.x/en.html#pages~Packages): 

  exports.install = function(options) {

    console.log('Hello from the package!');

    // Routing:
    F.route('/hello-world/', view_greeting);

    // A static file mapping:
    F.map('/myview.js', '@helloworld/myview.js');};

`function view_greeting() {
    // IMPORTANT: for the view will be used a layout out of this package.
    // or create your own this.layout('@helloworld/layout')
    this.view('@helloworld/myview');
} `

If you replace :     
F.route('/hello-world/', view_greeting);
with 
F.route('/hello-world.html', view_greeting);

You got a 404 on /hello-world.html (packages rebuild etc...)

total.js     : v2.0.0-37

**Comment by petersirka** [comment]
We disussed it on Skype :-)
