### ISSUE TITLE
2.0-39 - websocket parse problem

### ISSUE THREAD

**Issue by KiPSOFT** [totaljs/framework#413]
Hi;

Peter i'm testing beta version but have a little problem. my ws client send this message;

```
{"api_key":"9eTXbNQhRbSOByu6TAFGcmwAlBLO0Wbw","id":1354,"komut":"giris"}
```

message params not parsed to json on framework onMessage event.

**Comment by petersirka** [comment]
Hi @KiPSOFT,
did you have `json` flag in the route?

**Comment by KiPSOFT** [comment]
yes. 
```
    F.websocket('/comm', comm, {flags: ['json'], origin: ['*']});
```

**Comment by petersirka** [comment]
@KiPSOFT this declaration is obsolete. Try this: <http://docs.totaljs.com/latest/en.html#api~Framework~framework.websocket>

**Comment by KiPSOFT** [comment]
oh sorry. thanks. i'm trying to now.

peter my advice, you add version changes in docs.

**Comment by petersirka** [comment]
Yes, but I have to wait for a new version. I hope that next week I'll publish it.
