### ISSUE TITLE
Add custom config files for different enviroments

### ISSUE THREAD

**Issue by KrzysztofWilczek** [totaljs/framework#414]
Hi,
I have a case in which I need more than there predefined config files: config-debug, config-test and config-release. I have 3 different develop configurations and I need to be able to select one of 3 different debug config files - the same params different values. Can you add option to define custom config files per environment? So in general we will be able to say that we have as many different environments to run app with different configs as we like to. For example: config-debug-dev01, config-debug-dev02, etc.

**Comment by petersirka** [comment]
Hi @KrzysztofWilczek,
yes I understand. For this case total.js supports `configs` directory, read here <http://docs.totaljs.com/latest/en.html#pages~Directory%20structure>

**Comment by KrzysztofWilczek** [comment]
So I can have /configs/dev01-debug and /configs/dev02-debug but how I can decide when load dev01 and not dev02? Both of them will be loaded for debug case?

**Comment by petersirka** [comment]
Ohh I forgot on the enviroment, sorry.

Then you can use `F.useConfig()` method, creates some definition file and according to the enviroment set the config file. <http://docs.totaljs.com/latest/en.html#api~Framework~framework.useConfig>

**Comment by karolgorecki** [comment]
Hi,
there is an issue with the configs.

I've tried the `F.useConfig()` on version `1.8.0` and lower it works OK.
On higher versions (from `1.9.0`) it doesn't work as expected.

It looks like it's taking all config files from the folder in an alphabetic order.
So when I create a file `x`which will be the last it will override the previous configs.

**Comment by petersirka** [comment]
I have tested `F.useConfig()` on OSX + Windows and everything works correctly.
@karolgorecki can you test it with the latest beta version?

`configs` directory is read by `fs.readdirSync` and I think that this method sorts the files.

**Comment by karolgorecki** [comment]
I still have the problem with overriding the config by the files that are after the picked useConfig file.
Even with the beta version doesn't work.

You have also a small typo in beta version:
total.js/utils.js:1578 `contentTypes[ext.toLowerCase()] = type;` should be `CONTENTTYPES`

When I use `useConfig` shouldn't it only get the file/s passed to this function? Currently it's taking all files in the `configs` folder.

**Comment by petersirka** [comment]
@karolgorecki thanks, I have fixed it.
I have looked into the source-code and the framework reads config files like this:

```html
/configs/config-file1
/configs/config-file2
/configs/config-file3
/config
/config-debug
```

__Simple solution, create a definition:__
```javascript
// your-app/enviroments/
var path = F.path.root('enviroments');
U.ls(path, function(directories, files) {
    // files without extension are considered as directories
    // your conditions:
    directories.forEach(filename => F.useConfig('~' + directories[0]));
});
```

**Comment by karolgorecki** [comment]
Creating a definition & moving additional config to different folder should do the trick.
Thanks for your help!
