### ISSUE TITLE
totaljs --translate make empty file

### ISSUE THREAD

**Issue by dacrhu** [totaljs/framework#418]
Hi Peter,

```
[dacr@dacr teszt]$ totaljs --help
####################################################
# total.js - web application framework for node.js #
# version: v1.9.8                                  #
####################################################
without arguments          = creates empty-project
-translate                 = creates a resource file with the localized text from views
-translate "TEXT"          = creates an identificator for the resource
-translate filename        = parsers and creates a resource file from the text file
-translatecsv              = parsers and creates CSV with localization into the current directory
-diff source target        = creates differences between two resources "-diff filename_source filename_target"
-merge source target       = merges first resource into the second "-merge filename_source filename_target"
-clean source              = cleans a resource file "-clean filename_source"
-minify filename           = minifies .js, .css or .html file into filename.min.[extension]
-v or -version             = total.js version
/path/                     = target (default current directory)


[dacr@dacr teszt]$ totaljs
####################################################
# total.js - web application framework for node.js #
# version: v1.9.8                                  #
####################################################
Downloading "empty-project" from www.totaljs.com
Unpacking file.
Done.


[dacr@dacr teszt]$ totaljs -translate

####################################################
# total.js - web application framework for node.js #
# version: v1.9.8                                  #
####################################################

total.js: creating translation
total.js: the translation was created (0 texts)


[dacr@dacr teszt]$ cat translate.resource 
// Total.js translation file
// Created: 2016-07-03 21:25
[dacr@dacr teszt]$ 
```

I tested with a big project and result is same.

Thank you,
David

**Comment by petersirka** [comment]
Hi @dacrhu

I don't see `totaljs --translate` command:
```bash
cd yourapp
totaljs --translate
```

I'm waiting for a feedback.
PS:  try to use total.js 2.0? `npm install -g total.js@beta`

**Comment by dacrhu** [comment]
Sorry, copy paste error :) I edited the topic.

**Comment by dacrhu** [comment]
With 2.0 is same.

`[dacr@dacr teszt]$ totaljs -translate

####################################################
# total.js - web application framework for node.js #
# version: v2.0.0-59                               #
####################################################

total.js: creating translation
total.js: the translation was created (0 texts)
[dacr@dacr teszt]$ cat translate.resource 
// Total.js translation file
// Created: 2016-07-03 21:31
`

**Comment by petersirka** [comment]
Hmm.... Do your views contain the localization markup `<h1>@(TEXT)</h1>`?

**Comment by dacrhu** [comment]
Ok, PEBKAC.....
I close this ticket.

**Comment by petersirka** [comment]
Sorry for additional job (I think that you will update your project), but this markup is very important for localization mechanism.

All the best!

**Comment by gevMgevorgyan** [comment]
Hi guys can you help me to change translation language

**Comment by petersirka** [comment]
@gevMgevorgyan and where is the problem?

**Comment by gevMgevorgyan** [comment]
when i write --translate i want to translate in Armenian or other language how can i do this

**Comment by petersirka** [comment]
`total --translate` creates a resource file with text for localize. So then you need to translate the resource file and store it in `/resources/arm.resource`. Then you need to set `F.onLocale` delegate. More info in documentation.

- [Documentation](https://docs.totaljs.com/latest/en.html#pages~Localization)
- [Example](https://github.com/totaljs/examples/tree/master/localization-resources)
