### ISSUE TITLE
etag-version release

### ISSUE THREAD

**Issue by adrianrey05** [totaljs/framework#424]
Hello @petersirka.

settings may _etag-version_ is not working in release settings?
or I will be missing something more configuration?

Only change the number in the config file for the label _etag-version_ but the client does not modify the static files.

I await your help.
Thank you very much!

Adrian

**Comment by petersirka** [comment]
Hi @adrianrey05,
it works correcly. The option `etag-version` updates `etag` about `etag-version` value. I have tested it now: 

![Etag version](https://cloud.githubusercontent.com/assets/2414252/17447857/4c6e43d6-5b51-11e6-836f-f0d0d88ccf29.png)

This behaviour works in release mode. If you want to release cache then decrease this property <https://docs.totaljs.com/latest/en.html#api~FrameworkConfiguration~default-response-maxage> or use `versions` <https://docs.totaljs.com/latest/en.html#pages~File%3A%20versions> (I use version for my projects).

Thank you!

**Comment by adrianrey05** [comment]
@petersirka.
this is the header for static file

![image](https://cloud.githubusercontent.com/assets/5314570/17449054/42a39798-5b2e-11e6-985e-e9a31b37788f.png)

-. now, change the etag-version to **9** and save file _config_
-. restart the service.
-. and refresh client page only with key F5.

header static file is equals

![image](https://cloud.githubusercontent.com/assets/5314570/17449087/92af56d2-5b2e-11e6-9aaf-a57612b340a8.png)

time after...
but ... now I see that with the button "refresh" in chrome updates the files. :stuck_out_tongue_closed_eyes:

**Comment by petersirka** [comment]
:-D

**Comment by fgnm** [comment]
I have the same problem, changing etag_version does not works with chrome (both with F5 and refresh button). It's very annoying, how can I fix it? Maybe changing Cache-Control?
Thank you

**Comment by petersirka** [comment]
I recommend to use `versions` instead of changing of `ETag` because caching depends on browsers.

- versions <https://docs.totaljs.com/latest/en.html#pages~File%3A%20versions>
- or you can create own File route without caching

**Comment by fgnm** [comment]
Uhm so if I want to use `versions` I've to include each static file there, that is not much convenient if I have many static file..
If I want to make a custom File route how should I proceed?

**Comment by petersirka** [comment]
You can use versions or you can add a `timestamp` to each URL .... but this solution can decrease a HTTP performance.

You need to know that browser doesn't respect Etag value.  Browser caches files according to the URL. So the best way is to change a name of URL when you change a file. For e.g. from `logo.png` to `logo2.png`.

**Comment by fgnm** [comment]
I'm a bit confused on how to use versions, let's say I want to force refresh of my css file:
```
/css/default.css     : auto
```
When I include through total view engine `@{'default.css'}` it routes to for example `/css/default-7499392.css` and that's fine, however `default-7499392.css` does not exist and so return 404, what I'm wrong?
