### ISSUE TITLE
Roles not works

### ISSUE THREAD

**Issue by deadman2000** [totaljs/framework#428]
Roles not works for my project. I detect place where flags check failed:
![screen](https://cloud.githubusercontent.com/assets/12889180/18223583/2a1c3a52-71c4-11e6-8f0f-75deeb03c868.png)

**Comment by petersirka** [comment]
Ho do you use roles? I found a problem in roles before few weeks ago.

---

Can you create a small example for me? Inpsire by these example [authorization-roles](https://github.com/totaljs/examples/tree/master/authorization-roles) or [routing-flags-roles](https://github.com/totaljs/examples/tree/master/routing-flags-roles). Send me it on my email.

**Comment by deadman2000** [comment]
Sadly gmail not allow archive attachments. Here my small example: [RoleTest.zip](https://github.com/totaljs/framework/files/453509/RoleTest.zip)

I add flag in function F.onAuthorize:
```
        if (user.admin)
            flags.push('@admin');
```
And register route whith role admin:
```
F.route('/usersfiles', users_files, ['@admin']);
```

**Comment by deadman2000** [comment]
I still use 2.0.1. Maybe it's fixed in 2.0.2?

**Comment by petersirka** [comment]
Thank you, I'm going to test it.

**Comment by petersirka** [comment]
Try to update route like this:

```javascript
F.route('/usersfiles', users_files, ['@admin', 'authorize']);
```

`authorize` flag is very important for it. Give me a feedback. Thank you.

**Comment by deadman2000** [comment]
It's work fine with 'authorize'. Maybe add note to doc? Or make authorize not required with role flags?

**Comment by petersirka** [comment]
Yes, I'll add it into the documentation.
Thank you!
