### ISSUE TITLE
Bug in Image.indentity

### ISSUE THREAD

**Issue by maxxam11** [totaljs/framework#429]
Hello.

In function Image.indentity use `self.fileName`, but must be `self.filename`

```

Image.prototype.identify = function(cb) {
	var self = this;

	exec((self.isIM ? 'identify' : 'gm identify') + ' "' + self.fileName + '"', function(error, stdout, stderr) {

   ...
}
```

**Comment by petersirka** [comment]
Hi @maxxam11,
yes, you right --> I fixed it some time ago <https://github.com/totaljs/framework/tree/v2.0.2>. You can use latest stable beta `npm install total.js@beta`.

Thank you!
