### ISSUE TITLE
Cache.get defaul return undefined

### ISSUE THREAD

**Issue by maxxam11** [totaljs/framework#430]
Hello. 
`framework.cache.get(name, [def])` - Default value must be `null`, but now default value `undefined`

**Comment by petersirka** [comment]
Hi @maxxam11,
yes, I have updated it because of performance. It's a problem for you?

**Comment by maxxam11** [comment]
if `cache = ''`, then `!cache` don't work and i used `cache !== nul`'.
I allready fix it in my project.

**Comment by petersirka** [comment]
You can use this:

```javascript
if (cache != null)
    console.log('is not null and not undefined');
```

Thank you 👍
