### ISSUE TITLE
Cache problem

### ISSUE THREAD

**Issue by maxxam11** [totaljs/framework#434]
Hello.
```
 var a = { data:1 };
 var b = a;
    
F.cache.set('key', b);
F.cache.get('key');  //return { data: 1 }  
    
a.data = 2;
F.cache.get('key'); //return { data: 2 }  
```
this probleb is solved so ` F.cache.set('key', U.clone(b));`

but may be this need to make in cache?

**Comment by petersirka** [comment]
Hi @maxxam11,
yes, cache is a simple object which stores values and references directly. You can handle the problem with `clone` as  you wrote, but implemenation of it as a default behaviour is not a good way - because of __performance__.

Thank you.
