### ISSUE TITLE
HTML5 Offline application

### ISSUE THREAD

**Issue by ameykshirsagar** [totaljs/framework#437]
Hi,
I am trying to develop a HTML5 offline application and I didn't find any pointers in the documentation.
What could you suggest to make modifications in the code in order to support this concept??
Also if I have to serve the MIME type `text/cache-manifest` is the framework capable of doing it or do I have to depend on the third party module like [this](https://www.npmjs.com/package/appcache-node)
I just want to load views without making a trip to server to render it.

Thanks a lot in advance

**Comment by petersirka** [comment]
Hi @ameykshirsagar,
Total.js supports `text/cache-manifest`, here is a simple example <https://github.com/totaljs/examples/tree/master/html-appcache-offline>. Give me a feedback.

Thank you.

**Comment by ameykshirsagar** [comment]
Thank you @petersirka for the answer. Closing this thread.
