### ISSUE TITLE
Use config variables in workers

### ISSUE THREAD

**Issue by mnicolas80** [totaljs/framework#439]
Checking this example: [worker example ](https://github.com/totaljs/examples/blob/master/workers/workers/weather.js), tried to use existing custom config variable `CONFIG('weather-api')` but it wasn't defined.

Is there any way to use configuration variables in workers scope?

**Comment by petersirka** [comment]
Hi @mnicolas80,
if you want to use configuration then you have to load a framework in a worker:

```javascript
F.load('debug', ['config'], '../');

console.log(CONFIG('weather-api')); // it works! :-)
```

**Comment by petersirka** [comment]
Any news?

**Comment by mnicolas80** [comment]
nope...
The first lines of the worker contain the following code:
```javascript
require('total.js');
F.load('debug', ['config'], '../');
```
then I get "undefined" executing the following:
`
console.log(CONFIG('weather-api'));
`
so, I am not sure....

Thank you @petersirka

**Comment by petersirka** [comment]
Which version of Total.js do use? ... and which OS?

**Comment by petersirka** [comment]
Can you send me example?

**Comment by mnicolas80** [comment]
OS version: CentOS 7
Total.js version: 2.1.0

```javascript
require('total.js');
F.load('debug', ['config'], '../');

var Twitter = require('twitter');
var twitterClient = new Twitter({
  consumer_key: CONFIG('twitter.consumer_key'),
  consumer_secret: CONFIG('twitter.consumer_secret'),
  access_token_key: CONFIG('twitter.access_token_key'),
  access_token_secret: CONFIG('twitter.access_token_secret')
});

var params = {screen_name: 'mnicolas80', count: 3};
twitterClient.get('statuses/user_timeline', params, function(error, tweets, response) {
  if (!error) {
    process.send(tweets);
  } else {
    console.log(error);
  }
  process.exit();
});
```

**Comment by petersirka** [comment]
HI @mnicolas80, please try to use my example:
<https://www.dropbox.com/s/xp6ud6ffovgmxwa/workers.zip>

Thank you.
BTW: `process.send()` has a limit for data length.

**Comment by mnicolas80** [comment]
Hi @petersirka, I found the issue... the local Total.js version was 1.9.8.
I am sorry for loosing your time due to my mistake....

I tested both codes and work successfully! Could you please update the [workers example](https://github.com/totaljs/examples/blob/master/workers/workers/weather.js) and add some config variables?

Thank you

**Comment by petersirka** [comment]
@mnicolas80 I have updated example. Thank you!
