### ISSUE TITLE
Question: WebSocket

### ISSUE THREAD

**Issue by adrianrey05** [totaljs/framework#440]
Hi!
Is it possible to see all the rooms that are open websocket?

```js
F.websocket("/{room}/", socket, 	["JSON"]);
```

**Comment by petersirka** [comment]
Hi @adrianrey05,

```javascript
Object.keys(F.connections).forEach(function(id) {
    var controller = F.connections[id];
    controller.send({ yes: true });
});
```

__or you have to know a path:__
- <https://docs.totaljs.com/latest/en.html#api~Framework~framework.findConnections>
- <https://docs.totaljs.com/latest/en.html#api~Framework~framework.findConnection>

Thank you

**Comment by adrianrey05** [comment]
Hi @petersirka.
It's just what I needed, Thanks :+1:
