### ISSUE TITLE
Missing Tutorial

### ISSUE THREAD

**Issue by jack0088** [totaljs/framework#445]
The framework seems to be very solid as from what I've seen, but I couldn't find any proper tutorial on the web.
Is there any step-by-step text guide on how to create a complete 'To-Do-App' or a simple 'Blog' (with database, schemas, authentication, password encryption, cookies or session,..)? I can't figure it out by the sparse docs and examples.

**Comment by hepr** [comment]
Hi

You can find all documentation on http://docs.totaljs.com with more than 100 examples.

Herve

**Comment by petersirka** [comment]
Hi @jack0088,
- Here is a simple tutorial <https://docs.totaljs.com/latest/en.html#pages~Tutorial>
- 100+ examples <https://github.com/totaljs/examples>
- Source-code: Total.js BlogEngine <https://github.com/totaljs/blogengine>
- Source-code: Total.js Eshop <https://github.com/totaljs/eshop>
- Source-code: Total.js CMS <https://github.com/totaljs/cms>
- Source-code: Total.js HelpDesk <https://github.com/totaljs/helpdesk>

---

PS: We want to create a better tutorial for learning.
Thank you!

**Comment by petersirka** [comment]
@hepr thank you!
