### ISSUE TITLE
Cannot find module total.js

### ISSUE THREAD

**Issue by randycasburn** [totaljs/framework#446]
**Actions Taken:**
1. - Installed per instructions (https://github.com/totaljs/framework)
2. - Downloaded empty-project.zip (https://github.com/totaljs/framework/releases/download/v2.2.0/empty-project.zip)
3. - ran node index.js
4. - module.js threw with error total.js not found
5. - Then I tried the server-sent-events example with same result

**Results:**
```
~/server-sent-events: node -v
v5.4.1
~/server-sent-events: npm -v
3.6.0
~/server-sent-events: npm list -g | grep total
├── total.js@2.2.0
~/server-sent-events: totaljs -help

|==================================================|
| Total.js - Web framework for Node.js             |
| Version: v2.2.0                                  |
|==================================================|


~/server-sent-events: node .
module.js:327
    throw err;
    ^

Error: Cannot find module 'total.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/randy/server-sent-events/index.js:7:1)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
~/server-sent-events: 

```
**Suggestions?**

**Comment by petersirka** [comment]
Install Total.js locally, there is a Node.js problem with finding framework files.

https://nodejs.org/dist/latest-v6.x/docs/api/modules.html#modules_loading_from_node_modules_folders

```bash
$ cd server-sent-events
$ npm install total.js
$ node index.js
```

Thank you!

**Comment by randycasburn** [comment]
Makes Sense. 

May I please recommend you change the documentation? The instructions to install it globally appear in at least five places throughout the website and documentation. From here: https://docs.totaljs.com/latest/en.html#pages~Getting%20started "Other Ways To Install: 2."

> If you install framework as global module you do not need to install framework to each web application. 

The docs should be updated to reflect both a global install is necessary for the command line tools and a local install is required for the project to require the library. 

Here are instructions from the NPM docs that make the point clearly:
https://docs.npmjs.com/files/folders

> - Install it locally if you're going to require() it.
> - Install it globally if you're going to run it on the command line.

Please don't take any of this as criticism, but this does make someone unfamiliar with this work wonder what else in the documentation is misleading or incorrect.

Thanks for taking the time to respond, but more importantly, for providing what looks to be a well thought out framework that I'm excited to get my hands dirty with!

**Comment by petersirka** [comment]
Thank you, you're right. I'll add it into the docs.
