### ISSUE TITLE
js minify bug

### ISSUE THREAD

**Issue by hepr** [totaljs/framework#447]
In a js file I've got a regular expression

I've got this function
``
return jQuery.each(c,function(a,b){/raster.*/.test(b)&&d.push(b)}),d.push("retina"),d.join(" ")});
``

When minify js I obtained this :-(

``
return jQuery.each(c,function(a,b){/raster..test(b)&&d.push(b)}),d.push("retina"),d.join(" ")});
``

It thinks */ in my regular expression as a comment so it remove it.

**Comment by petersirka** [comment]
Hi @hepr, thank you ... I'll look into it today.

**Comment by petersirka** [comment]
@hepr I have fixed it. Please try latest beta version `npm install total.js@beta`.
I test it on my server.

Thank you!
