### ISSUE TITLE
On the fly install controllers

### ISSUE THREAD

**Issue by ameykshirsagar** [totaljs/framework#449]
Hi,
I am trying to make a microservices manager using [seneca](http://senecajs.org/) but my question is that, is it possible to install controllers and schema on the fly without restarting the server??

Thanks

**Comment by petersirka** [comment]
HI @ameykshirsagar, of course:

- controller <https://github.com/totaljs/examples/blob/master/framework-install-controller/index.js>
- model (with e.g. Schema) <https://github.com/totaljs/examples/blob/master/framework-install-model/index.js>

Thank you.
