### ISSUE TITLE
AppDesigner: code generated

### ISSUE THREAD

**Issue by adrianrey05** [totaljs/framework#451]
Hi,
When I create a new scheme by AppDesigner, I create the following code:
```js
NEWSCHEMA('scheme',function(schema){...});
```
To work inside the application I have to change to the following code:
```js
NEWSCHEMA('scheme').make(function(schema){...});
```
Is it possible to generate it with the 'make' function?

Thank you.

**Comment by petersirka** [comment]
Hi @adrianrey05,
my mistake. I have fixed it. Thank you!
