### ISSUE TITLE
use of variable i in foreach loop over objects

### ISSUE THREAD

**Issue by Athuli7** [totaljs/framework#452]
@{foreach i in repository.data.company.practice}
     @{repository.data.company.practice[i.key]}
@{end}

would fail. i keeps giving 1. I'm not sure if i is short for the index var.
Please look into it. It was intended, please mention it in the docs.

**Comment by petersirka** [comment]
Hi @Athuli7,
there was a bug. I have fixed it.

__Solution:__
You have to replace `@{foreach i ...` for e.g. `@{foreach m ...`. The problem is in `i` variable (newest version will contain my fix).
