### ISSUE TITLE
Bug with localization

### ISSUE THREAD

**Issue by hepr** [totaljs/framework#454]
Hi Peter,

I'm in 2.2.0 version.
I will using localization and it doesn't work.

I've 2 resource files
en.resource
fr.resource

I do this test in the same function :
console.log(RESOURCE('fr', 'Dashboard')); -> Tableau de bord (GOOD)
console.log(F.translate('fr', 'Dashboard')); -> Dashboard (BAD)
console.log(F.translator('fr', '@(Dashboard)')); ->Dashboard (BAD)

Thanks for your help

Have a nice day

**Comment by petersirka** [comment]
Hi @hepr,
it works correctly. You have to convert text via terminal/command-line `$ totaljs --translate` command in your app directory.

```html
// TRANSLATE('fr', 'Dashboard')     --> returns Dashboard
// TRANSLATOR('fr', '@(Dashboard)') --> returns Dashboard
T956107380        : Dashboard

// RESOURCE('Dashboard') --> returns Dashboard
Dashboard         : Dashboard
```

`TRANSLATE()` - converts text to hash
`TRANSLATOR()` - converts `@()` text to hash

---

Why hashing? Saves CPU and memory consumption.
Thank you!

**Comment by hepr** [comment]
Thank you for your response :-)
