### ISSUE TITLE
Image not saving

### ISSUE THREAD

**Issue by Humsas** [totaljs/framework#457]
Hello,

I'm using windows 7 64 bit, GraphicsMagick 1.3.25, Total.js v2.2.0 and when trying to save uploaded image, I receive error:

> Error: Command failed: gm -convert 'D:\***\tmp\7ikxkf8wyvitrcglhegi418aor-43337.upload' +profile '*' 'D:\***\public\picture\ghgn27156dzby1a.jpg'
gm convert: Unable to open file ('D:\***\tmp\7ikxkf8wyvitrcglhegi418aor-43337.upload') [No such file or directory].

I have not send answer from the server and file is in tmp folder(file copy works just fine).

What I have tried to do:

            let file = self.files[0],
                filename = F.path.public('picture/' + picName + '.jpg'),
                image = file.image();

            image.minify()
            .save(filename, (error, isSaved) => 
            {
                if(!isSaved)
                {
                    F.logE("Image not saved! " + error);
                }
            });
Then:
`image.pipe(fs.createWriteStream(filename));`

And:

            image.make(function(image2)
            {
                F.logE("asdsf");
                image2.output('jpg');
                image2.quality(90);
                image2.save(filename, (error, isSaved) => 
                {
                    F.logE("asdsf2");
                    if(!isSaved)
                    {
                        F.logE("Image not saved! " + error);
                    }
                    else
                    {
                        F.logE("Image saved! ");
                    }
                });
            });

After giving up, tried to run error command with console and found out, that it only works with " quotes:
`gm -convert "D:\***\1.jpg" +profile '*' "D:\***\public\picture\ghgn27156dzby1a.jpg"`

Any idea, how to fix this?

P.S. 
In my version this function doesn't exist, but is left in documentation https://docs.totaljs.com/latest/en.html#api~FrameworkUtils~Utils.isNullOrEmpty

**Comment by petersirka** [comment]
Hi @Humsas,
try to use latest beta version `npm install total.js@beta` and give me a feedback.

`U.isNullOrEmpty` has been removed because it's useless you can use `if (str) { console.log('is not null and not empty'); }`. I'll remove it from docs, thank you! I forgot on it.

**Comment by Humsas** [comment]
Thanks for fast response :)

First and third one are working fine now, but 
`image.pipe(fs.createWriteStream(filename));`
is still throwing errors:

> { Error: Uncaught, unspecified "error" event. (gm convert: Unable to open file ("D:/***/tmp/vipbrzvqvelo3waaqgppeqaor-782557.upload") [No such file or directory].
)
    at WriteStream.emit (events.js:163:17)
    at WriteStream.onerror (_stream_readable.js:579:12)
    at emitOne (events.js:96:13)
    at WriteStream.emit (events.js:188:7)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:548:20)

**Comment by petersirka** [comment]
I know where is the problem, show me your action in a controller. Thank you.

**Comment by Humsas** [comment]
Simplified version would be:
```
    let file = self.files[0],
                filename = F.path.public('picture/' + picName + '.jpg'),
                image = file.image();

            image.pipe(fs.createWriteStream(filename));
```

**Comment by petersirka** [comment]
__Otherwise:__

1. if you respond via `controller.view()` or `controller.json()` then the controller removes all uploaded files
2. you have to call `controller.noClear()` and when an image is processed you have to call `controller.clear()` or `req.clear()`, example:

```javascript
...
self.noClear();
var stream = fs.createWriteStream(filename);
image.pipe(stream);
CLEANUP(stream, function() {
    self.clear();
});
...
```
OR
```javascript
...
var stream = fs.createWriteStream(filename);
image.pipe(stream);
CLEANUP(stream, function() {
    self.json({ success: true });
    // or
    // self.view('success');
});
...
```

If you upload multiple files then you can use `.wait()` prototype in `Array`

```javascript
...
self.files.wait(function(file, next) {
    if (file.isImage()) 
        file.quality(90).output('jpg').save('yourfilename', next);
    else
        next();
}, () => self.json({ success: true }));
...
```

**Comment by Humsas** [comment]
As I wrote in the first post, I do not respond at all(found that problem in other issues) for testing, and still receive this error. Received Tmp file is not deleted and `file.pipe(fs.createWriteStream(filename));` proves that.

**Comment by petersirka** [comment]
Then you have to create the whole example for me.
I'll test it ASAP.

**Comment by Humsas** [comment]
https://github.com/totaljs/framework/issues/121#issuecomment-35800566
Maybe something from this will work with my previous controller:
```
function SaveImage()
{
    let file = self.files[0],
                filename = F.path.public('picture/' + picName + '.jpg'),
                image = file.image();

            image.pipe(fs.createWriteStream(filename));
}
```
Actually we could close the issue, because update to beta solved image.save problem, and I do not need image.pipe, it was only to test if something works at all.
