### ISSUE TITLE
Problem with events in controller

### ISSUE THREAD

**Issue by mmautomatizacion** [totaljs/framework#459]
Hi,
I'm using "Socket.io". For better organization, I have created a "socket.on('connection')" event in each controller, including only the events necesary for the controller. For the first time I access the site, It works correctly. But when I refresh the page, I receive two connection events for the same client.

The server detects correctly the disconnection of client. How can I disable the 'connection' event when socket close or when change controller/route?

Thanks

**Comment by petersirka** [comment]
Hi @mmautomatizacion,
if you want to use `socket.io` then:

__Instructions:__
1. disable Total.js WebSocket in Total.js config: `allow-websocket   : false`
2. then bind `socket.io` in some definition file: `var io = require('socket.io')(F.server);`

---

Ad your problem, try to remove events before you attach new events.

```javascript
socket.removeAllListeners('connection', ...);
socket.on('connection', ...);
```

Thank you.

**Comment by mmautomatizacion** [comment]
Removing all listeners works correctly. Maybe not the best solution, and now is more difficult define global events by websocket. But for me and for my current project is enough.

Thanks!

**Comment by petersirka** [comment]
Great! Thank you.
