### ISSUE TITLE
Compiled JS problem when missing ; before statement

### ISSUE THREAD

**Issue by martinjirku** [totaljs/framework#460]
Hi all, I was using third party JS-code for the UI animations. After javascript was compiled by Totaljs, I experienced an exception in web-browser's console.

## Reproduce:
  1. Download and unzip or create an empty project
  2. Open `./public/js/default.js` and replace default code, e.g. with this one:
   ```javascript
var foo = function() {};
foo() //missing semicolon - valid, because of automatic semicolon insertion (ASI)
if (true) {
  console.log('¯\\_(ツ)_/¯ - I am working!'); //after minification, this little guy won't work anymore.
}
```
  3. Start application, open browser and browser's developer tools.
  4. Notice, that in console, there is an exception (`Uncaught SyntaxError: Unexpected token if`)

## Problem:
Code is compiled/minified into:
```javascript
var foo=function(){};foo()if(true){console.log('I am working! :)')}
```
JS Engine expects *;* before statement, otherwise it fails, ASI is not applicable, because function `foo()` is not terminated by new line anymore.

**Comment by petersirka** [comment]
Hi @martinjirku,
yes. JS minificator doesn't analyse the code, only compresses it. It will be too complicated. You can change it:

<https://github.com/totaljs/examples/tree/master/external-compile-uglifyjs>

:-( sorry.

**Comment by martinjirku** [comment]
Great.. Thanks for the clarification!
Now I found this #309 and #105, so I will close this issue as well.
