### ISSUE TITLE
Capitalize bug?

### ISSUE THREAD

**Issue by maxxam11** [totaljs/framework#464]
Hi, Peter. 

`'first second'.capitalize()`

return **First Second**
It seems to be so **First second**.

**Comment by petersirka** [comment]
HI @maxxam11,
it's correct. The capitalize method is primary targeted on names.

But I can add an argument e.g. `onlyFirst`, example `'first second'.capitalize(true)`.

**Comment by maxxam11** [comment]
Yes, argument "onlyFirst" would very much help! Thanks!

--
С уважением, Максим Карачев

11 янв. 2017 г. 16:48 пользователь "Peter Širka" <notifications@github.com>
написал:

**Comment by petersirka** [comment]
__Please download source-code from GitHub (and replace all files in `node_modules/total.js`):__
<https://github.com/totaljs/framework/tree/v2.4.0>

Thank you!
