### ISSUE TITLE
docs.totaljs.com pages are missing after Framework

### ISSUE THREAD

**Issue by yexing** [totaljs/framework#465]
docs.totaljs.com pages are missing after Framework

**Comment by molda** [comment]
Hi @yexing could you be more specific about what's missing?
I just checked the docs and it all works as it should and no pages missing.

**Comment by yexing** [comment]
Sorry, it's my browser's cache, the old file lead to a js error. After I clean the cache, it works.

**Comment by molda** [comment]
Good to hear that :)
