### ISSUE TITLE
Website Sources

### ISSUE THREAD

**Issue by lazaridis-com** [totaljs/framework#467]
Where can I find the source-code of the website?

https://www.totaljs.com

**Comment by molda** [comment]
Hi @lazaridis-com the website is running on the CMS you can find here https://github.com/totaljs/cms

**Comment by lazaridis-com** [comment]
@molda , sorry, I meant the whole thing, the content. How can one make some change-suggestion, or contribute to the website content?

**Comment by lazaridis-com** [comment]
and where can one file issues subjecting the website-content (not the documentation, the website itself)

**Comment by petersirka** [comment]
@lazaridis-com you can contact us on info@totaljs.com or via Total.js Gitter (private chat) or __here__ if you have some suggestions.

Thank you!
