### ISSUE TITLE
Question : List of workers

### ISSUE THREAD

**Issue by ameykshirsagar** [totaljs/framework#468]
Hi,
Is it possible to list all the workers started by the framework ??
If no, any possible workaround??
Thanks a ton in advance.

**Comment by ameykshirsagar** [comment]
When using `F.worker` or `F.worker2`

**Comment by petersirka** [comment]
Hi @ameykshirsagar,
yes:

```javascript
Object.keys(F.workers).forEach(function(key) {
    var worker = F.workers[key];
    // e.g.
    worker.kill();
});

Thank you.

**Comment by ameykshirsagar** [comment]
Thank you so much. Closing the issue
