### ISSUE TITLE
How can reset Etag of static file?

### ISSUE THREAD

**Issue by stakost** [totaljs/framework#469]
Hi, Peter!

How can I reset Etag of static files, when they will be update?
When I rewrite some css/js files, total.js didn't update Etag. Just only if I update config etag-version

I don't see any methods to do it :(
Maybe you can add some method to look last-modified of file and activate it via config?

Like:
var stats = fs.statSync("/dir/file.txt");
var mtime = new Date(util.inspect(stats.mtime));

**Comment by petersirka** [comment]
Hi @stakost,
`etag-version` changes etag but I think that you have a problem with browser cache, right? I recommend to use `versions` feature for changing filenames - <https://docs.totaljs.com/latest/en.html#pages~File%3A%20versions>.

Last-modified header works same than `etag`. There is a problem in browser cache.
Give me a feedback.

**Comment by stakost** [comment]
Yes, problem with browser cache. 

https://docs.totaljs.com/latest/en.html#pages~File%3A%20versions.
It's not solution, because when browser loading, he looks Etag from server by filename and etag-version from config.

Solution for me is:
F.on('load', x => {
    F.config['etag-version'] = new Date().getTime();
});

But every time, when I'll restart server - browser will load static files again.

**Comment by petersirka** [comment]
Yes, because `etag-version` is always other. I recommend change `etag-version` in your config files. I'll try to add a real `last-modified` date to files into a new Total.js version (I'll give you a feedback when I publish new beta).

Thank you!

**Comment by stakost** [comment]
Thanks a lot!
