### ISSUE TITLE
Utils.parseInt doesn't return default value

### ISSUE THREAD

**Issue by Humsas** [totaljs/framework#471]
Hello,

I have problem that Utils.parseInt sometimes returns 0 and not my passed default value:

Utils.parseInt('', -1) returns 0,
Utils.parseInt('NaN', -1) returns 0.

**Comment by petersirka** [comment]
Hi @Humsas,
yes you're right. I have fixed it. I hope that new version will be next week.

<https://github.com/totaljs/framework/tree/v2.4.0>

**Comment by Humsas** [comment]
Thanks!
