### ISSUE TITLE
F.file('*.scss'   ---- wild card not set so request not detected

### ISSUE THREAD

**Issue by neonnds** [totaljs/framework#472]
I was trying out : 

examples/external-compile-sass/definitions/sass.js

But the *.scss was not detecting the scss included in my html.

Looking through index.js of the framework and reaching the "Framework.prototype.file" function it seems that *.scss does cause the wild card flag to be set. So I changed:

```
if (index !== -1) {
			extensions = {};
			extensions[a.substring(index + 2).trim()] = true;
			wildcard = false;
```

Too the following:

```
if (index !== -1) {
			extensions = {};
			extensions[a.substring(index + 2).trim()] = true;
			wildcard = true;
```

All works well now.

Please advise if this is a bug or if the example is missing something.

Love your work. Keep it up.

**Comment by petersirka** [comment]
Hi @neonnds,
I have fixed that example. Please download it again.

<https://github.com/totaljs/examples/blob/master/external-compile-sass/definitions/sass.js#L10>

Thank you!
