### ISSUE TITLE
What is the expected behaviour for POSTing back a JS array?

### ISSUE THREAD

**Issue by neonnds** [totaljs/framework#473]
I have some JQuery that POSTs back an array of values to my controller.

```
$.post("/my-post", {
	'tags'  :  ["first", "second"]
});
```

My controll has a route of /my-post and a single flag set to "post":

```
var controller = function() {
	var tags = self.body["tags[]"];
	console.log(tags);
	self.json({});
}
```

If the array length in my jquery post is greater than 1 than i get console output as a JS array, as expected:

```
[ 'first', 'second' ] 
```

However, if i set tags just to ["first"] in the jquery i get console output not as a JS array but rather just a JS string:

```
first
```

Why do i get an array on the server side with more than 1 argument. And a string on server side with just 1 argument?

Is this a bug or expected behaviour?

Thanks.

**Comment by petersirka** [comment]
Please format code on GitHub...
Always send data as JSON, that's my recommendation.

__Total.js uses a standard deserializer:__
<https://nodejs.org/dist/latest-v6.x/docs/api/querystring.html#querystring_querystring_parse_str_sep_eq_options>

__You can rewrite it:__
<https://docs.totaljs.com/latest/en.html#api~Framework~framework.onParseQuery>
