### ISSUE TITLE
nosql.js assumes string as search input

### ISSUE THREAD

**Issue by li0nsar3c00l** [totaljs/framework#474]
if a search option passed to 
`DatabaseBuilder.prototype.like = DatabaseBuilder.prototype.search = function(name, value, where)`
(nosql.js, l. 1629)
and it's of number type instead of string, it throws an error, because it can't convert e.g. an integer toLowerCase(). Not sure, if this is intended behaviour or I'm simply doing something wrong.
Possible fix:
```
case '*':
			fn = compare_like;
			if (value instanceof Array) {
				for (var i = 0, length = value.length; i < length; i++)
					value[i] = value[i].toLowerCase();
			} else if(value instanceof String)
				value = value.toLowerCase();
			break;
```

**Comment by petersirka** [comment]
Hi @li0nsar3c00l,
this is not a bug, as documentation says that `search` value has to be `string` - no other.
<https://docs.totaljs.com/latest/en.html#api~DatabaseBuilder~builder.search>

Converting values cost CPU.

**Comment by li0nsar3c00l** [comment]
Alright, then I have to do it myself upfront. thanks for quick response, I guess, you can close this issue now.

**Comment by li0nsar3c00l** [comment]
is there any other option to search for table entries, that are of integer type or do I have to save those values as string in the nosql db?

**Comment by petersirka** [comment]
You can find numbers via `builder.where()` or `builder.between()` or save it as string ... I create `search` property for each document, this is my recommendation :-)

**Comment by li0nsar3c00l** [comment]
Seems like should pay more attention to details in the docs.
In case you don't mind, could you post an example, how to combine multiple and/or conditions? The structure of that is not clear to me and trial&error hasn't produced the desired outcome yet.

**Comment by petersirka** [comment]
__Yes, I agree__ - but I have a zero budget for all, so I do what I can.... I improve docs continuously.

__Here is a real usage:__
https://github.com/totaljs/eshop/blob/master/models/products.js#L38
https://github.com/totaljs/blogengine/blob/master/models/blogs.js#L36
