### ISSUE TITLE
Cluster mode - problem with caching

### ISSUE THREAD

**Issue by stakost** [totaljs/framework#476]
Hi!

I have a problem. When I use cluster mode, static files every time comes with 200 status.
When I use 1 CPU (regular for node, without cluster) - that's ok - 304 status.

Could you help me to resolve that problem?

Source:
```
let http = require('http'),
    cluster = require('cluster'),
    os = require('os');

if (!cluster.isMaster) {
    let F = require('total.js');

    F.on('message', (message) => {
        if (message.type === 'id')
            framework.id = message.id;
    });

    return F.http('release');
}

let numCPUs = os.cpus().length;

for (var i = 0; i < numCPUs; i++) {
    let fork = cluster.fork();
    fork.send({ type: 'id', id: i });
}
```

**Comment by petersirka** [comment]
I'm going to check it.

**Comment by petersirka** [comment]
I have tested it and everything works correctly. Which browser did yo use?

__Chrome:__
- writes status 200, but the file is read from cache

![cache](https://cloud.githubusercontent.com/assets/2414252/22745976/97e7541a-ee22-11e6-97c7-0bc335aa5e05.png)

__Firefox__:
- shows status correctly

![Firefox](https://cloud.githubusercontent.com/assets/2414252/22746036/d4381e9a-ee22-11e6-806b-f33b46d5e271.png)

---

I used cluster with __4 instances__ and I tried several requests together.
Thank you!

**Comment by stakost** [comment]
Hm.. I used cluster with 8 instances. In Chrome, FF and other browsers status is 200 :(
Totaljs v.2.4.0

Maybe because I used the auth-module?
**Chrome:**
<img width="563" alt="2017-02-08 23 46 22" src="https://cloud.githubusercontent.com/assets/1586327/22747250/28f0e1d4-ee59-11e6-9f2b-28ad38ea952e.png">

**FF:**
<img width="916" alt="2017-02-08 23 47 52" src="https://cloud.githubusercontent.com/assets/1586327/22747272/37f39078-ee59-11e6-883a-9b054e1bea45.png">

**Comment by totaljs** [comment]
Can you create a small example for me?

**Comment by stakost** [comment]
Now I tested with empty project (downloaded from https://github.com/totaljs/framework/releases), just add that file. Same problem :( Always return 200 status

**release-cluster.js**
```
let http = require('http'),
    cluster = require('cluster'),
    os = require('os');

if (!cluster.isMaster) {
    let F = require('total.js');

    F.on('message', (message) => {
        if (message.type === 'id')
            framework.id = message.id;
    });

    return F.http('release');
}

let numCPUs = os.cpus().length;

for (var i = 0; i < numCPUs; i++) {
    let fork = cluster.fork();
    fork.send({ type: 'id', id: i });
}
```

**Comment by stakost** [comment]
Is it:
[empty-project.zip](https://github.com/totaljs/framework/files/761335/empty-project.zip)

**Comment by stakost** [comment]
Hm. Some times when I restarted server - work correctly. It's very strange

**Comment by stakost** [comment]
I'll try to catch problem and tell, why it appear

**Comment by stakost** [comment]
So sorry, it is problem on my side :(
Framework works correctly!

**Comment by petersirka** [comment]
No problem! Thank you.

**Comment by stakost** [comment]
I'll waiting you solution about this :)
https://github.com/totaljs/framework/issues/469
Now I fixed it like that:

in **config** add:
```
default-response-maxage: 0
```

and **definitions/etag-update.js**
```
F.on('load', x => {
    F.config['etag-version'] = new Date().getTime();
    F.cache.clear();
});
```

But this solution did not work in Cluster mode :(

**Comment by stakost** [comment]
Cache is cleaning every time when server is restart

**Comment by petersirka** [comment]
New version doesn't use `etag` for comparing etags by default (but the server sends it), it uses `Last-modified` date only. I think where can be that problem.

**Comment by stakost** [comment]
How can I change `last-modified` for flush cache?

**Comment by petersirka** [comment]
This is not possible, you have to change the file only (you have to perform touch file). Where is the problem here? Framework uses a real modification file date as `Last-modified` date.
