### ISSUE TITLE
@{model.customKey} cannot be used in javascript directly

### ISSUE THREAD

**Issue by li0nsar3c00l** [totaljs/framework#477]
Beeing used to ASP.NET made me want to implement partial [views](https://docs.totaljs.com/latest/en.html#api~FrameworkViews). This includes adding javascript for a partial view to the proper place in the main view via [sections](https://docs.totaljs.com/latest/en.html#pages~View%20engine~(sections)). Unfortunately I cannot use the model passed to the partial view in javascript directly.
Hackish Workaround: I have to assign it to html property and grab the value then in my javascript code.

**Comment by petersirka** [comment]
__I cannot use the model passed to the partial view in javascript directly.__
How do you mean it?

__This works:__

```html
<script>
@{if model.alert}
     alert('@{model.alertmessage}');
@{fi}
</script>
```

But I recommend:

```html
@{json(model, 'modeldata')}

<script>
    var model = JSON.parse(document.getElementById('modeldata').innerHTML);
    console.log(model);
</script>
```

**Comment by li0nsar3c00l** [comment]
First, sorry for bothering you so often. What I wanted to do was something like this
```
<script>
var x = @{model.alertmessage};
</script>
```
My current workaround is something quite similar to the second approach.

**Comment by petersirka** [comment]
```javascript
<script>
var x = '@{model.alertmessage}';

// or
// but alertmessage has to contain apostrophes/quotes
var x = @{!model.alertmessage};
</script>
```

**Comment by petersirka** [comment]
For future question you can use __Total.js messenger__ (it's faster):
<https://messenger.totaljs.com>
