### ISSUE TITLE
How can disable view cache?

### ISSUE THREAD

**Issue by s2dent** [totaljs/framework#478]
Hi, Peter!
How can I disable view cache in release mode?

**Comment by petersirka** [comment]
Hi @s2dent, why do you need it?

**Comment by petersirka** [comment]
Is there any news?

**Comment by s2dent** [comment]
Sometimes it is necessary to immediately see the changes in the templates in release mode.
For example:
`var options = {};
options.disableViewCache = true;
require('total.js').http('release', options);`

**Comment by petersirka** [comment]
I recommend to user `debug` mode for this case or you can decrease the cache for 1 minute (`config`):
- `default-interval-clear-cache   : 1` (each minute).

**Comment by s2dent** [comment]
It would be a Great if it is possible to carry out in release mode. 
I seems like a nice idea, and it would have added more customization to Total.js

**Comment by petersirka** [comment]
I assume that you store views from DB on HDD, right?

**Comment by s2dent** [comment]
Yes, right.

**Comment by petersirka** [comment]
For this case can use:
https://docs.totaljs.com/latest/en.html#api~FrameworkController~controller.viewCompile

**Comment by s2dent** [comment]
This is a suitable option for me.

**Comment by petersirka** [comment]
No problem.
