### ISSUE TITLE
Question : The OPTIONS request accept only one type of request

### ISSUE THREAD

**Issue by ameykshirsagar** [totaljs/framework#483]
Hi,
I am trying to consume the REST API built from Total.js in the Angular framework. The Angular `$http` module does a request to the `OPTIONS` request of the URL to check whether the request method is available. Here is the sample of my code for /location API
````
F.route('/location', function() {
    this.content(200, "", false, {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET,POST,PUT,DELETE'
    });
}, ['options']);
````
It works for `POST` type requests but doesn't works for `PUT` & `DELETE`

Here is the response header for the above request when called by using Postman
````
Access-Control-Allow-Headers →*
Access-Control-Allow-Methods →POST
Access-Control-Allow-Origin →chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
Access-Control-Max-Age →120
Connection →keep-alive
Date →Tue, 07 Mar 2017 05:44:38 GMT
Transfer-Encoding →chunked
````
Anything I am doing wrong??
Thanks

P.S :- It works for jQuery AJAX as the options is

**Comment by petersirka** [comment]
Try to register `CORS` via:

```javascript
F.cors('/location/', ['GET', 'POST', 'PUT', 'DELETE']);
```

Docs: <https://docs.totaljs.com/latest/en.html#api~Framework~F.cors>
And give me a feedback :-)

**Comment by ameykshirsagar** [comment]
The `OPTIONS` request now gets 200 in preflight. But still getting 403 on PUT
````
F.cors('/location/', ['GET', 'POST', 'PUT', 'DELETE']);
F.route('/location', create_user, ['cors', 'post', '*LocationREST']);
F.route('/location', function() {
    this.content(200, "", false, {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET,POST,PUT,DELETE', //'GET,POST,PUT,DELETE'
    });
}, ['options']);
F.route('/location/{id}', get_user, ['cors', 'GET', '*LocationREST']);
F.route('/location/{id}', update_team, ['put', '*LocationREST']);
````
If I request /location, I get 403. If I request /location/asd, I get 404.

**Comment by petersirka** [comment]
Don't use `F.cors()` and `F.route(..['cors'])`...

__Try again__:
```javascript
// missing *
F.cors('/location/*', ['GET', 'POST', 'PUT', 'DELETE']);
```

**Comment by ameykshirsagar** [comment]
Worked. Thanks. My bad for using `cors` flag and `F.cors()`.
Closing the thread
