### ISSUE TITLE
Conflict with package's controllers name and main controllers

### ISSUE THREAD

**Issue by harry-stot** [totaljs/framework#485]
If i have my controllers (in main folder) called default.js (or any name) and having the same in my package with exports.booting enabled, the package's controller override my main controller is erase (in memory)

Try it yourself : 
/path/controllers/default.js
`exports.install = function () {
	framework.route('/home', view_index);
};

function view_index() {
self.plain('ok');
}`

then create a package with booting = true and a controller called default.js

/path/packages/test-package/controllers/default.js
`exports.install = function () {
	framework.route('/another_url', view_another_url);
};

function view_index() {
self.plain('Another url ok');
}`

then try to access "/home" and "/another_url"

"home" will return 404 (it should return "ok") and "another_url" will return "Another url ok"

**Comment by petersirka** [comment]
I'll check it.

**Comment by petersirka** [comment]
@harry-stot I have fixed it. Please try to download it from GitHub or NPM: `npm install total.js@beta`. Give me a feedback.

100x thank you for this report.
