### ISSUE TITLE
RESTBuilder

### ISSUE THREAD

**Issue by ivanlunardi** [totaljs/framework#486]
RestBuilder do not catch 403 from remote api

**Comment by petersirka** [comment]
Hi @ivanlunardi,
it works correctly:

```javascript
require('total.js');

RESTBuilder.make(function(builder) {
	builder.url('http://getstatuscode.com/403');
	builder.exec(function(err, data, response) {
		console.log(response.status);
	});
});
```

Do you have some example?

**Comment by petersirka** [comment]
Any news?

**Comment by ivanlunardi** [comment]
ok this example work, i was thinking the error is in 'err' !

**Comment by petersirka** [comment]
Error contains only network errors (timeout/bad hostname/etc). I have to update docs about this info.

**Comment by ivanlunardi** [comment]
OK Thank You
