### ISSUE TITLE
String.isUrl() not working with most urls

### ISSUE THREAD

**Issue by Humsas** [totaljs/framework#488]
Hello,

isUrl() checking doesn't let urls without "http://" to pass check, even if they should be valid. Also if you check Url like "http://w" it passes as valid.

I suggest using regex checking something like:
`/^(https?:\/\/(?:www\.|(?!www))[^\s\.#!:\?\+=&@!$'~*,;\/\(\)\[\]]+\.[^\s#!\?\+=&@!$'~*,;\(\)\[\]\\]{2,}\/?|www\.[^\s#!:\.\?\+=&@!$'~*,;\/\(\)\[\]]+\.[^\s#!\?\+=&@!$'~*,;\(\)\[\]\\]{2,}\/?)$/i`

Thanks.

**Comment by petersirka** [comment]
Hi @Humsas,
you're right. I have fixed it.

Please download it from:
<https://github.com/totaljs/framework/tree/v2.5.0>
