### ISSUE TITLE
Will totaljs support sitemap ?

### ISSUE THREAD

**Issue by lyquocnam** [totaljs/framework#489]
How can implement sitemap ?

**Comment by petersirka** [comment]
Hi @lyquocnam,
how do you mean it? Here is a simple info about Total.js `sitemap` file: https://docs.totaljs.com/latest/en.html#pages~File%3A%20sitemap

Thank you!

**Comment by lyquocnam** [comment]
this exactly what i need : https://github.com/totaljs/examples/tree/master/xml-sitemap
Thanks author about this awesome project !
