### ISSUE TITLE
Problem with "allow-compile-style"

### ISSUE THREAD

**Issue by s2dent** [totaljs/framework#491]
Hi, @petersirka
When I'm debugging application I want to disable style minifier, but "allow-compile-style" don't work for me.

config:
allow-compile-html :	false
allow-compile-script : false
allow-compile-style :	false

Before compilation:
![default](https://cloud.githubusercontent.com/assets/5107044/25053495/4c30c792-2160-11e7-9e58-5d5d27a044df.png)

After compilation:
![default](https://cloud.githubusercontent.com/assets/5107044/25053567/ac0cbb9e-2160-11e7-9ba5-8c90503eaa9d.png)

I would like to note that the "allow-compile-html" and "allow-compile-script" worked

How can I fix this?
Best regards,
s2dent

**Comment by petersirka** [comment]
Hi @s2dent, I have fixed it. Please test it `$ npm install total.js@beta`.

Thank you!

**Comment by s2dent** [comment]
Worked. Thanks.
