### ISSUE TITLE
SchemaBuilder: Invalid request body framing gives 200 status code with error message

### ISSUE THREAD

**Issue by ameykshirsagar** [totaljs/framework#493]
Hi,
I have created a schema of request using SchemaBuilder and when I framing the request body variables using `SchemaBuilderEntity.define`. When any of the request variable is set required true like this 
`schema.define('name','String',true);`
And if the name isn't present in the request body, the error message has 200 status code. Shouldn't the error message has status code of 400 for invalid request body framing??
Just asking

**Comment by petersirka** [comment]
Hi @ameykshirsagar.
Yes. It's very complicated to describe it but I'll try to find a solution for it tomorrow, OK?

**Comment by ameykshirsagar** [comment]
Cool no problem

**Comment by petersirka** [comment]
I have added it as a new option in configuration file.

```html
// A default value
default-errorbuilder-status    : 200
```

or you can change it manually:

```javascript
error_builder_instance.status = 400;
```

You can test it now `npm install total.js@beta`.
Thank you!

**Comment by ameykshirsagar** [comment]
Awesome. Thank you.
