### ISSUE TITLE
wrong behaviour of total.js

### ISSUE THREAD

**Issue by hbakhtiyor** [totaljs/framework#494]
### versions

Node.js : v7.8.0
Total.js : v2.5.0

### code sample

`app.js`

```js
require('total.js').http('release');
```

`controllers/default.js`

```js
exports.install = () => {
  F.route('/', function() {
    this.header('Connection', 'close');
    this.plain('Hello World!');
  });
};

```

### results
`curl -I localhost:8000`

```
HTTP/1.1 404 Not Found
Vary: Accept-Encoding
X-Powered-By: Total.js
Cache-Control: private
Content-Type: text/plain; charset=utf-8
Date: Mon, 01 May 2017 18:33:10 GMT
Connection: keep-alive
```

HEAD request getting 404 error

**Comment by petersirka** [comment]
Hi @hbakhtiyor,
- <https://docs.totaljs.com/latest/en.html#api~FrameworkConfiguration~allow-head>
- or `F.route('/', YOUR_ACTION, ['head'])`

Thank you!

**Comment by hbakhtiyor** [comment]
hi @petersirka, thanks
