### ISSUE TITLE
the content-type is being ignored in header in RestBuilder

### ISSUE THREAD

**Issue by gyldcs** [totaljs/framework#495]
As you can see in the code bellow, I am setting the Content-Type in header to "www-form" but in the request the Content-Type is set to "application/json"

[Post request inspector](https://requestb.in/1jczrn61?inspect)

```
require('total.js')

RESTBuilder.make(function(builder) {
    // builder === instance of RESTBuilder
    builder.header('Content-Type', 'application/x-www-form-urlencoded');
    builder.url('http://requestb.in/1jczrn61');
    builder.post({"Test":"Hello"});
    builder.exec(function(err, response) {
        console.log(response)  
    });
});
```

**Comment by totaljs** [comment]
@gyldcs you have to use https://docs.totaljs.com/latest/en.html#api~RESTBuilder~instance.urlencoded instead of builder.post(). 👍

**Comment by gyldcs** [comment]
damn, it's working now, sorry
