### ISSUE TITLE
english errors on the main website

### ISSUE THREAD

**Issue by harry-wood** [totaljs/framework#496]
english errors on the main website https://www.totaljs.com  

The big strapline
_"Total.js Messenger is a small alternative to Slack. Our solution is small, fast and open-source web application which you can customize it **by** your needs. Try our great solution as a communication channel in your company or sell it **for** your customers."_

Should be...
_customize it **to** your needs_
_sell it **to** your customers_

Didn't find a repo with your website content in it, so leaving this here. Feel free to move it.

**Comment by petersirka** [comment]
Hi @harry-wood, thank you very much. Can I add you login to totaljs.com homepage? You can edit it directly and I'll be very happy!

Please write me email: petersirka@gmail.com
Thank you

**Comment by harry-wood** [comment]
I like the idea of an open source slack alternative so I wanted to help, but I don't really have time I'm afraid. Just swinging by to report the error. It's a very noticeable english error in a prominent place on the website, so I think you should fix it.

**Comment by petersirka** [comment]
No problem, thank you! I'll update it today.
