### ISSUE TITLE
Github login not working for "preview messenger"

### ISSUE THREAD

**Issue by destan** [totaljs/framework#497]
On this url: https://my.totaljs.com/?url=https%3A%2F%2Fmessenger.totaljs.com%2F

when I authorize github it redirects to following error:

![image](https://cloud.githubusercontent.com/assets/442813/25744997/7cdeb62e-31a5-11e7-9282-5fdf62066575.png)

**Comment by destan** [comment]
@petersirka I don't get it. As shown below I authorize the app to have/use my email address:

![image](https://cloud.githubusercontent.com/assets/442813/25754811/41c4ee18-31c9-11e7-82fa-4c102108869d.png)

According to [here](https://help.github.com/articles/connecting-with-third-party-applications/#user-data) the app is supposed to access the email address.

So why the error?

**Comment by petersirka** [comment]
Hmmm, I have enabled logging. Try to login again. I'm curious.

**Comment by nikhilknoldus** [comment]
Hi @petersirka Everything is really awesome, but just for the info. github still not working.
Thanks !! Keep up the great work.

**Comment by petersirka** [comment]
@nikhilknoldus Thank you. I know .. but Github doesn't send `email` field. I have tested it on my profile and GitHub returns my profile with email address. I don't want to enable profiles with no email.

Thank you!
