### ISSUE TITLE
Folders should be respected when loading views

### ISSUE THREAD

**Issue by ajimix** [totaljs/framework#499]
With the following folder structure:
```
views/
  test/
    index.html
  index.html
```

If you execute the following code in your controller:
```js
this.view('test/index');
```

The view `views/index.html` is loaded instead of `views/test/index.html`

**Comment by petersirka** [comment]
@ajimix what is your controller name?

**Comment by ajimix** [comment]
For this test I have two:
```
controllers
  test.js
  default.js
```

`default.js` is set to load `index` and loads the `views/index.html` which is correct.
`test.js` is set to load `test/index` so it should load the `views/test/index.html` but is not.

Is happening on a clean project too.

**Comment by petersirka** [comment]
All views are loaded according controller name.

__controllers/test.js__:

```javascript
exports.install = function() {
    F.route('/test/', view);
};

function view() {
    // is routed to "/views/test/index.html" (all controllers with excetp "default" controller
    // if the file doens't exist then it finds same view in parent directory
    this.view('index');
}
```

__controllers/default.js__:

```javascript
exports.install = function() {
    F.route('/', view);
};

function view() {
    // is routed to "/views/index.html"
    this.view('index');
}
```

I have tested it now and everything works correctly. Which OS do you use? Do you have TeamViewer? I can connect to you via TeamViewer - if you agree write me on https://messenger.totaljs.com

Thank you!

**Comment by ajimix** [comment]
Ok I see, the problem was that I was specifying the directory. So just doing `this.view('index')` inside the `test.js` controller made it work properly.
Maybe you can add that little note in the docs :)
Thanks for your time, I'm closing the issue 👍

**Comment by petersirka** [comment]
Here is a note:
<https://docs.totaljs.com/latest/en.html#pages~View%20engine~(defining-views-in-sub-directories)>

But yes, I have to improve it in docs.
