### ISSUE TITLE
F.schedule

### ISSUE THREAD

**Issue by ivanlunardi** [totaljs/framework#500]
It's possible to use schedule with "seconds" ?

**Comment by molda** [comment]
@ivanlunardi Can you be more specific? What do you want to achieve?

`schedules` are processed once a minute so it's more usefull for longer times not a seconds. 
Wouldn't setTimeout or setInterval be better?

**Comment by ivanlunardi** [comment]
hi , my needs is to run a schedule every 10 seconds.

**Comment by molda** [comment]
Then F.schedule is not what you want. 
You gonna need to use setInterval.

**Comment by ivanlunardi** [comment]
Thanks!
