### ISSUE TITLE
how do i perform keep-alive connection?

### ISSUE THREAD

**Issue by dima1034** [totaljs/framework#502]

**Comment by petersirka** [comment]
Hi @dima1034,

```javascript
F.on('ready', function() {
    F.server.on('connection', function(socket) {
        socket.setKeepAlive(true, 10);
    });
});
```

__Documentation:__
https://nodejs.org/dist/latest-v7.x/docs/api/net.html#net_socket_setkeepalive_enable_initialdelay

Thank you!

**Comment by dima1034** [comment]
you are good. but that's not about socket. it is about HTTP persistent connection

**Comment by dima1034** [comment]
anyway try to make some test for checking if server can handle stuff like keep-alive connection

**Comment by petersirka** [comment]
I think that it is about the socket. 

- http://stackoverflow.com/questions/12651466/how-to-set-the-http-keep-alive-timeout-in-a-nodejs-server
- I'll perform some tests

**Comment by petersirka** [comment]
So `socket.setKeepAlive()` is the only one way how to set keep-live connection. I didn't find another solution for it. As I wrote --> Total.js uses Node.js built-in http server.

Thank you!
