### ISSUE TITLE
Unable to Order

### ISSUE THREAD

**Issue by subbu05** [totaljs/framework#504]
The field "products" is invalid.

I get error when I order - checkout.

**Comment by petersirka** [comment]
@subbu05 which eshop? Premium or classic?

**Comment by subbu05** [comment]
Hi Peter, I have purchased premium version. I am seeing this issue on eshop premium.

**Comment by petersirka** [comment]
@subbu05 I have tested it and everything works correctly. I have latest version from <https://my.totaljs.com>. Historically was a some similar bug in the eshop.

Please try to download latest version from my.totaljs.com and give me a feedback.
Thank you!
