### ISSUE TITLE
Error Connecting my.totaljs.com

### ISSUE THREAD

**Issue by ChukkChukk** [totaljs/framework#505]
When sent to the [https://my.totaljs.com/](https://my.totaljs.com/) page to attempt to sign in with Github OAuth, error message below appears on the screen.

`[{"name":"email","error":"Email address is required."}]`

The Url is stuck with this message.

`https://my.totaljs.com/oauth2/github/callback/?code=65256b11a0bee65d5e9b`.

**Comment by petersirka** [comment]
Hi @ChukkChukk, yes ... Sometimes GitHub doesn't send email address and this is the problem. Are you sure you have public your email address?

Thank you!

**Comment by ChukkChukk** [comment]
I did not have my email on public, but switched it now. It had never been a problem before, so never even checked.  It does work now. Thank you, I really like your product!
