### ISSUE TITLE
Cant send static files with Nuxt.js middleware

### ISSUE THREAD

**Issue by ckpiggy** [totaljs/framework#506]
I tried to integrate Nuxt.js middleware with total.js
It works fine when I use it as a request handler of a plain old http server
```
const Nuxt = require('nuxt')
const options = require('./nuxt.config')
const nuxt = new Nuxt(options)
const http = require('http')

nuxt.build().then(function () {
    http.createServer(nuxt.render).listen(3000)
  })
```
But when I use it with total.js I got some problem about getting static assets.
I create a middleware and register route `/_nuxt/` for the middleware to send static files in `definitions` folder.
```
const Nuxt = require('nuxt')
const option = require('../nuxt.config')
const nuxt = new Nuxt(option)

nuxt.build().then(function () {
  F.middleware('nuxt', nuxt.render)
  F.file('/_nuxt/*', nuxt.render)
})
```

![2017-05-15 2 45 47](https://cloud.githubusercontent.com/assets/6531171/26036851/a6922562-3918-11e7-9893-e1b387e6c8cd.png)

Did I miss anything?

**Comment by petersirka** [comment]
@ckpiggy I'll look into it this week. It's out of my scope but I'll try to solve it.
Thank you.

**Comment by ckpiggy** [comment]
I am closing this issue since this issue is beyond the scope of total.js.

**Comment by petersirka** [comment]
@ckpiggy `next.js` has been a bit changed, I looked into it but I didn't have more free time for it up to now.

**Comment by petersirka** [comment]
I have solved this problem here:
https://github.com/totaljs/framework/issues/515
