### ISSUE TITLE
Multiple JOIN "NOSQL"

### ISSUE THREAD

**Issue by camilohaze** [totaljs/framework#510]
When I try to make multiple joins, it only does the relation of the first join that it finds.

How to use the join function?

Thank you.

**Comment by petersirka** [comment]
Hi @camilohaze,
I have tested it and everything works correctly:

```javascript
var users = NOSQL('users').find();

users.join('address', 'address').where('iduser', 'id').first();
users.join('tags', 'tags').where('iduser', 'id');

users.callback(function(err, response) {
     console.log(response);
});
```

__users.nosql__:
```json
{"id":1,"name":"Peter"}
{"id":2,"name":"Lucia"}
{"id":3,"name":"Igor"}
{"id":4,"name":"Jozef"}
{"id":5,"name":"Anna"}
```

__address.nosql__:
```json
{"iduser":1,"name":"Bratislava"}
{"iduser":3,"name":"Kosice"}
{"iduser":5,"name":"Zvolen"}
```

__tags.nosql__:
```json
{"iduser":1,"name":"Node.js"}
{"iduser":1,"name":"JavaScript"}
{"iduser":1,"name":"Total.js"}
```
__Results__:
```json
{"id":1,"name":"Peter","address":{"iduser":1,"name":"Bratislava"},"tags":[{"iduser":1,"name":"Node.js"},{"iduser":1,"name":"JavaScript"},{"iduser":1,"name":"Total.js"}]}
{"id":2,"name":"Lucia","tags":[]}
{"id":3,"name":"Igor","address":{"iduser":3,"name":"Kosice"},"tags":[]}
{"id":4,"name":"Jozef","tags":[]}
{"id":5,"name":"Anna","address":{"iduser":5,"name":"Zvolen"},"tags":[]}
```

**Comment by camilohaze** [comment]
Hi @petersirka 

I try to make a recursive join (multiple join to the same table) for example:

```javascript
        var codes = NOSQL('codes').find();

        codes.join('clients', 'lists')
                .where('id', 'client')
                .fields('id', 'title', 'code', 'abbreviation')
                .first();

        codes.join('blocks', 'lists')
                .where('id', 'block')
                .fields('id', 'title', 'code', 'abbreviation')
                .first();
```

**codes.nosql**
```javascript
{"id":1,"code":"01","client": 1, "block": 2}
```

**lists.nosql**
```javascript
{"id":1,"name":"ASDF", "type": "client"}
{"id":2,"name":"#1", "type": "block"}
```

**Error message**

> ======= 2017-05-21 15:57:59: system ---> TypeError: Cannot read property 'where' of undefined (http://localhost:8000/api/codes/?page=1&max=14) TypeError: Cannot read property 'where' of undefined
>     at SchemaBuilderEntity.onQuery (C:\Users\Cristian\Downloads\Telemedellín\InHouse\Run List\models\codes.js:39:17)
>     at SchemaBuilderEntity.query (C:\Users\Cristian\Downloads\Telemedellín\InHouse\Run List\node_modules\total.js\builders.js:993:9)
>     at Object.Controller.$query (C:\Users\Cristian\Downloads\Telemedellín\InHouse\Run List\node_modules\total.js\index.js:9738:19)
>     at Object.json_query (C:\Users\Cristian\Downloads\Telemedellín\InHouse\Run List\controllers\system.js:51:10)
>     at Subscribe.doExecute (C:\Users\Cristian\Downloads\Telemedellín\InHouse\Run List\node_modules\total.js\index.js:9252:23)
>     at Subscribe.execute (C:\Users\Cristian\Downloads\Telemedellín\InHouse\Run List\node_modules\total.js\index.js:9168:8)
>     at Subscribe.prepare (C:\Users\Cristian\Downloads\Telemedellín\InHouse\Run List\node_modules\total.js\index.js:9215:8)
>     at Subscribe.doEnd (C:\Users\Cristian\Downloads\Telemedellín\InHouse\Run List\node_modules\total.js\index.js:9326:8)
>     at IncomingMessage.subscribe_end (C:\Users\Cristian\Downloads\Telemedellín\InHouse\Run List\node_modules\total.js\index.js:9104:18)
>     at emitNone (events.js:86:13)

**Comment by petersirka** [comment]
I have fixed it.
Please download <https://github.com/totaljs/framework/blob/v2.6.0/nosql.js> and replace it in your `/node_modules/total.js/`.

Thank you!
PS: Give me a feedback.

**Comment by camilohaze** [comment]
Thanks for your prompt response, It worked perfectly. 👍

**Comment by petersirka** [comment]
Great! Thank you!
