### ISSUE TITLE
Help me: Nuxt

### ISSUE THREAD

**Issue by adrianrey05** [totaljs/framework#515]
Hi,
can´t you help me to configure nuxt with totaljs?
in the docs of nuxt there's an example of configure expressjs with nuxt.
https://github.com/nuxt-community/express-template/tree/master/template
like this

```js
import Nuxt from 'nuxt'
import express from 'express'

import api from './api'

const app = express()
const host = process.env.HOST || '127.0.0.1'
const port = process.env.PORT || 3000

app.set('port', port)

// Import API Routes
app.use('/api', api)

// Start nuxt.js
async function start() {
  // Import and Set Nuxt.js options
  let config = require('../nuxt.config.js')
  config.dev = !(process.env.NODE_ENV === 'production')
  // Instanciate nuxt.js
  const nuxt = new Nuxt(config)
  // Add nuxt.js middleware
  app.use(nuxt.render)
  // Listen the server
  app.listen(port, host)
  console.log('Server listening on ' + host + ':' + port) // eslint-disable-line no-console
}

start()
```
how can i write it in totaljs?
thanks

**Comment by petersirka** [comment]
Theoretically:

__Initialization__:
```javascript
require('total.js').http('debug');

const nuxt = new Nuxt(config)
F.middleware('nuxt', nuxt.render);
```

__Routes__:

```javascript
F.route('/api/', action, ['nuxt']);

// Or register nuxt middleware for all requests
// F.use('nuxt');
```

**Comment by adrianrey05** [comment]
Hi @petersirka,
You are awesome man! 
It's work, but for the files static of nuxt not work.
![image](https://user-images.githubusercontent.com/5314570/27393906-d6327b0c-5680-11e7-9eaa-c4dcc71e80a2.png)
![image](https://user-images.githubusercontent.com/5314570/27393933-f1eab012-5680-11e7-8a5e-d56be2d713bd.png)

this is the code 

```js
var Nuxt = require('nuxt')
async function start() {
  let config = require('./nuxt.config.js')
  const nuxt = new Nuxt(config)
  var result = await nuxt.build()
  require('total.js').http('debug', {})
  F.middleware('nuxt', nuxt.render)
  F.use('nuxt')
}
start();
```

**Comment by petersirka** [comment]
Can you send me your app (example) on my email without `node_modules`? I have to test it.

**Comment by petersirka** [comment]
- please install total.js beta `npm install total.js@beta`
- run it again :-)

Thank you!

**Comment by petersirka** [comment]
BTW: code of nuxt with another dependencies is a big hidden shit.

**Comment by adrianrey05** [comment]
you are the fucking genius man! (no offense) 
thank you very much!

what was the problem?

**Comment by petersirka** [comment]
🥇 👍  💯 Nuxt uses `res.send(BUFFER)` for static files and Total.js expected `res.send(code, body, [contentype])`. So I have updated `res.send()`.
