### ISSUE TITLE
Regular expression with F.route

### ISSUE THREAD

**Issue by ckpiggy** [totaljs/framework#517]
I want to use regular expression to exclude the routes start with `/api`, here is my regular expression: `'^(?!/api)[/A-Za-z0-9]*$'`. I've test with node command line:
```
> '/'.match('^(?!/api)[/A-Za-z0-9]*$')
[ '/', index: 0, input: '/' ]
> '/test'.match('^(?!/api)[/A-Za-z0-9]*$')
[ '/test', index: 0, input: '/test' ]
> '/a'.match('^(?!/api)[/A-Za-z0-9]*$')
[ '/a', index: 0, input: '/a' ]
> '/app'.match('^(?!/api)[/A-Za-z0-9]*$')
[ '/app', index: 0, input: '/app' ]
> '/api'.match('^(?!/api)[/A-Za-z0-9]*$')
null
```
It looks good in the test, but when I put it in F.route
```F.route('^(?!/api)[/A-Za-z0-9]*$', my_view)```
I got 404 error when I visit '/'

**Comment by petersirka** [comment]
Hi @ckpiggy, `RegExp` can be used only for dynamic parameters.

```javascript
F.route('/api/{/\d+/}/', action);
```

But you have to use a route with `function`:

```javascript
var reg = /^(?!/api)[/A-Za-z0-9]*$/;
F.route(url => reg.test(url), action);
```

Thank you and give me a feedback!

**Comment by ckpiggy** [comment]
It works!! Thank you.
```
exports.install = function () {
  const reg = /^(?!\/api)[/A-Za-z0-9_.]*$/
  F.route((url)=>{ return reg.test(url)}, nuxt, ['#nuxt'])
  F.file((url)=>{return reg.test(url.uri.path)}, nuxt, ['#nuxt'])
}

function nuxt () {
  //this should not be execute
  throw new Error('nuxt middle ware not working')
}
```
Actually, I was trying to use it with Nuxt.js. May I write an example about integrating Total.js with Nuxt.js ?

**Comment by petersirka** [comment]
About __Nuxt.js__ read here:
https://github.com/totaljs/framework/issues/515

**Comment by ckpiggy** [comment]
Oh! I mean I want to write an example for [totaljs/examples](https://github.com/totaljs/examples), since I haven't seen any related example. Anyway, I've made a pull request: totaljs/examples/pull/60 .
