### ISSUE TITLE
Mail module might do AUTH LOGIN even when credentials are not configured

### ISSUE THREAD

**Issue by mjiricka** [totaljs/framework#522]
I had a problem with mail module. My application stopped sending emails suddenly. Mail server reported: "lost connection after AUTH“. The module was trying to use AUTH PLAIN LOGIN even when my mail configuration does not contain credentials:

    mail.smtp.options : {"secure":false,"port":25,"user":"","password":"","timeout":10000}

I think this line in mail.js is incorrect:

    if ((line.indexOf('AUTH LOGIN PLAIN') !== -1 || line.indexOf('AUTH PLAIN LOGIN') !== -1) || (options.user && options.password)) 

Mail server can provide AUTH LOGIN, but e.g. senders from localhost do not need it. (That was my problem, later I add user authentication, but only for remote users!) Therefore I suggest to try to do AUTH LOGIN only when user and password are given. Changing second OR (||) for AND (&&) solved my problem.

(Only question is what to do when credentials are provided but server does not offer PLAIN LOGIN.)

**Comment by petersirka** [comment]
Hi @mjiricka,
the problem is bigger than I thought. I'll give you feedback today.

**Comment by petersirka** [comment]
Hi @mjiricka,
please try to use <https://github.com/totaljs/framework/tree/v2.8.0>. I have improved SMTP sender.

**Comment by mjiricka** [comment]
Hi! Yes, on my configuration this works!
