### ISSUE TITLE
Wrong root directory on Azure

### ISSUE THREAD

**Issue by trsh** [totaljs/framework#523]
I had problems running total.js app on azure and got to this line:

`var directory = U.$normalize(require.main ? Path.dirname(require.main.filename) : process.cwd());`

I added some logs:

`console.log(require.main);
console.log(process.cwd());
console.log(__dirname);`

I can see:

Module {
  id: '.',
  exports: {},
  parent: null,
  **filename**: 'D:\\Program Files (x86)\\iisnode\\interceptor.js',
  loaded: false,
  children: 
   [ Module {
       id: 'D:\\home\\site\\wwwroot\\release.js',
       exports: {},
       parent: [Circular],
       filename: 'D:\\home\\site\\wwwroot\\release.js',
       loaded: false,
       children: [Object],
       paths: [Object] } ],
  paths: 
   [ 'D:\\Program Files (x86)\\iisnode\\node_modules',
     'D:\\Program Files (x86)\\node_modules',
     'D:\\node_modules' ] }
D:\home\site\wwwroot
D:\home\site\wwwroot\node_modules\total.js

When it normalizes `filename` the root dir is taken as 'D:\Program Files (x86)\iisnode' what is obviously wrong.

**Comment by petersirka** [comment]
Read here:
<https://docs.totaljs.com/latest/en.html#pages~Troubleshooting~(hosting-total-js-applications-in-iis-on-windows)>

**Comment by trsh** [comment]
@petersirka 

This line `options.directory = process.cwd(); ` did it. I will do some additional tests and then close this.

**Comment by trsh** [comment]
@petersirka 

in my controller I use `require.main.require("./common/source/startup/routes.js")` so I can require lib from the root. As `require.main` is broken in Azure case, what would be the recommended way?

**Comment by petersirka** [comment]
@trsh you can use relative path like this `require('../../../xx.js')`. Therefore the framework has a simple structure.
