### ISSUE TITLE
Return a promise or export an async install function

### ISSUE THREAD

**Issue by ckpiggy** [totaljs/framework#524]
I use a remote mongodb, and the unit test started before the database connected.
How about we export an async install function or return a promise for the install function for the modules.
ex:
`my-app/modules/database.js`
```
const mongo = require('mongodb').MongoClient,
      url = CONFIG('mongodb-path')

// export an async install function (for nodejs 8.x+)
exports.install = async function () {
  try {
    let db = await mongo.connect(url)
    F.database = function (collection) {
      return collection ? db.collection(collection) : db
    }
    console.log('did connect to db ' + url)
  }catch(err){
    console.error(err)
  }
}
```
```
//or return promise
exports.install = function () {
  return mongo.connect(url)
    .then(function (db) {
      F.database = function (collection) {
        return collection ? db.collection(collection) : db
      }
      console.log('did connect to db ' + url)
    })
}
```
and the framework can use `Promise.all` or `await Promise.all` to wait for all the install function complete then go to next stage.

**Comment by petersirka** [comment]
@ckpiggy `install` method is evaluated immediately, it can't be async. About `async`, sure I will think about its implemention into the framework, but it's too early. Backward compatibility is very important for my. not all developers use v8 node.

**Comment by ckpiggy** [comment]
Thanks for your time, @petersirka . You are right, not all developer use node 8.x+. How about return an optional promise in `install` (node 6.x+) ?

**Comment by petersirka** [comment]
I don't see any sense for implementation of promises to `install` method. The framework executes `install` immediately and in order synchronously.

```javascript
exports.install = function(options) {
    mongo.connect(url).then(function (db) {     
        console.log('did connect to db ' + url)
        F.database = function (collection) {
            return collection ? db.collection(collection) : db
        };

        // Just you need to emit an event if the DB is ready
        EMIT('database', db);
    });
};
```

__Other dependencies__:

```javascript
ON('database', function(db) {
    console.log('DB IS READY');
});
```

**Comment by ckpiggy** [comment]
Hm, you are right. Thx.
