### ISSUE TITLE
Translate bug in 2.7

### ISSUE THREAD

**Issue by dacrhu** [totaljs/framework#529]
Hi, translate option generate some irrelevant item.

[dacr@berci test]$ totaljs

|==================================================|
| Total.js - Web framework for Node.js             |
| Version: v2.7.0                                  |
|==================================================|

Downloading "empty-project" from www.totaljs.com
Unpacking file.
Done.

[dacr@berci test]$ totaljs --translate

|==================================================|
| Total.js - Web framework for Node.js             |
| Version: v2.7.0                                  |
|==================================================|

Total.js: creating translation
Total.js: the translation was created (6 texts)

[dacr@berci test]$ cat translate.resource 
// Total.js translation file
// Created: 2017-07-25 19:05

// node_modules/total.js/index.js
T39            : '
T-75123236     : TEXT TO TRANSLATE

// node_modules/total.js/internal.js
T662061527     : ', indexű

Thank you!
David

**Comment by petersirka** [comment]
Hi Dávid,
I have fixed it, please install latest beta version of Total.js from NPM:

- `$ sudo npm install -g total.js@beta`

**Comment by petersirka** [comment]
Does it work?

**Comment by dacrhu** [comment]
Sorry for the late reply!
Working fine, thank you!

**Comment by petersirka** [comment]
Great! Thank you!
