### ISSUE TITLE
Document was conflit about controller.body and F.restful2

### ISSUE THREAD

**Issue by ckpiggy** [totaljs/framework#530]
The example:
```
exports.install = function() {

    F.restful2('/users/', ['*Users', 'authorized'], users_query, users_get, users_save, users_delete);

    // Framework creates these routes:
    // /users/ --> query (method: GET)
    // /users/{id}/ --> get (method: GET)
    // /users/ --> save (method: POST)
    // /users/ --> delete (method: DELETE)
};

function users_query() {
    // self.query exists for e.g. filters
    // self.body doesn't exist
}

function users_get(id) {
    // self.query exists for e.g. filters
    // self.body doesn't exist
}

function users_save() {
    // How to get ID? e.g.
    // this.body.id
}

function users_delete() {
    // How to get ID? e.g.
    // this.body.id
}
```
In the `user_delete` function should use `this.req.body.id` not `this.body.id`, because `controller.body` is only for `POST` and `PUT` method

**Comment by petersirka** [comment]
No, `controller.body` will work within `DELETE` method too, browser sends data in `body`.

**Comment by ckpiggy** [comment]
Please forgive my bad English, I didn't mean the framework not working. I mean the document has conflict about this.

![2017-07-27 4 02 43](https://user-images.githubusercontent.com/6531171/28660333-17cb892a-72e5-11e7-99f4-11f55de52be3.png)

**Comment by petersirka** [comment]
I understand. My english is bad too, I'm going to fix it.
