### ISSUE TITLE
F.test callback not invoked?

### ISSUE THREAD

**Issue by raythree** [totaljs/framework#532]
Hi, I'm trying to figure out how to do some cleanup after all tests have run. Using the default test setup works fine:
```
require('total.js').http('test', options);
```
but it looked to me like the ```F.test``` method had a callback, which I assumed was executed when all tests were done? I replaced the above with:

```
require('total.js');

F.test(true, [], function () {
  console.log('TESTING COMPLETE, executing cleanup');
});
```
All 3 tests I have are executed, but it seems that the callback is never invoked. Any recommendations for doing some cleanup after all tests?

BTW, I just started evaluating the framework a couple of days ago, and it is awesome!

**Comment by petersirka** [comment]
Hi @raythree,
I forgot to update documentation. `F.test()` is deprecated now, don't use it. Here is a simple solution for your needs:

```javascript
ON('test-begin', function() {
     console.log('begin');
});

ON('test-end', function() {
     console.log('end');
});
```

And thank you for your compliments, I appreciate it.

**Comment by raythree** [comment]
Thats great thank you!

**Comment by raythree** [comment]
OK I tried the above. It seems that ```test-begin``` is fired once before testing starts. However, ```test-end``` is fired for each test run (3 times in my case).  I need a callback that is fired once when all tests are complete, OR an individual "done" method for each TEST executed.  I want to execute cleanup either when all tests are done, or individual cleanup for each TEST.

**Comment by petersirka** [comment]
Where did you place this event?

I have tested it here and everything works correctly:
https://github.com/totaljs/examples/tree/master/assertion-testing

__Start script__:

```javascript
require('total.js').http('test');

ON('test-end', function() {
	console.log('DONE');
});
```

**Comment by raythree** [comment]
Like this:
```
require('total.js').http('test', options);

ON('test-begin', () => console.log('Tests STARTING'));

ON('test-end', () => {
  console.log('Tests ENDED, cleaning up'); 
});
```
Test end fires 3 times, as I have 3 TESTs in 2 files in the tests/ folder

**Comment by petersirka** [comment]
Are you sure you don't use `F.test()`? Try my example:
[assertion-testing.zip](https://github.com/totaljs/framework/files/1188666/assertion-testing.zip)

**Comment by raythree** [comment]
OK thanks, I can your DONE only executes once. I definitely removed the F.test. Will troubleshoot further a little later and report back. Thanks for the quick response.

**Comment by petersirka** [comment]
No problem. I'll fix docs.
Thank you!

**Comment by raythree** [comment]
OK, so I took your test and reproduced what I was seeing, where test-end is called more than once. Technically, I'm actually running integration tests, not "unit" tests, because I'm testing Mongoose models/schemas with a local mongo instance running. I usually do that for these type of db/model tests, rather than mocking the database. Everything works, it's just that when I do this the test-end is invoked multiple times. This is where I want to put my database cleanup (e.g. drop the test data from the collections).  If you run without a mongo instance, the tests fail and test-end is only called once. If you want to try and you have docker installed, you can run a local test DB like this:

```
docker run --name mongo-test -p 27017:27017 -v /Users/bill/databases/testdb:/data/db -d mongo
```
And here is the code:

[assertion-testing.zip](https://github.com/totaljs/framework/files/1190496/assertion-testing.zip)

Thank you!
Bill

**Comment by petersirka** [comment]
I found a problem in your test script:

```javascript
TEST('Test model schema', function () {
  let m = new MyModel( {
    name: 'bill'
  });  
  m.validate((err) => {
    // uuid required
    FAIL(err === null) // HERE --> here this test ends
    m.uuid = U.GUID(24);
    m.validate((err) => {
      OK(err === null) // --> and this is the problematic part, for this you need  anew TEST()
    });
  });
});
```

- `TEST()` expects the only one result `FAIL()` or `OK()` or multiple calls in a row immediately

__Solution__:

```javascript
TEST('Test model schema', function () {
  let m = new MyModel( {
    name: 'bill'
  });  
  m.validate((err) => {
    // uuid required
    FAIL(err === null);
    m.uuid = U.GUID(24);

    TEST('Validate schema', function () {
        m.validate((err) => {
            OK(err === null)
        });
     });

  });
});
```

**Comment by raythree** [comment]
Great thank you! I didn't realize TEST calls could be nested (or needed to be).
