### ISSUE TITLE
PUT and PATCH

### ISSUE THREAD

**Issue by raythree** [totaljs/framework#533]
Is "update" in restful2 implemented as a POST instead of a PUT, e.g. POST /endpoint/id? I'm adapting this backend and we have lots of clients that expect to use PUT. Also, if PATCH were supported it would allow individual fields to be updated, rather than a full document.

**Comment by petersirka** [comment]
You do not have to use `F.restful2()`. Use `F.restful()` - but it doesn't support `patch` or create your own routes directly:

```javascript
F.route('/users/',              action_query]);
F.route('/users/{id}/',         action_read]);
F.route('/users/',              action_create,  ['post']);
F.route('/users/{id}/',         action_update,  ['put']);
F.route('/users/{id}/{field}/', action_patch,   ['patch']);
F.route('/users/{id}',          action_remove,  ['delete']);
```

`F.restfull()` creates same code on background.
BTW: I prefer sending of smaller documents less than `1 kB`, in other words I don't use `PATCH` method 👍

**Comment by raythree** [comment]
Ah thanks. I even had the above routes in a comment in my code, but thought that I grabbed them from restful2 (either source code or docs). I started using that not noticing the different comments and thinking restful might later be deprecated by restful2.

**Comment by petersirka** [comment]
`F.restful()` won't be deprecated, I don't plan it so yet. BTW: you can extend `F` instance by adding method e.g. `restful3()` with your needs.
