### ISSUE TITLE
Is schema directory deliberately omitted from the debug "watch" list?

### ISSUE THREAD

**Issue by raythree** [totaljs/framework#535]
I noticed the schema directory is the only folder omitted from the list of watched folders in debug mode. I use this for Mongoose schemas, and do a manual restart after changing them. Is this deliberate to treat schema changes differently from other code changes?

Thanks!

**Comment by petersirka** [comment]
Hi @raythree,
the framework doesn't use `schema` directory, but I can update `debug.js` by adding new directory for watching. Which directory do you want to watch?

**Comment by raythree** [comment]
Hi Peter, adding the "schema" directory in debug.js would be great. Currently it watches all the others (controllers, models, definitions...).

Thanks!

**Comment by petersirka** [comment]
Jo @raythree,
I have added it. You can test it: `$ npm install total.js@beta`. Please be careful because I have improved NoSQL embedded counter and it's backwards incompatible (it will convert older files to a new version), but it works perfectly.

Thank you!
