### ISSUE TITLE
Question on F.onAuthorize

### ISSUE THREAD

**Issue by raythree** [totaljs/framework#536]
Hi, I noticed from looking at my logs that ```F.onAuthorize``` was being invoked for a route that did not include the ```authorize``` flag:
```
2017-08-10 06:43:28-04:00: [INFO] authorize - rejecting request missing authorization header
```
But then the request was allowed to proceed, as it should be. So it seems ```F.onAuthorize``` is invoked on every route, but it's rejection is ignored if the route does not have the flag. Is there a reason for not just skipping it's invocation for unauthorized routes? 

Thanks!

**Comment by petersirka** [comment]
That's true. It __needs to be called__ because you can have this case:

```javascript
F.route('/', home_auth, ['authorize']);
F.route('/', home_unauth, ['unauthorize']);
// or
F.route('/contact/', contact_both); // for auth/unauth
```

Framework needs to know whether the request is authorized or no. So therefore is called every request.
