### ISSUE TITLE
Issue serving a Webpack bundled static javascript app

### ISSUE THREAD

**Issue by raythree** [totaljs/framework#538]
I am having an issue serving a single-page Webpack application from static files.  Webpack is bundling the files into the static/app folder of the total.js app and it looks like this:

```
-rw-r--r--  1 bill  staff       382 Aug 21 06:01 index.html
-rw-r--r--  1 bill  staff       191 Aug 21 06:01 main.44e952fb19b12b10eda5f9de01713f33.css
-rw-r--r--  1 bill  staff       461 Aug 21 06:01 main.44e952fb19b12b10eda5f9de01713f33.css.map
-rw-r--r--  1 bill  staff   1363729 Aug 21 06:01 main.9c04012a34c3a12cf78c.js
-rw-r--r--  1 bill  staff  10376685 Aug 21 06:01 main.9c04012a34c3a12cf78c.js.map
```

I have Total.js configured with 2 controllers. One is serving a JSON API behind the route /api/*.  The single-page JS app is being served from another controller like this:

```
exports.install = function () {
  F.route('/', viewApp, true);
};

function viewApp() {
  var self = this;
  self.redirect('/app/index.html', true);
}
```

And the app's config file has this:

```
directory-public    : /static
allow-gzip          : true
```

NOTE: I have tried both allow-gzip true and false, it does not make a difference, I still observe the issue below.

I am sure the main.xxxxx.js bundle is fine, because I can open index.html in both Safari and Chrome. In both cases the size of the served JS file is 1.36 MB as expected. 

However, when loading the page via Total.js (either ```node debug.js``` or ```node release.js```), I observe the following when browsing to the root path:

1. All three files are served (index.html, main.xxx.js and main.xxx.css)
2. The size of the main.xxx.js bundle is incorrect. Rather than 1.36 MB, only about 770 K is served. 
3. The result in the browser is a Javascript syntax / parse error.

When enabling gzip, the response headers as viewed via Chrome dev tools show (as expected):

```
Content-Encoding:gzip
Content-Type:text/javascript; charset=utf-8
```

However, when I view the bundled JS app in the Chorome dev-tools (network response view), select all, then save to a file, the size is around 76 K. Likewise, when I have gzip disabled, the headers are:

```
Content-Length:776299
Content-Type:text/javascript; charset=utf-8
```
So in both cases, it does not seem to be serving the full bundled JS file. Any suggestions? Normally I serve static assets directly from Nginx, but this time I am serving them from behind the Total.js app because I plan on enabling authorization and only serving the UI files when the user has the right permissions. Currently I am only doing authorization on the api controller, which works fine.

Thanks!

**Comment by petersirka** [comment]
Hi @raythree,
can you send me an example with `/static` directory and this configuration? I'll test it.

Thank you!

**Comment by raythree** [comment]
Great thanks, I'm emailing you a link to a ZIP file with a stripped down version (and some notes). This still exhibits the behavior.

Thanks!

**Comment by petersirka** [comment]
I found a problem. Your CSS and JS is re-compressed again via Total.js. You need to disable a compression in `config` and everything will work correctly:

```html
allow-compile-script    : false
allow-compile-style     : false
```

Thank you!

**Comment by raythree** [comment]
Thank you!

**Comment by petersirka** [comment]
Give me a feedback if it won't work 🥇

**Comment by raythree** [comment]
Worked just fine!
