### ISSUE TITLE
documentation update for Mail.send when using office356

### ISSUE THREAD

**Issue by raythree** [totaljs/framework#540]
This is specific to Mail sending via office365, but hopefully it may help someone. Perhaps you could include in the Mail docs.

I was using the ```Mail.send``` as documented. Email was working fine from our Java servers using the same parameters, but I kept getting exceptions. I was sure the user, port, and password were correct.  A lot of googling led me to this:

https://stackoverflow.com/questions/29812132/error-sending-email-using-nodemailer-via-office365-smtp-meanjs-scaffold

So rather than using ```secure: false``` I used ```secureConnection: false```.

This was the mail options that finally worked. Not sure if the tls ciphers is needed or not, I just included it because it was described in the above link.

```
Mail.send('smtp.office365.com', 
  {
    user:'user@company.com', password: 'Secret', 
    secureConnection: false, port:587, tls: { ciphers: 'SSLv3' }}, 
    messages, (err) => {
    .... // err is null when using the params above 
```

**Comment by petersirka** [comment]
Hi @raythree,
__thank you__, but here is some info about it:

<https://docs.totaljs.com/latest/en.html#pages~Troubleshooting~(smtp-settings-for-gmail-office-and-zoho)>

BTW: `ciphers` is needed

**Comment by raythree** [comment]
Ah, thank you I missed that. So it seems "secure" is fine, not needed "secureConection", but the tls property is what I was missing?

**Comment by petersirka** [comment]
I didn't find any info about `secureConnection` in Node.js documetantion in `TLS`. `secure` is a switcher only: https://github.com/totaljs/framework/blob/master/mail.js#L465
