### ISSUE TITLE
RESTBuilder.prototype.file is defined twice in builders.js

### ISSUE THREAD

**Issue by frunjik** [totaljs/framework#541]
Two different versions of the function are defined,
one with buffer parameter and one without (I think the first one is the one wanted?)

**Comment by petersirka** [comment]
Hi @frunjik,
yes, but there are 3 features:

- `buffer` as `Buffer` e.g.:

```javascript
builder.file('file', 'logo.png', Fs.readFileSync('logo.png'));
```

- without `buffer` e.g.:

```javascript
builder.file('file', '/absolute/path/to/logo.png');
```

- `buffer` as `String` e.g.:

```javascript
builder.file('file', '/absolute/path/somefile.bin', 'logo.png');
```
Do you understand?

**Comment by frunjik** [comment]
Yes, but arent all three usages served by the first function definition ?
I think the second definition overwrites the first ?
Maybe im missing something...
I havent tested anything - I just happened to see it ...

2017-09-04 21:10 GMT+02:00 Peter Širka <notifications@github.com>:

**Comment by petersirka** [comment]
The method offers 3 possibilities, so you can choose the right one.

**Comment by petersirka** [comment]
Sorry ... I understand now, you're right. New version of Total.js (tomorrow) will have the only one declaration of `.file()` method.

Thank you!
