### ISSUE TITLE
.tpmignore

### ISSUE THREAD

**Issue by adrianrey05** [totaljs/framework#543]
Hi!
how can I add a folder inside .tpmignore?
it's possible?

thanks!

**Comment by adrianrey05** [comment]
in the file .tpmigore i have 
```terminal
node_modules
other_folder
foo
```
the function for read this file, tpm line 178
```js
skip = skip.concat(Fs.readFileSync(ignore[i]).toString('utf8').split('\n'));
```
but this return array ["node_modules\r", "other_folder\r", "foo\r"]
i add \r to split, like this
```js
skip = skip.concat(Fs.readFileSync(ignore[i]).toString('utf8').split('\r\n'));
```
this return a array ["node_modules", "other_folder", "foo"] and yes ignore the folder

**Comment by petersirka** [comment]
Hi,
you need to convert `newlines` to `unix` style --> `\n` only without `\r`. Total.js uses this parsing for all files e.g. `sitemap`, `workflows`, `resources`, etc..

**Comment by adrianrey05** [comment]
Hi, 
perfect, worked! sorry did not know!
Thanks!
