### ISSUE TITLE
upstream prematurely closed connection while reading upstream behind nginx proxy

### ISSUE THREAD

**Issue by ckpiggy** [totaljs/framework#544]
I've setup a nginx server as reverse proxy for my website.
When I test facebook share debuger I got the logs from nginx proxy
```
upstream prematurely closed connection while reading upstream, 
client: xxx.xxx.xx.xxx, server: XXXX.com. , 
request: "GET / HTTP/1.1", upstream: "http://xxx.xx.xx.xx:80/", host: "XXXX.com."

GET / HTTP/1.1" 206 70489 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)
```
The request headers:
```
{ host: 'archspace.com.tw',
  'x-real-ip': '173.252.90.87',
  'x-forwarded-for': '173.252.90.87',
  'x-forwarded-proto': 'https',
  connection: 'close',
  'user-agent': 'facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)',
  accept: '*/*',
  'accept-encoding': 'deflate, gzip',
  range: 'bytes=0-524287' }
```
It seems that the upstream close connection before all the data send.
What should I config to let the server not to close the connection ?

**Comment by petersirka** [comment]
I think that you have a problem with `timeout`. Can you show me a part where do you create a request?

**Comment by ckpiggy** [comment]
I use https://developers.facebook.com/tools/debug/sharing/ to test my domain https://archspace.com.tw/ 
and this is my nginx.conf
```
worker_processes auto;
events {
  worker_connections 1024;
}

http {
  sendfile on;

  upstream archspace.chatbot.com{
    server chatbot:80;
  }

  upstream archspace.index.com {
    server index:80;
    keepalive 20;
  }

  server {
    listen 443 ssl http2;
    listen [::]:443 default_server ipv6only=on http2;
    server_name archspace.com.tw;

    ssl_certificate       /etc/nginx/ssl/cert_chain.crt;
    ssl_certificate_key   /etc/nginx/ssl/archspace.com.tw.key;

    ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers on;

    location / {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_pass http://archspace.index.com;
      proxy_read_timeout       90;
    }

    location /chatbot/ {
      rewrite ^/chatbot/(.*)$ /$1 break;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_pass http://archspace.chatbot.com;
      proxy_read_timeout       90;
    }
  }
}
```

**Comment by petersirka** [comment]
Hmm, really I don't know where can be a problem. You need to debug it step-by-step. I can help you within support but as I wrote, I don't know where can be the problem and I need to debug it too.

**Comment by ckpiggy** [comment]
Is there any possible total.js will automatic response http 206?

**Comment by petersirka** [comment]
Total.js responds with `206` automatically if the request headers contain `range` key.

**Comment by ckpiggy** [comment]
What if the range is much bigger than the request file ?
facebook 's request header has `range: 'bytes=0-524287'` and my index.html only 46kB.

**Comment by ckpiggy** [comment]
I remove the 'range' in fb requests header... then it works!!!
```
this.req.headers.range && delete this.req.headers.range
```

**Comment by petersirka** [comment]
Can I see a part of Total.js code where do you use request/response?

**Comment by ckpiggy** [comment]
```
exports.install = function () {
  F.route('/', index)
}

function index () {
  this.req.headers.range && delete this.req.headers.range
  this.file('index.html')
}

```

**Comment by petersirka** [comment]
I'll test it today.

**Comment by petersirka** [comment]
Hi @ckpiggy, I don't know why Facebook uses `range  header with value`bytes=0-524287`, from where is this value? Because an initial value for `range` header hast to be `bytes=0-` because the request doesn't know the file size. So therefore my question.

**Comment by ckpiggy** [comment]
I use Postman test my site locally. I made a get request with headers
I only add `Range` `bytes=0-` in Postman header
```
{ host: 'localhost:8000',
  connection: 'keep-alive',
  'cache-control': 'no-cache',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36',
  'postman-token': 'b8b23118-2df4-b693-40ac-0d706da41508',
  accept: '*/*',
  'accept-encoding': 'gzip, deflate, br',
  'accept-language': 'en-US,en;q=0.8,zh-TW;q=0.6,zh;q=0.4,zh-CN;q=0.2',
  range: 'bytes=0-' }
```
And I got error like this:
![2017-09-13 5 31 48](https://user-images.githubusercontent.com/6531171/30370218-8448729a-98a9-11e7-905b-8ea1728379e7.png)

But as I remove the header `Range` `bytes=0-` it works fine.

**Comment by ckpiggy** [comment]
I created an empty project to test the problem with Postman
controllers/default.js
```
exports.install = function () {
  F.route('/', test)
}

function test () {
  console.log(this.req.headers)
  this.file('index.html')
}
```
public/index.html
```
<!DOCTYPE html>
<html>
    <h1>Hello</h1>
</html>
```
/index.js
```
require('total.js')
F.http('debug')
```
I still got error the same error if I set `Range` `bytes=0-` in header.

**Comment by petersirka** [comment]
I have tested it in Paw app and everything works correctly. I'll try to install postman.

**Comment by petersirka** [comment]
I have tested it in postman and postman has a bug (I think) :-D ...

**Comment by ckpiggy** [comment]
It seems facebook use the range bytes=0-524287 to scrap all the website shared on it. 
It works fine when I test `curl -H "Range: bytes=0-524287" -v https://www.totaljs.com/` and ` curl -H "Range: bytes=0-524287" -v https://www.youtube.com/`
But when I test my localhost with `curl -H "Range: bytes=0-524287" http://localhost:8000` the process hanging, I have to press `ctrl-c` to close the process.

**Comment by petersirka** [comment]
I know now... I have fixed it...  Try to download this source-code: https://github.com/totaljs/framework/tree/v2.8.1 and try to test it again.

**Comment by ckpiggy** [comment]
Cool! It works now, thank you!
