### ISSUE TITLE
Dependency injection for 'http' module

### ISSUE THREAD

**Issue by ckpiggy** [totaljs/framework#546]
I saw a framework benchmark in https://github.com/hbakhtiyor/node-frameworks-benchmark, the result is interesting. For example: 

## **Simple HTTP benchmark results (wrk) with close connection**
```
20220.47 Requests/sec - ukoa.js
13594.83 Requests/sec - ufeathers.js
12812.89 Requests/sec - uexpress.js
4204.16 Requests/sec - total/total.js
3043.56 Requests/sec - rawnode.js
2365.02 Requests/sec - feathers.js
2242.12 Requests/sec - koa.js
1784.28 Requests/sec - micro.js
1698.33 Requests/sec - express.js
1443.69 Requests/sec - restify.js
512.29 Requests/sec - hapi.js
158.26 Requests/sec - uws.js
``` 
Total.js is good. 

### **But what is ukoa.js?** 
I found 'u'kao.js stand for [uwebsocket](https://github.com/uNetworking/uWebSockets) with kao.js. uwebsocket has its own 'http' module, and the same interface like native nodejs.

Maybe we can accept an optional argument in F.http method.
```
F.http(mode, option, middleware, http)
```
If user provide a http module, we can use it or we use native node http module.
If you think it is OK. I am glad to send a PR for this issue.

**Comment by petersirka** [comment]
I saw this tests 4-6 months ago and I have updated framework for these needs. __But__ the big problem: __uwebsocket__ can't process POST/PUT/DELETE data and therefore I didn't continue to create something like `utotal`.

__Good news:__ Therefore I added `+v2.6.0` a new method `F.custom(mode, http, request, response, options)` just for similar cases.  It's not problem to create own HTTP module in pure `C` for the performance.

__Thank you!__ 👍

**Comment by ckpiggy** [comment]
Cool!
