### ISSUE TITLE
How to set another ErrorBuilder transformation for Validation

### ISSUE THREAD

**Issue by stakost** [totaljs/framework#547]
Hi!

Could you explain, how can I set new ErrorBuilder for schema validation?
I used schemas for routes like that example, but I need to change errors format

https://docs.totaljs.com/latest/en.html#pages~Validation

**Comment by stakost** [comment]
In documentation you wrote about it "As default are errors in ErrorBuilder serialized into the JSON like Object Array. You can rewrite this transformations via ErrorBuilder.addTransform() and ErrorBuilder.setTransform().", but I did not find it

**Comment by petersirka** [comment]
Hi, of course. You can find more info here:
<https://docs.totaljs.com/latest/en.html#api~ErrorBuilder~ErrorBuilder.addTransform>

```javascript
ErrorBuilder.addTransform('custom', function(isResponse) {
    var builder = [];

    for (var i = 0, length = this.items.length; i < length; i++) {
        var err = this.items[i];
        // err.name
        // err.error
        // err.path
        // err.index
        builder.push(err.error);
    }

    // isResponse: the output needs to be String because it will be returned in RESPONSE
    // If you want return e.g. XML, then set: builder.setContentTyp('text/xml');
    // If you want change a HTTP status, then set: builder.status = 400;
    return isResponse ? builder.join(';') : builder; 
});
```

**Comment by stakost** [comment]
Yes, I saw that. How can I use 'custom' transform for some Schemes?

**Comment by petersirka** [comment]
Good question.

- you need to call setTransform manually in the schema: `error.setTransform('mytransform');`
- or try to use `schema.setError(function(...) {})`

I'll think about better solution If it won't be enough.

**Comment by stakost** [comment]
I tried to set error.setTransform and try schema.setError, but didn't work for me :(

Now I use bad solution via ErrorBuilder.addTransform('custom', fn, true) (set transform by default)

**Comment by stakost** [comment]
> you need to call setTransform manually in the schema: error.setTransform('mytransform');
I no have access to error variable :(

**Comment by petersirka** [comment]
Then try to use `schema.setError(function(...) {})`

**Comment by stakost** [comment]
Great! Thats works! Thanks!
`
    schema.setError((error) => {
        error.setTransform('custom')
    })
`
