### ISSUE TITLE
Problem with new MODEL

### ISSUE THREAD

**Issue by maxxam11** [totaljs/framework#554]
Hello.
I update totaljs to last version and there was a new error when create new model: 

```
var model = new MODEL('test').model();

error:
500: Internal Server ErrorTypeError: (name) => F.model(name) is not a constructor
```

Model code:

```
var mongoose = require('mongoose');

var schema = mongoose.Schema({ 
    id: Number,
    name: String,
});

var model = mongoose.model('tests', schema);

exports.model = model;
exports.name = 'test';
```

In previous version there is not this error.

**Comment by petersirka** [comment]
Hi @maxxam11,
hmmm, there is arrow function and with `MODEL()` it doesn't work but with `F.model()` it works. Which version of Total.js was your previous?

**Comment by petersirka** [comment]
Can you test Total.js beta? Try: `npm install total.js@beta` --> it's stable.

**Comment by maxxam11** [comment]
It's work without `new`: `var model = MODEL('test').model();`
Thanks. I will test with beta.
