### ISSUE TITLE
throw4xx problem description

### ISSUE THREAD

**Issue by ckpiggy** [totaljs/framework#555]
I got 2 problem

1. When I use `controller.throw400(' a test error')`, the response is ` 400: Bad Requesta test error`. Should it be `400: Bad Request a test error` ?  (I am not sure if you need to add a space to append the problem description, since we can add the space when we input the description :-) )

2. When I use `controller.res.throw400('a test error')`, I got only `400: Bad Request` response. The problem description is missing.

**Comment by luoage** [comment]
you should use router with #404 in the first arguments

`F.route('#404', cb)`

**Comment by luoage** [comment]
And if you want rewrite throw404 method, you should change the prototype `Controller.prototype.throw404`

**Comment by ckpiggy** [comment]
@luoage thx for reply. But I don't want to rewrite throw404 method. What I want to address are
1. Maybe we could add a space in front of the problem message in response body
2. The behavior are different between `controller.throw400` and `controller.res.throw400`, `controller.res.throw400` wont send problem message with response.

**Comment by petersirka** [comment]
@ckpiggy there is a bug. I have fixed it + I have published a new beta version `$ npm install total.js@beta` (stable).

@luoage thank you!

**Comment by ckpiggy** [comment]
Wow so fast!
 I was trying to send a PR. 
Thank you @petersirka !

**Comment by petersirka** [comment]
Thank you!
