### ISSUE TITLE
post body size limitation

### ISSUE THREAD

**Issue by DarkKnight1992** [totaljs/framework#561]
How i can increase the post body size  ?

**Comment by molda** [comment]
There's a config https://docs.totaljs.com/latest/en.html#api~FrameworkConfiguration~default-request-length

**Comment by petersirka** [comment]
Or directly in the route:
<https://docs.totaljs.com/latest/en.html#api~Framework~F.route>

```javascript
F.route('/relative/', action, 512); // 512 kB
F.route('/relative/', action, ['flag1', 'flag2'], 1024); // 1024 kB
```

**Comment by petersirka** [comment]
@DarkKnight1992 I found bug in the latest version with a body length --> received `bytes` are not converted to `kB` for classic requests with except `multipart/form-data`. Next week will be a new version with this fix.

**Comment by DarkKnight1992** [comment]
@petersirka and @molda thanks guys
