### ISSUE TITLE
How to work with angular template in totaljs

### ISSUE THREAD

**Issue by mahdi-gh1373** [totaljs/framework#563]
Hi @petersirka 
I have a angular admin template an I want to use it with totaljs.
I put my files in public folder but I get a lot of error in my browser.
in my browser I write 

> http://localhost:8000/src/index.html#/app/Missions

`bootstrap.js:1 Uncaught SyntaxError: Unexpected token if

angular-sanitize.js:1 Uncaught SyntaxError: Invalid or unexpected token

angular-ui-router.js:1 Uncaught SyntaxError: Invalid regular expression flags

ocLazyLoad.js:1 Uncaught SyntaxError: Unexpected token var

main.js:1 Uncaught SyntaxError: Unexpected token if

ui-load.js:1 Uncaught SyntaxError: Unexpected token this

angular.js:1 Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module ngSanitize due to:
Error: [$injector:nomod] Module 'ngSanitize' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.8/$injector/nomod?p0=ngSanitize`

these errors are from my index.html file which is in 

> /public/src/index.html

What should i do for that?

**Comment by petersirka** [comment]
Hi @mahdi-gh1373,

- you need to disable compilation of JavaScript via `allow-compile-script    : false` in `config`
- or rename all scripts to e.g. `bootstrap.min.js`, `angular-sanitize.min.js` because `.min.` are not compiled again

Thank you.

**Comment by mahdi-gh1373** [comment]
@petersirka Thank you very much

>  allow-compile-script : false solve my problem.
