### ISSUE TITLE
How to set schema in rest builder in totaljs

### ISSUE THREAD

**Issue by mahdi-gh1373** [totaljs/framework#564]
Hi @petersirka
I have rest service with response like this : 
`{"total_rows":69,"rows":[
{"id":"Service_3a287fd1-f80a-4624-9862-28409681dae0","key":["service"],"value":{"id":"Service_3a287fd1-f80a-4624-9862-28409681dae0","TimeStamp":"2017-09-26T14:06:54.894Z","Title":"NFC"}},
{"id":"Service_4c92371e-a642-4c1e-b59a-ed77f4dd7d7f","key":["service"],"value":{"id":"Service_4c92371e-a642-4c1e-b59a-ed77f4dd7d7f","TimeStamp":"2017-09-26T14:06:54.894Z","Title":"Wifi"}},
{"id":"Service_5d98aea5-7065-42c6-855e-2069faa9ef93","key":["service"],"value":{"id":"Service_5d98aea5-7065-42c6-855e-2069faa9ef93","TimeStamp":"2017-09-26T14:06:54.894Z","Title":"GPS"}}
]
}`

The real response is in `value` property of response . I have a rest builder like this :

`     RESTBuilder.make(function (builder) {
      builder.url('http://example.com/_design/dev_customerId/_view/customerId?
      connection_timeout=60000&inclusive_end=true&key=%5B+%22' + customerId + '%22,+%22' + 
      docType + '%22+%5D&limit=6&skip=0&stale=false');

        builder.get();

        //builder.schema('Service');

        builder.exec(function (err, response) {

            console.log("Error: " + err);
            var data = [];
            for (var i = 0; i < response.rows.length; i++) {

                data.push(response.rows[i].value)
            }
            self.json(data, true);

        });
    });`

I have a array of json model (I call it `service`) in value property of response which I should write a for loop for returning that but I can't use schema for that because if I uncomment the `//builder.schema('service');`
I have e error :
` Cannot read property 'length' of undefined`
What should I do if I want to use schema features like validation for my rest builder that?

Thank you.

**Comment by petersirka** [comment]
Can I see you schema declaration?

**Comment by mahdi-gh1373** [comment]
```
const Fs = require('fs');

NEWSCHEMA('Service').make(function(schema) {
    schema.define('id', 'String(40)');
    schema.define('Title', 'String(30)');
    schema.define('TimeStamp', Date);
    schema.define('docType', 'String(40)');        
});
```
I don't write any validation yet because I can't use schema for that response.

**Comment by petersirka** [comment]
Yes, there is a problem. Because the schema is created from the whole response, not from `rows` only.

You need to update your schema:

```javascript
NEWSCHEMA('ServiceRow').make(function(schema) {
    schema.define('id', 'String(40)');
    schema.define('Title', 'String(30)');
    schema.define('TimeStamp', Date);
    schema.define('docType', 'String(40)');
});

NEWSCHEMA('Service').make(function(schema) {
    schema.define('rows', '[ServiceRow]');
});
```

and now it should work:

```javascript
    builder.schema('service');
    builder.exec(function (err, response) {
          console.log(response.rows);
          // each item should be ServiceRow
    });
```

**Comment by mahdi-gh1373** [comment]
Actually I  my real reponse is in `value` property of each `rows` .
Now the response is like this 
```
[
    {
        "id": "Service_3a287fd1-f80a-4624-9862-28409681dae0",
        "key": [
            "service"
        ],
        "value": {
            "id": "Service_3a287fd1-f80a-4624-9862-28409681dae0",
            "TimeStamp": "2017-09-26T14:06:54.894Z",
            "Title": "NFC"
        }
    },
    {
        "id": "Service_4c92371e-a642-4c1e-b59a-ed77f4dd7d7f",
        "key": [
            "service"
        ],
        "value": {
            "id": "Service_4c92371e-a642-4c1e-b59a-ed77f4dd7d7f",
            "TimeStamp": "2017-09-26T14:06:54.894Z",
            "Title": "Wifi"
        }
    },
    {
        "id": "Service_5d98aea5-7065-42c6-855e-2069faa9ef93",
        "key": [
            "service"
        ],
        "value": {
            "id": "Service_5d98aea5-7065-42c6-855e-2069faa9ef93",
            "TimeStamp": "2017-09-26T14:06:54.894Z",
            "Title": "GPS"
        }
    }
]
```
But the `value` is my real schema data,
So I change schema to :
```
`NEWSCHEMA('ServiceValue').make(function (schema) {
    schema.define('id', 'String(40)');
    schema.define('Title', 'String(30)');
    schema.define('TimeStamp', Date);
    schema.define('docType', 'String(40)');
});

NEWSCHEMA('ServiceRow').make(function (schema) {
    schema.define('value', '[ServiceValue]');
});

NEWSCHEMA('Service').make(function (schema) {
    schema.define('rows', '[ServiceRow]');
});`
```

and in ctrl:
```
        builder.schema('service');
        builder.exec(function (err, response) {
            console.log(response.rows.value);
            // each item should be ServiceRow
        });
```
But it doesn't work.

**Comment by petersirka** [comment]
Can you send me a small example on my email?

**Comment by mahdi-gh1373** [comment]
Sorry beacuse of this delay I'm working on my web service until I can send example.

**Comment by petersirka** [comment]
No problem.

**Comment by mahdi-gh1373** [comment]
another issues ,
I have a angular template in public folder which it has its controllers , services , ....
I see angular examples in totaljs . all of them are in app folder which they have their controller, templates , ...
If I understand well from angularjs-nedb-rest-resources example after define our routes in controller, we should create app folder and define app module inapp.js, after that we should define factory in app/resources for our model Which is in line with the routes we have defined in controller and finally in app/controllers we use that factory to define our functions.
But ng-app='app' and ng-controller='userCtrl' are define in views/app.html & layout.html but I don't use views in my project an I want to use them in my angular template .
What i should i do now?
I do not know if I could get it or not? But I want to use my routes as a service in my template.

Thank you.

**Comment by mahdi-gh1373** [comment]
[example-schema.zip](https://github.com/totaljs/framework/files/1385356/example-schema.zip)
Hi peter this is my example and I send you some information to use that.

Thank you

**Comment by petersirka** [comment]
Something new?

**Comment by mahdi-gh1373** [comment]
I sent an email to you about my problem.

**Comment by mahdi-gh1373** [comment]
Hi Peter
First of all thanks for your helps :)

If you call my webservice (I sent its address to your email)
You will see the result like this :

{"total_rows":3,"rows":[

{"id":"Service_3a287fd1-f80a-4624-9862-28409681dae0",
"key":["service"],
"value":{"id":"Service_3a287fd1-f80a-4624-9862-28409681dae0","TimeStamp":"2017-09-26T14:06:54.894Z","Title":"NFC"}},

{"id":"Service_4c92371e-a642-4c1e-b59a-ed77f4dd7d7f",
"key":["service"],
"value":{"id":"Service_4c92371e-a642-4c1e-b59a-ed77f4dd7d7f","TimeStamp":"2017-09-26T14:06:54.894Z","Title":"Wifi"}},

{"id":"Service_5d98aea5-7065-42c6-855e-2069faa9ef93",
"key":["service"],
"value":{"id":"Service_5d98aea5-7065-42c6-855e-2069faa9ef93","TimeStamp":"2017-09-26T14:06:54.894Z","Title":"GPS"}}
]
}

here in rows property I have some document, each document has id,key
and value property ,inside each value property is another
document(this is my real document) which has id,TimeStamp,Title,and
some of time docType .

this schema is looking for id,Title,TimeStamp,docType inside rows
document but rows doc has id,key,value so it should look for them
inside value property.


NEWSCHEMA('ServiceRow').make(function (schema) {
    schema.define('id', 'String(100)');
    schema.define('Title', 'String(30)');
    schema.define('TimeStamp', Date);
    schema.define('docType', 'String(40)');

    schema.setSave(function ($) {
        console.log("id :" + $.model.id + " Title :" + $.model.Title);
        $.callback(SUCCESS(true));
    });

});

NEWSCHEMA('Service').make(function (schema) {
    schema.define('rows', '[ServiceRow]');
});

this schema is looking for Title,TimeStamp,id,docType  in rows
property but it should look for that inside value property
and because of that it doesn't recognize my Title and TimeStamp in response :


Output in web browser:
 [
    {
        "id": "Service_3a287fd1-f80a-4624-9862-28409681",
        "Title": "",
        "TimeStamp": null,
        "docType": ""
    },
    {
        "id": "Service_4c92371e-a642-4c1e-b59a-ed77f4dd",
        "Title": "",
        "TimeStamp": null,
        "docType": ""
    },
    {
        "id": "Service_5d98aea5-7065-42c6-855e-2069faa9",
        "Title": "",
        "TimeStamp": null,
        "docType": ""
    }
]

I guess maybe my schema should be somthing like this :

NEWSCHEMA('ServiceValue').make(function (schema) {
    schema.define('id', 'String(50)');
    schema.define('Title', 'String(30)');
    schema.define('TimeStamp', Date);
    schema.define('docType', 'String(40)');
});

NEWSCHEMA('ServiceRow').make(function (schema) {
    schema.define('value', '[ServiceValue]');
});

NEWSCHEMA('Service').make(function (schema) {
    schema.define('rows', '[ServiceRow]');
});

But I don't know why it doesn't work


Thank you.

**Comment by petersirka** [comment]
Sorry for delay. This is solution:

```javascript
NEWSCHEMA('ServiceRowValue').make(function(schema) {
    schema.define('id', 'String');
    schema.define('TimeStamp', 'Date');
    schema.define('Title', 'String');
});

NEWSCHEMA('ServiceRow').make(function (schema) {
   schema.define('id', 'String(40)');
   schema.define('key', '[String]');

   schema.define('value', 'ServiceRowValue');
   // Or just use Object:
   // schema.define('value', 'Object');

   schema.setSave(function($) {
    console.log($.model);
    $.callback(SUCCESS(true));
   });
});

NEWSCHEMA('Service').make(function (schema) {
   schema.define('rows', '[ServiceRow]');
});
```

**Comment by mahdi-gh1373** [comment]
Thank you it's working now .
You are the best :-)
