### ISSUE TITLE
images with .jpeg gives 404: Not Found error 

### ISSUE THREAD

**Issue by DarkKnight1992** [totaljs/framework#566]
Getting an error trying to get jpeg images. Since we are converting the image from base64 but even if we hardcode this to be .jpg instead of .jpeg will cause further problems if users upload jpeg images as well.

I have tested when i change the same file name to jpg i can get the image but .jpeg give 404 all the time

**Comment by petersirka** [comment]
Hi, I don't know how, but `.jpeg` was missing in acceptable list. I have added it. Easy fix for the current version, just edit `config`:

```html
static-accepts-custom        : .jpeg
```

I want to publish a new version of Total.js this week.

**Comment by DarkKnight1992** [comment]
thanks for the quick response.
