### ISSUE TITLE
use resource key in resource file ( localization )

### ISSUE THREAD

**Issue by bkhurram** [totaljs/framework#567]
i have resource file that use variable @{resource ... } but currently does not work.

example: en.resource
`text : Lorem ipsum dolorum. @{resource("en", "label")} Lorem ipsum dolorum.`
`label : LABEL`

home.html 
`@{!resource("en", "text")}`
print:
> Lorem ipsum dolorum. @{resource("en", "label")} Lorem ipsum dolorum.

how can i fix?
with print:

> Lorem ipsum dolorum. LABEL Lorem ipsum dolorum.

**Comment by petersirka** [comment]
Hi @bkhurram, sorry for delay.
This won't work, code evaluation is not supported in `resources` with except `localization`.

https://docs.totaljs.com/latest/en.html#pages~Localization

__For example:__

```html
@(This text will be localized @{resource('en', 'key')} automatically.)
```

And then you need to use translation tools for creating localization:
https://docs.totaljs.com/latest/en.html#pages~Localization~(translation-tools)

__Generated en.resource__:

```html
key               : LABEL
T1301838957       : This text will be localized @{resource('en', 'key')} automatically.
```

__Output:__

```html
This text will be localized LABEL automatically.
```

**Comment by bkhurram** [comment]
thanks,
For Localization it's possible to set multiple file of resource for language?
for language **en** use this file: [ "en", "home-en", "contact-en" ]

now for set language i use:
```
F.onLocale = function(req) {
	var locale = "it";
	if( /^\/uk\//gmi.test( req.uri.pathname ) )
		locale = 'uk';
	else if( /^\/en\//gmi.test( req.uri.pathname ) )
		locale = 'en';

	F.log( "LOCALE ==>>"  + locale );

	F.global.locale = locale;
	return locale;
};
```
in template:
```
@(#key)
@(#keyHome)
@(#keyContact)
```
in Resource file:
```
en.resource
keyEN : label EN work

home-en.resource
keyHome : Home Page not work

contact-en.resource
keyContact : Contact Page not work
```

**Comment by petersirka** [comment]
This is not possible.

**Comment by petersirka** [comment]
Or it's possible but you need to return a `resource` name according `URL` in the `F. onLocale` delegate.

**Comment by bkhurram** [comment]
i did not understand, can you explane it better?

**Comment by petersirka** [comment]
```javascript
F.onLocale = function(req) {
    if (req.url === '/')
        return 'home-en';
    if (req.url === '/contact/')
        return 'contact-en';
   return 'en';
};
```

**Comment by bkhurram** [comment]
Thanks you very much for the answer, but that's not what i wanted.
you think this will be implemented in the future?

**Comment by petersirka** [comment]
I understand, but I don't have any plan for it. I recommend to use one resource for one localization.

**Comment by bkhurram** [comment]
what do you think about this code?

to read all the resources that contain the locale that start or end with the language setted in F.onLocale

> example
> \*\*\*\*-en.resource
> en-****.resource

```
/**
 * Translates text
 * @param {String} language A resource filename, optional.
 * @param {String} text
 * @return {String}
 */
F.translate = function(language, text) {

	var value;
	var resources = Object.keys(F.resources);

	if (!text) {
		text = language;
		language = undefined;
	}

	if ( language !== undefined ) {
		for( var i = 0; i < resources.length; i++ ) {

			var resourceName = resources[i];
			if ( resourceName.match( new RegExp("^" + language + "-.*$|^.*-" + language + "$|^" + language + "$", "gi") ) !== null ) {
				if (text[0] === '#' && text[1] !== ' ') {
					value = F.resource(resourceName, text.substring(1));
					if ( value ) {
						return value;
					}
				} else {
					value = F.resource(resourceName, 'T' + text.hash());
					if ( value ) {
						return value ? value : text;
					}
				}
			}
		}
	}

	if (text[0] === '#' && text[1] !== ' ')
		return F.resource(language, text.substring(1));

	var value = F.resource(language, 'T' + text.hash());
	return value ? value : text;
};
```

**Comment by petersirka** [comment]
I don't want to add this functionality. BTW: you can create a definition with this code and you have what you want.
