### ISSUE TITLE
Angular.js example

### ISSUE THREAD

**Issue by eMarek** [totaljs/framework#57]
Angular.js example https://github.com/petersirka/partial.js/tree/master/examples/angularjs does not work. Could you please fix it. I think that something is wrong with serving templates. It looks like partial.js wants to serve `js/project.js` with file_template function in `templates.js`.

**Comment by jorgemejia** [comment]
is it possible to implement angular 4 intead angular 2 ?

**Comment by petersirka** [comment]
I'd like, but I don't have any experience with Angular +4. So we need to wait for someone who updates example to Angular +4.
