### ISSUE TITLE
how to customize directories under app ?

### ISSUE THREAD

**Issue by luoage** [totaljs/framework#570]
```
$ tree -L 1
.
├── controllers
├── definitions
├── models
├── services
├── source
└── views
```

I added a directory of services to app. But in debug mode, services is not monitored. Can I customize directories under app ?

**Comment by petersirka** [comment]
Just add `services` here:
<https://github.com/totaljs/framework/blob/master/helpers/debug.js#L14>

**Comment by luoage** [comment]
Thx.
