### ISSUE TITLE
config static-url with absolute link

### ISSUE THREAD

**Issue by bkhurram** [totaljs/framework#571]
hii,

when i use **@{routeStatic('it/pub/js/script.js')}** with config= **static-url: https://images.domain.com** i will get = **ttps://images.domain/it/pub/js/script.js**

it's possible to use an absolute link for use an different images server?

Thanks,
Khurram

**Comment by petersirka** [comment]
Try use this example: [empty-project.zip](https://github.com/totaljs/framework/files/1414358/empty-project.zip)
It works, can you send me your example?

**Comment by bkhurram** [comment]
![capture](https://user-images.githubusercontent.com/2213964/32001924-751ae9b6-b99b-11e7-972f-8e6bde8c5cbc.JPG)

**Comment by petersirka** [comment]
Shit, there is a problem in Windows. It works on my Mac. I'm going to fix it.

**Comment by petersirka** [comment]
Please try to install latest beta version `$ npm install total.js@beta` and give me a feedback. Thank you!

**Comment by bkhurram** [comment]
now works!

Thanks for fix.
