### ISSUE TITLE
RESOURCE does not work properly

### ISSUE THREAD

**Issue by bkhurram** [totaljs/framework#572]
Hii,
RESOURCE not found key when key is uppercase:

`@{RESOURCE( "res-file", "key.UpperCase" )}` NOT WORK
`@{RESOURCE( "res-file", "key.uppercase" )}` WORK

res-file
```
key.UpperCase : KEY UpperCase FOUND
key.uppercase : KEY lower case FOUND
```
and when i use command **!RESOURCE** i have an error **self.RESOURCE is not a function** 

this error i have fix in this way:

from:
```
		case '!resource':
		case '!RESOURCE':
			return '$STRING(self.' + command.substring(1) + ')';
```
to:
```
		case '!resource':
			return '$STRING(self.' + command.substring(1) + ')';
		case '!RESOURCE':
			return '$STRING(self.' + command.substring(1).toLowerCase() + ')'; 
```

**Comment by petersirka** [comment]
Hi,
of course, it's `case-sensitive` as `configuration` too. My rule: use everytime lower-case chars.

**Comment by bkhurram** [comment]
see this:
```
@{resource( "res-file", "key.UpperCase" )} WORK
@{RESOURCE( "res-file", "key.UpperCase" )} WHY THIS NOT WORK and previous line work

@{!RESOURCE( "res-file", "key.UpperCase" )} give me an exception  "Error: View "/it/home/index": !RESOURCE( "res-file", "key.UpperCase") - Line: 10 - self.RESOURCE is not a function"
```

res-file
`key.UpperCase : KEY UpperCase FOUND`

**Comment by petersirka** [comment]
OMG, you're right. 100x sorry, my mistake.
I have fixed it, try `$ npm install total.js@beta`.

**Comment by bkhurram** [comment]
now it's not work @{!resource( "res-file", "key.UpperCase" )} 

```
		case '!resource':
			return '$STRING(self.' + command + ')';
```
i think you forget to add **.substring(1)**

this code work:
```
		case '!resource':
			return '$STRING(self.' + command.substring(1) + ')';
```

**Comment by petersirka** [comment]
OMG! I'm fucker. Thank you again. Please reinstall beta again.

**Comment by bkhurram** [comment]
It works well.

**Comment by petersirka** [comment]
Great! Thank you again!

**Comment by bkhurram** [comment]
**Thank you very much for the quick fix**
