### ISSUE TITLE
use Localization in resource file

### ISSUE THREAD

**Issue by bkhurram** [totaljs/framework#575]
HI,
Currently, localization does not work within another location

example
**page.html**
```
...
@(#label.one)<br/>
@(#label.two)<br/>
@(#label.tree)<br/>
...
```
**en.resource**
```
label.one : LABEL 1 @(#label.two)
label.two : LABEL 2 @(#label.tree)
label.tree : LABEL 3
```

**output:**
```
LABEL 1 @(#label.two)
LABEL 2 @(#label.tree)
LABEL 3
```

**i want my output as:**
```
LABEL 1 LABEL 2 LABEL 3
LABEL 2 LABEL 3
LABEL 3
```

is there a way to use it?

Thanks,
Khurram

**Comment by petersirka** [comment]
Hi @bkhurram, this is not possible. Resource can't contain a reference to another resource.

**Comment by bkhurram** [comment]
you might consider it an implementation to be done in the future
