### ISSUE TITLE
Typo on documentation

### ISSUE THREAD

**Issue by michalCapo** [totaljs/framework#579]
On `https://docs.totaljs.com/latest/en.html#api~FrameworkConfiguration~directory-controllers`

there is `directory-controllers` defined twice. One should be `directory-databases`. Or?

![image](https://user-images.githubusercontent.com/2294314/32703332-c1089816-c7f4-11e7-8976-83371d431420.png)

**Comment by petersirka** [comment]
Ohh, thank you! You're right. I have fixed it.

https://github.com/totaljs/documentation/commits/master
