### ISSUE TITLE
total.js on AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by raisty** [totaljs/framework#586]
I try install total.js on AWS Elastic Beanstalk.
All was fine till port.
I have always - 502 Bad gateway.
Even port 3000, 8000,... was setup.

My solution:
1. First make sure in package.json is script for starting: 
`"scripts": {
    "start": "node release.js",
    "test": "node debug.js"
  }`

2. In release.js setup port manually:
`options.port = parseInt(process.argv[2]) || 8081;`

I will investigate problem deeper. For now only this solution.

**Comment by petersirka** [comment]
I'll add it into the documentation.
