### ISSUE TITLE
Cluster doesn't work on VS Code

### ISSUE THREAD

**Issue by raisty** [totaljs/framework#587]
I try run cluster on Visual Studio Code on my 💖 Mac.
Cannot start it successfully.

My solution was disable cluster in debug.js:
`require('total.js').http('debug', options);` 

Is there any way to debug total.js even with clusters on VS Code?
PS: I am using VS in case of debugger.

**Comment by petersirka** [comment]
Hi @raisty, can you write me how do you run cluster? You can use preddefined helper:
<https://docs.totaljs.com/latest/en.html#api~FrameworkCluster>

BTW: you can run cluster in debug mode, there is no problem (__important__ it won't work with `require('total.js/debug')`).

**Comment by raisty** [comment]
Try run as follows:
`require('total.js').cluster.http(5, 'release', options);`

Then your mention is correct. I am using require.

**Comment by petersirka** [comment]
And does it work? BTW: you can use `debug` instead of `release`.

**Comment by raisty** [comment]
Thank you, problem solved.
