### ISSUE TITLE
How to use the option in schema?

### ISSUE THREAD

**Issue by twisig** [totaljs/framework#588]
Hi
I generate a model in designer. When I call my controller i have an issue with option.
Option is not defined !
Do you have an example how to use the option in the model ?

**Comment by petersirka** [comment]
Hi @twisig, can you show me your model?

**Comment by twisig** [comment]
Sorry Peter for the delay.
You can generate a simple table in Total.js Désigner and you can see the parameter ´Option’.
How to use that ?
