### ISSUE TITLE
Package config not work

### ISSUE THREAD

**Issue by ckpiggy** [totaljs/framework#590]
I try to create my MongHelper package (https://github.com/ckpiggy/totaljs_mongo_helper).

I follow the guide to create package use 
```
tpm creeate MongoHelper
```
and generate MongoHelper.package successfully.

My package need a url to connect to mongodb , so I throw an error if there is no url config.
But after I update the config file, I still got the error.
```
package#MongoHelper (Object): {url: 'mongodb://test.url'}
```
Did I miss something?

**Comment by petersirka** [comment]
Fixed: [totaljs_mongo_helper.zip](https://github.com/totaljs/framework/files/1524542/totaljs_mongo_helper.zip)
