### ISSUE TITLE
Future of Totaljs

### ISSUE THREAD

**Issue by twisig** [totaljs/framework#592]
Peter,

Can you share your vision about the future of Totaljs and your challenges for 2018 ?
What are the next enhancements for the version 3.0 ?

Thank you for your work :)

**Comment by twisig** [comment]
Check this link for the hosting : https://zeit.co/
Big Big program... Good luck

**Comment by twisig** [comment]
Do you integrate some security enhancements for 2018?

**Comment by webdesus** [comment]
Work on security is ongoing always. What kind of integration do you talking?

**Comment by petersirka** [comment]
My question is same.

**Comment by twisig** [comment]
I talk about the Helmet module : https://helmetjs.github.io/ 
Do we have the same security process with Total.js ?

**Comment by webdesus** [comment]
Hard question but i think it's redundancy... better using set header as string. Helmetjs has good docs about problems which might happen. But using their library I would not.

But if you have another oppinion. You can write somethink like this:

```javascript
const nocache = require('nocache')();
const frameguard= require('frameguard')();
F.on('request', function(req, res) { 
    nocache(req, res,()=>{
        frameguard(req, res, ()=>{});
    }); 
});
```
Not tested, but should work.

**Comment by twisig** [comment]
Thank you very much

**Comment by webdesus** [comment]
Some modules helmet so big, and execute very more logic. I would advise to examine helmetjs site and write once own definition file with your headers as strings. Then if you create new project you can copy this file.
You should get somethink like this:

```javascript
F.on('request', function(req, res) { 
    res.setHeader('Surrogate-Control', 'no-store')
    res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate')
    res.setHeader('Pragma', 'no-cache')
    res.setHeader('Expires', '0')
});
```
