### ISSUE TITLE
Standalone Flow and Dashboard?

### ISSUE THREAD

**Issue by davidAlittle** [totaljs/framework#594]
How tightly coupled to TotalJS are Flow/Dashboard/Flowboard? 

Total is an awesome framework, but for existing projects that would like to add Flow/Dashboard, it would be great if they were in a standalone framework, so they could be used without bringing in the rest of the system.

Unless there's a trivial way to do that already that doesn't introduce collisions and overhead?

**Comment by petersirka** [comment]
Hi @davidAlittle,
you can add Flow/Dashboard/Flowboard to your existing project, but they have to be written in Total.js. Total.js is around +70% of everything in all Total.js products. I don't see any problem to create standalone product with Flow/Flowboard/Dashboard and Total.js, the result will same and much simpler.

__Do you have a problem with overhead or do you have some collisions?__

Thank you!

**Comment by davidAlittle** [comment]
re. overhead/collisions: I haven't tried it yet. Right now, I have a project that's built using the Vue ecosystem (Vue, Vuex, vue-router, etc). There's a lot of redundancy between that system and TotalJS, and I don't have permission to port it away from Vue. It will probably be fine? I won't know until I try.

I'll give it a go and find out.  Thanks!

**Comment by petersirka** [comment]
Which framework do you use with VUE on server-side?

**Comment by davidAlittle** [comment]
It's a https://github.com/SimulatedGREG/electron-vue project, with everything enabled (So axios, vue-electron, vue-router, vuex, etc).

We can discuss this in your chat app, if you'd prefer.

**Comment by petersirka** [comment]
It's electron app, hmmm. What do you want to use Flow for? __Otherwise:__ you can run Total.js (Flow+Dashboard) on another port than Node.js server and they will work together without any problem.

**Comment by davidAlittle** [comment]
It's an SPA dashboard for machine control. Flow+Dashboard could be a quick way to let the end user build views that I might not have thought of, or to bring controls and indicators in from a bunch of pages into his own custom page.

I _could_ predefine the flows (since the user wouldn't have access to anything I didn't already have in the UI {though they might want to use some nodes to massage the data}) so they'd only need Dashboard. The nice thing about Flow, though, is you've already done some key IoT stuff, meaning we could let end users do some after market integration without having to support them or write a bunch of custom code to get their I/O into their HMI.

That does sound like the best solution, though I'll have to circle back around to it, as I don't know how running multiple Node instances in Electron works.

Honestly, it would probably simpler to just spin up a second Electron app based on TotalJS and just let the user alt-tab between them than trying to shoehorn them into the same app.

Thanks.

**Comment by petersirka** [comment]
I’m in my bed. You can run Total.js framework in the Electron instance (but you will start Total.js on another port) or you can run a child process with Total.js Flow. There is multiple ways how to do it. You need to find the best way and I’d like to help you. Just write me on Total.js messenger. Thank you!

**Comment by ductran54** [comment]
Hello, I have a TotalJS Flow and Dashboard on a server. I created custom input components in Dashboard and processed the information in Flow and then displayed the computed data in Dashboard. However, if there is a second user running the Dashboard site, they see the same content as the first user. My plan is to have different users to enter their own data on Dashboard and return the respective data on their own dashboard, is there a way which I can run multiple dashboards? Thank you!

**Comment by petersirka** [comment]
Hi @ductran54,
yes, because Flow + Dashboard isn't optimized for multiple users. You have two ways:

- create  a new instance of Flow with Dashboard for each user (new user = new app)
- create a custom solution with help of our existing UI components and FLOWSTREAM

Second way is hard, but you can optimized it for thousands of users.
