### ISSUE TITLE
[Feature Request] http2 support with totaljs

### ISSUE THREAD

**Issue by lyquocnam** [totaljs/framework#595]
this will be faster with http2 support author.

**Comment by petersirka** [comment]
I want to implement it, but `http2()` is experimental in Node.js and I want to wait `stable` state of this module. Therefore I recommend to use a reverse proxy e.g. __Nginx with HTTP2__.

**Comment by ckpiggy** [comment]
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion
This repository is great for integrating nginx proxy and letsencrypt @lyquocnam !!

**Comment by petersirka** [comment]
I'm closing this issue now, but I'll add a support for HTTP2 in the future.

**Comment by buzzeins** [comment]
any devs in that direction?

**Comment by TemaSM** [comment]
+1
Waiting for this feature.
@petersirka what do you think about even implementing automatic LetsEncrypt ACME challanges resolver into totaljs core? That will be killing-feature I think.

**Comment by petersirka** [comment]
It's a plan for `v4`. Currently we have prepared version `3.3.0` and then I want to work on `v4` which will support HTTP2 (I belive).

Alsoe you can use LetsEncrypt with Total.js, just install Total.js SuperAdmin. Anyway for multiple applications you will need to use a reverse proxy for HTTP2 too. There will be a lot of open questions :-D

**Comment by buzzeins** [comment]
thanks pete
