### ISSUE TITLE
How to make totaljs work with PWA ?

### ISSUE THREAD

**Issue by lyquocnam** [totaljs/framework#597]
How to make totaljs work with PWA ?

**Comment by molda** [comment]
Hi @lyquocnam as far as i understand PWA (hope you mean Progressive Web App) there's nothing you need to do on server-side.
I've seen a few examples and there was no server-side code required.

**Comment by lyquocnam** [comment]
i mean how to i can combine totaljs with pwa, i see no boilerplate for this

**Comment by petersirka** [comment]
@lyquocnam just copy all files/components to `public` directory. We don't have capacities for creating examples of each library. Try my advice and let me know.
