### ISSUE TITLE
include file in page lost model in layout

### ISSUE THREAD

**Issue by bkhurram** [totaljs/framework#599]
Hii,
When i include a file in page with submodel parameter **@{view('/test/inc/stripe', model.objtwo)}** then lost other model in layout.
When i include a file in page without model **@{view('/test/inc/stripe')}** then give an exception.

Work only when i include with param **@{view('/test/inc/stripe', model)}**

see this example-project: https://github.com/bkhurram/totaljs-test

http://localhost:8000/test1/
http://localhost:8000/test2/
http://localhost:8000/test3/

Thanks,
Khurram

**Comment by petersirka** [comment]
Hi, `model` is not shared with layout. __You need to use repository.__

![Model vs Repository](https://docs.totaljs.com/latest/resources/viewengine-repository-vs-model.png)

**Comment by bkhurram** [comment]
okay then layout see a model parameter it's wrong.
