### ISSUE TITLE
Email Template with FrameworkMail

### ISSUE THREAD

**Issue by Pourya8366** [totaljs/framework#602]
I send Email according to `email-send` example: [link](https://github.com/totaljs/examples/tree/master/email-send)
which is it seems the latest version but i want to send a html template which after searching i found this example: [link](https://github.com/totaljs/examples/tree/master/controller-mail)
which is you note that: 

> Note This example is based on the 1.9.x versions of total.js - there are some changes to the mail system in v2.0 and above.

and i use version 2.9 so i confused which approach i should use for email templating!

**Comment by petersirka** [comment]
Hi I have fixed readme. Email templating works correctly in Total.js `+2.9`. Docs: <https://docs.totaljs.com/latest/en.html#api~Framework~F.mail>
