### ISSUE TITLE
What is node_modules root Directory in views?

### ISSUE THREAD

**Issue by Pourya8366** [totaljs/framework#604]
Hi!
I install some npm packages and want to use them in views, it's might be a stupid question! but what is the node_modules root directory that i have to write in `src` of `script` element in a view?

**Comment by molda** [comment]
Hi.
**The easiest way** would be to use bellow config to make node_modules folder publicly accessible.

    directory-public-virtual    : '/node_modules/'

Now the src for 

    <app-folder>/node_modules/module_name/index.js

 would be

    /module_name/index.js

**Another way** could be to install modules for front-end into `node_modules` in public directory 

so the src  for 

    <app-folder>/public/node_modules/module_name/index.js

would be 

    /node_modules/module_name/index.js

**Comment by Pourya8366** [comment]
I do the first solution but i get the `net::ERR_ABORTED` Error for loading the js file!

**Comment by petersirka** [comment]
@Pourya8366 can you send me a simple project with the first solution?
