### ISSUE TITLE
Schema delegate argument only ErrorBuilder when use async

### ISSUE THREAD

**Issue by ckpiggy** [totaljs/framework#607]
```
schema.setSave(async function ($) {...}
```
The '$' become ErrorBuilder when add 'async' before delegate function
![2018-01-31 4 22 09](https://user-images.githubusercontent.com/6531171/35612222-ee779382-06a2-11e8-9d3e-91c90172c2e1.png)

**Comment by petersirka** [comment]
Hi @ckpiggy, I have fixed it `$ npm install total.js@beta` ...

**Comment by ckpiggy** [comment]
@petersirka it works!!
