### ISSUE TITLE
set ssl and work with https

### ISSUE THREAD

**Issue by mahdi-gh1373** [totaljs/framework#610]
Hi Peter
I want to work with https and I set my index.js like this :

```
var fs = require('fs');

var options = {};
options.https = {
   pfx: fs.readFileSync('./SSL/TolueAryan.pfx'),
   passphrase: 'mypass'
};
options.port = 8000;

require('total.js').https('release', options);
```

the server is coming up but it does't work!!!what should I do now?

**Comment by petersirka** [comment]
Can you write more info? What does the console read?

**Comment by mahdi-gh1373** [comment]
the console is show this but I can't access to that when I use : https://0.0.0.0:8000/

```
C:\toluebot\totaljs>node index
====================================================
PID         : 1500
Node.js     : v9.4.0
Total.js    : v2.9.2
OS          : win32 6.3.9600
====================================================
Name        : Total.js
Version     : 1.0.0
Author      : You company name
Date        : 2018-02-10 13:24:48
Mode        : release
====================================================

https://0.0.0.0:8000/
```
I need a simple https server .

**Comment by petersirka** [comment]
Ok and what's happend when you open `https://127.0.0.1:8000`?

**Comment by molda** [comment]
On windows you **can't use 0.0.0.0** Windows only supports `localhost` or `127.0.0.1`

**Comment by mahdi-gh1373** [comment]
When I open` https://localhost:8000/` I see that my site isn't secure .

**Comment by petersirka** [comment]
__isn't secure__:
:-) of course because the browser doesn't accept your certificate as trust. Do you have SSL from some trust authority? I think that localhost won't work as trusted ....

**Comment by webdesus** [comment]
@mahdi-gh1373 if you project not working with money, i would be recommend [this](https://www.sslforfree.com/) service. It's free ssl witch working fine in all browsers. For financial projects I would be recommend use paid services

**Comment by lodwig** [comment]
Hi, Peter.

I got same problem here my certificate is trusted it's show when i'am open in browser but when i'am open in PostMan Application with get on same address it's failed.

I am trying to get using cURL on my terminal no issue found. I am using OSX but on cURL with other client using ubuntu it's show error :

curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html
