### ISSUE TITLE
websocket 'Allow'

### ISSUE THREAD

**Issue by ivanlunardi** [totaljs/framework#613]
Hi,
if i set multiple "host" in definition
ex :   F.websocket('/ws/message/{id}', socket_homepage,['json','http://127.0.0.1.xip.io:10001','http://www.google.com]);
this piece of conde : 

if (length) {
		if (allow.indexOf('*') === -1) {
			for (var i = 0; i < length; i++) {
				if (origin.indexOf(allow[i]) === -1)
					return false;
			}
		}
	}

in in WebSocketClient.prototype.prepare
return false every time

Ivan

**Comment by petersirka** [comment]
I'm solving it...

**Comment by petersirka** [comment]
Hi @ivanlunardi,
can you try latest beta version? `$ npm install total.js@beta`

**Comment by ivanlunardi** [comment]
i'm trying

**Comment by ivanlunardi** [comment]
now it works! thanks

**Comment by petersirka** [comment]
Great!

**Comment by petersirka** [comment]
Hi @ivanlunardi,
I have published stable release `2.9.4` with this fix. `$ npm install total.js`
