### ISSUE TITLE
App Designer return schema with 'undefined'

### ISSUE THREAD

**Issue by blaasvaer** [totaljs/framework#618]
I get a file that only contains the word 'undefined' when I install a schema from the App Designer using:

```
tpm install http:// … [random package url].package
```

Is the app broken? Or am I doing something wrong?

**Comment by blaasvaer** [comment]
It seems the tpm module is somehow broken ...

**Comment by molda** [comment]
Hi i just tried it and it works OK for me. Can you share the link to https://designer.totaljs.com/????/ so i can have a look at your schema?

**Comment by blaasvaer** [comment]
Yeah, seems to work now. I think Peter fixed it. Wasn't working, and he was aware of it, so ... I guess he fixed it.
