### ISSUE TITLE
websocket send string encodeing

### ISSUE THREAD

**Issue by ckpiggy** [totaljs/framework#622]
I use websocket to send string `hello jorge` to client (https://www.websocket.org/echo.html),
and the client display `%22hello%20jorge%22`.

It seems the string has been encoded before sending. How can I send original string to client ?

**Comment by petersirka** [comment]
Hi @ckpiggy,
you can disable it easily:
<https://docs.totaljs.com/latest/en.html#api~FrameworkConfiguration~default-websocket-encodedecode>

But you will have a problem with UTF-8 chars.
