### ISSUE TITLE
Different behaviour of method

### ISSUE THREAD

**Issue by miguelavaqrod** [totaljs/framework#629]
Hi,

I realized that controller.binary and Response.prototype.binary do not handle parameters the same way.
I can do:
controller.binary(buffer, contentType, headers)
but not in Response prototype, as I need to specify all params to be able to set headers...
res.binary(buffer, contentType, type, null, headers)

By design?

Thanks!

**Comment by petersirka** [comment]
Hi @miguelavaqrod yes, you're right. I have updated `res.binary()` but I can't publish it as a beta version yet because I have unfinished update for NoSQL :-D.

Tomorrow I'll publish a new beta version into the NPM and I'll give you a feedback!
Thank you!

**Comment by miguelavaqrod** [comment]
Thanks for your quick response Peter!
And... congratulations for that amazing framework!
Looking to be a premium member just for supporting you...

**Comment by petersirka** [comment]
Thank you! I appreciate it.
I have published a new beta version into the NPM, please re-install Total.js:

```bash
$ npm install total.js@beta
```
