### ISSUE TITLE
feature-request: middleware negation flags

### ISSUE THREAD

**Issue by AyushG3112** [totaljs/framework#630]
Hi, 

I have a middleware, say `maintenance-mode-checker`. I want to run this middleware for all my routes, excluding 3 specific ones. Is it possible to introduce negation flags in the system, so that global middlewares can be blocked from executed for specific routes?

For example, maybe I can do

``` javascript
F.route('/some-route',
    handler, // handler
    ['get', 'post', 'cors'], // normal flags
    ['maintenance-mode-checker'] // negation flags - DON'T run these middlewares
);
```

**Comment by petersirka** [comment]
Hi.
I will think about it. Now you can use `GROUP()`:

```javascript
exports.install = function() {
    GROUP(['#middleware', 'authorize'], function() {
        ROUTE('/api/posts/', json_posts, ['put']);
        ROUTE('/api/commnets/', json_posts, ['post']);
    });
}
```

<https://docs.totaljs.com/latest/en.html#api~Framework~F.group>

**Comment by petersirka** [comment]
I thought about it and it would be useless.
Thank you!
