### ISSUE TITLE
Angular has stopped working since 2.9.2

### ISSUE THREAD

**Issue by mmautomatizacion** [totaljs/framework#632]
Hi,
Total.js 2.9.1 has been the last version that work with angular routing. The "angular-routing" example doesn't work with lastest version of Total.js.

**Comment by petersirka** [comment]
Hi @mmautomatizacion,
yes you'right. I have fixed it. Please try to download latest beta version of Total.js `$npm install total.js@beta`.

Thank you!

**Comment by mmautomatizacion** [comment]
Works correctly! Thanks @petersirka

**Comment by petersirka** [comment]
Great! Thanks for the report!
