### ISSUE TITLE
Resource is not working

### ISSUE THREAD

**Issue by ckpiggy** [totaljs/framework#633]
I defined a string in my /resources/en.resource file ex:
`test: the test`
and try to get it by 
`RESOURCE('en', 'test')`
and I got empty string.

![2018-04-29 10 50 06](https://user-images.githubusercontent.com/6531171/39407870-b95ffa2a-4bff-11e8-9e70-98d76dd95afc.png)

I found the framework did got the resource string in 'body' in index.js:7773, but when we trying to parseConfig() in line 7777 we got empty obj.

**Comment by petersirka** [comment]
Can you send me your resource file? Which version of Total.js do you use?

**Comment by ckpiggy** [comment]
I use version 2.9.4

**Comment by petersirka** [comment]
__Can you send me your resource file?__

**Comment by petersirka** [comment]
@ckpiggy you need to add __space__ before `:`.

__Good__:

```html
text : key
key:name : key
```

__Bad__:
```html
text: key
```

In some cases can your keys contains `:` so therefore you need to add min. one space.
@molda thank you for solving this issue.
