### ISSUE TITLE
Delete Flag

### ISSUE THREAD

**Issue by ivanlunardi** [totaljs/framework#634]
In 2.9.4 a can't use 'delete' flag in request , other flags works.

Thank you

es:
exports.install = function () {
    F.route('/prova',prova,['delete'])
};

function prova() {
    var self = this;
    self.json(SUCCESS(true));
}

**Comment by petersirka** [comment]
Hi @ivanlunardi,
which content-type is used in your request? `DELETE` method is same like `POST` or `PUT` method and Total.js expects `application/json` or `application/x-www-form-urlencoded`.

**Comment by ivanlunardi** [comment]
i use $http client of angularjs , if in the same route a change delete in post , it works.
with delete i receive 404 ,now  i will try to force content-type

**Comment by ivanlunardi** [comment]
forcing content-type it works. 
thank you
