### ISSUE TITLE
What is the 'proper' way to disable any 'layout' in views?

### ISSUE THREAD

**Issue by blaasvaer** [totaljs/framework#637]
I'm passing an empty string to layout, but it seems odd to do it this way. Is there any 'proper' way to disable a layout for a view?

```
@{layout('')}
```

**Comment by molda** [comment]
@blaasvaer that is a proper way. It's simple and it works.
What do you think would be a more proper way?

**Comment by petersirka** [comment]
@blaasvaer try this:
<https://docs.totaljs.com/latest/en.html#api~FrameworkConfiguration~default-layout>

**Comment by blaasvaer** [comment]
Thank you for confirming my best guess ; )

And not really sure how to answer that.

But when something happens by default (layout in this case), then to make it *not* use the default, you usually have to *define* it somehow – that's why I figured: if you have to specify *some* other layout than the default one by using a string, you could point to *no* layout using an empty string (but when actually typing it out, I had no idea whether this would throw me an error or not).

But my problem really is, that I don't *know* whether the framework provides a *special feature* or not for this (like `@{no_layout}` or whatever), as it is not specified specifically in the docs.

And that's just more reasons why it feels a lot like guessing when working with totaljs.

Complete documentation usually covers all use cases. But I guess, that's just me.
