### ISSUE TITLE
Configurations Folder

### ISSUE THREAD

**Issue by juniarz** [totaljs/framework#642]
When changing: `directory-configs` in `./config || ./config-debug || ./config-release ||  ./config-test`, the framework still tries to load the default `directory-configs`: `/configs/` folder.

`F.path.configs()` returns `/configs/` in `F.$configure_configs` function.

Causing `Error: EISDIR: illegal operation on a directory` when using `/configs/` folder for other purposes.

v2.9.4

**Comment by petersirka** [comment]
Hi,
yes and the only way how to hande it is to update `debug.js` or `release.js` file:

```javascript
// ===================================================
// FOR DEVELOPMENT
// Total.js - framework for Node.js platform
// https://www.totaljs.com
// ===================================================

const options = {};

// ...
// ...
// ...
options.config = { 'directory-configs': '/config/' };
// ...
// ...
// ...

require('total.js/debug')(options);
```

Configs files are loaded together when the framework is starting...

**Comment by juniarz** [comment]
Hi peter,

I've tried to configure the folder as suggested above, the error still appears.

**Comment by petersirka** [comment]
Please send me your project on my email, I’ll check it.

**Comment by petersirka** [comment]
Can you send me your project?
