### ISSUE TITLE
how does data-jc-bind work?

### ISSUE THREAD

**Issue by Jusys** [totaljs/framework#644]
How does automatic two-way data binding work? 
I have such code:

`<div data-jc="textbox" data-jc-path="forma.Name" data-jc-bind="">Name</div>`
`<button onclick="window.forma.Name='kuku'">Ok</button>`
`<script>`
`  window.forma = {};`
`  window.forma.Name = 'labas';`
`</script>`

On page loading textbox is assigned value 'labas', but when I click Ok - textbox value does not change. When I call `MAIN.update()` - only then value changes. 

Is this a bug or I'm missing something?

3.0.0
jComponent v15

**Comment by petersirka** [comment]
Look here:
<https://jsfiddle.net/petersirka/r0kmhtvw/>

BTW: please use Total.js messenger for future questions: <https://messenger.totaljs.com> or my channel <https://messenger.totaljs.com/petersirka/>

**Comment by petersirka** [comment]
I forgot to answer:

```html
<button onclick="window.forma.Name='kuku'">Ok</button>
```
- this won't work because components don't know about your changes path
- you need to notify change via `SET()`, `UPDATE()`, etc. methods

```html
<button onclick="SET('forma.Name', 'kuku')">Ok</button>
```

**Comment by Jusys** [comment]
Dėkoju.

**Comment by Jusys** [comment]
P.S. I thought that there is some automatic cycle, that checks values, like in angular..

**Comment by petersirka** [comment]
It's because of performance, but you can use jComponent `CREATE()` (A simple wrapper for `Proxy` object):

https://jsfiddle.net/petersirka/r0kmhtvw/4/
__It doesn't work in IE__: https://caniuse.com/#search=proxy
