### ISSUE TITLE
JS minification deletes necessary space

### ISSUE THREAD

**Issue by HACKHERS** [totaljs/framework#645]
Hello, I found some problems with the JS minification.

Before minification: `this.id="ui-id-"+ ++t`
After minification: `this.id="ui-id-"+++t`
Problem: Deleting the extra space that makes `ui-id` plus `++t` breaks the script. Console: `Uncaught ReferenceError: Invalid left-hand side expression in postfix operation`

**Comment by petersirka** [comment]
Hi,
I have updated JS compressor, try to download framework from GitHub and replace all files in your `/node_modules/total.js/`:
https://github.com/totaljs/framework/tree/v3.0.0

Or you can replace internal JS compressor:
https://github.com/totaljs/examples/tree/master/external-compile-uglifyjs

**Comment by HACKHERS** [comment]
Thanks thats what I have done actually with some simple modification 👍 
PS: Premium CMS fails on admin views if you don't check file extension (js)
```
F.onCompileScript = function (filename, code) {

	if(F.isDebug) return code; // for debugging performance

    if(filename !== undefined && path.extname(filename) !== ".js")
		return code;

	return UglifyJS.minify(code).code;
};
```
