### ISSUE TITLE
Group routes

### ISSUE THREAD

**Issue by gibson** [totaljs/framework#652]
Have you feature for grouping routes? I want to use `authorize` for all routes, except authorization routes

**Comment by petersirka** [comment]
Yes:

```javascript
GROUP(['authorize'], function() {
    ROUTE(...);
    ROUTE(...);
    ROUTE(...);
    ROUTE(...);
    ROUTE(...);
    ROUTE(...);
    ROUTE(...);
    ROUTE(...);
});
```

https://docs.totaljs.com/latest/en.html#api~Framework~F.group

**Comment by gibson** [comment]
I think we need in documentation section for routing

**Comment by petersirka** [comment]
Yes, I'll extend `Controller` section in docs by adding `GROUP()`. BTW: please use for next questions [Total.js Messenger](https://messenger.totaljs.com). It will be better and faster.

Thank you!
