### ISSUE TITLE
Marketing: splash page message doesn't make sense

### ISSUE THREAD

**Issue by truedat101** [totaljs/framework#654]
Please relocate this issue to wherever you are logging totaljs.com site bugs.

On the total.js website: This image shows: https://www.totaljs.com/download/B20180424T000000010.png 

Text is "Why does not NASA use total.js?"

It's a strange way to market the framework.  And it is also bad grammar to use english in this way.  It should read: "Why doesn't NASA use total.js?" (contraction).  Also, not sure you can use a trademarked organization's name in your marketing, at least, you may not want to.   

I feel the campaign, if you can call it that, is really about selling the points of Total.js that you don't yet know, and cycle through them on the splash image:
- small size : list size
- minimal (0) external dependencies
- modern : list features you consider modern
- well-maintained (list how many releases per year, major, minor)
- performance (list key performance characteristics)
- some other funny stuff: number of years to learn it (0), number of minutes to install webpack and compile (this is a stab at reactjs) == 0, number of minutes to set it up(1), etc...

**Comment by petersirka** [comment]
Thank you, I have prepared a new image, but it waits for 1st august. I agree, my english is very bad and I'm working on it everyday, but it's very very hard. I thank you for your points, I'll use them.

If you have a lot of free time I can add you an access to Total.js website and you can fix all my grammar mistakes. I'll be happy. Thank you again, I appreciate it.

**Comment by truedat101** [comment]
I am your humble servant on these matters of english language.  It's an awful language with a mashup of things from Germanic, French, Latin, Spanish, etc., all mixed together, with some  rules and many exceptions.  Worse is the colloquial regional use of the language which makes it hard to determine meaning (we speak differently in SF area than people in NYC).  And throw in a lot of bad english being taught by supposed language scholars (Japan, for example, teaches english for at least 8 years of education but produces very few good english speakers after 8 years).  

Anyway, since I feel a bit indebted to you for the great project and code, I will continue to look for places to improve documentation and site marketing/information.

Is this the correct project to provide bugs/suggestions for documentation and site related items?

**Comment by petersirka** [comment]
Great and really I appreciate it!

Yes this is correct project. Also you can use Total.js messenger for tracking bugs/improvements, just write me <https://messenger.totaljs.com/users/petersirka/>, I'm still online.

Thank you! I would also like to repay.
