### ISSUE TITLE
$.error.push in SchemaOption not loads error message from the resource file

### ISSUE THREAD

**Issue by ckpiggy** [totaljs/framework#658]
my default.resource
```
error-database : Database error
```
when I call `$.error.push('msg', '@error-database', 500)`
I got :
```
[
  {
    name: 'msg',
    error: '@error-database'
  }
]
```
I thought I will get something like :
```
[
  {
    name: 'msg',
    error: 'Database error'
  }
]
```

**Comment by petersirka** [comment]
__It works__, test it:
[emptyproject.zip](https://github.com/totaljs/framework/files/2276909/emptyproject.zip)

**Comment by ckpiggy** [comment]
I found it is because I use send error response with `$.error.output()`
It work if I use `$.error.json()`
Thank you @petersirka

**Comment by petersirka** [comment]
Please show me your code with `.output()`. If you use it directly in response then you need to use `error.output(true)`. Thank you.
