### ISSUE TITLE
Merge JS/CSS without comments

### ISSUE THREAD

**Issue by mnicolas80** [totaljs/framework#660]
Hi,

It it possible when merging JS/CSS assets to remove the existing or generating comments in the output files?
e.g. merge command:
```
MERGE('/js/output.js', '/js/fileA.js', '/js/fileB.js');
```
combines/minifies the above files and adds a comment after/before each file's content.
```
/*
 * ==========================
 * MERGED: <FILE_PATH>/js/fileA.js
 * ==========================
 */
```

Suggestion: the comments removal could be enabled/disabled according to a provided flag.

**Comment by petersirka** [comment]
Hi, comments are removed when the app will be in `release` mode. Comments are for `debug` mode only.

**Comment by mnicolas80** [comment]
Confirmed!
But what about the existing comments in some assets?
e.g.
```
/*! jQuery v3.1.0 | (c) jQuery Foundation | jquery.org/license */
```
Can these comments be removed too?

Thank you Peter!

**Comment by petersirka** [comment]
Framework doesn't remove comments in minified scripts which are not minified via Total.js. You can remove the comments manually.

BTW: it's good to keep licenses :-)

**Comment by mnicolas80** [comment]
Understood,

thank you!
