### ISSUE TITLE
Merge bundling files with `--` prefix only works on first build/bundle on debug

### ISSUE THREAD

**Issue by pnmcosta** [totaljs/framework#663]
Hi Peter,

Found a small issue with the merging of bundling files using the `--` prefix.

At the moment, if you update your file, it is copying the file to `.src` instead of remerging with the existing bundle file, it does report the change as an UPD:

`--- UPD --- [ 2018-09-01 14:31:55 ] ----------------> /themes/admin/public/--ui.css`

Easily worked around by stopping and starting the process.

Cheers,
P.

**Comment by petersirka** [comment]
Hi Pedro, I have fixed it now. Download latest beta version.

Thank you!

**Comment by pnmcosta** [comment]
Perfect, confirmed. thank you so much.
