### ISSUE TITLE
config of "QUERYPARSEROPTIONS.maxkeys"

### ISSUE THREAD

**Issue by ivanlunardi** [totaljs/framework#668]
i tried to implements "datatable"       with[ server-side integration](https://datatables.net/examples/server_side/post.html).
The number of key used by datatable ( in post request ) are proportional to number of colums.
With 4 columns we exeed the "33" max key.
It is possible to put this value in config ?

p.s. i tried to modify the value in index.js and it works.

Thank you ivan

**Comment by petersirka** [comment]
Hi,
yes, you're right. I have added a new config option:

```html
default-request-maxkeys     : 33
```

BTW: you need to download latest beta version of Total.js `$ npm install total.js@beta`. Let me know.

**Comment by ivanlunardi** [comment]
it works.....
Thank you

**Comment by petersirka** [comment]
Great! __Maybe__ next week will be a new release.

**Comment by ivanlunardi** [comment]
ok . 
good works
