### ISSUE TITLE
Set session cookies with no expiration date

### ISSUE THREAD

**Issue by fgnm** [totaljs/framework#669]
I need to create a session cookie, so no expiration date should be included in the cookie string. However (even check the code) it seems that Total.js does not support session cookies.

Is there any way to do this?

**Comment by petersirka** [comment]
Hi @fgnm,
try this:

```javascript
controller.cookie('name', 'value');
// or
contorller.cookie('name', 'value', null);
```

**Comment by fgnm** [comment]
Thank you so much!
```JavaScript 
controller.cookie('name', 'value');
```
Worked as expected. Anyway I'd like to suggest to add this in the docs: https://docs.totaljs.com/latest/en.html#api~FrameworkController~controller.cookie
Because "expiration" is not marked as optional, this could make confusion :)

**Comment by petersirka** [comment]
Yes, there is missing, but I have added it. I want to publish a new version of Total.js next week, so then will be updated docs.

Thank you!
