### ISSUE TITLE
Schema function called twice in a single request

### ISSUE THREAD

**Issue by ckpiggy** [totaljs/framework#670]
I created an api to send sms
```
exports.install = function () {
  F.route('/sms-send/{target}', ['post', 'json', '*SMS --> @insert'])
}
```
I found the schema.insert function was called twice in a single request.
But when I test with `GETSCHEMA`
```
GETSCHEMA('SMS').insert({phone: '0987654321'}, {target: 'staff'}, (err, obj) => {
      OK(!err, 'expect no error')
      OK(obj && obj.ok, 'expect response')
})
```
The insert function only called once.

**Comment by ckpiggy** [comment]
I found it is because I call twice `next` in my `F.onAuthorize` delegate
```
F.onAuthorize = async function (req, res, flags, next) {
  let user
  try {
    const data = decryptToken(req)
    user = await findUserByTokenData(data)
    flags.push(`@${user.role}`)
  } catch (e) {
    next(false)
  } finally {
   next(true, user)
  }
}
```
If auth failed, `next` will called in catch block and finally block.
But I am also curious about "Will the routes doesn't have authorized flag trigger the authorize delegate?"
It seems every route will trigger the delegate and ignore the callback result if the route doesn't have `authorized` flag

**Comment by petersirka** [comment]
`onAuthorize` must be executed every request because the routing depends on it. So it doesn't matter if you have `authorize`, `unauthorize` flag or no.

**Comment by ckpiggy** [comment]
Thank you @petersirka
