### ISSUE TITLE
How to send an image from an URL

### ISSUE THREAD

**Issue by separovichabel** [totaljs/framework#672]
I have have a service that will furnishes some images from a URL, and i want to set the response Header Content-Type as image/png.

How can i set the Header? The response is comming with Content-Type →application/json; charset=utf-8, but i want it to be image/png. 

My code is some thing like that:

`  F.route("/common/signature", get, ["*Signature", 'range',"image","get", "cors", 'head']);

function get() {
    var self = this;
    var options = {};
    options.self = self;

    self.$workflow("get", options, self.callback());
}

NEWSCHEMA("Signature").make(function(schema) {

    schema.addWorkflow("get", function(error, model, options, callback) {
        const url = "https://blablabla.io/bla.png";
        
        request(url, (err, res, body) => {
            if (err) { return callback(err); }
            options.self.header("Content-Type", "image/png");
            callback(body);
          });    
    });
});`

No image is shown, only binaries like: 
`"\ufffdPNG\r\n\u001a\n\u0000\u0000\u0000\rIHDR\u0000\u0000\u00028\u0000\u0000\u0000\ufffd\b\u0002\u0000\u0000\u0000\ufffdW-l\u0000\u0000\ufffd\u0000IDATx\ufffd\ufffd\u0007\ufffd\ufffdĵ\ufffdϙ\u0019I\ufffdoߵw]\ufffd\rn\u0604b;\u0010bJ\ufffdG\ufffd\u0003\ufffd\ufffdЌ\ufffd\ufffd%\ufffd$!\u000fȃ$\ufffd\u0012 \r^ \ufffd\ufffd\u0010BB\ufffd\u00001\u0010\ufff..."`

Sorry for poor english. Is it clear?

**Comment by petersirka** [comment]
You need to use __Total.js v3__:

```javascript
// BAD
F.route("/common/signature", get, ["*Signature", 'range',"image","get", "cors", 'head'])

// GOOD:
ROUTE('GET /common/signature/ *Signature --> @get');
CORS();
```

__Schema__:

```javascript
schema.addWorkflow('get', function($) {
    const url = 'https://www.totaljs.com/img/logo2.svg';
    $.controller.proxy(url);
    $.callback = null;
});
```

**Comment by separovichabel** [comment]
Sorry for the delay.
I'm using `ROUTE()` now but the `$.controller.proxy(url);` is timing out.

Any reason for that? or is there any other way to furnish an image from another site?

**Route**
```
ROUTE('/common/signature/',      get,   ['*Signature', 'get', 'cors']);
function get() {
	var self = this;
        var options = {};
	options.search = self.query.search;
    self.$workflow('get', options, self.callback());
}
```
**Schema**

```
schema.addWorkflow('get', function($) {
        const url = 'https://www.totaljs.com/img/logo2.svg';
        $.controller.proxy(url);
        $.callback = null;
    });
```
**Response**

```
{
    "statusCode": 408,
    "error": "Request Timeout",
    "message": "There have been some errors with api, please report the problem or difficulty to the technical team responsible"
}
```

**Comment by petersirka** [comment]
Does the terminal log contain something? Can you create a small example which I can test on my Mac?

**Comment by separovichabel** [comment]
The time out is an intern problem with my server.
But no image is shown with that exemple:

**proxy-test.js**
`require('total.js/debug')({});`

**controllers/default.js**
```
exports.install = () => {

    ROUTE('/', get, ['*Proxy', 'cors', 'proxy']);
    
    NEWSCHEMA("Proxy").make(function(schema) {
        schema.addWorkflow('get', function($) {
            $.controller.proxy('https://assets3.thrillist.com/v1/image/2558908/size/tmg-article_tall.jpg');
            $.callback = null;
        });
    });
}

function get() {
    var self = this;
    var options = {"search": self.query.search};
    self.$workflow('get', options, self.callback());
}
```

**Comment by separovichabel** [comment]
Unfortnantly `U.download` is not helpping me. There is something wrong with url encoding.
I want to send `blabla.com?preguiça=é`
but it actualy sends `blabla.com?pregui�a=�`
Does it accept utf-8 ? how can i fix it?

**Comment by petersirka** [comment]
Yes, but you need to encode it ... 

```javascript
U.download('https://....?param=' + encodeURIComponent('yourvalue'), ['get'], function(err, response) {

});
```
