### ISSUE TITLE
Route any request if a flag is present

### ISSUE THREAD

**Issue by fgnm** [totaljs/framework#674]
Hello, I'm looking for a smart method to route every page to a single one if, during onAuthorize, is set a special flag.
Currently I handle the route in this way:
```JavaScript
    ROUTE('/profile', view_personal, ['authorize']);
    ROUTE('/profile/address', view_address, ['authorize']);
    ROUTE('/profile/contacts', view_contacts, ['authorize']);
    .....
```
The idea is to have a single line that route: /profile, /profile/address, /profile/contacts to another function if there is a flag. So I've tried this route:
```JavaScript
    ROUTE('/*', view_index, ['authorize', '@customflag']);
```
But it does not override existing routes and remove any 404 (not a good choice). Maybe the regex route could be the solution but the example in docs does not works.

**Comment by petersirka** [comment]
Hi,
`@customflag` can be used for roles only. `RegExp` routing can be a part of dynamic argument only. 

```javascript
ROUTE(function(url, req, flags) {
    return (/YOUR_REG_EXP/).test(url);
}, your_action);
```

__Or you can use routing `group`:__

<https://docs.totaljs.com/latest/en.html#api~HttpRouteOptionsFlags~%26group_name>

**Comment by fgnm** [comment]
Thank you for clarification, indeed `@customflag` is exactly for roles purpose. Users with that role shouldn't be able to explore the whole `['authorize']` pages but only one. So I ask if there is a better solution instead of doing something like this:
```JavaScript
exports.install = function () {
    ROUTE('/profile', view_personal, ['authorize']);
    ROUTE('/profile/address', view_address, ['authorize']);
    ROUTE('/profile/contacts', view_contacts, ['authorize']);

    ROUTE('/profile', view_index, ['authorize', '@customflag']);
    ROUTE('/profile/address', view_index, ['authorize', '@customflag']);
    ROUTE('/profile/contacts', view_index, ['authorize', '@customflag']);
}
```
I've many ROUTE and I don't want to duplicate each one to check `@customflag`. 

Basically I'm looking for a smarter solution for write a routing rule that redirect everything to a single page, if the authenticated user ha `@customflag` role.
Are groups the solution? I didn't understand well the doc, could you make me an example for what I'm trying to do?

Thank you :)

**Comment by petersirka** [comment]
I understand. Then `roles` must work. Show me your implementation of `F.onAuthorize` ... There you need to add your role to `flags` argument:

```javascript
F.onAuthorize = function(req, res, flags, callback) {
    flags.push('customflag');
    callback(true, USER_OBJ);
};
```

- then routing will work correctly

**Comment by petersirka** [comment]
😁so does it work?

**Comment by petersirka** [comment]
Only wildcard routing with your custom logic.

**Comment by fgnm** [comment]
Okay but this one:
```JavaScript
ROUTE('/*', view_index, ['authorize', '@customflag']);
```
Does not override already existing route. I mean that `/profile` page will always use `view_personal` instead of `view_index`. It seems that there is a sort of priority during routing that I've don't understand. /* routing seems to have less priority then /profile.

**Comment by molda** [comment]
If all you want is to write less code then this may help

```
function routes() {
    ROUTE('/profile', view_personal, ['authorize']);
    ROUTE('/profile/address', view_address, ['authorize']);
    ROUTE('/profile/contacts', view_contacts, ['authorize']);
}

exports.install = function () {
    routes();
    GROUP(['@customflag'], routes);
}
```

**Comment by petersirka** [comment]
Yes, it's correct.

- routes with `*` wildcard have lower priority
- more flags, bigger priority

I meant that you create your own mechanism in some action in a route with `wildcard`.

**Comment by fgnm** [comment]
So maybe I can try the inverse. Is it possible to do something like: Route the page if is not present this flag, otherwise show 401?

**Comment by petersirka** [comment]
Inversion is not possible. You can perform your own route in `#404` action or you need to use wildcard routing with your own routing logic.

**Comment by fgnm** [comment]
Okay, thank you for clarifications
