### ISSUE TITLE
Cluster https

### ISSUE THREAD

**Issue by EddiDin** [totaljs/framework#686]
Hello. How can i start cluster on https? (I didn't find this information in docs).

**Comment by EddiDin** [comment]
Thanks. I will wait for the update!

**Comment by petersirka** [comment]
Hi @EddiDin,
I have added `https` into the `cluster`. Try it `$ npm install total.js@beta` and let me know.

**Comment by neophylon** [comment]
Hi @pertersirka
I have got a error message on Chrome : ERR_SSL_VERSION_OR_CIPHER_MISMATCH
my index.js
// ===================================================
// FOR DEVELOPMENT
// Total.js - framework for Node.js platform
// https://www.totaljs.com
// ===================================================

const options = {};
options.ip = '0.0.0.0';
options.port = parseInt(process.argv[2]);
const fs = require('fs');
options.https = {
	key: fs.readFileSync('/etc/letsencrypt/live/xxx.xxx.xxx/privkey.pem'),
	cert: fs.readFileSync('/etc/letsencrypt/live/xxx.xxx.xxx/cert.pem')
}

require('total.js').cluster.https('auto', 'debug', options);

**Comment by petersirka** [comment]
@neophylon and does it work with:

```javascript
require('total.js').https('debug', options);
```

?

**Comment by neophylon** [comment]
Sorry for late.
if i use 'require('total.js').https('debug', options);', everything is fine.
So, now I have used only https not cluster https.
But I want to use cluster https. I installed totaljs@beta version already.

**Comment by petersirka** [comment]
Shit, sorry --> my bad, try this:

```javascript
require('total.js').cluster.https(5, 'debug', options);
```

**Comment by neophylon** [comment]
I fixed index.js as you mentioned it.
but I still got the error "ERR_SSL_VERSION_OR_CIPHER_MISMATCH" on chrome
my index.js
----------------------------------------------------------------------------------------------------------------
const options = {};
options.ip = '0.0.0.0';
options.port = 7001
const fs = require('fs');
options.https = {
	key: fs.readFileSync('/etc/letsencrypt/live/domain.com/privkey.pem'),
	cert: fs.readFileSync('/etc/letsencrypt/live/domain.com/cert.pem')
}

require('total.js').cluster.https(4, 'debug', options);
----------------------------------------------------------------------------------------------------------------
what i am wrong.!

**Comment by neophylon** [comment]
when I use
```
require('total.js').cluster.https(5, 'debug', options);
```
I still get the error "ERR_SSL_VERSION_OR_CIPHER_MISMATCH" on the Chrome browser

So, I try to modify my index.js and total.js/cluster.js.

index.js
```
options.https = {
	key: fs.readFileSync('/etc/letsencrypt/live/eapi.lhcloud.net/privkey.pem'),
	cert: fs.readFileSync('/etc/letsencrypt/live/eapi.lhcloud.net/cert.pem')
}
==>
options.https = {
	key: '/etc/letsencrypt/live/eapi.lhcloud.net/privkey.pem',
	cert: '/etc/letsencrypt/live/eapi.lhcloud.net/cert.pem'
}

require('total.js').cluster.https(5, 'debug', options);
```
total.js/cluster.js
```
function on_init(msg){
......................
                        if (msg.https){
				msg.options.https.key = Fs.readFileSync(msg.options.https.key);
				msg.options.https.cert = Fs.readFileSync(msg.options.https.cert);
		        	F.https(msg.mode, msg.options);
		        }else{
		                F.http(msg.mode, msg.options);
		        }
.....................
```
It works.

**Comment by petersirka** [comment]
Great, just create a pull request if you can to `v3.2.0`. Just let me know if you can't make pull request.

**Comment by neophylon** [comment]
Thank you,
But it can't use with "require('total.js').https('debug',options);".
So, I'm just temporary using it.

**Comment by petersirka** [comment]
Mhhh, I know where is the problem. Buffer (with of key + cert) is not sent to child process. I'll fix it today.

**Comment by petersirka** [comment]
I have fixed it. Sorry for delay. Try it `$ npm install total.js@beta`. Now you can use as you wrote:

```javascript
options.https = {
	key: '/etc/letsencrypt/live/domain.com/privkey.pem',
	cert: '/etc/letsencrypt/live/domain.com/cert.pem'
};

// OR

options.https = {
	key: 'BASE64',
	cert: 'BASE64'
}
```

Thank you!

**Comment by neophylon** [comment]
I update total.js@beta. then try it
I got the follow error
=========================
======= 2019-01-18 13:39:10: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.createSecureContext (_tls_common.js:88:17)
    at Server (_tls_wrap.js:819:25)
    at new Server (https.js:60:14)
    at Object.createServer (https.js:80:10)
    at listen (/opt/cluster_test/node_modules/total.js/index.js:6799:21)
    at /opt/cluster_test/node_modules/total.js/index.js:6826:6
    at /opt/cluster_test/node_modules/total.js/index.js:3920:16
    at Array.AP.async (/opt/cluster_test/node_modules/total.js/utils.js:5015:16)
    at /opt/cluster_test/node_modules/total.js/index.js:3915:16
    at Array.AP.async (/opt/cluster_test/node_modules/total.js/utils.js:5015:16)

=========================

**Comment by petersirka** [comment]
Show me your code.

**Comment by neophylon** [comment]
index.js
// ===================================================
// FOR DEVELOPMENT
// Total.js - framework for Node.js platform
// https://www.totaljs.com
// ===================================================

const options = {};
options.ip = '0.0.0.0';
options.port = parseInt(process.argv[2]);
// options.config = { name: 'Total.js' };
// options.inspector = "192.168.1.242:9580";
options.https = {
	key:'/etc/letsencrypt/live/xxx.xxx.xxx/privkey.pem',
	cert:'/etc/letsencrypt/live/xxx.xxx.xxx/cert.pem'
}

require('total.js').cluster.https(4, 'debug', options);
//require('total.js').https('debug', options);

// Use a terminal for testing:
// $ siege -b -r 10 http://127.0.0.1:8000/

total.js version : "total.js": "^3.2.0-6"

**Comment by petersirka** [comment]
I have tested it. It works correctly.

```
2019-01-18 13:39:10: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
```

This error means that you have invalid certificate or key.
