### ISSUE TITLE
High CPU load after 1d

### ISSUE THREAD

**Issue by germama** [totaljs/framework#688]
Hi there! First of all - I am a heavy user of total.js and really love it - thanks for this nice pice of software.

After one day the CPU load (an RAM usage) goes constantly up until it reaches 80-90% on one core.
The web frontend is not usable anymore, every request times out. Is there a way to debug, which function is causing a memory leak?

After killing the process, forever respawns it and everything is back to normal.

**Comment by petersirka** [comment]
Hi @germama,
first of all - thank you. This is not normal behavior. Can you describe more your app?

- which dependencies have you used?
- what the app does do?
- how many visitors/connections do you have?
- are you sure you don't have any infinity loop?

__Thank you!__

**Comment by germama** [comment]
I recently added one more tab in Flow which contains various 3 sec timers.
Those trigger a custom ping component which uses npm ping package for probing different hosts and npm influxdb to store those results in InfluxDB.

There was at least no obvious memory leak visible but I need to investigate further.

**Comment by petersirka** [comment]
I use Flow in some projects and without any problem:

![Flow](https://user-images.githubusercontent.com/2414252/50442275-74743900-08fe-11e9-968f-df916cf97fa6.png)

![Flow 2](https://user-images.githubusercontent.com/2414252/50442314-9bcb0600-08fe-11e9-8a35-975b929413bc.JPG)

Let me know if you found something....

---

BTW: try to enable internal `debug` mode in __/config__ file:

```
allow_debug    : true
```

Framework creates an internal snapshot to `/yourapp/usage.log` file. If you will have high CPU then send me this file, maybe it helps.

**Comment by petersirka** [comment]
Some news?

**Comment by germama** [comment]
I believe Total.JS is working properly.
Figured out that https://www.npmjs.com/package/influxdb-nodejs has some memory issues.
Connecting to InfluxDB using this library and writing a dataset leads to excessive memory consumption over time.

**Comment by petersirka** [comment]
OK, then I'm closing this issue.
