### ISSUE TITLE
How to show error and success messages in views?

### ISSUE THREAD

**Issue by Pourya8366** [totaljs/framework#692]
I want to send flash messages to views in total.js and i see an alternative approach with use of query string and check that flag for know what to show in view:

in controller:
`this.redirect('/?success=1');`

and in related view:
```
@{if query.success}
    //proper message
@{fi}
```
but i want to know is there any other approach available to show any status (error or success) messages?

**Comment by petersirka** [comment]
In some cases I use same approach but __I recommend__ to do it on client-side via JavaScript if it's possible and my next recommendation is to send all forms via `AJAX`, always. Less code on server-side brings more benefits:

- less CPU and memory consuption on server-side
- output of view can be cached
- better performance
- smaller transmission data

---

Here is a __Flash module__ with same functionality as in __Express.js__, but I don't recommend it: https://github.com/totaljs/modules/tree/master/Miscellaneous/flash

For rendering some flash messages you can use `controller.repository` object or `model` or you can create some View Engine Helper. There are many ways how to do it.
