### ISSUE TITLE
connect websocket to nanomsg/zeromq websocket transport

### ISSUE THREAD

**Issue by wprayudo** [totaljs/framework#694]

**Comment by wprayudo** [comment]
how I can connect websocket route to another supported websocket protocols in nanomsg/zeromq ?

Thank you,

Regards.

**Comment by petersirka** [comment]
Hi @wprayudo,
only via `WEBSOCKETCLIENT()`: https://docs.totaljs.com/latest/en.html#api~WebSocketClient
