### ISSUE TITLE
Does the websocket support fragmentation?

### ISSUE THREAD

**Issue by vasekd** [totaljs/framework#695]
I'm using traeffic web proxy that uses fragmentation of websocket messages.

Currently set to 4096B.

https://forge.tedomum.net/tedomum/traefik/blob/55f610422a8e66506a812013da1fd938a5b9c093/vendor/github.com/gorilla/websocket/conn.go

Is it some possibility to read the fragmented message in total.js?

**Comment by petersirka** [comment]
Now Total.js doesn't support fragmentation. I didn't have any problem yet because I still work with messages with the fixed length. Fragmentation is about messages with uknown size. We can look into it but I don't have any idea how to implement it.
