### ISSUE TITLE
NoSQL databse and AWS Elastick Beanstalk

### ISSUE THREAD

**Issue by fgnm** [totaljs/framework#696]
I've a problem with NoSQL embedded database. When I create a new database  
```JavaScript
const refreshTokensDB = NOSQL('refreshTokens');
...
refreshTokensDB.insert({ token: refreshToken, id: data.Item.id }, true).where('token', refreshToken);
...
```
Total.js creates a new file `/database/refreshTokens.nosql` in the root of the project and populate it. But when AWS Elastic Beanstalk deploy a new version of the app the whole root project directory is substituted with a new one, so the .nosql database file (populated online by the users) is lost.

An easy solution could be to change default path and use instance home directory to store .nosql files, but I really do not want to keep the database in the same EC2 instance of the app.

I would like to put the .nosql file in a safer and larger place, such as S3 Bucket, and allow Total to read and write it. How can I do that?

Thank you

**Comment by petersirka** [comment]
Hi @fgnm, this is not possible because NoSQL engine works with FileSystem only. For S3 Bucket is needed to use network connection and there won't work NoSQL engine.

__So you have two possibilities:__
- use another DB like MongoDB or PostgreSQL
- or use virtual private server (I use it too)

**Comment by fgnm** [comment]
What a pity, unfortunately I need AWS Elastic Beanstalk, because hardware auto scaling, so I can't use a normal VPS.

Anyway I'll go with my external DBs, but I hope that someday NoSQL engine could support something like that, because it's really easy to use it together with Total :smile:

**Comment by petersirka** [comment]
I understand, but you need to know that NoSQL embedded can't be used in cluster. NoSQL is targeted for very small apps. Good luck!
