### ISSUE TITLE
Utils.request  GET timeout

### ISSUE THREAD

**Issue by cstange** [totaljs/framework#697]
Request are getting timeout using method GET because 'Content-Length' = 2 by default on
Node 8+

I think the problem was the las commit:

https://github.com/totaljs/framework/commit/3ce3a79318246a6e3e1de636ea855ab9caddc7d5

**Comment by petersirka** [comment]
I fixed it some time ago:
https://github.com/totaljs/framework/blob/v3.2.0/utils.js#L619

Try to user Total.js beta `$ npm install total.js@beta`.

**Comment by petersirka** [comment]
I have released a new version of Total.js.
Just update `$ npm install total.js`.
