### ISSUE TITLE
CSV translation problem with special characters

### ISSUE THREAD

**Issue by fgnm** [totaljs/framework#700]
Hi! I've noticed a bug with CSV translation parser script. In some of my strings I must include some HTML special characters, for example the `&amp;`, well the parser recognize the ; as delimiter, so parsing is compromised.

Also I would understand the reason of the `replace()` in this line: https://github.com/totaljs/framework/blob/master/bin/totaljs#L768, why it duplicates `"`? 

I'm writing a manager for collaborative translations, thank you.

**Comment by petersirka** [comment]
Can you send me some view? I need to test it.

**Comment by petersirka** [comment]
BTW why quotes are duplicated? 
Read here: https://stackoverflow.com/questions/17808511/properly-escape-a-double-quote-in-csv

**Comment by fgnm** [comment]
For example:
```HTML
<div>
@(I love Total.js; It's a very good framework)
</div>
```
With the command `totaljs --translatecsv` I got something like:
```CSV
Hash;Text;Translation
T-14328244;"I love Total.js; It's a very good framework";
```
Then run `totaljs -csv translate.csv`:
```
// Total.js resource file
// Created: 2019-02-20 15:42

T-14328244           : It's a very good framework
```
And it's wrong. So, I've edit your script to replace each `;` into `\;`, similar to double quote escape, and modified `line.split(';')` into `line.split(/(?<!\\);/g)` in your `parse_csv(content)` function.

There will certainly be more smart solutions :see_no_evil:

**Comment by petersirka** [comment]
Yes, I will need to rewrite CSV parser... Shit.

**Comment by petersirka** [comment]
Hi, I have added `csv` parser. Try to it: `$ npm install -g total.js@beta`.
