### ISSUE TITLE
databases[name] is not a function

### ISSUE THREAD

**Issue by CERyanKamal** [totaljs/framework#704]
I am using total.js v 3.2.4

While trying to connect multiple database I face this error in console
```
F.install('controller', '') ---> TypeError: databases[name] is not a function TypeError: databases[name] is not a function
    at Framework.F.database (C:\Users\turbo\Desktop\kaizen-system\definitions\postgresql.js:9:27)
```

here's my postgresql definition file
```
const databases = {};
databases.source = require('sqlagent/pg').connect(CONFIG('database'));//main user database
databases.traders = require('sqlagent/pg').connect(CONFIG('TradersDB'));//traders database

F.database = function(name) {
    // returns SQL Agent instance
    return databases[name]();
};
```

If I try to run the following queries 
```
var sql = DB('source');
var traders = DB('traders');

sql.select('inventories.invs').take(5);
            sql.exec(console.log);
 traders.select('public.items').take(5);
            traders.exec(console.log);
```

the first query(sql) is running successfully while the other query (traders) throw an error or relation 'public.items' is not defined along with the error at the beginning of this issue

Can you help please ? 
Thanks in advance

**Comment by petersirka** [comment]
Hi, I recommend to use our `DBMS` module:
https://wiki.totaljs.com/dbms/02-usage/

```javascript
const dbms = require('dbms');
dbms.init('source', 'postgresql://user:pass@localhost:5432/dbname1');
dbms.init('traders', 'postgresql://user:pass@localhost:5432/dbname1');
```
__Usage__:

```javascript
var db = DBMS();
db.find('source/inventories.invs').take(100).set('inventories');
db.find('traders/public.items').take(100).set('items');
db.callback(console.log);
```

It's our alternative to SQL Agent.

**Comment by CERyanKamal** [comment]
Thank you Peter, 
Your example works perfect with db.find method but when I try db.query like this

`db.query('select * from source/inventories.invs').callback(console.log);`

it throws an error of 
```
TypeError: Cannot read property 'db' of undefined
    at DBMS.DP.next (C:\Users\turbo\Desktop\kaizen-system\node_modules\dbms\index.js:223:24)
```

Thanks for this amazing framework

**Comment by petersirka** [comment]
Sorry, there is a bit confusion and I found a bug with `query`, but I have fixed it now. Please reinstall DBMS from NPM.

```javascript
// a bit modified .query():
db.query('inventories', 'select * from invs').callback(console.log);
// or with .conn()
db.query('select * from invs').conn('inventories').callback(console.log);
```

__Recommendation__:

```javascript
db.find('inventories/invs').where('removed', false).fields('id', 'name').callback(console.log);
```
Let me know.

**Comment by petersirka** [comment]
Understand. Not a problem and just let me know if something won't work.
BTW: Thank you!
