### ISSUE TITLE
Bug, F.worker not working on 3.2.4

### ISSUE THREAD

**Issue by traubo279** [totaljs/framework#708]
It seem that F.worker does not execute workers even one with a simple console.log on current 3.2.4

**Comment by petersirka** [comment]
Hi @traubo279,
`F.worker()` returns executes only one instance of worker and it returns `child_process` object. If you want to execute multiple same workers then you need to use `WORKER2()`.

**Comment by traubo279** [comment]
> Hi @traubo279,
> `F.worker()` returns executes only one instance of worker and it returns `child_process` object. If you want to execute multiple same workers then you need to use `WORKER2()`.

Hi @peterkc , in my case, both F.worker and F.worker2 do return the child_process object but don't execute anything inside the source worker file on version 3.2.4, i tried reinstall from npm and it doesnt work. Finally i reversed to 3.1.0 and it work. Node version tested on 8.9.1 and 11.5.0.

**Comment by petersirka** [comment]
Can you send me two examples with `v3.2.4` and `v3.1.0`? I'll test it.

**Comment by traubo279** [comment]
Here is my code in folder **definitions**/cron.js
```
function repeat () {
    let cc = F.worker("a", "worker")
    console.log("worker should be executed");
}
setInterval(repeat, 5000);
F.once('load', repeat);
```
and a simple  in folder **workers**/a.js  with 
`
console.log('message from worker')
`
Output on 3.1.0:
<img width="618" alt="Screen Shot 2019-05-31 at 1 18 42 PM" src="https://user-images.githubusercontent.com/8275961/58685641-a3f40980-83a6-11e9-89f0-2b538b139c8f.png">
Output on 3.2.4: 
<img width="644" alt="Screen Shot 2019-05-31 at 1 16 53 PM" src="https://user-images.githubusercontent.com/8275961/58685584-75762e80-83a6-11e9-8073-99ea78297a3e.png">

**Comment by petersirka** [comment]
Hi. I have changed behaviour for workers. Each worker has been executed in `silent` mode. But I have updated core of Total.js:

- I have added a new config item called `allow_workers_silent   : false`
- default value is `false` as you expect (same like in `v3.1.0` version)
- I have published a new beta version `$ npm install total.js@beta`

I'm not sure if this new behaviour is OK but it's better.

**Comment by traubo279** [comment]
Hi @petersirka, it seem to work fine if `allow_workers_silent` is not exist or missing from the config file. Manually set it to false will result the same as set it to true in the config file.

**Comment by petersirka** [comment]
Hi @traubo279 , by default is `false` ... I have tested it and it works correctly. For `F.worker2()` is set to `true` (this can't be changed) because the reason is `pipe` between app and child process and `worker2` executes a callback with the response from the `stdout` stream.

**Comment by traubo279** [comment]
@petersirka, yes i know it working on default, but when i have`"allow_workers_silent : false"` in config, it's the same as "allow_workers_silent : true", which is may be miss leading to some people .. ;)

**Comment by petersirka** [comment]
__True_, I have fixed it. Thank you. New beta will be released next week.
