### ISSUE TITLE
totaljs --translate "PROJECT_NAME" is not working

### ISSUE THREAD

**Issue by luasenvy** [totaljs/framework#709]
hi, i want to translate 'Dashboard'.

so i enter on command line `total --translate "Dashboard"`.

but, Proceed to the template 'dashobard' installation process.

Can I avoid this situation without regenerating the entire resource file?

thank you ;)

**Comment by petersirka** [comment]
Hi @luasenvy,
sorry for delay.

I have fixed it, please install beta version of Total.js: `$ npm install -g total.js@beta` and let me know if something won't work.

Thank you!
