### ISSUE TITLE
default_root

### ISSUE THREAD

**Issue by eugenner** [totaljs/framework#711]
After setting **default_root** parameter in the config, for example for CMS app, application doesn't work like should be, it shows Login Form (when url is pointed on the added default_root, "default_root : /cms/" for ex.) And probably the same situation with Eshop app. It was attempt to use two applications on the same host. Or this option is about custom applications only?

**Comment by petersirka** [comment]
Hi. CMS is not optimized for `defualt_root`. App must have some optimalization for it.

**Comment by eugenner** [comment]
Hi, so probably it will be good to correct information about this option: https://blog.totaljs.com/blogs/news/20180801-total-js-v3-0-0/

> **Improved domain root changing**
> 
> This improved feature will help you if you want to provide multiple Total.js apps on the same domain divided by path e.g. /eshop/, /cms/, /helpdesk/.

I meant that this phrase: "will help" sounds little bit confusing. It is still need to some coding... ok.

**Comment by petersirka** [comment]
Yes but CMS and Eshop is older than Total.js v3... But new version of products will support it.
