### ISSUE TITLE
Can not set cache for 60 seconds ?

### ISSUE THREAD

**Issue by aalfiann** [totaljs/framework#720]
I've tried like this
```
var key = 'test-cache';
var item = CACHE(key);
var date = {timestamp:new Date().toISOString().replace("T"," ").replace("Z","").substr(0,19)};
if(!item){
  CACHE(key,date,'60 seconds');
  console.log(date);
} else {
  console.log(item);
}
```

but cache is always refresh after 2minutes?

whats the problem?

**Comment by petersirka** [comment]
Hi. There is a simple answer.

- `CACHE()` users `F.cache.get2()` method which is optimized for the performance and there can be a delay max. 1 minute
- if you want to use accurate time-reading of cache then you need to use `F.cache.get(key)` for reading

**Comment by aalfiann** [comment]
Solved. Thank you so much.
