### ISSUE TITLE
Error 408: Request Timeout

### ISSUE THREAD

**Issue by joaomirandasa** [totaljs/framework#723]
Guys, i don't know if i doing something wrong on my codes but recorrently ( running on PM2 ) i facing this error message:

` Error: 408: Request Timeout
at ClientRequest.<anonymous> (/var/www/SERVER/node_modules/total.js/utils.js:601:20)
at Object.onceWrapper (events.js:277:13)
at ClientRequest.emit (events.js:189:13)
at TLSSocket.emitRequestTimeout (_http_client.js:662:40)
at Object.onceWrapper (events.js:277:13)
at TLSSocket.emit (events.js:189:13)
at TLSSocket.Socket._onTimeout (net.js:440:8)
at ontimeout (timers.js:436:11)
at tryOnTimeout (timers.js:300:5)
at listOnTimeout (timers.js:263:5)
at Timer.processTimers (timers.js:223:10)`

i can't tracking this error because does not have sufficient information about it and how to fix. Someone already passed by something like that?

I take the opportunity to ask about another problem, when I am running TotalJS + Flow persistently via PM2 and make changes to the designer these changes are not saved at all, any idea what it might be?

**Comment by petersirka** [comment]
This error throws `U.request()` method... Also this method uses `RESTBuilder` or some Flow components. I need to see Flow designer and then I can help more.

> when I am running TotalJS + Flow persistently via PM2 and make changes to the designer these changes are not saved at all, any idea what it might be?

- Do you have latest version Flow? If no, try to download it...
- Are you sure that Flow is running in singlethread? PM2 can run the app in Cluster and this can make a problem.
- Is the only one problem captured in the log? Or there is a more errors?

I provide around 5 instances of Flow and without any problem.... But I use Total.js SuperAdmin.

**Comment by joaomirandasa** [comment]
First of all, thank you so much for this amazing application that is TotalJS - best application I have ever seen!

I investigated a bit more about the error and realized that it is in U.request () - I make many requests per second, I don't know why but this is generating the error. Below is an example of the request I make. Usually i call this SEND_AUDIO() 20 times per second.

`WHATSAPP_LOWER.prototype.SEND_AUDIO = function (DESTINO,AUDIO_URL){
	var that = this;
	return new Promise(function(resolve, reject) {
    	U.request(that.URL_CALL+'/that.token', ['post'], {phone:DESTINO, audio:AUDIO_URL}, function(err, data, status, headers, host) {
			if (!err) {
				resolve(JSON.parse(data));
			} else if (err){
				SEND_MESSAGE_ERROR(err);
			}
		}, null, null);
    })
}`

I don't know if I'm right, but I believe that calling the function with Promise many times before the request response is causing it, am I correct in this hypothesis? Do you have any idea how to improve this?

**About Flow:**

I always use totalJs in cluster mode, could this be causing the error? If it is better I will migrate to superadmin.

Another question that came to me now, is it possible to use designer data outside of server? I say access the designer who has a file in an instance external to the server running TotalJs+Flow.

**Comment by petersirka** [comment]
I recommend to remove promise. But try to download beta version of Flow: `$ npm install total.js@beta`, it's stable and supports `keepalive` flag. Here is improved code.

```javascript
const FLAGS = ['post', 'keepalive'];

// Better solution:
WHATSAPP_LOWER.prototype.SEND_AUDIO = function(DESTINO, AUDIO_URL, CALLBACK) {
    var that = this;
    U.request(that.URL_CALL + '/that.token', FLAGS, {
        phone: DESTINO,
        audio: AUDIO_URL
    }, function(err, data) {
        CALLBACK && CALLBACK(err, data ? JSON.parse(data) : null);
    });
};

// Or your solution with Promises:
WHATSAPP_LOWER.prototype.SEND_AUDIO = function(DESTINO, AUDIO_URL) {
    var that = this;
    return new Promise(function(resolve, reject) {
        U.request(that.URL_CALL + '/that.token', FLAGS, {
            phone: DESTINO,
            audio: AUDIO_URL
        }, function(err, data) {
            if (err)
                SEND_MESSAGE_ERROR(err);
            else
                resolve(JSON.parse(data));
        });
    });
};
```

About the error, I assume that target server doesn't respond in short time. You can extend timeout, but the memory of application will grow up.

---

> I always use totalJs in cluster mode, could this be causing the error? If it is better I will migrate to superadmin.

This is not good message. Total.js Flow can't run in cluster mode, it won't work. It's optimized for singlethread only. Cluster mode isn't possible to implement there. Application __must be optimized__ for cluster mode.

> Another question that came to me now, is it possible to use designer data outside of server?

Yes this is possible. This is from `readme` of Flow (I need to update docs in Wiki):

```javascript
// +v5.2.0
// options.type = 'bundle'; // 'bundle', 'server', 'client'
// "bundle" -> loads server and client together
// "server" -> loads server only
// "client" -> loads client only but it needs external URL (look to "options.external")

// +v5.2.0
// options.external = 'ws://yourserver.com/$dashboard/';
// Can contain an external URL for WebSocket
```
