### ISSUE TITLE
How to load script from npm_modules in html view

### ISSUE THREAD

**Issue by aalfiann** [totaljs/framework#724]
I have already 

`npm install chunk-handler`

but I dont know how to use that script into view engine.

I have tried like this
```
<script src="/chunk-handler/src/chunkhandler.js"></script>

//or

<script src="/npm_modules/chunk-handler/src/chunkhandler.js"></script>
``` 

but script is not loaded because 404.

**Comment by petersirka** [comment]
- all scripts are loaded from `public` directory
- so try to open `public` directory and there install npm module
- then must be module available via HTTP

**Comment by aalfiann** [comment]
I can't do that because the js is for nodejs. the file has module.exports. so it will getting error when loaded into html view directly with tag <script>

There is something weird I found is on socket.io library

**debug.js**
```javascript
require('total.js')

// Below here is required to run socket client in UI only
var socketio = require('socket.io');

F.on("load", function() {
    this.io = socketio.listen(this.server);
});

F.http('debug');
```

HTML view
```javascript
@{title('Total.js with socket.io')}
<script>
var socket=io.connect('http://127.0.0.1:8000',{transports: [ 'polling']});
</script>
```

The socketio library is able to load, but another library can't load.

Why this happend?

**Comment by molda** [comment]
There are 2 libraries for socket.io.
- server side (does not work in browser)
- client side (does not work in node.js on the server)

So if you think you are using same library on server as well as client you are wrong.

If you want you can make node_modules directory public by adding config 
`directory_public_virtual  :   node_modules`
But i would not recomend that.

But even if you do that the libraries that are not meant to run on the client(browser) won't work.

**Comment by petersirka** [comment]
If you want to use `Socket.io` in the background with Total.js then you need to disable WebSocket
<https://docs.totaljs.com/latest/en.html#api~FrameworkConfiguration~allow_websocket>:

```
allow_websocket    : false
```

**Comment by aalfiann** [comment]
Thanks, I got it works now.
