### ISSUE TITLE
How to connect nosql from another server?

### ISSUE THREAD

**Issue by raultaufan** [totaljs/framework#726]
var DB = require('nosql');
    var nosql = DB.load('http://IP Address or URL/test.nosql');

    nosql.find().make(function(builder) {
        builder.callback(function(err, response, count) {
            console.log(response);
        });
    });

I can connected nosql from another drive/folder. But I can't connect from another server / IP Address.
How to connect nosql from another server?

Thanks...

**Comment by petersirka** [comment]
Hi @raultaufan, sorry for delay. Try this:

Make a script __test.js__:

```javascript
require('total.js');

NOSQL('https://www.totaljs.com/test.nosql').find().fields('title', 'price').callback(console.log);
```

__Run it__:
```bash
$ node test.js
```

- you can read-only database from another server

**Comment by raultaufan** [comment]
Thank you
I have been able to connect total.js to Nosql on another server.
you saved my time...

But, how to write (insert, modify, remove) nosql on another server? Using MongoDB?

**Comment by petersirka** [comment]
Yes, you need use MongoDB or PostgreSQL because NoSQL embedded database works only with local flat files like SQLite database.

**Comment by raultaufan** [comment]
Thank you Peter Sirka ....
