### ISSUE TITLE
Controller.body don't get all form fields if the form exceed a certain number of fields  (or size; i can't tell).

### ISSUE THREAD

**Issue by elomraydino** [totaljs/framework#729]
Can you please check why I can't get more than 24 fields in **controller.body**? V.3.2.4

**Comment by petersirka** [comment]
Are you sure 24 fields? There is a limit for max. 33 keys...

You can extend the limit by adding `default_requests_maxkeys` into the config:
https://docs.totaljs.com/latest/en.html#api~FrameworkConfiguration~default_request_maxkeys

BTW: I recommend to send data via JSON.

**Comment by elomraydino** [comment]
OK. Thanks!
