### ISSUE TITLE
Body request in DELETE method is empty

### ISSUE THREAD

**Issue by aalfiann** [totaljs/framework#731]
My question is how to get body request value when using DELETE method?

**controller**
```javascript
exports.install = function() {
    ROUTE('/api/user/delete', ['delete','*User --> @delete']);
};
```
**schema**
```javascript
NEWSCHEMA('User').make(function(schema) {
  schema.define('id', 'string');
  schema.addWorkflow('delete', function($) {
    console.log($.model);
  });
});
```

**cURL**
```bash
curl -X DELETE \
  http://127.0.0.1:8000/api/user/delete \
  -H 'Content-Type: application/json' \
  -H 'Host: 127.0.0.1:8000' \
  -H 'cache-control: no-cache' \
  -d '{
	"id":"5d88af3e45df0a0e376e6724"
}'
```

**console.log**
Why the id is empty?
```bash
SchemaInstance { id: '' }
```

**Comment by petersirka** [comment]
Hi @aalfiann,
preparing of data is disabled in `DELETE` method. You can get raw data via `$.body` property. It's because in most cases you send only `id` of record for deleting some records. Therefore Total.js disables validation.

**Comment by aalfiann** [comment]
Yeah, in most cases only need `id` record for deleting the data. But in our project there is 3 conditions required and it's too long if I just put it in url. 

Btw, `$.body` is work. 

Thank you very much.
