### ISSUE TITLE
Sharing view-helper between different partials

### ISSUE THREAD

**Issue by buzzeins** [totaljs/framework#732]
Hi, how to share a viiew helper in different view-partials properly? For instance:

# Helper:
```
@{helper article(item)}
<li>...</li>
@{end}

```

# Views/Partials:
list.html
  - @{view('partials/wrapper_list_default', list)} 
  - @{view('partials/wrapper_list_superhero, list)}

Each partial is gonna use the same helper. How to, without to replicate the inline helper?

thx

**Comment by petersirka** [comment]
Hi,
you need to create helper in another way <https://docs.totaljs.com/latest/en.html#api~global~DEF.helpers> ... another way isn't possible.

**Comment by buzzeins** [comment]
even better, thx :D
