### ISSUE TITLE
Promises first

### ISSUE THREAD

**Issue by buzzeins** [totaljs/framework#735]
Morning, any plans to rewrite callback-porn to promises? may 4.x?

**Comment by petersirka** [comment]
__I don't know__. Currently Total.js Schemas / Operations / TaskBuilder can decrease count of callbacks rapidly. So our projects are really clean for my eyes.

**Comment by aalfiann** [comment]
I more prefer async await or callback than using promise.

**Comment by TemaSM** [comment]
Agree with @buzzeins. Promises and async/await will probably bring more cleaner code

**Comment by TemaSM** [comment]
> I more prefer async await or callback than using promise.

@aalfiann async/await are built on top of Promises, so it's just syntax sugar for writing less code and less block-scoped-hell code like this:
```javascript
request.then((res) => {
    res.getContent().then((dom) => {
        dom.find('body').then(...) // and more times ...
    }).catch(err)
}).catch(err)
```
-> the same as code below (much more better with async/await, isn't it?)
```javascript
let res = await request()
let dom = await res.getContent()
let el = await dom.find('body')
```

**Comment by petersirka** [comment]
BTW: promises are implemented in `RESTBuilder`, `DBMS` module and in NOSQL embedded database too. Documentation doesn't contain info about promises, but usage is very easy:

```javascript
RESTBuilder.GET(..).promise().then(...)
NOSQL('users').find().promise().then(...)
```
