### ISSUE TITLE
Not able to send mail using node_module/total.js/index.js/F.mail function

### ISSUE THREAD

**Issue by shivam201312** [totaljs/framework#736]
Hi.. i am trying to send mail using totaljs  mail function . 
Projectroot/modulesfolder/.js -> which calls F.mail function
Code inside js function
```
self.mail(emailTo, title, layout, params, function(data){console.log("Callback function called"); console.log(data)});
```
I have tried to send mail from localhost and live server . no error is displayed but also no mail is sent from the user . 
I have checked email credentials by sending mail from php mailer .Credentials are fine . i am able to send mail through phpmailer .
Any suggestion how can i debug ?

**Comment by petersirka** [comment]
Hi,
first, sorry for delay. The code below enables debugging:

```javacript
Mail.debug = true;
```

You can put it everywhere, `Mail` is a global variable.

**Comment by petersirka** [comment]
Any news?
