### ISSUE TITLE
can I receive array or object type parameters with file transfers?

### ISSUE THREAD

**Issue by luasenvy** [totaljs/framework#738]
when transferring files via multipart
can I receive array or object type parameters in a schemas?

like this:
```
let formData = new FormData()
formData.append('numbers[]', 1)
formData.append('numbers[]', 2)
formData.append('numbers[]', 3)
// $.model.numbers === [ 1, 2, 3 ]

formData.append('nested[one]', 1)
formData.append('nested[two]', 2)
// $.model.nested === { one: 1, two: 2 }
```

**Comment by petersirka** [comment]
Hi,
for arrays try this:

```javascript
formData.append('numbers', 1);
formData.append('numbers', 2);
formData.append('numbers', 3);
// numbers=1&numbers=2&numbers=3
```

Nested object aren't supported.

__My recommendation__:

- firstly you need to upload file(s) and return URL address or identifier of the uploaded file(s)
- then create an object and send it in JSON format

**Comment by luasenvy** [comment]
Thanks for letting me know :)
