### ISSUE TITLE
When using a field of type array with multipart, 1 length array parameter are lost

### ISSUE THREAD

**Issue by luasenvy** [totaljs/framework#742]
When using a field of type array with multipart
For arrays of length 1, the parameters are lost.

multipart form: 
![image](https://user-images.githubusercontent.com/24634713/71945225-9ab6ff00-3209-11ea-98ad-31402438ef5d.png)

schema.define:
![image](https://user-images.githubusercontent.com/24634713/71945262-ac98a200-3209-11ea-920e-717af05e6618.png)

in workflow:
![image](https://user-images.githubusercontent.com/24634713/71945290-c0dc9f00-3209-11ea-8918-9607aec6949f.png)

**Comment by petersirka** [comment]
You need to specify a type of Array, maybe there is a problem. Try to update schema like this:

```javascript
schema.define('keep_docs', '[String]');
schema.define('keep_gallery, '[String]');
```

**Comment by luasenvy** [comment]
thanks to reply

i try to update schema define and request again:
![image](https://user-images.githubusercontent.com/24634713/72040201-2b194080-32eb-11ea-9b7b-dc9ced52139c.png)

![image](https://user-images.githubusercontent.com/24634713/72040158-08872780-32eb-11ea-8f2e-bedee5b00d5a.png)

but there is the same problem.:
![image](https://user-images.githubusercontent.com/24634713/72040187-20f74200-32eb-11ea-80f8-09f14046ea07.png)

**Comment by petersirka** [comment]
Please make an example and send me it via email petersirka@gmail.com. Thank you!

**Comment by luasenvy** [comment]
ok,
i will work that in weekend
thanks :)
