### ISSUE TITLE
Kind off memory leak on global variables.

### ISSUE THREAD

**Issue by elomraydino** [totaljs/framework#743]
I observe a sort off memory leak using GLOBAL to store app settings that i don't want to load from db at each request. I first put them directly in GLOBAL then in MAIN but still have the same behavior. After some hours and sometime some days those settings are not accessible any more. Bellow the way I load an use them. The app is currently running on node 10.18.0 but I plan to move to node 12 suspecting a nodejs memory leak bug.

```javascript
//Loading at app start
F.on('load', function () {
    //Load settings from db.
    var Setting = MODEL('setting').model; //Mongoose model
    Setting.find({
        alive: true,
    }).then((settings) => {
        settings.forEach(setting => {
            MAIN[setting.ref] = setting.value; // value is Object
        });
        console.log('Settings loaded');
    }).catch((err) => {
        console.log('Error loading settings -->> ', err.message);
    });
});
```

```html
<!-- usage in view -|- address, phone, email don't show anymore on the page after the app run for some days-->
<div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
    <h5>@(Adresse)</h5>
    <p>@{MAIN.identity.address}</p>
    <h5>@(Contact)</h5>
    <p><i class="fa fa-phone fa-fw"></i> @{MAIN.identity.phone}</p>
    <p><i class="fa fa-envelope fa-fw"></i> @{MAIN.identity.email}</p>
</div>
```

**Comment by petersirka** [comment]
I can help you, this is very small amout of information. We provide more than 100 apps and without any problem. Memory leak can be caused with storing a lot of information in objects.

- you can extend memory for Node.js process via `node --max-old-space-size=8192 release.js` (8 GB memory)
- or watch what your object contains (I think that the problem is here)

Is the problem in view only or the problem is in entire app?

**Comment by elomraydino** [comment]
The objects are js objects containing simple information (string, int, boolean) like user info, report schedule time and api ids... the problem is in in the entire app.  Thanks for the advises; I will try them! I will close the issue for now. But in case you find something about this, please share.

**Comment by petersirka** [comment]
OK, just let me know.
