### ISSUE TITLE
PATCH method and Schema validation

### ISSUE THREAD

**Issue by fgnm** [totaljs/framework#749]
I've noticed that automatic schema validation does not works if I use `PATCH` as HTTP method.
For example:
```JavaScript
ROUTE('PATCH [api]/v1/user/patch            *user --> @patch', ['authorize']);
...
NEWSCHEMA('user', function (schema) {
    schema.define('region', 'Upper', true);
    schema.setPatch(function($) {
        $.success();
    });
});
```
Return `success` even if I request `curl -X PATCH -H 'Content-Type: application/json' -i 'http://api.localhost:8000/v1/user/patch' --data '{ }'`
In this case the body is empty and no `region` field is provided, but the schema does not validate. If I use the `POST` method instead of `PATCH` it works as expected and returns an error.

**Comment by petersirka** [comment]
The framework validates received fields only with `PATCH` method. So your behaviour is correct. 

```javascript
schema.setPatch(function($) {
    if (!$.keys.length) {
    }
});
```

**Comment by fgnm** [comment]
Thank you as always for the clear explanation :smile:
