### ISSUE TITLE
mongoose model.find() detected as Array.prototype.find

### ISSUE THREAD

**Issue by xtorrentx** [totaljs/framework#758]
When I set mongoose Model as global, I got warning like this

```
OBSOLETE / IMPORTANT ---> "Array.prototype.find()" will be removed in v4, use alternative "Array.prototype.findItem()"
```

The problem is mongoose model have to loaded in one time only, so there is no another way except make it as global.

how to fix this? 

Thank you

**Comment by petersirka** [comment]
Does it Mongoose work or no? Total.js extends `Array` prototype by adding `.find()` but this method is deprecated. If you will have a problem with Mongoose then try to implement polyfill <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find> to a definition file.
