### ISSUE TITLE
Don't work default_websocket_maxlength

### ISSUE THREAD

**Issue by dispbd** [totaljs/framework#761]
I have files. Let's say they are about megabytes in size.
I am encoding these files with _ArrayBuffer_ or String. And I ship via _websockets_.
The server settings contain the parameter **default_websocket_maxlength: 20000**.
But it doesn't seem to work. The server does not want to receive data larger than 255kb. That being said, there is no error on either the client or server side. Just silence!
So I thought for a long time that the problem was in my code. But it's definitely a worker, because if you send less than 255kb, then everything works great!

Is there a problem with the server engine or have I not specified any other startup parameters?

**Comment by petersirka** [comment]
Please try to send smaller data if it will work. Better will be to create a small example and send me it as zip package, can you create some example? I'll test it.

**Comment by dispbd** [comment]
Here's an example. Everything seems to be clear there.
[_default_websocket_maxlength.zip](https://github.com/totaljs/framework/files/4984189/_default_websocket_maxlength.zip)

But apparently I did not fully understand what was the matter. Probably the problem is not so much in the file size as in its content. Although it is possible in both. And this is very strange!

The project has a **_testfiles_** folder for testing. For example, the file **_3610kb.txt_** is transmitted by websockets. But the server does not want to accept the file **_5415kb.txt_** with exactly the same duplicated content. And there is, for example, **_testWork.txt_** (the type of files that we will work with directly) - the content is different and weighs only _413kb_, but the server does not want to accept either.

At first I sinned on _unicode hex characters_, which are in the **_testWork.txt_** file, but they are not in the other files, since they are just copies of the index.js content.

Moreover, the problem is most likely on the server side, since if there was an error when sending, it would be right in the browser console, because the events were processed. However, there are no errors on the server either. The server seems to pass this message, while not closing the connection, but also not accepting more other messages, even if it had previously accepted them.

Perhaps I'm dumb and don't see an obvious solution, but I can't figure out how else to check.
I hope I wrote it clearly, and I apologize for my English!)
Here's an example. Everything seems to be clear there.

But apparently I did not fully understand what was the matter. Probably the problem is not so much in the file size as in its content. Although it is possible in both. And this is very strange!

The project has a testfiles folder for testing. For example, the file **_3610kb.txt_** is transmitted by websockets. But the server does not want to accept the file **_5415kb.txt_** with exactly the same duplicated content. And there is, for example, testWork.txt (the type of files that we will work with directly) - the content is different and weighs only _413kb_, but the server does not want to accept either.

At first I sinned on unicode hex characters, which are in the **_testWork.txt_** file, but they are not in the other files, since they are just copies of the index.js content.

Moreover, the problem is most likely on the server side, since if there was an error when sending, it would be right in the browser console, because the events were processed. However, there are no errors on the server either. The server seems to pass this message, while not closing the connection, but also not accepting more other messages, even if it had previously accepted them.

Perhaps I'm dumb and don't see an obvious solution, but I can't figure out how else to check.
I hope I wrote it clearly, and I apologize for my English!)
Thanks for your responsiveness!

**Comment by petersirka** [comment]
I found a problem, but I need to perform several tests. I think that it works - **try it**: `$ npm install total.js@beta`. Let me know if you find some problem.

**Comment by petersirka** [comment]
BTW: your example helped a lot! Thank you!

**Comment by dispbd** [comment]
Checked it out. For persuasiveness, I even tested how he transfers 6 thousand files at once - everything works great!

I'm waiting for the official release and close the question!
Thank you very much for the prompt solution of the problem !!!
And for the engine as a whole you have a separate respect, it's cool!
