### ISSUE TITLE
Why is static file caching not working?

### ISSUE THREAD

**Issue by dispbd** [totaljs/framework#764]
Hello. I can't figure out why static file caching doesn't work. There are many options on the Internet for configuring nginx. For instance, any of them:

[https://belvg.com/blog/static-content-caching-with-nginx.html](https://belvg.com/blog/static-content-caching-with-nginx.html)
[https://stackoverflow.com/questions/40688536/nginx-cache-whole-node-express-application](https://stackoverflow.com/questions/40688536/nginx-cache-whole-node-express-application)
[https://gist.github.com/mattd/1006398/598df8f218a18bc1b0f3415550b4a369f37afb7c](https://gist.github.com/mattd/1006398/598df8f218a18bc1b0f3415550b4a369f37afb7c)

But none of them work! I'm already starting to sin on the Total.js. In my view engine, this is done for example - **_@{image('logo.gif')}_** or **_@{js('default.js')}_**. nginx overload after changing settings and all other nginx settings work fine.!

Can you please tell me what's the matter?

**Comment by petersirka** [comment]
Hi @dispbd, 
the question is: __in which mode is your app running?__ Because `debug` mode disables cache, for example try www.totaljs.com (it uses Total.js CMS with Total.js v3).
