### ISSUE TITLE
Totaljs in Docker : default.css and default.js don't load -  408 server timeout

### ISSUE THREAD

**Issue by wilrona** [totaljs/framework#766]
Hello,
I make a web service with totaljs which must work on docker. But the default.css and default.js file does not load even though it is present.
I have a **408 server timeout error**.

All the other files load without problem except the two in docker.
But when I run the app out of docker, I don't have this problem.

Can you help me ?

**Comment by petersirka** [comment]
Hi, try to look into the output fo console/terminal (logs). Maybe is there some problem.

**Comment by wilrona** [comment]
Thanks for the feedback

I checked my console / terminal and actually found an error.

I changed the information in my Dockerfile because I could not create the "tmp" folder when launching the application.

Its now working
