### ISSUE TITLE
transfer bug in 3.4.6

### ISSUE THREAD

**Issue by sersh88** [totaljs/framework#772]
Hello, 
In 3.4.6 version only first request to controller with .cancel().transfer() will be served. All other will return 404.
Reproduce with this code as default controller:

```javascript
exports.install = function() {
    ROUTE('/*', transfer);
    ROUTE('/=serve-base', base);
};

function transfer() {
    this.cancel().transfer('/=serve-base')
}

function base() {
    this.content('test', 'text/html')
}
```
Try to go to any url, like /blablabla. First request will output `test`, all subsequent - 404 error. It's wrong cache in F.temporary.other I guess.

**Comment by petersirka** [comment]
Hi @sersh88,
yes there was a bug. I have fixed it.

- `$ npm install total.js@beta`
- BTW: beta is stable
