### ISSUE TITLE
[feature] : How to create custom node (component) using python script 

### ISSUE THREAD

**Issue by VinayChaudhari1996** [totaljs/framework#775]
Hello Guys , 

How can I create custom node using python script with few user input fields ?

Thanks ,

**Comment by molda** [comment]
Hi, can you clarify, what you mean by "custom node"?
Are you by any chance refering to a component in totaljs/flow application?

**Comment by petersirka** [comment]
@VinayChaudhari1996 it's possible. In Node.js, you can spawn a process with e.g. Python, and then you can communicate via IPC between the Flow component and Python script. So you can wrap this functionality to the Flow component (not hard).

**Comment by VinayChaudhari1996** [comment]
> @VinayChaudhari1996 it's possible. In Node.js, you can spawn a process with e.g. Python, and then you can communicate via IPC between the Flow component and Python script. So you can wrap this functionality to the Flow component (not hard).

Yeah exactly , like we do in node-red 

Can you share example where I can run simple python program in node ?

I'm am looking for template where I can plug my python script it. 

Thanks

**Comment by VinayChaudhari1996** [comment]
> Hi, can you clarify, what you mean by "custom node"?
> Are you by any chance refering to a component in totaljs/flow application?

Yeah , A component where we can plug python script in it.
