### ISSUE TITLE
Serve Angular components views using TotalJS

### ISSUE THREAD

**Issue by skalyanapu-mtuity** [totaljs/framework#776]
We want to embed the FlowJS dashboard into our angular stand-alone app?  Ideally I prefer to have flowJS only without TotalJS , but we're ok to have totalJS render the angular app also

**Comment by petersirka** [comment]
Do you want to use server-side implementation of Flow or Flow designer without server-side implementation? Here is client-side component called j-Flow: https://componentator.com/components/j-flow/ (without server-side implementation)

**Comment by skalyanapu-mtuity** [comment]
We want Flow without server-side implementation, within an angular application, and without the dependency of totaljs.
Does https://componentator.com/components/j-flow/ work without totaljs?

**Comment by petersirka** [comment]
__Yes__, j-Flow is only a client-side component.
