### ISSUE TITLE
DBMS PostgreSQL doesn't catch an error

### ISSUE THREAD

**Issue by aalfiann** [totaljs/framework#778]
Hello @petersirka ,

I just found that DBMS for PostgreSQL doesn't catch an error.

To reproduce:
```js
require('total.js');
const assert = require('assert');

function isArray (a) {
  return (!!a) && (a.constructor === Array);
}

it('database connection', async function () {
    this.timeout(120000);
    require('dbms').init('postgres://postgres:kamisama@191.168.88.25:5432/postgres', ERROR('PostgreSQL'));
    try {
      const result = await DBMS().query('select * from mydata limit 1').promise();
      if (result) {
        assert.strictEqual(isArray(result), true);
      } else {
        assert.ok(false);
      }
    } catch (err) {
      throw new Error(err);
    }
  });
```

Note:
- As you can see, the IP address is wrong, the DBMS should catch this error, but failed (has been wait for 120 second).
- If the IP address is right, but the port is wrong, DBMS successfully catch an error (connect ECONNREFUSED).
- I use totaljs 3

Please help, did I miss something?

**Comment by petersirka** [comment]
HI @aalfiann, please create issue in DBMS repository - https://github.com/totaljs/dbms.
