### ISSUE TITLE
AUTH global function is recieving undefined in $.params

### ISSUE THREAD

**Issue by LandyCuadra** [totaljs/framework#783]
Hi, I am having a problem with the AUTH global, I am trying to evaluate some GET routes based on a param they send in the route... but when I try to get the value, I get this error

`Cannot destructure property 'clientid' of '$.params' as it is undefined`

any idea of what I may be doing wrong?....

**Comment by petersirka** [comment]
@LandyCuadra. The framework executes the `AUTH()` method before is evaluated routing because the routing needs information about the result from the `AUTH()` method.

- `$.params` is parsed after routing

**Comment by LandyCuadra** [comment]
so there si no way to do that?, because the documentation shows I could access those properties.. 

https://docs.totaljs.com/total4/407ff001jy51c/#4893f001wa51c -> in "+posibilities"

**Comment by petersirka** [comment]
My mistake. It's fixed.

**Comment by LandyCuadra** [comment]
great!, thank you
