### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [totaljs/framework#784]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by petersirka** [comment]
We will prepare it.

**Comment by JamieSlome** [comment]
@petersirka - thanks, appreciate your follow-up!

Was there any conclusion on the report that we received?

https://huntr.dev/bounties/87d94b4a-7a58-490c-b546-a05d33c2f168/
