### ISSUE TITLE
How to hide X-Powered-By for security reason?

### ISSUE THREAD

**Issue by aalfiann** [totaljs/framework#787]
For security reason, sometimes I want to hide X-Powered-By, to make hacker hardly to determine what technology behind the website.

I've tried

```
exports.install = function () {
  F.route('/', homePage);
}

function homePage {
  this.header('X-Powered-By', '');
  this.view('index');
}
```

But didn't working..

**Comment by petersirka** [comment]
Hi @aalfiann, just set: <https://docs.totaljs.com/total4/4047c001sd51c/#4c0f5001nr51c>
