### ISSUE TITLE
Timeout Set Up

### ISSUE THREAD

**Issue by lodwig** [totaljs/framework#788]
Hi Peter, 

I am using total.js version 3 and i need to increase request timeout for a route, i was try using :

1. `ROUTE('POST /product/import/', importProduct, ['authorize', 1200000]);`  
2. `ROUTE('POST /product/import/', importProduct, ['authorize', {timeout:1200000}]);` 
3. `ROUTE('POST /product/import/', importProduct, ['authorize', {timeout:false}]);`  

and it has no effect and i was configure my nginx  on server scope:

`proxy_read_timeout 1200;`
`proxy_connect_timeout 1200;`
`proxy_send_timeout 1200;`

and i was upgrade on config file on app:

`default_request_timeout         : 1200000`

and i always got return in 2-3 minutes with error code 408, i need 20 minutes to validating my XLSX file and save that validating data to my database server.

Thank you in advance.

**Comment by petersirka** [comment]
Hi @lodwig, **I'll check if there is a bug or not**. But I think that it would be better to change your code. So I recommend closing ASAP a request with importing, and in another request, you can check the current state of importing.

BTW: Are you using the latest version of Total.js v3?

**Comment by lodwig** [comment]
Hi, Peter 

I have middleware to authorize request, and i think it's from browser,  chrome will set request is timeout if the request more than 2 minutes.

I will close this issue, i was change my flow to validate XLSX file and send user FCM message the result of validation.

**Comment by petersirka** [comment]
@lodwig try to use this flag: https://docs.totaljs.com/latest/en.html#api~HttpRouteOptionsFlags~delay
