### ISSUE TITLE
Exporting the JSON

### ISSUE THREAD

**Issue by KarimX32** [totaljs/framework#797]
I wanted to know if there is any way I can export the JSON but in a different file instead of designer.json

so basically if 2 users have my website opened and using the page if one click applies it overwrites the other user's data.
so I wanted to know if there is a way or a workaround so I can save it in a different file. 

I really appreciate any help you can provide.

**Comment by petersirka** [comment]
Hi @KarimX32. You mean the Total.js Flow? If yes, then the Flow is not optimized for multiple users. I recommend creating an independent process for each user.

But you can change the saving/loading behaviour easily:
https://github.com/totaljs/flow/blob/master/definitions/flowstream.js#L25

**Comment by KarimX32** [comment]
thank you for replying, i also wanted to know what kind of encoding is used in flow.package, because I wanted to change the main template, I just wanted to remove the apply button and replace it with a save button

**Comment by KarimX32** [comment]
> https://github.com/totaljs/flow/blob/master/definitions/flowstream.js#L25

**Comment by KarimX32** [comment]
> https://github.com/totaljs/flow/blob/master/definitions/flowstream.js#L25
so i just searched for that function in the node modules and basically my entire project however I had no results, where can I find this exactly?

**Comment by KarimX32** [comment]
this as example, i just added a gg.html for testing, and I copied one of the encoded stuff above and it actually created a gg.html with the same code a forms/intro-welcome

https://cdn.discordapp.com/attachments/854742527155109889/1066109339456262184/Screenshot_2023-01-20_at_11.37.46_PM.png

that's the image for what I did.

```js
<div data---="intro__common.form__if:welcome;close:@(Done);next:@(Next);exec:introform/done" class="hidden">
	<figure>
		<div class="padding black">
			<div class="m"><i class="fa fa-5x green fa-project-diagram"></i></div>
			<div>@(Welcome to JavaScript Visual Programming Interface called <b>Total.js Flow</b>.)</div>
		</div>
	</figure>
	<figure>
		<div class="padding black">
			<div class="m"><i class="fa fa-5x fa-plug"></i></div>
			<div>@(Your Flow designer is <b>currently empty</b> and you need to install some Flow components.)</div>
		</div>
	</figure>
	<figure>
		<div class="padding black">
			<div class="m"><i class="fa fa-5x fa-plug"></i></div>
			<div>@(Or you can start much faster, just download preddefined Flow designs and modify them by your needs.)</div>
		</div>
	</figure>
	<figure>
		<div class="padding black">
			<div class="m"><i class="fa fa-5x fa-check-circle green"></i></div>
			<div>@(Thank you for using <b>Total.js Flow</b>.)</div>
		</div>
	</figure>
</div>

<script>

	PLUGIN('introform', function(exports) {
		exports.done = function() {
			SETTER('shortcuts', 'exec', 'f1');
		};
	});

</script>
```

received this, so I want to be able to write an HTML code and just encode it and put it in the flow.package so I can basically create my own default tmp.

thank you.

**Comment by KarimX32** [comment]
i just noticed i was opening this issue on totaljs/framework not on totaljs/flow

I really apologise for that, can we just continue here?

**Comment by petersirka** [comment]
You're using an older version of Flow. Please, can you create a new issue in the Flow repository and we will continue there. And make a screenshot of your project structure.

Thank you
